%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_LTW17_rep';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_LTW17_rep.log');
M_.exo_names = 'eugc';
M_.exo_names_tex = 'eugc';
M_.exo_names_long = 'eugc';
M_.exo_names = char(M_.exo_names, 'euz');
M_.exo_names_tex = char(M_.exo_names_tex, 'euz');
M_.exo_names_long = char(M_.exo_names_long, 'euz');
M_.exo_names = char(M_.exo_names, 'eua');
M_.exo_names_tex = char(M_.exo_names_tex, 'eua');
M_.exo_names_long = char(M_.exo_names_long, 'eua');
M_.exo_names = char(M_.exo_names, 'eub');
M_.exo_names_tex = char(M_.exo_names_tex, 'eub');
M_.exo_names_long = char(M_.exo_names_long, 'eub');
M_.exo_names = char(M_.exo_names, 'eum');
M_.exo_names_tex = char(M_.exo_names_tex, 'eum');
M_.exo_names_long = char(M_.exo_names_long, 'eum');
M_.exo_names = char(M_.exo_names, 'eui');
M_.exo_names_tex = char(M_.exo_names_tex, 'eui');
M_.exo_names_long = char(M_.exo_names_long, 'eui');
M_.exo_names = char(M_.exo_names, 'euw');
M_.exo_names_tex = char(M_.exo_names_tex, 'euw');
M_.exo_names_long = char(M_.exo_names_long, 'euw');
M_.exo_names = char(M_.exo_names, 'eup');
M_.exo_names_tex = char(M_.exo_names_tex, 'eup');
M_.exo_names_long = char(M_.exo_names_long, 'eup');
M_.endo_names = 'cs';
M_.endo_names_tex = 'cs';
M_.endo_names_long = 'cs';
M_.endo_names = char(M_.endo_names, 'cn');
M_.endo_names_tex = char(M_.endo_names_tex, 'cn');
M_.endo_names_long = char(M_.endo_names_long, 'cn');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'gc');
M_.endo_names_tex = char(M_.endo_names_tex, 'gc');
M_.endo_names_long = char(M_.endo_names_long, 'gc');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'sb');
M_.endo_names_tex = char(M_.endo_names_tex, 'sb');
M_.endo_names_long = char(M_.endo_names_long, 'sb');
M_.endo_names = char(M_.endo_names, 'tauk');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauk');
M_.endo_names_long = char(M_.endo_names_long, 'tauk');
M_.endo_names = char(M_.endo_names, 'taul');
M_.endo_names_tex = char(M_.endo_names_tex, 'taul');
M_.endo_names_long = char(M_.endo_names_long, 'taul');
M_.endo_names = char(M_.endo_names, 'tauc');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauc');
M_.endo_names_long = char(M_.endo_names_long, 'tauc');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'kbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbar');
M_.endo_names_long = char(M_.endo_names_long, 'kbar');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'Pb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pb');
M_.endo_names_long = char(M_.endo_names_long, 'Pb');
M_.endo_names = char(M_.endo_names, 'cstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstar');
M_.endo_names_long = char(M_.endo_names_long, 'cstar');
M_.endo_names = char(M_.endo_names, 'piL');
M_.endo_names_tex = char(M_.endo_names_tex, 'piL');
M_.endo_names_long = char(M_.endo_names_long, 'piL');
M_.endo_names = char(M_.endo_names, 'rL');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL');
M_.endo_names_long = char(M_.endo_names_long, 'rL');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rb');
M_.endo_names_long = char(M_.endo_names_long, 'rb');
M_.endo_names = char(M_.endo_names, 'Tk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tk');
M_.endo_names_long = char(M_.endo_names_long, 'Tk');
M_.endo_names = char(M_.endo_names, 'Tl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tl');
M_.endo_names_long = char(M_.endo_names_long, 'Tl');
M_.endo_names = char(M_.endo_names, 'Tc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tc');
M_.endo_names_long = char(M_.endo_names_long, 'Tc');
M_.endo_names = char(M_.endo_names, 'cobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'cobs');
M_.endo_names_long = char(M_.endo_names_long, 'cobs');
M_.endo_names = char(M_.endo_names, 'iobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'iobs');
M_.endo_names_long = char(M_.endo_names_long, 'iobs');
M_.endo_names = char(M_.endo_names, 'gcobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcobs');
M_.endo_names_long = char(M_.endo_names_long, 'gcobs');
M_.endo_names = char(M_.endo_names, 'wobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wobs');
M_.endo_names_long = char(M_.endo_names_long, 'wobs');
M_.endo_names = char(M_.endo_names, 'bobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bobs');
M_.endo_names_long = char(M_.endo_names_long, 'bobs');
M_.endo_names = char(M_.endo_names, 'Robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Robs');
M_.endo_names_long = char(M_.endo_names_long, 'Robs');
M_.endo_names = char(M_.endo_names, 'Piobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Piobs');
M_.endo_names_long = char(M_.endo_names_long, 'Piobs');
M_.endo_names = char(M_.endo_names, 'Lobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lobs');
M_.endo_names_long = char(M_.endo_names_long, 'Lobs');
M_.endo_names = char(M_.endo_names, 'ugc');
M_.endo_names_tex = char(M_.endo_names_tex, 'ugc');
M_.endo_names_long = char(M_.endo_names_long, 'ugc');
M_.endo_names = char(M_.endo_names, 'uz');
M_.endo_names_tex = char(M_.endo_names_tex, 'uz');
M_.endo_names_long = char(M_.endo_names_long, 'uz');
M_.endo_names = char(M_.endo_names, 'ua');
M_.endo_names_tex = char(M_.endo_names_tex, 'ua');
M_.endo_names_long = char(M_.endo_names_long, 'ua');
M_.endo_names = char(M_.endo_names, 'ub');
M_.endo_names_tex = char(M_.endo_names_tex, 'ub');
M_.endo_names_long = char(M_.endo_names_long, 'ub');
M_.endo_names = char(M_.endo_names, 'um');
M_.endo_names_tex = char(M_.endo_names_tex, 'um');
M_.endo_names_long = char(M_.endo_names_long, 'um');
M_.endo_names = char(M_.endo_names, 'ui');
M_.endo_names_tex = char(M_.endo_names_tex, 'ui');
M_.endo_names_long = char(M_.endo_names_long, 'ui');
M_.endo_names = char(M_.endo_names, 'uw');
M_.endo_names_tex = char(M_.endo_names_tex, 'uw');
M_.endo_names_long = char(M_.endo_names_long, 'uw');
M_.endo_names = char(M_.endo_names, 'up');
M_.endo_names_tex = char(M_.endo_names_tex, 'up');
M_.endo_names_long = char(M_.endo_names_long, 'up');
M_.endo_partitions = struct();
M_.param_names = 'AD';
M_.param_names_tex = 'AD';
M_.param_names_long = 'AD';
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, 'bet');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'delt');
M_.param_names_tex = char(M_.param_names_tex, 'delt');
M_.param_names_long = char(M_.param_names_long, 'delt');
M_.param_names = char(M_.param_names, 'alph');
M_.param_names_tex = char(M_.param_names_tex, 'alph');
M_.param_names_long = char(M_.param_names_long, 'alph');
M_.param_names = char(M_.param_names, 'etaw');
M_.param_names_tex = char(M_.param_names_tex, 'etaw');
M_.param_names_long = char(M_.param_names_long, 'etaw');
M_.param_names = char(M_.param_names, 'etap');
M_.param_names_tex = char(M_.param_names_tex, 'etap');
M_.param_names_long = char(M_.param_names_long, 'etap');
M_.param_names = char(M_.param_names, 'gamm100');
M_.param_names_tex = char(M_.param_names_tex, 'gamm100');
M_.param_names_long = char(M_.param_names_long, 'gamm100');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'muHH');
M_.param_names_tex = char(M_.param_names_tex, 'muHH');
M_.param_names_long = char(M_.param_names_long, 'muHH');
M_.param_names = char(M_.param_names, 'omegaw');
M_.param_names_tex = char(M_.param_names_tex, 'omegaw');
M_.param_names_long = char(M_.param_names_long, 'omegaw');
M_.param_names = char(M_.param_names, 'omegap');
M_.param_names_tex = char(M_.param_names_tex, 'omegap');
M_.param_names_long = char(M_.param_names_long, 'omegap');
M_.param_names = char(M_.param_names, 'gpsi');
M_.param_names_tex = char(M_.param_names_tex, 'gpsi');
M_.param_names_long = char(M_.param_names_long, 'gpsi');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'chiw');
M_.param_names_tex = char(M_.param_names_tex, 'chiw');
M_.param_names_long = char(M_.param_names_long, 'chiw');
M_.param_names = char(M_.param_names, 'chip');
M_.param_names_tex = char(M_.param_names_tex, 'chip');
M_.param_names_long = char(M_.param_names_long, 'chip');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names_long = char(M_.param_names_long, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'gammgc');
M_.param_names_tex = char(M_.param_names_tex, 'gammgc');
M_.param_names_long = char(M_.param_names_long, 'gammgc');
M_.param_names = char(M_.param_names, 'gammtk');
M_.param_names_tex = char(M_.param_names_tex, 'gammtk');
M_.param_names_long = char(M_.param_names_long, 'gammtk');
M_.param_names = char(M_.param_names, 'gammtl');
M_.param_names_tex = char(M_.param_names_tex, 'gammtl');
M_.param_names_long = char(M_.param_names_long, 'gammtl');
M_.param_names = char(M_.param_names, 'gammz');
M_.param_names_tex = char(M_.param_names_tex, 'gammz');
M_.param_names_long = char(M_.param_names_long, 'gammz');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhob');
M_.param_names_tex = char(M_.param_names_tex, 'rhob');
M_.param_names_long = char(M_.param_names_long, 'rhob');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names_long = char(M_.param_names_long, 'rhoi');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhop');
M_.param_names_tex = char(M_.param_names_tex, 'rhop');
M_.param_names_long = char(M_.param_names_long, 'rhop');
M_.param_names = char(M_.param_names, 'rhogc');
M_.param_names_tex = char(M_.param_names_tex, 'rhogc');
M_.param_names_long = char(M_.param_names_long, 'rhogc');
M_.param_names = char(M_.param_names, 'rhotk');
M_.param_names_tex = char(M_.param_names_tex, 'rhotk');
M_.param_names_long = char(M_.param_names_long, 'rhotk');
M_.param_names = char(M_.param_names, 'rhotl');
M_.param_names_tex = char(M_.param_names_tex, 'rhotl');
M_.param_names_long = char(M_.param_names_long, 'rhotl');
M_.param_names = char(M_.param_names, 'rhotc');
M_.param_names_tex = char(M_.param_names_tex, 'rhotc');
M_.param_names_long = char(M_.param_names_long, 'rhotc');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'siga');
M_.param_names_tex = char(M_.param_names_tex, 'siga');
M_.param_names_long = char(M_.param_names_long, 'siga');
M_.param_names = char(M_.param_names, 'sigb');
M_.param_names_tex = char(M_.param_names_tex, 'sigb');
M_.param_names_long = char(M_.param_names_long, 'sigb');
M_.param_names = char(M_.param_names, 'sigm');
M_.param_names_tex = char(M_.param_names_tex, 'sigm');
M_.param_names_long = char(M_.param_names_long, 'sigm');
M_.param_names = char(M_.param_names, 'sigi');
M_.param_names_tex = char(M_.param_names_tex, 'sigi');
M_.param_names_long = char(M_.param_names_long, 'sigi');
M_.param_names = char(M_.param_names, 'sigw');
M_.param_names_tex = char(M_.param_names_tex, 'sigw');
M_.param_names_long = char(M_.param_names_long, 'sigw');
M_.param_names = char(M_.param_names, 'sigp');
M_.param_names_tex = char(M_.param_names_tex, 'sigp');
M_.param_names_long = char(M_.param_names_long, 'sigp');
M_.param_names = char(M_.param_names, 'siggc');
M_.param_names_tex = char(M_.param_names_tex, 'siggc');
M_.param_names_long = char(M_.param_names_long, 'siggc');
M_.param_names = char(M_.param_names, 'sigz');
M_.param_names_tex = char(M_.param_names_tex, 'sigz');
M_.param_names_long = char(M_.param_names_long, 'sigz');
M_.param_names = char(M_.param_names, 'thet');
M_.param_names_tex = char(M_.param_names_tex, 'thet');
M_.param_names_long = char(M_.param_names_long, 'thet');
M_.param_names = char(M_.param_names, 'alphag');
M_.param_names_tex = char(M_.param_names_tex, 'alphag');
M_.param_names_long = char(M_.param_names_long, 'alphag');
M_.param_names = char(M_.param_names, 'rhoem');
M_.param_names_tex = char(M_.param_names_tex, 'rhoem');
M_.param_names_long = char(M_.param_names_long, 'rhoem');
M_.param_names = char(M_.param_names, 'rhoeg');
M_.param_names_tex = char(M_.param_names_tex, 'rhoeg');
M_.param_names_long = char(M_.param_names_long, 'rhoeg');
M_.param_names = char(M_.param_names, 'rhoez');
M_.param_names_tex = char(M_.param_names_tex, 'rhoez');
M_.param_names_long = char(M_.param_names_long, 'rhoez');
M_.param_names = char(M_.param_names, 'Lbar');
M_.param_names_tex = char(M_.param_names_tex, 'Lbar');
M_.param_names_long = char(M_.param_names_long, 'Lbar');
M_.param_names = char(M_.param_names, 'Pibar');
M_.param_names_tex = char(M_.param_names_tex, 'Pibar');
M_.param_names_long = char(M_.param_names_long, 'Pibar');
M_.param_names = char(M_.param_names, 'lamprice');
M_.param_names_tex = char(M_.param_names_tex, 'lamprice');
M_.param_names_long = char(M_.param_names_long, 'lamprice');
M_.param_names = char(M_.param_names, 'lamwage');
M_.param_names_tex = char(M_.param_names_tex, 'lamwage');
M_.param_names_long = char(M_.param_names_long, 'lamwage');
M_.param_names = char(M_.param_names, 'sbss');
M_.param_names_tex = char(M_.param_names_tex, 'sbss');
M_.param_names_long = char(M_.param_names_long, 'sbss');
M_.param_names = char(M_.param_names, 'taulss');
M_.param_names_tex = char(M_.param_names_tex, 'taulss');
M_.param_names_long = char(M_.param_names_long, 'taulss');
M_.param_names = char(M_.param_names, 'taukss');
M_.param_names_tex = char(M_.param_names_tex, 'taukss');
M_.param_names_long = char(M_.param_names_long, 'taukss');
M_.param_names = char(M_.param_names, 'taucss');
M_.param_names_tex = char(M_.param_names_tex, 'taucss');
M_.param_names_long = char(M_.param_names_long, 'taucss');
M_.param_names = char(M_.param_names, 'Rhoss');
M_.param_names_tex = char(M_.param_names_tex, 'Rhoss');
M_.param_names_long = char(M_.param_names_long, 'Rhoss');
M_.param_names = char(M_.param_names, 'gammss');
M_.param_names_tex = char(M_.param_names_tex, 'gammss');
M_.param_names_long = char(M_.param_names_long, 'gammss');
M_.param_names = char(M_.param_names, 'expgss');
M_.param_names_tex = char(M_.param_names_tex, 'expgss');
M_.param_names_long = char(M_.param_names_long, 'expgss');
M_.param_names = char(M_.param_names, 'Rss');
M_.param_names_tex = char(M_.param_names_tex, 'Rss');
M_.param_names_long = char(M_.param_names_long, 'Rss');
M_.param_names = char(M_.param_names, 'Rbarss');
M_.param_names_tex = char(M_.param_names_tex, 'Rbarss');
M_.param_names_long = char(M_.param_names_long, 'Rbarss');
M_.param_names = char(M_.param_names, 'Pbss');
M_.param_names_tex = char(M_.param_names_tex, 'Pbss');
M_.param_names_long = char(M_.param_names_long, 'Pbss');
M_.param_names = char(M_.param_names, 'Rkss');
M_.param_names_tex = char(M_.param_names_tex, 'Rkss');
M_.param_names_long = char(M_.param_names_long, 'Rkss');
M_.param_names = char(M_.param_names, 'psi1ss');
M_.param_names_tex = char(M_.param_names_tex, 'psi1ss');
M_.param_names_long = char(M_.param_names_long, 'psi1ss');
M_.param_names = char(M_.param_names, 'mcss');
M_.param_names_tex = char(M_.param_names_tex, 'mcss');
M_.param_names_long = char(M_.param_names_long, 'mcss');
M_.param_names = char(M_.param_names, 'wss');
M_.param_names_tex = char(M_.param_names_tex, 'wss');
M_.param_names_long = char(M_.param_names_long, 'wss');
M_.param_names = char(M_.param_names, 'KLss');
M_.param_names_tex = char(M_.param_names_tex, 'KLss');
M_.param_names_long = char(M_.param_names_long, 'KLss');
M_.param_names = char(M_.param_names, 'OmegLss');
M_.param_names_tex = char(M_.param_names_tex, 'OmegLss');
M_.param_names_long = char(M_.param_names_long, 'OmegLss');
M_.param_names = char(M_.param_names, 'YLss');
M_.param_names_tex = char(M_.param_names_tex, 'YLss');
M_.param_names_long = char(M_.param_names_long, 'YLss');
M_.param_names = char(M_.param_names, 'ILss');
M_.param_names_tex = char(M_.param_names_tex, 'ILss');
M_.param_names_long = char(M_.param_names_long, 'ILss');
M_.param_names = char(M_.param_names, 'CLss');
M_.param_names_tex = char(M_.param_names_tex, 'CLss');
M_.param_names_long = char(M_.param_names_long, 'CLss');
M_.param_names = char(M_.param_names, 'rkss');
M_.param_names_tex = char(M_.param_names_tex, 'rkss');
M_.param_names_long = char(M_.param_names_long, 'rkss');
M_.param_names = char(M_.param_names, 'ZLss');
M_.param_names_tex = char(M_.param_names_tex, 'ZLss');
M_.param_names_long = char(M_.param_names_long, 'ZLss');
M_.param_names = char(M_.param_names, 'ZnLss');
M_.param_names_tex = char(M_.param_names_tex, 'ZnLss');
M_.param_names_long = char(M_.param_names_long, 'ZnLss');
M_.param_names = char(M_.param_names, 'CnLss');
M_.param_names_tex = char(M_.param_names_tex, 'CnLss');
M_.param_names_long = char(M_.param_names_long, 'CnLss');
M_.param_names = char(M_.param_names, 'CsLss');
M_.param_names_tex = char(M_.param_names_tex, 'CsLss');
M_.param_names_long = char(M_.param_names_long, 'CsLss');
M_.param_names = char(M_.param_names, 'CstarLss');
M_.param_names_tex = char(M_.param_names_tex, 'CstarLss');
M_.param_names_long = char(M_.param_names_long, 'CstarLss');
M_.param_names = char(M_.param_names, 'lss');
M_.param_names_tex = char(M_.param_names_tex, 'lss');
M_.param_names_long = char(M_.param_names_long, 'lss');
M_.param_names = char(M_.param_names, 'csss');
M_.param_names_tex = char(M_.param_names_tex, 'csss');
M_.param_names_long = char(M_.param_names_long, 'csss');
M_.param_names = char(M_.param_names, 'cnss');
M_.param_names_tex = char(M_.param_names_tex, 'cnss');
M_.param_names_long = char(M_.param_names_long, 'cnss');
M_.param_names = char(M_.param_names, 'yss');
M_.param_names_tex = char(M_.param_names_tex, 'yss');
M_.param_names_long = char(M_.param_names_long, 'yss');
M_.param_names = char(M_.param_names, 'kss');
M_.param_names_tex = char(M_.param_names_tex, 'kss');
M_.param_names_long = char(M_.param_names_long, 'kss');
M_.param_names = char(M_.param_names, 'Omegss');
M_.param_names_tex = char(M_.param_names_tex, 'Omegss');
M_.param_names_long = char(M_.param_names_long, 'Omegss');
M_.param_names = char(M_.param_names, 'css');
M_.param_names_tex = char(M_.param_names_tex, 'css');
M_.param_names_long = char(M_.param_names_long, 'css');
M_.param_names = char(M_.param_names, 'invss');
M_.param_names_tex = char(M_.param_names_tex, 'invss');
M_.param_names_long = char(M_.param_names_long, 'invss');
M_.param_names = char(M_.param_names, 'zss');
M_.param_names_tex = char(M_.param_names_tex, 'zss');
M_.param_names_long = char(M_.param_names_long, 'zss');
M_.param_names = char(M_.param_names, 'bss');
M_.param_names_tex = char(M_.param_names_tex, 'bss');
M_.param_names_long = char(M_.param_names_long, 'bss');
M_.param_names = char(M_.param_names, 'gcss');
M_.param_names_tex = char(M_.param_names_tex, 'gcss');
M_.param_names_long = char(M_.param_names_long, 'gcss');
M_.param_names = char(M_.param_names, 'kyss');
M_.param_names_tex = char(M_.param_names_tex, 'kyss');
M_.param_names_long = char(M_.param_names_long, 'kyss');
M_.param_names = char(M_.param_names, 'cyss');
M_.param_names_tex = char(M_.param_names_tex, 'cyss');
M_.param_names_long = char(M_.param_names_long, 'cyss');
M_.param_names = char(M_.param_names, 'lyss');
M_.param_names_tex = char(M_.param_names_tex, 'lyss');
M_.param_names_long = char(M_.param_names_long, 'lyss');
M_.param_names = char(M_.param_names, 'TKss');
M_.param_names_tex = char(M_.param_names_tex, 'TKss');
M_.param_names_long = char(M_.param_names_long, 'TKss');
M_.param_names = char(M_.param_names, 'TLss');
M_.param_names_tex = char(M_.param_names_tex, 'TLss');
M_.param_names_long = char(M_.param_names_long, 'TLss');
M_.param_names = char(M_.param_names, 'TCss');
M_.param_names_tex = char(M_.param_names_tex, 'TCss');
M_.param_names_long = char(M_.param_names_long, 'TCss');
M_.param_names = char(M_.param_names, 'Sss');
M_.param_names_tex = char(M_.param_names_tex, 'Sss');
M_.param_names_long = char(M_.param_names_long, 'Sss');
M_.param_names = char(M_.param_names, 'sgcss');
M_.param_names_tex = char(M_.param_names_tex, 'sgcss');
M_.param_names_long = char(M_.param_names_long, 'sgcss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 49;
M_.param_nbr = 93;
M_.orig_endo_nbr = 49;
M_.aux_vars = [];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_LTW17_rep_static');
erase_compiled_function('US_LTW17_rep_dynamic');
M_.orig_eq_nbr = 49;
M_.eq_nbr = 49;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 24 0;
 0 25 0;
 1 26 0;
 2 27 73;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 3 32 0;
 4 33 0;
 0 34 74;
 0 35 75;
 5 36 76;
 6 37 77;
 7 38 0;
 8 39 0;
 9 40 78;
 10 41 0;
 11 42 0;
 0 43 0;
 12 44 0;
 0 45 0;
 13 46 0;
 0 47 79;
 14 48 80;
 15 49 0;
 0 50 0;
 0 51 81;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 16 65 0;
 17 66 0;
 18 67 0;
 19 68 0;
 20 69 0;
 21 70 0;
 22 71 0;
 23 72 0;]';
M_.nstatic = 22;
M_.nfwrd   = 4;
M_.npred   = 18;
M_.nboth   = 5;
M_.nsfwrd   = 9;
M_.nspred   = 23;
M_.ndynamic   = 27;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(49, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(93, 1);
M_.NNZDerivatives = [210; 0; -1];
M_.params( 1 ) = 20;
AD = M_.params( 1 );
M_.params( 2 ) = 0.99;
bet = M_.params( 2 );
M_.params( 3 ) = 0.025;
delt = M_.params( 3 );
M_.params( 4 ) = 0.33;
alph = M_.params( 4 );
M_.params( 5 ) = 0.14;
etaw = M_.params( 5 );
M_.params( 6 ) = 0.14;
etap = M_.params( 6 );
M_.params( 93 ) = 0.11;
sgcss = M_.params( 93 );
M_.params( 50 ) = 1.47;
sbss = M_.params( 50 );
M_.params( 51 ) = 0.186;
taulss = M_.params( 51 );
M_.params( 52 ) = 0.218;
taukss = M_.params( 52 );
M_.params( 53 ) = 0.023;
taucss = M_.params( 53 );
M_.params( 7 ) = 0.242968973360760;
gamm100 = M_.params( 7 );
M_.params( 8 ) = 1.540098680199818;
xi = M_.params( 8 );
M_.params( 9 ) = 0;
muHH = M_.params( 9 );
M_.params( 10 ) = 0.873633441786572;
omegaw = M_.params( 10 );
M_.params( 11 ) = 0.889634877904653;
omegap = M_.params( 11 );
M_.params( 12 ) = 0.126297919145076;
gpsi = M_.params( 12 );
M_.params( 13 ) = 5.213147230492578;
s = M_.params( 13 );
M_.params( 14 ) = 0.089393160044567;
chiw = M_.params( 14 );
M_.params( 15 ) = 0.060355303068460;
chip = M_.params( 15 );
M_.params( 16 ) = 1.142492263502070;
phipi = M_.params( 16 );
M_.params( 17 ) = 0.178225311630840;
phiy = M_.params( 17 );
M_.params( 18 ) = 0.214956274043740;
gammgc = M_.params( 18 );
M_.params( 19 ) = 0;
gammtk = M_.params( 19 );
M_.params( 20 ) = 0;
gammtl = M_.params( 20 );
M_.params( 21 ) = (-0.028247874637231);
gammz = M_.params( 21 );
M_.params( 22 ) = 0.251431768280169;
rhoa = M_.params( 22 );
M_.params( 23 ) = 0.314713788054350;
rhob = M_.params( 23 );
M_.params( 24 ) = 0.756483804459602;
rhor = M_.params( 24 );
M_.params( 25 ) = 0.511411853483883;
rhoi = M_.params( 25 );
M_.params( 26 ) = 0.326894727384245;
rhow = M_.params( 26 );
M_.params( 27 ) = 0.724249353191094;
rhop = M_.params( 27 );
M_.params( 28 ) = 0.984047962915516;
rhogc = M_.params( 28 );
M_.params( 29 ) = 0;
rhotk = M_.params( 29 );
M_.params( 30 ) = 0;
rhotl = M_.params( 30 );
M_.params( 31 ) = 0;
rhotc = M_.params( 31 );
M_.params( 32 ) = 0.98;
rhoz = M_.params( 32 );
M_.params( 33 ) = 1.03292319884557;
siga = M_.params( 33 );
M_.params( 34 ) = 42.6559249998644;
sigb = M_.params( 34 );
M_.params( 35 ) = 0.231187433032408;
sigm = M_.params( 35 );
M_.params( 36 ) = 0.978941599253400;
sigi = M_.params( 36 );
M_.params( 37 ) = 0.250356962066959;
sigw = M_.params( 37 );
M_.params( 38 ) = 0.0988174659346631;
sigp = M_.params( 38 );
M_.params( 39 ) = 1.83235871273796;
siggc = M_.params( 39 );
M_.params( 40 ) = 2.68115974402062;
sigz = M_.params( 40 );
M_.params( 41 ) = 0.989468754445726;
thet = M_.params( 41 );
M_.params( 42 ) = (-0.185909020087479);
alphag = M_.params( 42 );
M_.params( 43 ) = 0;
rhoem = M_.params( 43 );
M_.params( 44 ) = 0.126568144141410;
rhoeg = M_.params( 44 );
M_.params( 45 ) = 0.8;
rhoez = M_.params( 45 );
M_.params( 46 ) = 475.202534563017;
Lbar = M_.params( 46 );
M_.params( 47 ) = 0.643991271663901;
Pibar = M_.params( 47 );
M_.params( 48 ) = (1+M_.params(2)*M_.params(15))*M_.params(11)/((1-M_.params(2)*M_.params(11))*(1-M_.params(11)));
lamprice = M_.params( 48 );
M_.params( 49 ) = M_.params(10)*(1+M_.params(2))*(1+M_.params(8)*(1+1/M_.params(5)))/((1-M_.params(2)*M_.params(10))*(1-M_.params(10)));
lamwage = M_.params( 49 );
M_.params( 54 ) = (1-1/M_.params(1))*1/M_.params(2);
Rhoss = M_.params( 54 );
M_.params( 55 ) = M_.params(7)/100;
gammss = M_.params( 55 );
M_.params( 56 ) = exp(M_.params(55));
expgss = M_.params( 56 );
M_.params( 57 ) = M_.params(56)/M_.params(2);
Rss = M_.params( 57 );
M_.params( 58 ) = 100*(M_.params(57)-1);
Rbarss = M_.params( 58 );
M_.params( 59 ) = 1/(M_.params(57)-M_.params(54));
Pbss = M_.params( 59 );
M_.params( 60 ) = (exp(M_.params(55))/M_.params(2)-1+M_.params(3))/(1-M_.params(52));
Rkss = M_.params( 60 );
M_.params( 61 ) = (1-M_.params(52))*M_.params(60);
psi1ss = M_.params( 61 );
M_.params( 62 ) = 1/(1+M_.params(6));
mcss = M_.params( 62 );
M_.params( 63 ) = (M_.params(62)*(1-M_.params(4))^(1-M_.params(4))*M_.params(4)^M_.params(4)*M_.params(60)^(-M_.params(4)))^(1/(1-M_.params(4)));
wss = M_.params( 63 );
M_.params( 64 ) = M_.params(4)*M_.params(63)/M_.params(60)/(1-M_.params(4));
KLss = M_.params( 64 );
M_.params( 65 ) = M_.params(64)^M_.params(4)-M_.params(60)*M_.params(64)-M_.params(63);
OmegLss = M_.params( 65 );
M_.params( 66 ) = M_.params(64)^M_.params(4)-M_.params(65);
YLss = M_.params( 66 );
M_.params( 67 ) = M_.params(64)*M_.params(56)*(1-(1-M_.params(3))*exp((-M_.params(55))));
ILss = M_.params( 67 );
M_.params( 68 ) = M_.params(66)*(1-M_.params(93))-M_.params(67);
CLss = M_.params( 68 );
M_.params( 69 ) = M_.params(60);
rkss = M_.params( 69 );
M_.params( 70 ) = M_.params(66)*((1-M_.params(57)*exp((-M_.params(55))))*M_.params(50)-M_.params(93))+M_.params(53)*M_.params(68)+M_.params(63)*M_.params(51)+M_.params(64)*M_.params(52)*M_.params(69);
ZLss = M_.params( 70 );
M_.params( 71 ) = M_.params(70);
ZnLss = M_.params( 71 );
M_.params( 72 ) = (M_.params(63)*(1-M_.params(51))+M_.params(71))/(1+M_.params(53));
CnLss = M_.params( 72 );
M_.params( 73 ) = (M_.params(68)-M_.params(9)*M_.params(72))/(1-M_.params(9));
CsLss = M_.params( 73 );
M_.params( 74 ) = M_.params(73)+M_.params(66)*M_.params(93)*M_.params(42);
CstarLss = M_.params( 74 );
M_.params( 75 ) = (M_.params(63)*(1-M_.params(51))/((1+M_.params(53))*(1+M_.params(5)))*1/((1-exp((-M_.params(55)))*M_.params(41))*M_.params(74)))^(1/(1+M_.params(8)));
lss = M_.params( 75 );
M_.params( 76 ) = M_.params(73)*M_.params(75);
csss = M_.params( 76 );
M_.params( 77 ) = M_.params(72)*M_.params(75);
cnss = M_.params( 77 );
M_.params( 78 ) = M_.params(66)*M_.params(75);
yss = M_.params( 78 );
M_.params( 79 ) = M_.params(64)*M_.params(75);
kss = M_.params( 79 );
M_.params( 80 ) = M_.params(65)*M_.params(75);
Omegss = M_.params( 80 );
M_.params( 81 ) = M_.params(68)*M_.params(75);
css = M_.params( 81 );
M_.params( 82 ) = M_.params(67)*M_.params(75);
invss = M_.params( 82 );
M_.params( 83 ) = M_.params(70)*M_.params(75);
zss = M_.params( 83 );
M_.params( 84 ) = M_.params(50)*M_.params(78);
bss = M_.params( 84 );
M_.params( 85 ) = M_.params(93)*M_.params(78);
gcss = M_.params( 85 );
M_.params( 86 ) = M_.params(79)/M_.params(78);
kyss = M_.params( 86 );
M_.params( 87 ) = M_.params(81)/M_.params(78);
cyss = M_.params( 87 );
M_.params( 88 ) = M_.params(75)/M_.params(78);
lyss = M_.params( 88 );
M_.params( 89 ) = M_.params(52)*M_.params(69)*M_.params(79);
TKss = M_.params( 89 );
M_.params( 90 ) = M_.params(63)*M_.params(51)*M_.params(75);
TLss = M_.params( 90 );
M_.params( 91 ) = M_.params(53)*M_.params(81);
TCss = M_.params( 91 );
M_.params( 92 ) = M_.params(53)*M_.params(81)+M_.params(52)*M_.params(69)*M_.params(79)+M_.params(63)*M_.params(51)*M_.params(75)-M_.params(85)-M_.params(83);
Sss = M_.params( 92 );
oo_.dr.eigval = check(M_,options_,oo_);
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(39)^2;
M_.Sigma_e(2, 2) = M_.params(40)^2;
M_.Sigma_e(3, 3) = M_.params(33)^2;
M_.Sigma_e(4, 4) = M_.params(34)^2;
M_.Sigma_e(5, 5) = M_.params(35)^2;
M_.Sigma_e(6, 6) = M_.params(36)^2;
M_.Sigma_e(7, 7) = M_.params(37)^2;
M_.Sigma_e(8, 8) = M_.params(38)^2;
options_.irf = 40;
options_.nograph = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('US_LTW17_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_LTW17_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_LTW17_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_LTW17_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_LTW17_rep_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_LTW17_rep_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_LTW17_rep_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
