% Replication of impulse response functions

% Sebastian Kripfganz, Goethe-University Frankfurt
% February 17, 2010

% This file plots all impulse response functions in one figure using the
%  data generated by the 'stoch_simul' function of the Dynare package.
% Note that this code requires Dynare, version 3.

clear all;
clc;

% Adjust path to folder where replication file is stored
cd([cd '/CL_MS07_rep']);


% Simulation with the real interest rate as the policy instrument
dynare 'ms07replic_r'

% Reordering of the shock variables according to the original figures
lgxx_(1,:)  = lgx_(1,:);
lgxx_(2,:)  = lgx_(12,:);
lgxx_(3,:)  = lgx_(14,:);
lgxx_(4,:)  = lgx_(11,:);
lgxx_(5,:)  = lgx_(9,:);
lgxx_(6,:)  = lgx_(8,:);
lgxx_(7,:)  = lgx_(2,:);
lgxx_(8,:)  = lgx_(10,:);
lgxx_(9,:)  = lgx_(7,:);
lgxx_(10,:) = lgx_(6,:);
lgxx_(11,:) = lgx_(13,:);
lgxx_(12,:) = lgx_(3,:);
lgxx_(13,:) = lgx_(4,:);
lgxx_(14,:) = lgx_(5,:);

% Storage of impulse response functions
nov_ = size(var_list_,1);    % number of variables
nox_ = size(lgxx_,1);        % number of shocks
irf_r = zeros(options_.irf,nov_,nox_);
for jj = 1:nov_
    for kk = 1:nox_
        sh_name = deblank(lgxx_(kk,:));
        var_name = deblank(var_list_(jj,:));
        irf_name = strcat(var_name,'_',sh_name);
        irf_r(:,jj,kk) = eval(irf_name);
    end
end
save('ms07replic_r.mat','irf_r','lgxx_','nov_','nox_')

% Simulation with the nominal interest rate as the policy instrument
dynare 'ms07replic_i'

load('ms07replic_r.mat')
irf_i = zeros(options_.irf,nov_,nox_);
for jj = 1:nov_
    for kk = 1:nox_
        sh_name = deblank(lgxx_(kk,:));
        var_name = deblank(var_list_(jj,:));
        irf_name = strcat(var_name,'_',sh_name);
        irf_i(:,jj,kk) = eval(irf_name);
    end
end

figure
for jj = 1:(nov_*ceil(nox_/2))
    subplot(ceil(nox_/2),nov_,jj);
    sh_nr = ceil(jj/nov_);
    var_nr = jj-nov_*(sh_nr-1);
    irf_data_r = irf_r(:,var_nr,sh_nr);
    irf_data_i = irf_i(:,var_nr,sh_nr);
    plot(0:options_.irf-1,irf_data_r(1:options_.irf),'-r','linewidth',2)
    hold on
    plot(0:options_.irf-1,irf_data_i(1:options_.irf),'-b','linewidth',2)
    hold on
    plot([0 options_.irf-1],[0 0],'-k','linewidth',2);
    hold off
end

subplot(7,5,1);
ylim([-0.5 0.5]);
title('\Delta y');
ylabel('a_H');
subplot(7,5,2);
ylim([-0.2 0.2]);
title('\pi_Z');
subplot(7,5,3);
ylim([0 1]);
title('rer');
subplot(7,5,4);
ylim([-2 2]);
title('l');
subplot(7,5,5);
ylim([-0.5 0.5]);
title('CA/Y');

subplot(7,5,6);
ylim([0 0.4]);
ylabel('\zeta_T');
subplot(7,5,7);
ylim([-0.1 0.1]);
subplot(7,5,8);
ylim([-1 0]);
subplot(7,5,9);
ylim([-0.2 0.2]);
subplot(7,5,10);
ylim([-0.2 0.2]);

subplot(7,5,11);
ylim([-1 1]);
ylabel('y_S');
subplot(7,5,12);
ylim([-0.02 0.02]);
subplot(7,5,13);
ylim([-0.2 0.2]);
subplot(7,5,14);
ylim([0 0.2]);
subplot(7,5,15);
ylim([-0.2 0.2]);

subplot(7,5,16);
ylim([-0.02 0.02]);
ylabel('\zeta_L');
subplot(7,5,17);
ylim([-0.005 0.005]);
subplot(7,5,18);
ylim([-0.1 0]);
subplot(7,5,19);
ylim([-0.1 0]);
subplot(7,5,20);
ylim([-0.02 0.02]);

subplot(7,5,21);
ylim([-1 1]);
ylabel('\zeta_I');
subplot(7,5,22);
ylim([-0.1 0.1]);
subplot(7,5,23);
ylim([0 0.5]);
subplot(7,5,24);
ylim([-2 2]);
subplot(7,5,25);
ylim([-1 1]);

subplot(7,5,26);
ylim([-0.2 0.2]);
ylabel('\zeta_C');
subplot(7,5,27);
ylim([0 0.04]);
subplot(7,5,28);
ylim([-0.4 0]);
subplot(7,5,29);
ylim([-0.5 0.5]);
subplot(7,5,30);
ylim([-0.2 0.2]);

subplot(7,5,31);
ylim([-0.2 0.2]);
ylabel('\zeta_G');
subplot(7,5,32);
ylim([-0.01 0.01]);
subplot(7,5,33);
ylim([-0.05 0.05]);
subplot(7,5,34);
ylim([-0.5 0.5]);
subplot(7,5,35);
ylim([-0.02 0.02]);

figure
for jj = 1:(nov_*ceil(nox_/2))
    subplot(ceil(nox_/2),nov_,jj);
    sh_nr = ceil(jj/nov_)+7;
    var_nr = jj-nov_*(sh_nr-8);
    irf_data_r = irf_r(:,var_nr,sh_nr);
    irf_data_i = irf_i(:,var_nr,sh_nr);
    plot(0:options_.irf-1,irf_data_r(1:options_.irf),'-r','linewidth',2)
    hold on
    plot(0:options_.irf-1,irf_data_i(1:options_.irf),'-b','linewidth',2)
    hold on
    plot([0 options_.irf-1],[0 0],'-k','linewidth',2);
    hold off
end

subplot(7,5,1);
ylim([-0.5 0.5]);
title('\Delta y');
ylabel('\zeta_m');
subplot(7,5,2);
ylim([-0.2 0.2]);
title('\pi_Z');
subplot(7,5,3);
ylim([-2 0]);
title('rer');
subplot(7,5,4);
ylim([-1 0]);
title('l');
subplot(7,5,5);
ylim([-0.5 0.5]);
title('CA/Y');

subplot(7,5,6);
ylim([-0.1 0.1]);
ylabel('p_S^\ast');
subplot(7,5,7);
ylim([-0.05 0.05]);
subplot(7,5,8);
ylim([-0.5 0]);
subplot(7,5,9);
ylim([0 0.4]);
subplot(7,5,10);
ylim([-0.5 0.5]);

subplot(7,5,11);
ylim([-0.1 0.1]);
ylabel('p_O^\ast');
subplot(7,5,12);
ylim([-0.05 0.05]);
subplot(7,5,13);
ylim([-0.4 0]);
subplot(7,5,14);
ylim([-0.4 0]);
subplot(7,5,15);
ylim([-0.2 0.2]);

subplot(7,5,16);
ylim([-1 1]);
ylabel('y^\ast');
subplot(7,5,17);
ylim([-0.05 0.05]);
subplot(7,5,18);
ylim([-0.5 0.5]);
subplot(7,5,19);
ylim([0 2]);
subplot(7,5,20);
ylim([-1 1]);

subplot(7,5,21);
ylim([-0.2 0.2]);
ylabel('i^\ast');
subplot(7,5,22);
ylim([-0.5 0.5]);
subplot(7,5,23);
ylim([-2 2]);
subplot(7,5,24);
ylim([-0.5 0.5]);
subplot(7,5,25);
ylim([-0.5 0.5]);

subplot(7,5,26);
ylim([-0.05 0.05]);
ylabel('\pi^\ast');
subplot(7,5,27);
ylim([-0.1 0.1]);
subplot(7,5,28);
ylim([-1 1]);
subplot(7,5,29);
ylim([-0.2 0.2]);
subplot(7,5,30);
ylim([-0.5 0.5]);

subplot(7,5,31);
ylim([-0.5 0.5]);
ylabel('\zeta_F^\ast');
subplot(7,5,32);
ylim([-0.5 0.5]);
subplot(7,5,33);
ylim([-2 0]);
subplot(7,5,34);
ylim([-2 2]);
subplot(7,5,35);
ylim([-1 1]);