%% Benchimol, J. 2015. "Money in the Production Function: A New Keynesian DSGE Perspective."

%%
clear all;
clc;
close all;

% adjust path to folder where replication file is stored
cd([cd '/EA_BE15_rep']);

%% IRFs with Taylor rule
dynare EA_BE15_rep;

figure(1)
subplot(3,3,1)
plot(0.8*pi_ua)
title('Inflation')
subplot(3,3,2)
plot(0.8*y_ua)
title('Output')
subplot(3,3,3)
plot(0.8*ir_ua)
title('Nominal Rate')
subplot(3,3,4)
plot(0.8*rr_ua)
title('Real Rate')
subplot(3,3,5)
plot(0.8*ygap_ua)
title('Output Gap')
subplot(3,3,6)
plot(0.8*mp_ua)
title('Firms real money')
subplot(3,3,7)
plot(0.8*mn_ua)
title('households real money')
subplot(3,3,8)
plot(0.8*vel_ua)
title('Velocity')
saveas(1, '..\Technology_shock.png')

figure(2)
subplot(3,3,1)
plot(pi_uu)
title('Inflation')
subplot(3,3,2)
plot(y_uu)
title('Output')
subplot(3,3,3)
plot(ir_uu)
title('Nominal Rate')
subplot(3,3,4)
plot(rr_uu)
title('Real Rate')
subplot(3,3,5)
plot(ygap_uu)
title('Output Gap')
subplot(3,3,6)
plot(mp_uu)
title('Firms real money')
subplot(3,3,7)
plot(mn_uu)
title('households real money')
subplot(3,3,8)
plot(vel_uu)
title('Velocity')
saveas(2, '..\Preference_shock.png')

figure(3)
subplot(3,3,1)
plot(pi_ui)
title('Inflation')
subplot(3,3,2)
plot(y_ui)
title('Output')
subplot(3,3,3)
plot(ir_ui)
title('Nominal Rate')
subplot(3,3,4)
plot(rr_ui)
title('Real Rate')
subplot(3,3,5)
plot(ygap_ui)
title('Output Gap')
subplot(3,3,6)
plot(mp_ui)
title('Firms real money')
subplot(3,3,7)
plot(mn_ui)
title('households real money')
subplot(3,3,8)
plot(vel_ui)
title('Velocity')
saveas(3, '..\Interest_rate_shock.png')

figure(4)
subplot(3,3,1)
plot(pi_up)
title('Inflation')
subplot(3,3,2)
plot(y_up)
title('Output')
subplot(3,3,3)
plot(ir_up)
title('Nominal Rate')
subplot(3,3,4)
plot(rr_up)
title('Real Rate')
subplot(3,3,5)
plot(ygap_up)
title('Output Gap')
subplot(3,3,6)
plot(mp_up)
title('Firms real money')
subplot(3,3,7)
plot(mn_up)
title('households real money')
subplot(3,3,8)
plot(vel_up)
title('Velocity')
saveas(4, '..\Firms_money_demand_shock.png')

figure(5)
subplot(3,1,1)
plot(mp_un)
title('Firms real money')
subplot(3,1,2)
plot(mn_un)
title('households real money')
subplot(3,1,3)
plot(vel_un)
title('Velocity')
saveas(5, '..\HHs_money_demand_shock.png')
