%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'NK_GM07_error';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GM07_error.log');
M_.exo_names = 'eps_h';
M_.exo_names_tex = 'eps\_h';
M_.exo_names_long = 'eps_h';
M_.exo_names = char(M_.exo_names, 'eps_a1');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a1');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a1');
M_.exo_names = char(M_.exo_names, 'eps_a2');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a2');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a2');
M_.exo_names = char(M_.exo_names, 'eps_a3');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_a3');
M_.exo_names_long = char(M_.exo_names_long, 'eps_a3');
M_.exo_names = char(M_.exo_names, 'eps_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_i');
M_.exo_names_long = char(M_.exo_names_long, 'eps_i');
M_.endo_names = 'dp';
M_.endo_names_tex = 'dp';
M_.endo_names_long = 'dp';
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega');
M_.endo_names_long = char(M_.endo_names_long, 'omega');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'xi');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi');
M_.endo_names_long = char(M_.endo_names_long, 'xi');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'a1');
M_.endo_names_tex = char(M_.endo_names_tex, 'a1');
M_.endo_names_long = char(M_.endo_names_long, 'a1');
M_.endo_names = char(M_.endo_names, 'a2');
M_.endo_names_tex = char(M_.endo_names_tex, 'a2');
M_.endo_names_long = char(M_.endo_names_long, 'a2');
M_.endo_names = char(M_.endo_names, 'a3');
M_.endo_names_tex = char(M_.endo_names_tex, 'a3');
M_.endo_names_long = char(M_.endo_names_long, 'a3');
M_.endo_names = char(M_.endo_names, 'EFP');
M_.endo_names_tex = char(M_.endo_names_tex, 'EFP');
M_.endo_names_long = char(M_.endo_names_long, 'EFP');
M_.endo_names = char(M_.endo_names, 'rT');
M_.endo_names_tex = char(M_.endo_names_tex, 'rT');
M_.endo_names_long = char(M_.endo_names_long, 'rT');
M_.endo_names = char(M_.endo_names, 'rIB');
M_.endo_names_tex = char(M_.endo_names_tex, 'rIB');
M_.endo_names_long = char(M_.endo_names_long, 'rIB');
M_.endo_names = char(M_.endo_names, 'rL');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL');
M_.endo_names_long = char(M_.endo_names_long, 'rL');
M_.endo_names = char(M_.endo_names, 'rB');
M_.endo_names_tex = char(M_.endo_names_tex, 'rB');
M_.endo_names_long = char(M_.endo_names_long, 'rB');
M_.param_names = 'phi';
M_.param_names_tex = 'phi';
M_.param_names_long = 'phi';
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'k');
M_.param_names_tex = char(M_.param_names_tex, 'k');
M_.param_names_long = char(M_.param_names_long, 'k');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'rr');
M_.param_names_tex = char(M_.param_names_tex, 'rr');
M_.param_names_long = char(M_.param_names_long, 'rr');
M_.param_names = char(M_.param_names, 'V');
M_.param_names_tex = char(M_.param_names_tex, 'V');
M_.param_names_long = char(M_.param_names_long, 'V');
M_.param_names = char(M_.param_names, 'boc');
M_.param_names_tex = char(M_.param_names_tex, 'boc');
M_.param_names_long = char(M_.param_names_long, 'boc');
M_.param_names = char(M_.param_names, 'F');
M_.param_names_tex = char(M_.param_names_tex, 'F');
M_.param_names_long = char(M_.param_names_long, 'F');
M_.param_names = char(M_.param_names, 'K');
M_.param_names_tex = char(M_.param_names_tex, 'K');
M_.param_names_long = char(M_.param_names_long, 'K');
M_.param_names = char(M_.param_names, 'n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'n\_ss');
M_.param_names_long = char(M_.param_names_long, 'n_ss');
M_.param_names = char(M_.param_names, 'm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'm\_ss');
M_.param_names_long = char(M_.param_names_long, 'm_ss');
M_.param_names = char(M_.param_names, 'c_ss');
M_.param_names_tex = char(M_.param_names_tex, 'c\_ss');
M_.param_names_long = char(M_.param_names_long, 'c_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_ss');
M_.param_names = char(M_.param_names, 'omega_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_ss');
M_.param_names = char(M_.param_names, 'lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'lambda_ss');
M_.param_names = char(M_.param_names, 'mc_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mc\_ss');
M_.param_names_long = char(M_.param_names_long, 'mc_ss');
M_.param_names = char(M_.param_names, 'EFP_ss');
M_.param_names_tex = char(M_.param_names_tex, 'EFP\_ss');
M_.param_names_long = char(M_.param_names_long, 'EFP_ss');
M_.param_names = char(M_.param_names, 'rT_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rT\_ss');
M_.param_names_long = char(M_.param_names_long, 'rT_ss');
M_.param_names = char(M_.param_names, 'rIB_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rIB\_ss');
M_.param_names_long = char(M_.param_names_long, 'rIB_ss');
M_.param_names = char(M_.param_names, 'rL_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rL\_ss');
M_.param_names_long = char(M_.param_names_long, 'rL_ss');
M_.param_names = char(M_.param_names, 'rB_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rB\_ss');
M_.param_names_long = char(M_.param_names_long, 'rB_ss');
M_.param_names = char(M_.param_names, 'rho_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_h');
M_.param_names = char(M_.param_names, 'rho_a1');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a1');
M_.param_names_long = char(M_.param_names_long, 'rho_a1');
M_.param_names = char(M_.param_names, 'rho_a2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a2');
M_.param_names_long = char(M_.param_names_long, 'rho_a2');
M_.param_names = char(M_.param_names, 'rho_a3');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a3');
M_.param_names_long = char(M_.param_names_long, 'rho_a3');
M_.param_names = char(M_.param_names, 'mu_1');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_1');
M_.param_names_long = char(M_.param_names_long, 'mu_1');
M_.param_names = char(M_.param_names, 'mu_2');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_2');
M_.param_names_long = char(M_.param_names_long, 'mu_2');
M_.param_names = char(M_.param_names, 'mu_3');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_3');
M_.param_names_long = char(M_.param_names_long, 'mu_3');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 21;
M_.param_nbr = 34;
M_.orig_endo_nbr = 21;
M_.aux_vars = [];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK_GM07_error_static');
erase_compiled_function('NK_GM07_error_dynamic');
M_.lead_lag_incidence = [
 0 6 27;
 0 7 28;
 0 8 0;
 0 9 29;
 0 10 0;
 0 11 0;
 0 12 30;
 0 13 0;
 0 14 0;
 0 15 31;
 1 16 0;
 0 17 0;
 0 18 0;
 2 19 32;
 3 20 0;
 4 21 0;
 0 22 0;
 0 23 0;
 5 24 0;
 0 25 0;
 0 26 0;]';
M_.nstatic = 11;
M_.nfwrd   = 5;
M_.npred   = 4;
M_.nboth   = 1;
M_.nsfwrd   = 6;
M_.nspred   = 5;
M_.ndynamic   = 10;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(21, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(34, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 83;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.4;
phi = M_.params( 1 );
M_.params( 2 ) = 0.36;
eta = M_.params( 2 );
M_.params( 3 ) = 10;
theta = M_.params( 3 );
M_.params( 22 ) = 0.9090909090909091;
mc_ss = M_.params( 22 );
M_.params( 4 ) = 0.99;
beta = M_.params( 4 );
M_.params( 5 ) = 0.05;
kappa = M_.params( 5 );
M_.params( 6 ) = 0.65;
alpha = M_.params( 6 );
M_.params( 7 ) = 0.2;
k = M_.params( 7 );
M_.params( 8 ) = 0.025;
delta = M_.params( 8 );
M_.params( 9 ) = 0.005;
gamma = M_.params( 9 );
M_.params( 11 ) = 0.31;
V = M_.params( 11 );
M_.params( 10 ) = 0.005;
rr = M_.params( 10 );
M_.params( 12 ) = 0.56;
boc = M_.params( 12 );
M_.params( 13 ) = 9;
F = M_.params( 13 );
M_.params( 28 ) = 0.6;
rho_h = M_.params( 28 );
M_.params( 29 ) = 0.99;
rho_a1 = M_.params( 29 );
M_.params( 30 ) = 0.99;
rho_a2 = M_.params( 30 );
M_.params( 31 ) = 0.9;
rho_a3 = M_.params( 31 );
M_.params( 32 ) = 1.5;
mu_1 = M_.params( 32 );
M_.params( 33 ) = 0.5;
mu_2 = M_.params( 33 );
M_.params( 34 ) = 0.0;
mu_3 = M_.params( 34 );
M_.params( 14 ) = 9.19;
K = M_.params( 14 );
M_.params( 15 ) = 0.3195;
n_ss = M_.params( 15 );
M_.params( 16 ) = 0.0063;
m_ss = M_.params( 16 );
M_.params( 17 ) = 0.8409;
c_ss = M_.params( 17 );
M_.params( 18 ) = 1.949;
w_ss = M_.params( 18 );
M_.params( 19 ) = M_.params(12)*M_.params(17);
b_ss = M_.params( 19 );
M_.params( 20 ) = 0.237;
omega_ss = M_.params( 20 );
M_.params( 21 ) = 0.457;
lambda_ss = M_.params( 21 );
M_.params( 23 ) = M_.params(11)*M_.params(18)*M_.params(16)/(M_.params(17)*(1-M_.params(6))*(1-M_.params(10)));
EFP_ss = M_.params( 23 );
M_.params( 24 ) = 0.015;
rT_ss = M_.params( 24 );
M_.params( 25 ) = 0.0021;
rIB_ss = M_.params( 25 );
M_.params( 26 ) = 0.0066;
rL_ss = M_.params( 26 );
M_.params( 27 ) = 0.0052;
rB_ss = M_.params( 27 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = (1)^2;
options_.irf = 20;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
var_list_ = 'n';
var_list_ = char(var_list_, 'w');
var_list_ = char(var_list_, 'm');
var_list_ = char(var_list_, 'q');
var_list_ = char(var_list_, 'rIB');
var_list_ = char(var_list_, 'mc');
var_list_ = char(var_list_, 'c');
var_list_ = char(var_list_, 'lambda');
var_list_ = char(var_list_, 'EFP');
var_list_ = char(var_list_, 'rB');
var_list_ = char(var_list_, 'dp');
var_list_ = char(var_list_, 'rT');
info = stoch_simul(var_list_);
save('NK_GM07_error_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GM07_error_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GM07_error_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GM07_error_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GM07_error_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
