%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'EA_PV15_bg_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_PV15_bg_rep.log');
M_.exo_names = 'e_a_h';
M_.exo_names_tex = 'e\_a\_h';
M_.exo_names_long = 'e_a_h';
M_.exo_names = char(M_.exo_names, 'e_g_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_g_h');
M_.exo_names = char(M_.exo_names, 'e_beta_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta_h');
M_.exo_names = char(M_.exo_names, 'e_a_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_a_f');
M_.exo_names = char(M_.exo_names, 'e_g_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_g_f');
M_.exo_names = char(M_.exo_names, 'e_beta_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta_f');
M_.exo_names = char(M_.exo_names, 'e_n_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_n_h');
M_.exo_names = char(M_.exo_names, 'e_n_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_n_f');
M_.exo_names = char(M_.exo_names, 'e_q_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_q_h');
M_.exo_names = char(M_.exo_names, 'e_q_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_q_f');
M_.exo_names = char(M_.exo_names, 'e_rL_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL_h');
M_.exo_names = char(M_.exo_names, 'e_rL_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL_f');
M_.exo_names = char(M_.exo_names, 'e_w_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_w_h');
M_.exo_names = char(M_.exo_names, 'e_w_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_w_f');
M_.exo_names = char(M_.exo_names, 'e_ib_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib_h');
M_.exo_names = char(M_.exo_names, 'e_ib_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib_f');
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_beta');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta');
M_.exo_names = char(M_.exo_names, 'e_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n');
M_.exo_names_long = char(M_.exo_names_long, 'e_n');
M_.exo_names = char(M_.exo_names, 'e_q');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q');
M_.exo_names_long = char(M_.exo_names_long, 'e_q');
M_.exo_names = char(M_.exo_names, 'e_rL');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL');
M_.exo_names = char(M_.exo_names, 'e_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w');
M_.exo_names_long = char(M_.exo_names_long, 'e_w');
M_.exo_names = char(M_.exo_names, 'e_ib');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib');
M_.exo_names = char(M_.exo_names, 'e_r');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_r');
M_.exo_names_long = char(M_.exo_names_long, 'e_r');
M_.endo_names = 'y_h';
M_.endo_names_tex = 'y\_h';
M_.endo_names_long = 'y_h';
M_.endo_names = char(M_.endo_names, 'y_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_f');
M_.endo_names_long = char(M_.endo_names_long, 'y_f');
M_.endo_names = char(M_.endo_names, 'y_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'y_ea');
M_.endo_names = char(M_.endo_names, 'c_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_h');
M_.endo_names_long = char(M_.endo_names_long, 'c_h');
M_.endo_names = char(M_.endo_names, 'c_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_f');
M_.endo_names_long = char(M_.endo_names_long, 'c_f');
M_.endo_names = char(M_.endo_names, 'c_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'c_ea');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pi_h');
M_.endo_names = char(M_.endo_names, 'pi_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pi_f');
M_.endo_names = char(M_.endo_names, 'pi_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'pi_ea');
M_.endo_names = char(M_.endo_names, 'pic_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pic_h');
M_.endo_names = char(M_.endo_names, 'pic_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pic_f');
M_.endo_names = char(M_.endo_names, 'w_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_h');
M_.endo_names_long = char(M_.endo_names_long, 'w_h');
M_.endo_names = char(M_.endo_names, 'w_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_f');
M_.endo_names = char(M_.endo_names, 'wh_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_h');
M_.endo_names_long = char(M_.endo_names_long, 'wh_h');
M_.endo_names = char(M_.endo_names, 'wh_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_f');
M_.endo_names_long = char(M_.endo_names_long, 'wh_f');
M_.endo_names = char(M_.endo_names, 'h_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_h');
M_.endo_names_long = char(M_.endo_names_long, 'h_h');
M_.endo_names = char(M_.endo_names, 'h_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_f');
M_.endo_names_long = char(M_.endo_names_long, 'h_f');
M_.endo_names = char(M_.endo_names, 'mc_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_h');
M_.endo_names_long = char(M_.endo_names_long, 'mc_h');
M_.endo_names = char(M_.endo_names, 'mc_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_f');
M_.endo_names_long = char(M_.endo_names_long, 'mc_f');
M_.endo_names = char(M_.endo_names, 'k_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_h');
M_.endo_names_long = char(M_.endo_names_long, 'k_h');
M_.endo_names = char(M_.endo_names, 'k_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_f');
M_.endo_names_long = char(M_.endo_names_long, 'k_f');
M_.endo_names = char(M_.endo_names, 'i_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_h');
M_.endo_names_long = char(M_.endo_names_long, 'i_h');
M_.endo_names = char(M_.endo_names, 'i_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_f');
M_.endo_names_long = char(M_.endo_names_long, 'i_f');
M_.endo_names = char(M_.endo_names, 'i_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'i_ea');
M_.endo_names = char(M_.endo_names, 'z_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_h');
M_.endo_names_long = char(M_.endo_names_long, 'z_h');
M_.endo_names = char(M_.endo_names, 'z_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_f');
M_.endo_names_long = char(M_.endo_names_long, 'z_f');
M_.endo_names = char(M_.endo_names, 'q_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_h');
M_.endo_names_long = char(M_.endo_names_long, 'q_h');
M_.endo_names = char(M_.endo_names, 'q_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_f');
M_.endo_names = char(M_.endo_names, 'ToT');
M_.endo_names_tex = char(M_.endo_names_tex, 'ToT');
M_.endo_names_long = char(M_.endo_names_long, 'ToT');
M_.endo_names = char(M_.endo_names, 'b_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_h');
M_.endo_names_long = char(M_.endo_names_long, 'b_h');
M_.endo_names = char(M_.endo_names, 'ku_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ku_h');
M_.endo_names = char(M_.endo_names, 'ku_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ku_f');
M_.endo_names = char(M_.endo_names, 'u_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_h');
M_.endo_names_long = char(M_.endo_names_long, 'u_h');
M_.endo_names = char(M_.endo_names, 'u_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_f');
M_.endo_names_long = char(M_.endo_names_long, 'u_f');
M_.endo_names = char(M_.endo_names, 'CA');
M_.endo_names_tex = char(M_.endo_names_tex, 'CA');
M_.endo_names_long = char(M_.endo_names_long, 'CA');
M_.endo_names = char(M_.endo_names, 'omega_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_h');
M_.endo_names_long = char(M_.endo_names_long, 'omega_h');
M_.endo_names = char(M_.endo_names, 'omega_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_f');
M_.endo_names_long = char(M_.endo_names_long, 'omega_f');
M_.endo_names = char(M_.endo_names, 'n_E_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_h');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_h');
M_.endo_names = char(M_.endo_names, 'n_E_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_f');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_f');
M_.endo_names = char(M_.endo_names, 'r_K_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_h');
M_.endo_names = char(M_.endo_names, 'r_K_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_f');
M_.endo_names = char(M_.endo_names, 'ld_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ld_h');
M_.endo_names = char(M_.endo_names, 'ld_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ld_f');
M_.endo_names = char(M_.endo_names, 'rr_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_h');
M_.endo_names_long = char(M_.endo_names_long, 'rr_h');
M_.endo_names = char(M_.endo_names, 'rr_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_f');
M_.endo_names_long = char(M_.endo_names_long, 'rr_f');
M_.endo_names = char(M_.endo_names, 's_h');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_h');
M_.endo_names_long = char(M_.endo_names_long, 's_h');
M_.endo_names = char(M_.endo_names, 's_f');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_f');
M_.endo_names_long = char(M_.endo_names_long, 's_f');
M_.endo_names = char(M_.endo_names, 'nk_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_h');
M_.endo_names_long = char(M_.endo_names_long, 'nk_h');
M_.endo_names = char(M_.endo_names, 'nk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'nk_f');
M_.endo_names = char(M_.endo_names, 'v_E_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_h');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_h');
M_.endo_names = char(M_.endo_names, 'v_E_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_f');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_f');
M_.endo_names = char(M_.endo_names, 'mcL_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_h');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_h');
M_.endo_names = char(M_.endo_names, 'mcL_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_f');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_f');
M_.endo_names = char(M_.endo_names, 'ls_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ls_h');
M_.endo_names = char(M_.endo_names, 'ls_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ls_f');
M_.endo_names = char(M_.endo_names, 'ls_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'ls_ea');
M_.endo_names = char(M_.endo_names, 'r_L_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_h');
M_.endo_names = char(M_.endo_names, 'r_L_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_f');
M_.endo_names = char(M_.endo_names, 's_B_h');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_h');
M_.endo_names_long = char(M_.endo_names_long, 's_B_h');
M_.endo_names = char(M_.endo_names, 's_B_f');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_f');
M_.endo_names_long = char(M_.endo_names_long, 's_B_f');
M_.endo_names = char(M_.endo_names, 'pl_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pl_h');
M_.endo_names = char(M_.endo_names, 'pl_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pl_f');
M_.endo_names = char(M_.endo_names, 'bk_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_h');
M_.endo_names_long = char(M_.endo_names_long, 'bk_h');
M_.endo_names = char(M_.endo_names, 'bk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'bk_f');
M_.endo_names = char(M_.endo_names, 'ibn_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_h');
M_.endo_names = char(M_.endo_names, 'ibn_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_f');
M_.endo_names = char(M_.endo_names, 'IBs_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_h');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_h');
M_.endo_names = char(M_.endo_names, 'IBs_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_f');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_f');
M_.endo_names = char(M_.endo_names, 'IB_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'IB\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'IB_ea');
M_.endo_names = char(M_.endo_names, 'r_IB_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_h');
M_.endo_names = char(M_.endo_names, 'r_IB_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_f');
M_.endo_names = char(M_.endo_names, 'p_IB_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_h');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_h');
M_.endo_names = char(M_.endo_names, 'p_IB_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_f');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_f');
M_.endo_names = char(M_.endo_names, 'IBd_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_h');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_h');
M_.endo_names = char(M_.endo_names, 'IBd_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_f');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_f');
M_.endo_names = char(M_.endo_names, 'a_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_h');
M_.endo_names_long = char(M_.endo_names_long, 'a_h');
M_.endo_names = char(M_.endo_names, 'a_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_f');
M_.endo_names_long = char(M_.endo_names_long, 'a_f');
M_.endo_names = char(M_.endo_names, 'g_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_h');
M_.endo_names_long = char(M_.endo_names_long, 'g_h');
M_.endo_names = char(M_.endo_names, 'g_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_f');
M_.endo_names_long = char(M_.endo_names_long, 'g_f');
M_.endo_names = char(M_.endo_names, 'beta_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'beta\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'beta_shock_h');
M_.endo_names = char(M_.endo_names, 'beta_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'beta\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'beta_shock_f');
M_.endo_names = char(M_.endo_names, 'n_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'n_shock_h');
M_.endo_names = char(M_.endo_names, 'n_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'n_shock_f');
M_.endo_names = char(M_.endo_names, 'q_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'q_shock_h');
M_.endo_names = char(M_.endo_names, 'q_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_shock_f');
M_.endo_names = char(M_.endo_names, 'rL_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'rL_shock_h');
M_.endo_names = char(M_.endo_names, 'rL_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'rL_shock_f');
M_.endo_names = char(M_.endo_names, 'w_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'w_shock_h');
M_.endo_names = char(M_.endo_names, 'w_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_shock_f');
M_.endo_names = char(M_.endo_names, 'ib_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ib_shock_h');
M_.endo_names = char(M_.endo_names, 'ib_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ib_shock_f');
M_.endo_names = char(M_.endo_names, 'r_shock');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_shock');
M_.endo_names_long = char(M_.endo_names_long, 'r_shock');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_491');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_491');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_491');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_525');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_525');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_525');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_42_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_43_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_43\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_43_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_58_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_58\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_58_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_74_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_74\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_74_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_75_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_75\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_75_1');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_105_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_105\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_105_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_106_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_106\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_106_0');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'thetap_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetap\_h');
M_.param_names_long = char(M_.param_names_long, 'thetap_h');
M_.param_names = char(M_.param_names, 'thetap_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetap\_f');
M_.param_names_long = char(M_.param_names_long, 'thetap_f');
M_.param_names = char(M_.param_names, 'xi_B');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_B');
M_.param_names_long = char(M_.param_names_long, 'xi_B');
M_.param_names = char(M_.param_names, 'xi_I_h');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_I\_h');
M_.param_names_long = char(M_.param_names_long, 'xi_I_h');
M_.param_names = char(M_.param_names, 'xi_I_f');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_I\_f');
M_.param_names_long = char(M_.param_names_long, 'xi_I_f');
M_.param_names = char(M_.param_names, 'GYss');
M_.param_names_tex = char(M_.param_names_tex, 'GYss');
M_.param_names_long = char(M_.param_names_long, 'GYss');
M_.param_names = char(M_.param_names, 'rho_a_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_a_h');
M_.param_names = char(M_.param_names, 'rho_g_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_g_h');
M_.param_names = char(M_.param_names, 'rho_a_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_a_f');
M_.param_names = char(M_.param_names, 'rho_g_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_g_f');
M_.param_names = char(M_.param_names, 'rho_beta_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_beta\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_beta_f');
M_.param_names = char(M_.param_names, 'rho_beta_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_beta\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_beta_h');
M_.param_names = char(M_.param_names, 'rho_n_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_n\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_n_h');
M_.param_names = char(M_.param_names, 'rho_n_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_n\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_n_f');
M_.param_names = char(M_.param_names, 'rho_q_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_q\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_q_h');
M_.param_names = char(M_.param_names, 'rho_q_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_q\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_q_f');
M_.param_names = char(M_.param_names, 'rho_L_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_L\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_L_h');
M_.param_names = char(M_.param_names, 'rho_L_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_L\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_L_f');
M_.param_names = char(M_.param_names, 'rho_W_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_W\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_W_h');
M_.param_names = char(M_.param_names, 'rho_W_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_W\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_W_f');
M_.param_names = char(M_.param_names, 'rho_B_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_B\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_B_h');
M_.param_names = char(M_.param_names, 'rho_B_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_B\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_B_f');
M_.param_names = char(M_.param_names, 'u_W_h');
M_.param_names_tex = char(M_.param_names_tex, 'u\_W\_h');
M_.param_names_long = char(M_.param_names_long, 'u_W_h');
M_.param_names = char(M_.param_names, 'u_W_f');
M_.param_names_tex = char(M_.param_names_tex, 'u\_W\_f');
M_.param_names_long = char(M_.param_names_long, 'u_W_f');
M_.param_names = char(M_.param_names, 'rho_ag_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ag\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_ag_h');
M_.param_names = char(M_.param_names, 'rho_ag_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ag\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_ag_f');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pi');
M_.param_names_long = char(M_.param_names_long, 'phi_pi');
M_.param_names = char(M_.param_names, 'phi_dy');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_dy');
M_.param_names_long = char(M_.param_names_long, 'phi_dy');
M_.param_names = char(M_.param_names, 'rho_R');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_R');
M_.param_names_long = char(M_.param_names_long, 'rho_R');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'sigmaC_h');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaC\_h');
M_.param_names_long = char(M_.param_names_long, 'sigmaC_h');
M_.param_names = char(M_.param_names, 'sigmaC_f');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaC\_f');
M_.param_names_long = char(M_.param_names_long, 'sigmaC_f');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'sigmaL_h');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaL\_h');
M_.param_names_long = char(M_.param_names_long, 'sigmaL_h');
M_.param_names = char(M_.param_names, 'sigmaL_f');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaL\_f');
M_.param_names_long = char(M_.param_names_long, 'sigmaL_f');
M_.param_names = char(M_.param_names, 'xiL_h');
M_.param_names_tex = char(M_.param_names_tex, 'xiL\_h');
M_.param_names_long = char(M_.param_names_long, 'xiL_h');
M_.param_names = char(M_.param_names, 'xiL_f');
M_.param_names_tex = char(M_.param_names_tex, 'xiL\_f');
M_.param_names_long = char(M_.param_names_long, 'xiL_f');
M_.param_names = char(M_.param_names, 'thetaL_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL\_h');
M_.param_names_long = char(M_.param_names_long, 'thetaL_h');
M_.param_names = char(M_.param_names, 'thetaL_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL\_f');
M_.param_names_long = char(M_.param_names_long, 'thetaL_f');
M_.param_names = char(M_.param_names, 'xiw_h');
M_.param_names_tex = char(M_.param_names_tex, 'xiw\_h');
M_.param_names_long = char(M_.param_names_long, 'xiw_h');
M_.param_names = char(M_.param_names, 'xiw_f');
M_.param_names_tex = char(M_.param_names_tex, 'xiw\_f');
M_.param_names_long = char(M_.param_names_long, 'xiw_f');
M_.param_names = char(M_.param_names, 'thetaw_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw\_h');
M_.param_names_long = char(M_.param_names_long, 'thetaw_h');
M_.param_names = char(M_.param_names, 'thetaw_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw\_f');
M_.param_names_long = char(M_.param_names_long, 'thetaw_f');
M_.param_names = char(M_.param_names, 'alpha_I');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_I');
M_.param_names_long = char(M_.param_names_long, 'alpha_I');
M_.param_names = char(M_.param_names, 'alpha_C');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_C');
M_.param_names_long = char(M_.param_names_long, 'alpha_C');
M_.param_names = char(M_.param_names, 'Rss');
M_.param_names_tex = char(M_.param_names_tex, 'Rss');
M_.param_names_long = char(M_.param_names_long, 'Rss');
M_.param_names = char(M_.param_names, 'Hss');
M_.param_names_tex = char(M_.param_names_tex, 'Hss');
M_.param_names_long = char(M_.param_names_long, 'Hss');
M_.param_names = char(M_.param_names, 'Zss');
M_.param_names_tex = char(M_.param_names_tex, 'Zss');
M_.param_names_long = char(M_.param_names_long, 'Zss');
M_.param_names = char(M_.param_names, 'Iss');
M_.param_names_tex = char(M_.param_names_tex, 'Iss');
M_.param_names_long = char(M_.param_names_long, 'Iss');
M_.param_names = char(M_.param_names, 'Qss');
M_.param_names_tex = char(M_.param_names_tex, 'Qss');
M_.param_names_long = char(M_.param_names_long, 'Qss');
M_.param_names = char(M_.param_names, 'Kss');
M_.param_names_tex = char(M_.param_names_tex, 'Kss');
M_.param_names_long = char(M_.param_names_long, 'Kss');
M_.param_names = char(M_.param_names, 'Yss');
M_.param_names_tex = char(M_.param_names_tex, 'Yss');
M_.param_names_long = char(M_.param_names_long, 'Yss');
M_.param_names = char(M_.param_names, 'Css');
M_.param_names_tex = char(M_.param_names_tex, 'Css');
M_.param_names_long = char(M_.param_names_long, 'Css');
M_.param_names = char(M_.param_names, 'Wss');
M_.param_names_tex = char(M_.param_names_tex, 'Wss');
M_.param_names_long = char(M_.param_names_long, 'Wss');
M_.param_names = char(M_.param_names, 'xip_h');
M_.param_names_tex = char(M_.param_names_tex, 'xip\_h');
M_.param_names_long = char(M_.param_names_long, 'xip_h');
M_.param_names = char(M_.param_names, 'xip_f');
M_.param_names_tex = char(M_.param_names_tex, 'xip\_f');
M_.param_names_long = char(M_.param_names_long, 'xip_f');
M_.param_names = char(M_.param_names, 'hc_h');
M_.param_names_tex = char(M_.param_names_tex, 'hc\_h');
M_.param_names_long = char(M_.param_names_long, 'hc_h');
M_.param_names = char(M_.param_names, 'hc_f');
M_.param_names_tex = char(M_.param_names_tex, 'hc\_f');
M_.param_names_long = char(M_.param_names_long, 'hc_f');
M_.param_names = char(M_.param_names, 'psi_h');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_h');
M_.param_names_long = char(M_.param_names_long, 'psi_h');
M_.param_names = char(M_.param_names, 'psi_f');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_f');
M_.param_names_long = char(M_.param_names_long, 'psi_f');
M_.param_names = char(M_.param_names, 'ETA_Sss');
M_.param_names_tex = char(M_.param_names_tex, 'ETA\_Sss');
M_.param_names_long = char(M_.param_names_long, 'ETA_Sss');
M_.param_names = char(M_.param_names, 'gamma_E');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_E');
M_.param_names_long = char(M_.param_names_long, 'gamma_E');
M_.param_names = char(M_.param_names, 'RKss');
M_.param_names_tex = char(M_.param_names_tex, 'RKss');
M_.param_names_long = char(M_.param_names_long, 'RKss');
M_.param_names = char(M_.param_names, 'RRLss');
M_.param_names_tex = char(M_.param_names_tex, 'RRLss');
M_.param_names_long = char(M_.param_names_long, 'RRLss');
M_.param_names = char(M_.param_names, 'Nss');
M_.param_names_tex = char(M_.param_names_tex, 'Nss');
M_.param_names_long = char(M_.param_names_long, 'Nss');
M_.param_names = char(M_.param_names, 'Lss');
M_.param_names_tex = char(M_.param_names_tex, 'Lss');
M_.param_names_long = char(M_.param_names_long, 'Lss');
M_.param_names = char(M_.param_names, 'NKss');
M_.param_names_tex = char(M_.param_names_tex, 'NKss');
M_.param_names_long = char(M_.param_names_long, 'NKss');
M_.param_names = char(M_.param_names, 'OMEGAss');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGAss');
M_.param_names_long = char(M_.param_names_long, 'OMEGAss');
M_.param_names = char(M_.param_names, 'ka');
M_.param_names_tex = char(M_.param_names_tex, 'ka');
M_.param_names_long = char(M_.param_names_long, 'ka');
M_.param_names = char(M_.param_names, 'wmin');
M_.param_names_tex = char(M_.param_names_tex, 'wmin');
M_.param_names_long = char(M_.param_names_long, 'wmin');
M_.param_names = char(M_.param_names, 'w_sup');
M_.param_names_tex = char(M_.param_names_tex, 'w\_sup');
M_.param_names_long = char(M_.param_names_long, 'w_sup');
M_.param_names = char(M_.param_names, 'w_inf');
M_.param_names_tex = char(M_.param_names_tex, 'w\_inf');
M_.param_names_long = char(M_.param_names_long, 'w_inf');
M_.param_names = char(M_.param_names, 'varkappa_h');
M_.param_names_tex = char(M_.param_names_tex, 'varkappa\_h');
M_.param_names_long = char(M_.param_names_long, 'varkappa_h');
M_.param_names = char(M_.param_names, 'varkappa_f');
M_.param_names_tex = char(M_.param_names_tex, 'varkappa\_f');
M_.param_names_long = char(M_.param_names_long, 'varkappa_f');
M_.param_names = char(M_.param_names, 'chi_IB_h');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_IB\_h');
M_.param_names_long = char(M_.param_names_long, 'chi_IB_h');
M_.param_names = char(M_.param_names, 'chi_IB_f');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_IB\_f');
M_.param_names_long = char(M_.param_names_long, 'chi_IB_f');
M_.param_names = char(M_.param_names, 'gammatild_E');
M_.param_names_tex = char(M_.param_names_tex, 'gammatild\_E');
M_.param_names_long = char(M_.param_names_long, 'gammatild_E');
M_.param_names = char(M_.param_names, 'gamma_B');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_B');
M_.param_names_long = char(M_.param_names_long, 'gamma_B');
M_.param_names = char(M_.param_names, 'hL_h');
M_.param_names_tex = char(M_.param_names_tex, 'hL\_h');
M_.param_names_long = char(M_.param_names_long, 'hL_h');
M_.param_names = char(M_.param_names, 'hL_f');
M_.param_names_tex = char(M_.param_names_tex, 'hL\_f');
M_.param_names_long = char(M_.param_names_long, 'hL_f');
M_.param_names = char(M_.param_names, 'alpha_L');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_L');
M_.param_names_long = char(M_.param_names_long, 'alpha_L');
M_.param_names = char(M_.param_names, 'alpha_IB');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_IB');
M_.param_names_long = char(M_.param_names_long, 'alpha_IB');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'Vss');
M_.param_names_tex = char(M_.param_names_tex, 'Vss');
M_.param_names_long = char(M_.param_names_long, 'Vss');
M_.param_names = char(M_.param_names, 'BKss');
M_.param_names_tex = char(M_.param_names_tex, 'BKss');
M_.param_names_long = char(M_.param_names_long, 'BKss');
M_.param_names = char(M_.param_names, 'IBss');
M_.param_names_tex = char(M_.param_names_tex, 'IBss');
M_.param_names_long = char(M_.param_names_long, 'IBss');
M_.param_names = char(M_.param_names, 'RFss');
M_.param_names_tex = char(M_.param_names_tex, 'RFss');
M_.param_names_long = char(M_.param_names_long, 'RFss');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'hib_h');
M_.param_names_tex = char(M_.param_names_tex, 'hib\_h');
M_.param_names_long = char(M_.param_names_long, 'hib_h');
M_.param_names = char(M_.param_names, 'hib_f');
M_.param_names_tex = char(M_.param_names_tex, 'hib\_f');
M_.param_names_long = char(M_.param_names_long, 'hib_f');
M_.exo_det_nbr = 0;
M_.exo_nbr = 25;
M_.endo_nbr = 103;
M_.param_nbr = 94;
M_.orig_endo_nbr = 93;
M_.aux_vars(1).endo_index = 94;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 95;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 96;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 43;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(4).endo_index = 97;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 44;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 98;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 58;
M_.aux_vars(5).orig_lead_lag = -1;
M_.aux_vars(6).endo_index = 99;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 59;
M_.aux_vars(6).orig_lead_lag = -1;
M_.aux_vars(7).endo_index = 100;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 75;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 101;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 76;
M_.aux_vars(8).orig_lead_lag = -1;
M_.aux_vars(9).endo_index = 102;
M_.aux_vars(9).type = 3;
M_.aux_vars(9).orig_index = 13;
M_.aux_vars(9).orig_lead_lag = 0;
M_.aux_vars(10).endo_index = 103;
M_.aux_vars(10).type = 3;
M_.aux_vars(10).orig_index = 14;
M_.aux_vars(10).orig_lead_lag = 0;
M_.Sigma_e = zeros(25, 25);
M_.Correlation_matrix = eye(25, 25);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('EA_PV15_bg_rep_static');
erase_compiled_function('EA_PV15_bg_rep_dynamic');
M_.lead_lag_incidence = [
 1 61 0;
 2 62 0;
 0 63 0;
 3 64 164;
 4 65 165;
 0 66 0;
 5 67 0;
 6 68 166;
 7 69 167;
 0 70 0;
 8 71 168;
 9 72 169;
 10 73 170;
 11 74 171;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 12 81 0;
 13 82 0;
 14 83 172;
 15 84 173;
 0 85 0;
 0 86 0;
 0 87 0;
 16 88 0;
 17 89 0;
 18 90 0;
 19 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 174;
 0 102 175;
 20 103 0;
 21 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 22 109 0;
 23 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 24 115 0;
 25 116 0;
 0 117 0;
 26 118 176;
 27 119 177;
 0 120 0;
 0 121 0;
 28 122 0;
 29 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 30 131 0;
 31 132 0;
 32 133 0;
 33 134 0;
 34 135 0;
 35 136 0;
 36 137 0;
 37 138 0;
 38 139 0;
 39 140 0;
 40 141 178;
 41 142 179;
 42 143 0;
 43 144 0;
 44 145 0;
 45 146 0;
 46 147 0;
 47 148 0;
 48 149 0;
 49 150 0;
 50 151 0;
 51 152 0;
 52 153 0;
 0 154 180;
 0 155 181;
 53 156 0;
 54 157 0;
 55 158 0;
 56 159 0;
 57 160 0;
 58 161 0;
 59 162 0;
 60 163 0;]';
M_.nstatic = 39;
M_.nfwrd   = 4;
M_.npred   = 46;
M_.nboth   = 14;
M_.nsfwrd   = 18;
M_.nspred   = 60;
M_.ndynamic   = 64;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:25];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(103, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(25, 1);
M_.params = NaN(94, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 476;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.995;
beta = M_.params( 1 );
M_.params( 3 ) = 0.02;
delta = M_.params( 3 );
M_.params( 2 ) = 0.25;
alpha = M_.params( 2 );
M_.params( 9 ) = 0.24;
GYss = M_.params( 9 );
M_.params( 6 ) = 0.0007;
xi_B = M_.params( 6 );
M_.params( 70 ) = 0.40;
NKss = M_.params( 70 );
SLss		= 2/400;	
M_.params( 50 ) = 0.3333333333333333;
Hss = M_.params( 50 );
M_.params( 34 ) = 2;
sigmaC_h = M_.params( 34 );
M_.params( 35 ) = 2.04;
sigmaC_f = M_.params( 35 );
M_.params( 60 ) = 0.32;
hc_h = M_.params( 60 );
M_.params( 61 ) = 0.57;
hc_f = M_.params( 61 );
M_.params( 37 ) = .59;
sigmaL_h = M_.params( 37 );
M_.params( 38 ) = .66;
sigmaL_f = M_.params( 38 );
M_.params( 4 ) = 0.56;
thetap_h = M_.params( 4 );
M_.params( 5 ) = 0.56;
thetap_f = M_.params( 5 );
M_.params( 58 ) = 0.07;
xip_h = M_.params( 58 );
M_.params( 59 ) = 0.08;
xip_f = M_.params( 59 );
M_.params( 45 ) = 0.67;
thetaw_h = M_.params( 45 );
M_.params( 46 ) = 0.6;
thetaw_f = M_.params( 46 );
M_.params( 43 ) = 0.46;
xiw_h = M_.params( 43 );
M_.params( 44 ) = 0.36;
xiw_f = M_.params( 44 );
M_.params( 41 ) = 0.29;
thetaL_h = M_.params( 41 );
M_.params( 42 ) = 0.31;
thetaL_f = M_.params( 42 );
M_.params( 39 ) = 0.12;
xiL_h = M_.params( 39 );
M_.params( 40 ) = 0.21;
xiL_f = M_.params( 40 );
M_.params( 7 ) = 0.63;
xi_I_h = M_.params( 7 );
M_.params( 8 ) = 1.87;
xi_I_f = M_.params( 8 );
M_.params( 78 ) = 0.48;
chi_IB_h = M_.params( 78 );
M_.params( 79 ) = 0.23;
chi_IB_f = M_.params( 79 );
M_.params( 62 ) = 0.66;
psi_h = M_.params( 62 );
M_.params( 63 ) = 0.68;
psi_f = M_.params( 63 );
M_.params( 76 ) = 0.05;
varkappa_h = M_.params( 76 );
M_.params( 77 ) = 0.08;
varkappa_f = M_.params( 77 );
M_.params( 82 ) = 0.96;
hL_h = M_.params( 82 );
M_.params( 83 ) = 0.95;
hL_f = M_.params( 83 );
M_.params( 93 ) = 0.20;
hib_h = M_.params( 93 );
M_.params( 94 ) = 0.21;
hib_f = M_.params( 94 );
M_.params( 92 ) = 0.25;
lambda = M_.params( 92 );
M_.params( 30 ) = 1.85;
phi_pi = M_.params( 30 );
M_.params( 31 ) = 0.15;
phi_dy = M_.params( 31 );
M_.params( 33 ) = 0.84;
rho = M_.params( 33 );
M_.params( 48 ) = 0.17;
alpha_C = M_.params( 48 );
M_.params( 47 ) = 0.06;
alpha_I = M_.params( 47 );
M_.params( 84 ) = 0.09;
alpha_L = M_.params( 84 );
M_.params( 85 ) = 0.11;
alpha_IB = M_.params( 85 );
M_.params( 36 ) = 4.43;
mu = M_.params( 36 );
M_.params( 86 ) = 2.02;
nu = M_.params( 86 );
M_.params( 87 ) = 0.87;
xi = M_.params( 87 );
M_.params( 10 ) = 0.99;
rho_a_h = M_.params( 10 );
M_.params( 12 ) = 0.99;
rho_a_f = M_.params( 12 );
M_.params( 11 ) = 0.93;
rho_g_h = M_.params( 11 );
M_.params( 13 ) = 0.91;
rho_g_f = M_.params( 13 );
M_.params( 15 ) = 0.81;
rho_beta_h = M_.params( 15 );
M_.params( 14 ) = 0.54;
rho_beta_f = M_.params( 14 );
M_.params( 16 ) = 0.96;
rho_n_h = M_.params( 16 );
M_.params( 17 ) = 0.96;
rho_n_f = M_.params( 17 );
M_.params( 18 ) = 0.47;
rho_q_h = M_.params( 18 );
M_.params( 19 ) = 0.59;
rho_q_f = M_.params( 19 );
M_.params( 20 ) = 0.99;
rho_L_h = M_.params( 20 );
M_.params( 21 ) = 0.90;
rho_L_f = M_.params( 21 );
M_.params( 24 ) = 0.90;
rho_B_h = M_.params( 24 );
M_.params( 25 ) = 0.93;
rho_B_f = M_.params( 25 );
M_.params( 22 ) = 0.99;
rho_W_h = M_.params( 22 );
M_.params( 23 ) = 0.99;
rho_W_f = M_.params( 23 );
M_.params( 26 ) = 0.51;
u_W_h = M_.params( 26 );
M_.params( 27 ) = 0.28;
u_W_f = M_.params( 27 );
M_.params( 32 ) = 0.41;
rho_R = M_.params( 32 );
M_.params( 28 ) = 0.84;
rho_ag_h = M_.params( 28 );
M_.params( 29 ) = 0.83;
rho_ag_f = M_.params( 29 );
M_.params( 49 ) = 1/M_.params(1);
Rss = M_.params( 49 );
M_.params( 67 ) = M_.params(49)+SLss;
RRLss = M_.params( 67 );
M_.params( 73 ) = 1-M_.params(70);
wmin = M_.params( 73 );
M_.params( 72 ) = 1/M_.params(70);
ka = M_.params( 72 );
M_.params( 71 ) = M_.params(73)*(M_.params(67)/M_.params(49))^(1/M_.params(72));
OMEGAss = M_.params( 71 );
M_.params( 66 ) = (1-M_.params(70))*M_.params(67)/M_.params(71);
RKss = M_.params( 66 );
Gw			= 1-((wmin/OMEGAss)^(ka-1));
ETA_Dss 	= 1-(wmin/OMEGAss)^ka;
M_.params( 64 ) = (M_.params(73)/M_.params(71))^M_.params(72);
ETA_Sss = M_.params( 64 );
M_.params( 74 ) = M_.params(71)*M_.params(72)/(M_.params(72)-1);
w_sup = M_.params( 74 );
M_.params( 75 ) = M_.params(72)/(M_.params(72)-1)*(M_.params(71)^(1-M_.params(72))-M_.params(73)^(1-M_.params(72)))/(M_.params(71)^(-M_.params(72))-M_.params(73)^(-M_.params(72)));
w_inf = M_.params( 75 );
M_.params( 53 ) = 1;
Qss = M_.params( 53 );
M_.params( 54 ) = ((M_.params(66)*M_.params(53)-M_.params(53)*(1-M_.params(3)))/(M_.params(2)*M_.params(50)^(1-M_.params(2))))^(1/(M_.params(2)-1));
Kss = M_.params( 54 );
M_.params( 68 ) = M_.params(70)*M_.params(53)*M_.params(54);
Nss = M_.params( 68 );
M_.params( 69 ) = M_.params(53)*M_.params(54)-M_.params(68);
Lss = M_.params( 69 );
gammatild_E_h=w_sup^(1-varkappa_h);
gammatild_E_f=w_sup^(1-varkappa_f);
M_.params( 88 ) = M_.params(66)*M_.params(54)*M_.params(71)*M_.params(64)/(M_.params(72)-1);
Vss = M_.params( 88 );
M_.params( 65 ) = M_.params(68)/M_.params(88);
gamma_E = M_.params( 65 );
M_.params( 51 ) = M_.params(66)*M_.params(53)-M_.params(53)*(1-M_.params(3));
Zss = M_.params( 51 );
M_.params( 55 ) = M_.params(54)*M_.params(51)/M_.params(2);
Yss = M_.params( 55 );
M_.params( 57 ) = (1-M_.params(2))*M_.params(55)/M_.params(50);
Wss = M_.params( 57 );
M_.params( 56 ) = M_.params(55)*(1-M_.params(9))-M_.params(3)*M_.params(54);
Css = M_.params( 56 );
M_.params( 52 ) = M_.params(3)*M_.params(54);
Iss = M_.params( 52 );
M_.params( 89 ) = 0.11*M_.params(69);
BKss = M_.params( 89 );
M_.params( 90 ) = M_.params(69)*0.2;
IBss = M_.params( 90 );
M_.params( 91 ) = M_.params(69)-M_.params(89)-M_.params(90);
RFss = M_.params( 91 );
PI_Bss 		= (ETA_Sss*RRLss*Lss - Rss*IBss);
M_.params( 81 ) = 1-M_.params(89)/PI_Bss;
gamma_B = M_.params( 81 );
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (.88)^2;
M_.Sigma_e(7, 7) = (0.14)^2;
M_.Sigma_e(15, 15) = (2.28)^2;
options_.irf = 24;
options_.order = 1;
var_list_=[];
var_list_ = 'y_h';
var_list_ = char(var_list_, 'y_f');
var_list_ = char(var_list_, 'c_h');
var_list_ = char(var_list_, 'c_f');
var_list_ = char(var_list_, 'pic_h');
var_list_ = char(var_list_, 'pic_f');
var_list_ = char(var_list_, 'r');
var_list_ = char(var_list_, 'y_ea');
info = stoch_simul(var_list_);
save('EA_PV15_bg_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_PV15_bg_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_PV15_bg_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_PV15_bg_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_PV15_bg_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
