%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'NK_MPT10_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_MPT10_rep.log');
M_.exo_names = 'e';
M_.exo_names_tex = 'e';
M_.exo_names_long = 'e';
M_.exo_names = char(M_.exo_names, 'e_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_i');
M_.exo_names_long = char(M_.exo_names_long, 'e_i');
M_.endo_names = 'q';
M_.endo_names_tex = 'q';
M_.endo_names_long = 'q';
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta');
M_.endo_names_long = char(M_.endo_names_long, 'theta');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'phi_i');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_i');
M_.endo_names_long = char(M_.endo_names_long, 'phi_i');
M_.endo_names = char(M_.endo_names, 'omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega');
M_.endo_names_long = char(M_.endo_names_long, 'omega');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'w_bar');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_bar');
M_.endo_names_long = char(M_.endo_names_long, 'w_bar');
M_.endo_names = char(M_.endo_names, 'w_und');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_und');
M_.endo_names_long = char(M_.endo_names_long, 'w_und');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'tau');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau');
M_.endo_names_long = char(M_.endo_names_long, 'tau');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'varphi');
M_.endo_names_tex = char(M_.endo_names_tex, 'varphi');
M_.endo_names_long = char(M_.endo_names_long, 'varphi');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'i_nom');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_nom');
M_.endo_names_long = char(M_.endo_names_long, 'i_nom');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'Dis');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dis');
M_.endo_names_long = char(M_.endo_names_long, 'Dis');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'P_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_F');
M_.endo_names_long = char(M_.endo_names_long, 'P_F');
M_.endo_names = char(M_.endo_names, 'P_Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_Z');
M_.endo_names_long = char(M_.endo_names_long, 'P_Z');
M_.endo_names = char(M_.endo_names, 'theta_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'theta_fe');
M_.endo_names = char(M_.endo_names, 'p_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'p_fe');
M_.endo_names = char(M_.endo_names, 'y_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'y_fe');
M_.endo_names = char(M_.endo_names, 'rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'rk_fe');
M_.endo_names = char(M_.endo_names, 'n_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'n_fe');
M_.endo_names = char(M_.endo_names, 'a_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'a_fe');
M_.endo_names = char(M_.endo_names, 'omega_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'omega_fe');
M_.endo_names = char(M_.endo_names, 'k_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'k_fe');
M_.endo_names = char(M_.endo_names, 'i_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'i_fe');
M_.endo_names = char(M_.endo_names, 'u_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'u_fe');
M_.endo_names = char(M_.endo_names, 'v_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'v_fe');
M_.endo_names = char(M_.endo_names, 'lambda_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_fe');
M_.endo_names = char(M_.endo_names, 'c_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'c_fe');
M_.endo_names = char(M_.endo_names, 'F_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'F_fe');
M_.endo_names = char(M_.endo_names, 'phi_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_fe');
M_.endo_names = char(M_.endo_names, 'w_bar_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_bar\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_bar_fe');
M_.endo_names = char(M_.endo_names, 'S_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'S_fe');
M_.endo_names = char(M_.endo_names, 'w_und_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_und\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_und_fe');
M_.endo_names = char(M_.endo_names, 'w_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_fe');
M_.endo_names = char(M_.endo_names, 'H_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'H_fe');
M_.endo_names = char(M_.endo_names, 'phi_i_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_i\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_i_fe');
M_.endo_names = char(M_.endo_names, 'm_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'm_fe');
M_.endo_names = char(M_.endo_names, 'Lambda_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_fe');
M_.endo_names = char(M_.endo_names, 'q_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'q_fe');
M_.endo_names = char(M_.endo_names, 'varphi_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'varphi\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'varphi_fe');
M_.endo_names = char(M_.endo_names, 'r_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'r_fe');
M_.endo_names = char(M_.endo_names, 'mc_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'mc_fe');
M_.endo_names = char(M_.endo_names, 'Y_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Y_fe');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.param_names = 'alpha';
M_.param_names_tex = 'alpha';
M_.param_names_long = 'alpha';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'gamma_m');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_m');
M_.param_names_long = char(M_.param_names_long, 'gamma_m');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta_k');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_k');
M_.param_names_long = char(M_.param_names_long, 'eta_k');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'Y_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'Y_over_K');
M_.param_names = char(M_.param_names, 'K_over_N');
M_.param_names_tex = char(M_.param_names_tex, 'K\_over\_N');
M_.param_names_long = char(M_.param_names_long, 'K_over_N');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'omega_bar');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar');
M_.param_names_long = char(M_.param_names_long, 'omega_bar');
M_.param_names = char(M_.param_names, 'theta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_ss');
M_.param_names_long = char(M_.param_names_long, 'theta_ss');
M_.param_names = char(M_.param_names, 'p_ss');
M_.param_names_tex = char(M_.param_names_tex, 'p\_ss');
M_.param_names_long = char(M_.param_names_long, 'p_ss');
M_.param_names = char(M_.param_names, 'q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'q\_ss');
M_.param_names_long = char(M_.param_names_long, 'q_ss');
M_.param_names = char(M_.param_names, 'Lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lambda_ss');
M_.param_names = char(M_.param_names, 'phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_ss');
M_.param_names = char(M_.param_names, 'phi_i_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_i\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_i_ss');
M_.param_names = char(M_.param_names, 'n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'n\_ss');
M_.param_names_long = char(M_.param_names_long, 'n_ss');
M_.param_names = char(M_.param_names, 'u_ss');
M_.param_names_tex = char(M_.param_names_tex, 'u\_ss');
M_.param_names_long = char(M_.param_names_long, 'u_ss');
M_.param_names = char(M_.param_names, 'v_ss');
M_.param_names_tex = char(M_.param_names_tex, 'v\_ss');
M_.param_names_long = char(M_.param_names_long, 'v_ss');
M_.param_names = char(M_.param_names, 'm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'm\_ss');
M_.param_names_long = char(M_.param_names_long, 'm_ss');
M_.param_names = char(M_.param_names, 'rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'rk_ss');
M_.param_names = char(M_.param_names, 'k_ss');
M_.param_names_tex = char(M_.param_names_tex, 'k\_ss');
M_.param_names_long = char(M_.param_names_long, 'k_ss');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'i_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_ss');
M_.param_names = char(M_.param_names, 'omega_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_ss');
M_.param_names = char(M_.param_names, 'S_ss');
M_.param_names_tex = char(M_.param_names_tex, 'S\_ss');
M_.param_names_long = char(M_.param_names_long, 'S_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'w_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_bar_ss');
M_.param_names = char(M_.param_names, 'w_und_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_und\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_und_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'lambda_ss');
M_.param_names = char(M_.param_names, 'tau_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_ss');
M_.param_names_long = char(M_.param_names_long, 'tau_ss');
M_.param_names = char(M_.param_names, 'H_ss');
M_.param_names_tex = char(M_.param_names_tex, 'H\_ss');
M_.param_names_long = char(M_.param_names_long, 'H_ss');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'gam_P');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_P');
M_.param_names_long = char(M_.param_names_long, 'gam_P');
M_.param_names = char(M_.param_names, 'infl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'infl\_ss');
M_.param_names_long = char(M_.param_names_long, 'infl_ss');
M_.param_names = char(M_.param_names, 'inflstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inflstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'inflstar_ss');
M_.param_names = char(M_.param_names, 'mc_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mc\_ss');
M_.param_names_long = char(M_.param_names_long, 'mc_ss');
M_.param_names = char(M_.param_names, 'P_F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'P\_F\_ss');
M_.param_names_long = char(M_.param_names_long, 'P_F_ss');
M_.param_names = char(M_.param_names, 'P_Z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'P\_Z\_ss');
M_.param_names_long = char(M_.param_names_long, 'P_Z_ss');
M_.param_names = char(M_.param_names, 'Dis_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Dis\_ss');
M_.param_names_long = char(M_.param_names_long, 'Dis_ss');
M_.param_names = char(M_.param_names, 'r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r\_ss');
M_.param_names_long = char(M_.param_names_long, 'r_ss');
M_.param_names = char(M_.param_names, 'i_nom_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_nom\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_nom_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 65;
M_.param_nbr = 56;
M_.orig_endo_nbr = 65;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK_MPT10_rep_static');
erase_compiled_function('NK_MPT10_rep_dynamic');
M_.lead_lag_incidence = [
 0 14 0;
 0 15 79;
 0 16 0;
 1 17 0;
 0 18 0;
 0 19 0;
 2 20 0;
 0 21 80;
 3 22 0;
 0 23 81;
 0 24 0;
 0 25 0;
 4 26 82;
 0 27 0;
 0 28 0;
 0 29 83;
 0 30 0;
 0 31 84;
 0 32 0;
 0 33 0;
 0 34 85;
 0 35 0;
 5 36 0;
 0 37 0;
 0 38 0;
 0 39 86;
 0 40 87;
 0 41 0;
 6 42 0;
 0 43 0;
 7 44 0;
 8 45 0;
 9 46 88;
 0 47 0;
 0 48 89;
 0 49 90;
 0 50 0;
 0 51 91;
 0 52 0;
 0 53 92;
 10 54 0;
 0 55 0;
 0 56 0;
 11 57 0;
 12 58 93;
 0 59 0;
 0 60 0;
 13 61 0;
 0 62 0;
 0 63 94;
 0 64 0;
 0 65 0;
 0 66 95;
 0 67 0;
 0 68 0;
 0 69 96;
 0 70 97;
 0 71 0;
 0 72 98;
 0 73 0;
 0 74 99;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;]';
M_.nstatic = 34;
M_.nfwrd   = 18;
M_.npred   = 10;
M_.nboth   = 3;
M_.nsfwrd   = 21;
M_.nspred   = 13;
M_.ndynamic   = 31;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(65, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(56, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 238;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 8 ) = 1;
sigma = M_.params( 8 );
M_.params( 2 ) = 0.9966554934125964;
beta = M_.params( 2 );
M_.params( 6 ) = 0.008333333333333333;
delta = M_.params( 6 );
M_.params( 1 ) = 0.3333333333333333;
alpha = M_.params( 1 );
M_.params( 7 ) = 9.720000000000001;
eta_k = M_.params( 7 );
M_.params( 12 ) = 0.9654893846056297;
rho_g = M_.params( 12 );
M_.params( 3 ) = 0.965;
rho = M_.params( 3 );
M_.params( 5 ) = 0.5;
gamma = M_.params( 5 );
M_.params( 9 ) = 0.5;
eta = M_.params( 9 );
varphi_ss=1; 
M_.params( 16 ) = 0.9;
omega_bar = M_.params( 16 );
M_.params( 15 ) = 0.2;
G_over_Y = M_.params( 15 );
M_.params( 42 ) = 0;
rho_i = M_.params( 42 );
M_.params( 43 ) = 1.144714242553332;
kappa_pi = M_.params( 43 );
M_.params( 44 ) = 0.5;
kappa_y = M_.params( 44 );
M_.params( 47 ) = 0;
gam_P = M_.params( 47 );
M_.params( 46 ) = 0.9166666666666666;
gam = M_.params( 46 );
M_.params( 45 ) = 7.25;
epsilon = M_.params( 45 );
M_.params( 48 ) = 1;
infl_ss = M_.params( 48 );
M_.params( 49 ) = 1;
inflstar_ss = M_.params( 49 );
M_.params( 53 ) = 1;
Dis_ss = M_.params( 53 );
M_.params( 50 ) = (M_.params(45)-1)/M_.params(45);
mc_ss = M_.params( 50 );
M_.params( 17 ) = 0.5;
theta_ss = M_.params( 17 );
M_.params( 18 ) = 0.45;
p_ss = M_.params( 18 );
M_.params( 4 ) = M_.params(18)*M_.params(17)^(M_.params(5)-1);
gamma_m = M_.params( 4 );
M_.params( 19 ) = M_.params(4)*M_.params(17)^(-M_.params(5));
q_ss = M_.params( 19 );
M_.params( 20 ) = 1;
Lambda_ss = M_.params( 20 );
M_.params( 21 ) = 0;
phi_ss = M_.params( 21 );
M_.params( 22 ) = 0;
phi_i_ss = M_.params( 22 );
M_.params( 23 ) = M_.params(18)/(M_.params(18)+1-M_.params(3));
n_ss = M_.params( 23 );
M_.params( 24 ) = 1-M_.params(23);
u_ss = M_.params( 24 );
M_.params( 25 ) = M_.params(17)*M_.params(24);
v_ss = M_.params( 25 );
M_.params( 26 ) = M_.params(4)*M_.params(24)^M_.params(5)*M_.params(25)^(1-M_.params(5));
m_ss = M_.params( 26 );
M_.params( 27 ) = 1/M_.params(2)+M_.params(6)-1;
rk_ss = M_.params( 27 );
M_.params( 54 ) = M_.params(27)-M_.params(6);
r_ss = M_.params( 54 );
M_.params( 13 ) = M_.params(27)/(M_.params(1)*M_.params(50));
Y_over_K = M_.params( 13 );
M_.params( 14 ) = M_.params(13)^(1/(M_.params(1)-1));
K_over_N = M_.params( 14 );
M_.params( 28 ) = M_.params(23)*M_.params(14);
k_ss = M_.params( 28 );
M_.params( 29 ) = M_.params(13)*M_.params(28);
y_ss = M_.params( 29 );
M_.params( 30 ) = M_.params(50)*(1-M_.params(1))*M_.params(29)/M_.params(23);
a_ss = M_.params( 30 );
M_.params( 31 ) = M_.params(6)*M_.params(28);
i_ss = M_.params( 31 );
M_.params( 38 ) = M_.params(29)*M_.params(15);
g_ss = M_.params( 38 );
M_.params( 40 ) = M_.params(38);
tau_ss = M_.params( 40 );
M_.params( 56 ) = M_.params(29);
Y_ss = M_.params( 56 );
M_.params( 55 ) = M_.params(54);
i_nom_ss = M_.params( 55 );
M_.params( 51 ) = M_.params(50)*1/(1-M_.params(2)*M_.params(46))*M_.params(56);
P_F_ss = M_.params( 51 );
M_.params( 52 ) = 1/(1-M_.params(2)*M_.params(46))*M_.params(56);
P_Z_ss = M_.params( 52 );
M_.params( 32 ) = M_.params(16)*M_.params(30);
omega_ss = M_.params( 32 );
M_.params( 33 ) = (M_.params(30)-M_.params(32))/(1-M_.params(2)*(M_.params(3)-M_.params(18)*M_.params(9)));
S_ss = M_.params( 33 );
M_.params( 34 ) = (1-M_.params(9))*M_.params(33);
F_ss = M_.params( 34 );
M_.params( 11 ) = M_.params(34)*M_.params(19);
kappa = M_.params( 11 );
c_ss = y_ss - g_ss - i_ss - kappa*v_ss;
M_.params( 35 ) = M_.params(30)-M_.params(34)*(1-M_.params(3)*M_.params(2));
w_ss = M_.params( 35 );
M_.params( 36 ) = M_.params(30)+M_.params(34)*M_.params(3)*M_.params(2);
w_bar_ss = M_.params( 36 );
M_.params( 37 ) = M_.params(36)-M_.params(33);
w_und_ss = M_.params( 37 );
M_.params( 10 ) = M_.params(32)/(c_ss*M_.params(8)-M_.params(23)*M_.params(32)*(M_.params(8)-1));
b = M_.params( 10 );
M_.params( 39 ) = (M_.params(8)*M_.params(10)/M_.params(32))^M_.params(8);
lambda_ss = M_.params( 39 );
M_.params( 41 ) = (M_.params(33)-M_.params(34))*M_.params(39);
H_ss = M_.params( 41 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 11 ) = M_.params(17);
oo_.steady_state( 10 ) = M_.params(18);
oo_.steady_state( 3 ) = M_.params(29);
oo_.steady_state( 2 ) = M_.params(27);
oo_.steady_state( 9 ) = M_.params(23);
oo_.steady_state( 5 ) = M_.params(30);
oo_.steady_state( 17 ) = M_.params(32);
oo_.steady_state( 4 ) = M_.params(28);
oo_.steady_state( 13 ) = M_.params(31);
oo_.steady_state( 12 ) = M_.params(24);
oo_.steady_state( 24 ) = M_.params(25);
oo_.steady_state( 7 ) = M_.params(39);
oo_.steady_state( 15 ) = c_ss;
oo_.steady_state( 23 ) = M_.params(38);
oo_.steady_state( 22 ) = M_.params(40);
oo_.steady_state( 8 ) = M_.params(34);
oo_.steady_state( 14 ) = M_.params(21);
oo_.steady_state( 19 ) = M_.params(36);
oo_.steady_state( 21 ) = M_.params(33);
oo_.steady_state( 20 ) = M_.params(37);
oo_.steady_state( 6 ) = M_.params(35);
oo_.steady_state( 18 ) = M_.params(41);
oo_.steady_state( 16 ) = M_.params(22);
oo_.steady_state( 25 ) = M_.params(26);
oo_.steady_state( 26 ) = M_.params(20);
oo_.steady_state( 1 ) = M_.params(19);
oo_.steady_state( 27 ) = varphi_ss;
oo_.steady_state( 28 ) = M_.params(54);
oo_.steady_state( 29 ) = M_.params(55);
oo_.steady_state( 30 ) = M_.params(50);
oo_.steady_state( 31 ) = M_.params(53);
oo_.steady_state( 32 ) = M_.params(56);
oo_.steady_state( 33 ) = M_.params(48);
oo_.steady_state( 34 ) = M_.params(49);
oo_.steady_state( 35 ) = M_.params(51);
oo_.steady_state( 36 ) = M_.params(52);
oo_.steady_state( 37 ) = M_.params(17);
oo_.steady_state( 38 ) = M_.params(18);
oo_.steady_state( 39 ) = M_.params(29);
oo_.steady_state( 40 ) = M_.params(27);
oo_.steady_state( 41 ) = M_.params(23);
oo_.steady_state( 42 ) = M_.params(30);
oo_.steady_state( 43 ) = M_.params(32);
oo_.steady_state( 44 ) = M_.params(28);
oo_.steady_state( 45 ) = M_.params(31);
oo_.steady_state( 46 ) = M_.params(24);
oo_.steady_state( 47 ) = M_.params(25);
oo_.steady_state( 48 ) = M_.params(39);
oo_.steady_state( 49 ) = c_ss;
oo_.steady_state( 50 ) = M_.params(34);
oo_.steady_state( 51 ) = M_.params(21);
oo_.steady_state( 52 ) = M_.params(36);
oo_.steady_state( 53 ) = M_.params(33);
oo_.steady_state( 54 ) = M_.params(37);
oo_.steady_state( 55 ) = M_.params(35);
oo_.steady_state( 56 ) = M_.params(41);
oo_.steady_state( 57 ) = M_.params(22);
oo_.steady_state( 58 ) = M_.params(26);
oo_.steady_state( 59 ) = M_.params(20);
oo_.steady_state( 60 ) = M_.params(19);
oo_.steady_state( 61 ) = varphi_ss;
oo_.steady_state( 62 ) = M_.params(54);
oo_.steady_state( 63 ) = M_.params(50);
oo_.steady_state( 64 ) = M_.params(56);
oo_.steady_state( 65 ) = 0;
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = log((M_.params(38)+M_.params(29)*0.01)/M_.params(38))^2;
options_.irf = 20;
options_.order = 1;
var_list_=[];
var_list_ = 'outputgap';
var_list_ = char(var_list_, 'infl');
var_list_ = char(var_list_, 'i_nom');
var_list_ = char(var_list_, 'y');
info = stoch_simul(var_list_);
save('NK_MPT10_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_MPT10_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_MPT10_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_MPT10_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_MPT10_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
