%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_FV15_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_FV15_rep.log');
M_.exo_names = 'epsd';
M_.exo_names_tex = 'epsd';
M_.exo_names_long = 'epsd';
M_.exo_names = char(M_.exo_names, 'epsphi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsphi');
M_.exo_names_long = char(M_.exo_names_long, 'epsphi');
M_.exo_names = char(M_.exo_names, 'epsmu_I');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsmu\_I');
M_.exo_names_long = char(M_.exo_names_long, 'epsmu_I');
M_.exo_names = char(M_.exo_names, 'epsA');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsA');
M_.exo_names_long = char(M_.exo_names_long, 'epsA');
M_.exo_names = char(M_.exo_names, 'epsm');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsm');
M_.exo_names_long = char(M_.exo_names_long, 'epsm');
M_.exo_names = char(M_.exo_names, 'ud');
M_.exo_names_tex = char(M_.exo_names_tex, 'ud');
M_.exo_names_long = char(M_.exo_names_long, 'ud');
M_.exo_names = char(M_.exo_names, 'uphi');
M_.exo_names_tex = char(M_.exo_names_tex, 'uphi');
M_.exo_names_long = char(M_.exo_names_long, 'uphi');
M_.exo_names = char(M_.exo_names, 'umu');
M_.exo_names_tex = char(M_.exo_names_tex, 'umu');
M_.exo_names_long = char(M_.exo_names_long, 'umu');
M_.exo_names = char(M_.exo_names, 'uA');
M_.exo_names_tex = char(M_.exo_names_tex, 'uA');
M_.exo_names_long = char(M_.exo_names_long, 'uA');
M_.exo_names = char(M_.exo_names, 'um');
M_.exo_names_tex = char(M_.exo_names_tex, 'um');
M_.exo_names_long = char(M_.exo_names_long, 'um');
M_.exo_names = char(M_.exo_names, 'epspi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epspi');
M_.exo_names_long = char(M_.exo_names_long, 'epspi');
M_.exo_names = char(M_.exo_names, 'epsy');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsy');
M_.exo_names_long = char(M_.exo_names_long, 'epsy');
M_.endo_names = 'd';
M_.endo_names_tex = 'd';
M_.endo_names_long = 'd';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'mu_z');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_z');
M_.endo_names_long = char(M_.endo_names_long, 'mu_z');
M_.endo_names = char(M_.endo_names, 'mu_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_I');
M_.endo_names_long = char(M_.endo_names_long, 'mu_I');
M_.endo_names = char(M_.endo_names, 'mu_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_A');
M_.endo_names_long = char(M_.endo_names_long, 'mu_A');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'PI');
M_.endo_names_tex = char(M_.endo_names_tex, 'PI');
M_.endo_names_long = char(M_.endo_names_long, 'PI');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'ld');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld');
M_.endo_names_long = char(M_.endo_names_long, 'ld');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names_long = char(M_.endo_names_long, 'wstar');
M_.endo_names = char(M_.endo_names, 'PIstarw');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstarw');
M_.endo_names_long = char(M_.endo_names_long, 'PIstarw');
M_.endo_names = char(M_.endo_names, 'PIstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstar');
M_.endo_names_long = char(M_.endo_names_long, 'PIstar');
M_.endo_names = char(M_.endo_names, 'g1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g1');
M_.endo_names_long = char(M_.endo_names_long, 'g1');
M_.endo_names = char(M_.endo_names, 'g2');
M_.endo_names_tex = char(M_.endo_names_tex, 'g2');
M_.endo_names_long = char(M_.endo_names_long, 'g2');
M_.endo_names = char(M_.endo_names, 'yd');
M_.endo_names_tex = char(M_.endo_names_tex, 'yd');
M_.endo_names_long = char(M_.endo_names_long, 'yd');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names_long = char(M_.endo_names_long, 'vp');
M_.endo_names = char(M_.endo_names, 'vw');
M_.endo_names_tex = char(M_.endo_names_tex, 'vw');
M_.endo_names_long = char(M_.endo_names_long, 'vw');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'sigma_dt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_dt');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_dt');
M_.endo_names = char(M_.endo_names, 'sigma_phit');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_phit');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_phit');
M_.endo_names = char(M_.endo_names, 'sigma_mut');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_mut');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_mut');
M_.endo_names = char(M_.endo_names, 'sigma_At');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_At');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_At');
M_.endo_names = char(M_.endo_names, 'sigma_mt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_mt');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_mt');
M_.endo_names = char(M_.endo_names, 'gammaPIt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammaPIt');
M_.endo_names_long = char(M_.endo_names_long, 'gammaPIt');
M_.endo_names = char(M_.endo_names, 'gammayt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammayt');
M_.endo_names_long = char(M_.endo_names_long, 'gammayt');
M_.endo_names = char(M_.endo_names, 'yg');
M_.endo_names_tex = char(M_.endo_names_tex, 'yg');
M_.endo_names_long = char(M_.endo_names_long, 'yg');
M_.param_names = 'h';
M_.param_names_tex = 'h';
M_.param_names_long = 'h';
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'gammma1');
M_.param_names_tex = char(M_.param_names_tex, 'gammma1');
M_.param_names_long = char(M_.param_names_long, 'gammma1');
M_.param_names = char(M_.param_names, 'gammma2');
M_.param_names_tex = char(M_.param_names_tex, 'gammma2');
M_.param_names_long = char(M_.param_names_long, 'gammma2');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'varpsi');
M_.param_names_tex = char(M_.param_names_tex, 'varpsi');
M_.param_names_long = char(M_.param_names_long, 'varpsi');
M_.param_names = char(M_.param_names, 'gammma');
M_.param_names_tex = char(M_.param_names_tex, 'gammma');
M_.param_names_long = char(M_.param_names_long, 'gammma');
M_.param_names = char(M_.param_names, 'chiw');
M_.param_names_tex = char(M_.param_names_tex, 'chiw');
M_.param_names_long = char(M_.param_names_long, 'chiw');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'thetap');
M_.param_names_tex = char(M_.param_names_tex, 'thetap');
M_.param_names_long = char(M_.param_names_long, 'thetap');
M_.param_names = char(M_.param_names, 'thetaw');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw');
M_.param_names_long = char(M_.param_names_long, 'thetaw');
M_.param_names = char(M_.param_names, 'alppha');
M_.param_names_tex = char(M_.param_names_tex, 'alppha');
M_.param_names_long = char(M_.param_names_long, 'alppha');
M_.param_names = char(M_.param_names, 'Rbar');
M_.param_names_tex = char(M_.param_names_tex, 'Rbar');
M_.param_names_long = char(M_.param_names_long, 'Rbar');
M_.param_names = char(M_.param_names, 'PIbar');
M_.param_names_tex = char(M_.param_names_tex, 'PIbar');
M_.param_names_long = char(M_.param_names_long, 'PIbar');
M_.param_names = char(M_.param_names, 'gammmaR');
M_.param_names_tex = char(M_.param_names_tex, 'gammmaR');
M_.param_names_long = char(M_.param_names_long, 'gammmaR');
M_.param_names = char(M_.param_names, 'gammmaPI');
M_.param_names_tex = char(M_.param_names_tex, 'gammmaPI');
M_.param_names_long = char(M_.param_names_long, 'gammmaPI');
M_.param_names = char(M_.param_names, 'gammmay');
M_.param_names_tex = char(M_.param_names_tex, 'gammmay');
M_.param_names_long = char(M_.param_names_long, 'gammmay');
M_.param_names = char(M_.param_names, 'Phi');
M_.param_names_tex = char(M_.param_names_tex, 'Phi');
M_.param_names_long = char(M_.param_names_long, 'Phi');
M_.param_names = char(M_.param_names, 'rhod');
M_.param_names_tex = char(M_.param_names_tex, 'rhod');
M_.param_names_long = char(M_.param_names_long, 'rhod');
M_.param_names = char(M_.param_names, 'rhophi');
M_.param_names_tex = char(M_.param_names_tex, 'rhophi');
M_.param_names_long = char(M_.param_names_long, 'rhophi');
M_.param_names = char(M_.param_names, 'Lambdamu');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdamu');
M_.param_names_long = char(M_.param_names_long, 'Lambdamu');
M_.param_names = char(M_.param_names, 'LambdaA');
M_.param_names_tex = char(M_.param_names_tex, 'LambdaA');
M_.param_names_long = char(M_.param_names_long, 'LambdaA');
M_.param_names = char(M_.param_names, 'Lambdax');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdax');
M_.param_names_long = char(M_.param_names_long, 'Lambdax');
M_.param_names = char(M_.param_names, 'LambdaYd');
M_.param_names_tex = char(M_.param_names_tex, 'LambdaYd');
M_.param_names_long = char(M_.param_names_long, 'LambdaYd');
M_.param_names = char(M_.param_names, 'sigma_d');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_d');
M_.param_names_long = char(M_.param_names_long, 'sigma_d');
M_.param_names = char(M_.param_names, 'sigma_phi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_phi');
M_.param_names_long = char(M_.param_names_long, 'sigma_phi');
M_.param_names = char(M_.param_names, 'sigma_mu');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_mu');
M_.param_names_long = char(M_.param_names_long, 'sigma_mu');
M_.param_names = char(M_.param_names, 'sigma_A');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_A');
M_.param_names_long = char(M_.param_names_long, 'sigma_A');
M_.param_names = char(M_.param_names, 'sigma_m');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_m');
M_.param_names_long = char(M_.param_names_long, 'sigma_m');
M_.param_names = char(M_.param_names, 'rhosigd');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigd');
M_.param_names_long = char(M_.param_names_long, 'rhosigd');
M_.param_names = char(M_.param_names, 'rhosigphi');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigphi');
M_.param_names_long = char(M_.param_names_long, 'rhosigphi');
M_.param_names = char(M_.param_names, 'rhosigmu');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigmu');
M_.param_names_long = char(M_.param_names_long, 'rhosigmu');
M_.param_names = char(M_.param_names, 'rhosigA');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigA');
M_.param_names_long = char(M_.param_names_long, 'rhosigA');
M_.param_names = char(M_.param_names, 'rhosigm');
M_.param_names_tex = char(M_.param_names_tex, 'rhosigm');
M_.param_names_long = char(M_.param_names_long, 'rhosigm');
M_.param_names = char(M_.param_names, 'rhogammaPI');
M_.param_names_tex = char(M_.param_names_tex, 'rhogammaPI');
M_.param_names_long = char(M_.param_names_long, 'rhogammaPI');
M_.param_names = char(M_.param_names, 'rhogammay');
M_.param_names_tex = char(M_.param_names_tex, 'rhogammay');
M_.param_names_long = char(M_.param_names_long, 'rhogammay');
M_.param_names = char(M_.param_names, 'eta_d');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_d');
M_.param_names_long = char(M_.param_names_long, 'eta_d');
M_.param_names = char(M_.param_names, 'eta_phi');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_phi');
M_.param_names_long = char(M_.param_names_long, 'eta_phi');
M_.param_names = char(M_.param_names, 'eta_mu');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_mu');
M_.param_names_long = char(M_.param_names_long, 'eta_mu');
M_.param_names = char(M_.param_names, 'eta_A');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_A');
M_.param_names_long = char(M_.param_names_long, 'eta_A');
M_.param_names = char(M_.param_names, 'eta_m');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_m');
M_.param_names_long = char(M_.param_names_long, 'eta_m');
M_.param_names = char(M_.param_names, 'sigma_pi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_pi');
M_.param_names_long = char(M_.param_names_long, 'sigma_pi');
M_.param_names = char(M_.param_names, 'sigma_y');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_y');
M_.param_names_long = char(M_.param_names_long, 'sigma_y');
M_.exo_det_nbr = 0;
M_.exo_nbr = 12;
M_.endo_nbr = 36;
M_.param_nbr = 46;
M_.orig_endo_nbr = 36;
M_.aux_vars = [];
M_.predetermined_variables = [ 23 ];
M_.Sigma_e = zeros(12, 12);
M_.Correlation_matrix = eye(12, 12);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_FV15_rep_static');
erase_compiled_function('US_FV15_rep_dynamic');
M_.lead_lag_incidence = [
 1 19 55;
 2 20 56;
 0 21 57;
 0 22 58;
 0 23 0;
 0 24 59;
 3 25 0;
 4 26 60;
 0 27 61;
 5 28 62;
 0 29 63;
 0 30 64;
 0 31 65;
 0 32 0;
 6 33 0;
 0 34 66;
 0 35 0;
 0 36 67;
 0 37 68;
 0 38 69;
 7 39 0;
 0 40 0;
 8 41 0;
 9 42 0;
 10 43 0;
 0 44 0;
 11 45 0;
 0 46 0;
 12 47 0;
 13 48 0;
 14 49 0;
 15 50 0;
 16 51 0;
 17 52 0;
 18 53 0;
 0 54 0;]';
M_.nstatic = 7;
M_.nfwrd   = 11;
M_.npred   = 14;
M_.nboth   = 4;
M_.nsfwrd   = 15;
M_.nspred   = 18;
M_.ndynamic   = 29;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:12];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(36, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(12, 1);
M_.params = NaN(46, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 184;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 5 ) = 0.025;
delta = M_.params( 5 );
M_.params( 8 ) = 10;
epsilon = M_.params( 8 );
M_.params( 7 ) = 10;
eta = M_.params( 7 );
M_.params( 21 ) = 0;
Phi = M_.params( 21 );
M_.params( 4 ) = 0.001;
gammma2 = M_.params( 4 );
M_.params( 2 ) = 0.99;
betta = M_.params( 2 );
M_.params( 1 ) = 0.9;
h = M_.params( 1 );
M_.params( 9 ) = 8;
varpsi = M_.params( 9 );
M_.params( 10 ) = 1.17;
gammma = M_.params( 10 );
M_.params( 6 ) = 9.5;
kappa = M_.params( 6 );
M_.params( 15 ) = 0.21;
alppha = M_.params( 15 );
M_.params( 38 ) = 0.95;
rhogammaPI = M_.params( 38 );
M_.params( 39 ) = 0;
rhogammay = M_.params( 39 );
M_.params( 46 ) = 0;
sigma_y = M_.params( 46 );
M_.params( 13 ) = 0.8139;
thetap = M_.params( 13 );
M_.params( 12 ) = 0.6186;
chi = M_.params( 12 );
M_.params( 14 ) = 0.6869;
thetaw = M_.params( 14 );
M_.params( 11 ) = 0.6340;
chiw = M_.params( 11 );
M_.params( 18 ) = 0.7855;
gammmaR = M_.params( 18 );
M_.params( 20 ) = 0.2457599579806542;
gammmay = M_.params( 20 );
M_.params( 19 ) = 1.045086858349019;
gammmaPI = M_.params( 19 );
M_.params( 17 ) = 1.0005;
PIbar = M_.params( 17 );
M_.params( 22 ) = 0.1182;
rhod = M_.params( 22 );
M_.params( 23 ) = 0.9331;
rhophi = M_.params( 23 );
M_.params( 31 ) = 0.02021561405793051;
sigma_A = M_.params( 31 );
M_.params( 28 ) = 0.1376005990405501;
sigma_d = M_.params( 28 );
M_.params( 29 ) = 0.08222466180162495;
sigma_phi = M_.params( 29 );
M_.params( 30 ) = 0.002409586796292499;
sigma_mu = M_.params( 30 );
M_.params( 32 ) = 0.002478752176666359;
sigma_m = M_.params( 32 );
M_.params( 24 ) = 3.4e-3;
Lambdamu = M_.params( 24 );
M_.params( 25 ) = 2.8e-3;
LambdaA = M_.params( 25 );
M_.params( 33 ) = 0.9506;
rhosigd = M_.params( 33 );
M_.params( 34 ) = 0.1275;
rhosigphi = M_.params( 34 );
M_.params( 35 ) = 0.7508;
rhosigmu = M_.params( 35 );
M_.params( 36 ) = 0.2411;
rhosigA = M_.params( 36 );
M_.params( 37 ) = 0.8550;
rhosigm = M_.params( 37 );
M_.params( 40 ) = 0.1007;
eta_d = M_.params( 40 );
M_.params( 41 ) = 2.8316;
eta_phi = M_.params( 41 );
M_.params( 42 ) = 0.3115;
eta_mu = M_.params( 42 );
M_.params( 43 ) = 0.7720;
eta_A = M_.params( 43 );
M_.params( 44 ) = 0.5732;
eta_m = M_.params( 44 );
M_.params( 45 ) = 0.145;
sigma_pi = M_.params( 45 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
M_.Sigma_e(5, 5) = (1)^2;
M_.Sigma_e(6, 6) = (1)^2;
M_.Sigma_e(7, 7) = (1)^2;
M_.Sigma_e(8, 8) = (1)^2;
M_.Sigma_e(9, 9) = (1)^2;
M_.Sigma_e(10, 10) = (1)^2;
M_.Sigma_e(11, 11) = (1)^2;
M_.Sigma_e(12, 12) = (1)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 21;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
var_list_ = 'yd';
var_list_ = char(var_list_, 'yg');
var_list_ = char(var_list_, 'c');
var_list_ = char(var_list_, 'R');
var_list_ = char(var_list_, 'PI');
info = stoch_simul(var_list_);
save('US_FV15_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_FV15_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_FV15_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_FV15_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_FV15_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
