%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GSSZ17_rep';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GSSZ17_rep.log');
M_.exo_names = 'eA';
M_.exo_names_tex = 'eA';
M_.exo_names_long = 'eA';
M_.exo_names = char(M_.exo_names, 'eR');
M_.exo_names_tex = char(M_.exo_names_tex, 'eR');
M_.exo_names_long = char(M_.exo_names_long, 'eR');
M_.exo_names = char(M_.exo_names, 'eF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eF');
M_.exo_names_long = char(M_.exo_names_long, 'eF');
M_.exo_names = char(M_.exo_names, 'eD');
M_.exo_names_tex = char(M_.exo_names_tex, 'eD');
M_.exo_names_long = char(M_.exo_names_long, 'eD');
M_.endo_names = 'xi';
M_.endo_names_tex = 'xi';
M_.endo_names_long = 'xi';
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'pt');
M_.endo_names_tex = char(M_.endo_names_tex, 'pt');
M_.endo_names_long = char(M_.endo_names_long, 'pt');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'pii');
M_.endo_names_tex = char(M_.endo_names_tex, 'pii');
M_.endo_names_long = char(M_.endo_names_long, 'pii');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'pS');
M_.endo_names_tex = char(M_.endo_names_tex, 'pS');
M_.endo_names_long = char(M_.endo_names_long, 'pS');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'dt');
M_.endo_names_tex = char(M_.endo_names_tex, 'dt');
M_.endo_names_long = char(M_.endo_names_long, 'dt');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'abar');
M_.endo_names_tex = char(M_.endo_names_tex, 'abar');
M_.endo_names_long = char(M_.endo_names_long, 'abar');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'xi_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi\_f');
M_.endo_names_long = char(M_.endo_names_long, 'xi_f');
M_.endo_names = char(M_.endo_names, 's_f');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_f');
M_.endo_names_long = char(M_.endo_names_long, 's_f');
M_.endo_names = char(M_.endo_names, 'c_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_f');
M_.endo_names_long = char(M_.endo_names_long, 'c_f');
M_.endo_names = char(M_.endo_names, 'x_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_f');
M_.endo_names_long = char(M_.endo_names_long, 'x_f');
M_.endo_names = char(M_.endo_names, 'pt_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pt\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pt_f');
M_.endo_names = char(M_.endo_names, 'y_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_f');
M_.endo_names_long = char(M_.endo_names_long, 'y_f');
M_.endo_names = char(M_.endo_names, 'h_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_f');
M_.endo_names_long = char(M_.endo_names_long, 'h_f');
M_.endo_names = char(M_.endo_names, 'pii_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pii\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pii_f');
M_.endo_names = char(M_.endo_names, 'w_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_f');
M_.endo_names = char(M_.endo_names, 'pS_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pS\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pS_f');
M_.endo_names = char(M_.endo_names, 'm_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_f');
M_.endo_names_long = char(M_.endo_names_long, 'm_f');
M_.endo_names = char(M_.endo_names, 'dt_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dt\_f');
M_.endo_names_long = char(M_.endo_names_long, 'dt_f');
M_.endo_names = char(M_.endo_names, 'z_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_f');
M_.endo_names_long = char(M_.endo_names_long, 'z_f');
M_.endo_names = char(M_.endo_names, 'abar_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'abar\_f');
M_.endo_names_long = char(M_.endo_names_long, 'abar_f');
M_.endo_names = char(M_.endo_names, 'mu_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_f');
M_.endo_names_long = char(M_.endo_names_long, 'mu_f');
M_.endo_names = char(M_.endo_names, 'v_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_f');
M_.endo_names_long = char(M_.endo_names_long, 'v_f');
M_.endo_names = char(M_.endo_names, 'lambda_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_f');
M_.endo_names = char(M_.endo_names, 'R_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_f');
M_.endo_names_long = char(M_.endo_names_long, 'R_f');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'pii_w');
M_.endo_names_tex = char(M_.endo_names_tex, 'pii\_w');
M_.endo_names_long = char(M_.endo_names_long, 'pii_w');
M_.endo_names = char(M_.endo_names, 'pii_w_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pii\_w\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pii_w_f');
M_.endo_names = char(M_.endo_names, 'lw');
M_.endo_names_tex = char(M_.endo_names_tex, 'lw');
M_.endo_names_long = char(M_.endo_names_long, 'lw');
M_.endo_partitions = struct();
M_.param_names = 'alpha';
M_.param_names_tex = 'alpha';
M_.param_names_long = 'alpha';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'gam_x');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_x');
M_.param_names_long = char(M_.param_names_long, 'gam_x');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'rho_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_s');
M_.param_names = char(M_.param_names, 'gam_h');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_h');
M_.param_names_long = char(M_.param_names_long, 'gam_h');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'rho_A');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_A');
M_.param_names_long = char(M_.param_names_long, 'rho_A');
M_.param_names = char(M_.param_names, 'gam_p');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_p');
M_.param_names_long = char(M_.param_names_long, 'gam_p');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'rho_y');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_y');
M_.param_names_long = char(M_.param_names_long, 'rho_y');
M_.param_names = char(M_.param_names, 'rho_pi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pi');
M_.param_names_long = char(M_.param_names_long, 'rho_pi');
M_.param_names = char(M_.param_names, 'varrhobar');
M_.param_names_tex = char(M_.param_names_tex, 'varrhobar');
M_.param_names_long = char(M_.param_names_long, 'varrhobar');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'rho_F');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_F');
M_.param_names_long = char(M_.param_names_long, 'rho_F');
M_.param_names = char(M_.param_names, 'rho_D');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_D');
M_.param_names_long = char(M_.param_names_long, 'rho_D');
M_.param_names = char(M_.param_names, 'Asig');
M_.param_names_tex = char(M_.param_names_tex, 'Asig');
M_.param_names_long = char(M_.param_names_long, 'Asig');
M_.param_names = char(M_.param_names, 'Rsig');
M_.param_names_tex = char(M_.param_names_tex, 'Rsig');
M_.param_names_long = char(M_.param_names_long, 'Rsig');
M_.param_names = char(M_.param_names, 'Fsig');
M_.param_names_tex = char(M_.param_names_tex, 'Fsig');
M_.param_names_long = char(M_.param_names_long, 'Fsig');
M_.param_names = char(M_.param_names, 'Dsig');
M_.param_names_tex = char(M_.param_names_tex, 'Dsig');
M_.param_names_long = char(M_.param_names_long, 'Dsig');
M_.param_names = char(M_.param_names, 'zeta');
M_.param_names_tex = char(M_.param_names_tex, 'zeta');
M_.param_names_long = char(M_.param_names_long, 'zeta');
M_.param_names = char(M_.param_names, 'eta_w');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_w');
M_.param_names_long = char(M_.param_names_long, 'eta_w');
M_.param_names = char(M_.param_names, 'gam_w');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_w');
M_.param_names_long = char(M_.param_names_long, 'gam_w');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 44;
M_.param_nbr = 23;
M_.orig_endo_nbr = 44;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_GSSZ17_rep_static');
erase_compiled_function('NK_GSSZ17_rep_dynamic');
M_.orig_eq_nbr = 44;
M_.eq_nbr = 44;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 12 56;
 1 13 0;
 0 14 57;
 2 15 0;
 3 16 0;
 0 17 0;
 0 18 58;
 0 19 59;
 4 20 0;
 5 21 0;
 6 22 60;
 0 23 61;
 0 24 62;
 0 25 63;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 64;
 0 30 65;
 7 31 0;
 0 32 0;
 8 33 0;
 0 34 0;
 9 35 0;
 0 36 66;
 10 37 0;
 11 38 0;
 0 39 0;
 0 40 0;
 0 41 67;
 0 42 0;
 0 43 68;
 0 44 69;
 0 45 70;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 71;
 0 50 72;
 0 51 0;
 0 52 0;
 0 53 73;
 0 54 0;
 0 55 0;]';
M_.nstatic = 16;
M_.nfwrd   = 17;
M_.npred   = 10;
M_.nboth   = 1;
M_.nsfwrd   = 18;
M_.nspred   = 11;
M_.ndynamic   = 28;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(44, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(23, 1);
M_.NNZDerivatives = [180; -1; -1];
M_.params( 1 ) = 0.85;
alpha = M_.params( 1 );
M_.params( 2 ) = 0.985;
beta = M_.params( 2 );
M_.params( 3 ) = 1.001;
gam_x = M_.params( 3 );
M_.params( 4 ) = (-0.75);
theta = M_.params( 4 );
M_.params( 5 ) = 0.95;
rho_s = M_.params( 5 );
M_.params( 6 ) = 0.2;
gam_h = M_.params( 6 );
M_.params( 7 ) = 2.00;
eta = M_.params( 7 );
M_.params( 8 ) = 0.900;
rho_A = M_.params( 8 );
M_.params( 9 ) = 10;
gam_p = M_.params( 9 );
M_.params( 10 ) = 0.750;
rho_r = M_.params( 10 );
M_.params( 11 ) = 0.00;
rho_y = M_.params( 11 );
M_.params( 12 ) = 2.00;
rho_pi = M_.params( 12 );
M_.params( 13 ) = 0.5;
varrhobar = M_.params( 13 );
M_.params( 14 ) = 0.05;
sig = M_.params( 14 );
M_.params( 15 ) = 0.900;
rho_F = M_.params( 15 );
M_.params( 16 ) = 0.900;
rho_D = M_.params( 16 );
M_.params( 17 ) = 0.010;
Asig = M_.params( 17 );
M_.params( 18 ) = 0.006250;
Rsig = M_.params( 18 );
M_.params( 19 ) = 0.250;
Fsig = M_.params( 19 );
M_.params( 20 ) = 0.003333333333333334;
Dsig = M_.params( 20 );
M_.params( 21 ) = 1.000;
zeta = M_.params( 21 );
M_.params( 22 ) = 2.000;
eta_w = M_.params( 22 );
M_.params( 23 ) = 30;
gam_w = M_.params( 23 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
options_.ar = 4;
options_.irf = 20;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
options_.periods = 50000;
options_.pruning = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('NK_GSSZ17_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GSSZ17_rep_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
