%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'NK_RA16_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_RA16_rep.log');
M_.exo_names = 'e_i';
M_.exo_names_tex = 'e\_i';
M_.exo_names_long = 'e_i';
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'GDP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP');
M_.endo_names_long = char(M_.endo_names_long, 'GDP');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'U');
M_.endo_names_tex = char(M_.endo_names_tex, 'U');
M_.endo_names_long = char(M_.endo_names_long, 'U');
M_.endo_names = char(M_.endo_names, 'Cp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cp');
M_.endo_names_long = char(M_.endo_names_long, 'Cp');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'Ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce');
M_.endo_names_long = char(M_.endo_names_long, 'Ce');
M_.endo_names = char(M_.endo_names, 'Cb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cb');
M_.endo_names_long = char(M_.endo_names_long, 'Cb');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'Rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl');
M_.endo_names_long = char(M_.endo_names_long, 'Rl');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'V');
M_.endo_names_tex = char(M_.endo_names_tex, 'V');
M_.endo_names_long = char(M_.endo_names_long, 'V');
M_.endo_names = char(M_.endo_names, 'phi_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_e');
M_.endo_names_long = char(M_.endo_names_long, 'phi_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_prime');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_prime');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_prime');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'Lr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lr');
M_.endo_names_long = char(M_.endo_names_long, 'Lr');
M_.endo_names = char(M_.endo_names, 'Le');
M_.endo_names_tex = char(M_.endo_names_tex, 'Le');
M_.endo_names_long = char(M_.endo_names_long, 'Le');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Nb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nb');
M_.endo_names_long = char(M_.endo_names_long, 'Nb');
M_.endo_names = char(M_.endo_names, 'phi_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_b');
M_.endo_names_long = char(M_.endo_names_long, 'phi_b');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'spread_RlR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RlR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RlR');
M_.endo_names = char(M_.endo_names, 'spread_RkR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RkR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RkR');
M_.endo_names = char(M_.endo_names, 'spread_RbR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RbR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RbR');
M_.endo_names = char(M_.endo_names, 'spread_RkRb');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RkRb');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RkRb');
M_.endo_names = char(M_.endo_names, 'R4');
M_.endo_names_tex = char(M_.endo_names_tex, 'R4');
M_.endo_names_long = char(M_.endo_names_long, 'R4');
M_.endo_names = char(M_.endo_names, 'Pi4');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi4');
M_.endo_names_long = char(M_.endo_names_long, 'Pi4');
M_.endo_names = char(M_.endo_names, 'Y_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Y_fe');
M_.endo_names = char(M_.endo_names, 'GDP_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'GDP_fe');
M_.endo_names = char(M_.endo_names, 'I_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'I\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'I_fe');
M_.endo_names = char(M_.endo_names, 'K_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'K_fe');
M_.endo_names = char(M_.endo_names, 'l_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'l_fe');
M_.endo_names = char(M_.endo_names, 'U_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'U\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'U_fe');
M_.endo_names = char(M_.endo_names, 'Cp_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cp\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Cp_fe');
M_.endo_names = char(M_.endo_names, 'C_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'C_fe');
M_.endo_names = char(M_.endo_names, 'Ce_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Ce_fe');
M_.endo_names = char(M_.endo_names, 'Cb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Cb_fe');
M_.endo_names = char(M_.endo_names, 'varrho_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'varrho_fe');
M_.endo_names = char(M_.endo_names, 'R_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'R_fe');
M_.endo_names = char(M_.endo_names, 'Rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rk_fe');
M_.endo_names = char(M_.endo_names, 'rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'rk_fe');
M_.endo_names = char(M_.endo_names, 'Rb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rb_fe');
M_.endo_names = char(M_.endo_names, 'Rl_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rl_fe');
M_.endo_names = char(M_.endo_names, 'w_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_fe');
M_.endo_names = char(M_.endo_names, 'Q_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Q_fe');
M_.endo_names = char(M_.endo_names, 'Pi_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Pi_fe');
M_.endo_names = char(M_.endo_names, 'mc_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'mc_fe');
M_.endo_names = char(M_.endo_names, 'N_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'N\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'N_fe');
M_.endo_names = char(M_.endo_names, 'V_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'V\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'V_fe');
M_.endo_names = char(M_.endo_names, 'phi_e_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_e\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_e_fe');
M_.endo_names = char(M_.endo_names, 'omega_bar_prime_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_prime\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_prime_fe');
M_.endo_names = char(M_.endo_names, 'L_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'L_fe');
M_.endo_names = char(M_.endo_names, 'Lr_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lr\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lr_fe');
M_.endo_names = char(M_.endo_names, 'Le_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Le\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Le_fe');
M_.endo_names = char(M_.endo_names, 'Nb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Nb_fe');
M_.endo_names = char(M_.endo_names, 'phi_b_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_b\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_b_fe');
M_.endo_names = char(M_.endo_names, 'z_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'z_fe');
M_.endo_names = char(M_.endo_names, 'Lambda_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_fe');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'xi_p');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p');
M_.param_names_long = char(M_.param_names_long, 'xi_p');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'psi_L');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_L');
M_.param_names_long = char(M_.param_names_long, 'psi_L');
M_.param_names = char(M_.param_names, 'psi_K');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_K');
M_.param_names_long = char(M_.param_names_long, 'psi_K');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'N_nb');
M_.param_names_tex = char(M_.param_names_tex, 'N\_nb');
M_.param_names_long = char(M_.param_names_long, 'N_nb');
M_.param_names = char(M_.param_names, 'psi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_pi');
M_.param_names_long = char(M_.param_names_long, 'psi_pi');
M_.param_names = char(M_.param_names, 'psi_y');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_y');
M_.param_names_long = char(M_.param_names_long, 'psi_y');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'sigma_i');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_i');
M_.param_names_long = char(M_.param_names_long, 'sigma_i');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'brate');
M_.param_names_tex = char(M_.param_names_tex, 'brate');
M_.param_names_long = char(M_.param_names_long, 'brate');
M_.param_names = char(M_.param_names, 'omega_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_bar_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'F1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F1\_ss');
M_.param_names_long = char(M_.param_names_long, 'F1_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'G1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G1\_ss');
M_.param_names_long = char(M_.param_names_long, 'G1_ss');
M_.param_names = char(M_.param_names, 'G11_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G11\_ss');
M_.param_names_long = char(M_.param_names_long, 'G11_ss');
M_.param_names = char(M_.param_names, 'Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma_ss');
M_.param_names = char(M_.param_names, 'Gamma1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma1\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma1_ss');
M_.param_names = char(M_.param_names, 'Gamma11_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma11\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma11_ss');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'xi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_ss');
M_.param_names_long = char(M_.param_names_long, 'xi_ss');
M_.param_names = char(M_.param_names, 'spread_RkRb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'spread\_RkRb\_ss');
M_.param_names_long = char(M_.param_names_long, 'spread_RkRb_ss');
M_.param_names = char(M_.param_names, 'phi_e_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_e\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_e_ss');
M_.param_names = char(M_.param_names, 'Pi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pi\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pi_ss');
M_.param_names = char(M_.param_names, 'R_ss');
M_.param_names_tex = char(M_.param_names_tex, 'R\_ss');
M_.param_names_long = char(M_.param_names_long, 'R_ss');
M_.param_names = char(M_.param_names, 'Rl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rl\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rl_ss');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'X_ss');
M_.param_names_tex = char(M_.param_names_tex, 'X\_ss');
M_.param_names_long = char(M_.param_names_long, 'X_ss');
M_.param_names = char(M_.param_names, 'mc_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mc\_ss');
M_.param_names_long = char(M_.param_names_long, 'mc_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'rk_ss');
M_.param_names = char(M_.param_names, 'K_over_l');
M_.param_names_tex = char(M_.param_names_tex, 'K\_over\_l');
M_.param_names_long = char(M_.param_names_long, 'K_over_l');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'l_ss');
M_.param_names_tex = char(M_.param_names_tex, 'l\_ss');
M_.param_names_long = char(M_.param_names_long, 'l_ss');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'Gov_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gov\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gov_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'omega_bar_prime_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar\_prime\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_bar_prime_ss');
M_.param_names = char(M_.param_names, 'V_ss');
M_.param_names_tex = char(M_.param_names_tex, 'V\_ss');
M_.param_names_long = char(M_.param_names_long, 'V_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'Le_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Le\_ss');
M_.param_names_long = char(M_.param_names_long, 'Le_ss');
M_.param_names = char(M_.param_names, 'Lr_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lr\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lr_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_ss');
M_.param_names = char(M_.param_names, 'Ce_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ce\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ce_ss');
M_.param_names = char(M_.param_names, 'phi_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_b_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'x_ss');
M_.param_names_tex = char(M_.param_names_tex, 'x\_ss');
M_.param_names_long = char(M_.param_names_long, 'x_ss');
M_.param_names = char(M_.param_names, 'eta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_ss');
M_.param_names_long = char(M_.param_names_long, 'eta_ss');
M_.param_names = char(M_.param_names, 'nu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_ss');
M_.param_names = char(M_.param_names, 'Nb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nb_ss');
M_.param_names = char(M_.param_names, 'Nb_e_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nb\_e\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nb_e_ss');
M_.param_names = char(M_.param_names, 'Cb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Cb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Cb_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'Cp_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Cp\_ss');
M_.param_names_long = char(M_.param_names_long, 'Cp_ss');
M_.param_names = char(M_.param_names, 'GDP_ss');
M_.param_names_tex = char(M_.param_names_tex, 'GDP\_ss');
M_.param_names_long = char(M_.param_names_long, 'GDP_ss');
M_.param_names = char(M_.param_names, 'varrho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varrho\_ss');
M_.param_names_long = char(M_.param_names_long, 'varrho_ss');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'gamma_p');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_p');
M_.param_names_long = char(M_.param_names_long, 'gamma_p');
M_.param_names = char(M_.param_names, 'tr_omega_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tr\_omega\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'tr_omega_bar_ss');
M_.param_names = char(M_.param_names, 'spread_RbR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'spread\_RbR\_ss');
M_.param_names_long = char(M_.param_names_long, 'spread_RbR_ss');
M_.param_names = char(M_.param_names, 'chi_e');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_e');
M_.param_names_long = char(M_.param_names_long, 'chi_e');
M_.param_names = char(M_.param_names, 'c_U');
M_.param_names_tex = char(M_.param_names_tex, 'c\_U');
M_.param_names_long = char(M_.param_names_long, 'c_U');
M_.param_names = char(M_.param_names, 'xi_p_fe');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p\_fe');
M_.param_names_long = char(M_.param_names_long, 'xi_p_fe');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 71;
M_.param_nbr = 80;
M_.orig_endo_nbr = 71;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK_RA16_rep_static');
erase_compiled_function('NK_RA16_rep_dynamic');
M_.lead_lag_incidence = [
 0 27 0;
 0 28 0;
 1 29 98;
 2 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 3 34 99;
 0 35 0;
 0 36 0;
 4 37 0;
 5 38 0;
 0 39 100;
 0 40 0;
 0 41 101;
 0 42 0;
 0 43 0;
 6 44 0;
 7 45 0;
 8 46 102;
 0 47 0;
 9 48 0;
 0 49 0;
 10 50 0;
 11 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 12 55 0;
 13 56 0;
 14 57 103;
 0 58 0;
 0 59 104;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 15 68 105;
 16 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 17 73 106;
 0 74 0;
 0 75 0;
 18 76 0;
 19 77 0;
 0 78 107;
 0 79 0;
 0 80 108;
 0 81 0;
 0 82 0;
 20 83 0;
 21 84 109;
 0 85 0;
 22 86 0;
 0 87 0;
 23 88 0;
 24 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 25 93 0;
 26 94 110;
 0 95 0;
 0 96 111;
 0 97 0;]';
M_.nstatic = 39;
M_.nfwrd   = 6;
M_.npred   = 18;
M_.nboth   = 8;
M_.nsfwrd   = 14;
M_.nspred   = 26;
M_.ndynamic   = 32;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(71, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(80, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 272;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.9958;
beta = M_.params( 1 );
M_.params( 3 ) = 0.6;
h = M_.params( 3 );
M_.params( 2 ) = 0.25;
varphi = M_.params( 2 );
M_.params( 4 ) = 0.33;
alpha = M_.params( 4 );
M_.params( 5 ) = 0.025;
delta = M_.params( 5 );
M_.params( 79 ) = 100;
c_U = M_.params( 79 );
M_.params( 6 ) = 4;
eta_i = M_.params( 6 );
M_.params( 7 ) = 6;
epsilon = M_.params( 7 );
M_.params( 8 ) = 0.67;
xi_p = M_.params( 8 );
M_.params( 80 ) = 0.00000001;
xi_p_fe = M_.params( 80 );
M_.params( 75 ) = 0;
gamma_p = M_.params( 75 );
M_.params( 10 ) = 1;
psi_L = M_.params( 10 );
M_.params( 11 ) = 1;
psi_K = M_.params( 11 );
M_.params( 12 ) = 0.35;
sigma = M_.params( 12 );
M_.params( 13 ) = 0.298122852301025;
mu = M_.params( 13 );
M_.params( 14 ) = 0.975;
gamma = M_.params( 14 );
M_.params( 9 ) = 0.9915;
theta = M_.params( 9 );
M_.params( 17 ) = 1.5;
psi_pi = M_.params( 17 );
M_.params( 18 ) = 0.125;
psi_y = M_.params( 18 );
M_.params( 19 ) = 0.8;
rho_i = M_.params( 19 );
M_.params( 20 ) = 0.9;
rho_a = M_.params( 20 );
M_.params( 34 ) = 0.9;
rho_g = M_.params( 34 );
M_.params( 21 ) = 0.16;
sigma_i = M_.params( 21 );
M_.params( 22 ) = 1.2;
sigma_a = M_.params( 22 );
sigma_g = 1;        
M_.params( 23 ) = 0.2;
G_over_Y = M_.params( 23 );
M_.params( 24 ) = 0.0075;
brate = M_.params( 24 );
M_.params( 38 ) = 1.005528976378205;
Pi_ss = M_.params( 38 );
M_.params( 39 ) = M_.params(38)/M_.params(1);
R_ss = M_.params( 39 );
M_.params( 77 ) = 1.000499625436899;
spread_RbR_ss = M_.params( 77 );
M_.params( 42 ) = M_.params(77)*M_.params(39);
Rb_ss = M_.params( 42 );
M_.params( 62 ) = 8;
phi_b_ss = M_.params( 62 );
M_.params( 25 ) = exp(M_.params(12)*norminv(M_.params(24),0,1)-0.5*M_.params(12)^2);
omega_bar_ss = M_.params( 25 );
M_.params( 76 ) = (0.5*M_.params(12)^2+log(M_.params(25)))/M_.params(12);
tr_omega_bar_ss = M_.params( 76 );
M_.params( 26 ) = normcdf(M_.params(76),0,1);
F_ss = M_.params( 26 );
M_.params( 27 ) = 1/(M_.params(12)*M_.params(25))*normpdf(M_.params(76),0,1);
F1_ss = M_.params( 27 );
F11_ss= -F1_ss/omega_bar_ss*(1+(log(omega_bar_ss)+0.5*sigma^2)/sigma^2); 
M_.params( 28 ) = normcdf(M_.params(76)-M_.params(12),0,1);
G_ss = M_.params( 28 );
M_.params( 29 ) = M_.params(25)*M_.params(27);
G1_ss = M_.params( 29 );
M_.params( 30 ) = M_.params(27)+M_.params(25)*F11_ss;
G11_ss = M_.params( 30 );
M_.params( 31 ) = M_.params(25)*(1-M_.params(26))+M_.params(28);
Gamma_ss = M_.params( 31 );
M_.params( 32 ) = 1-M_.params(26);
Gamma1_ss = M_.params( 32 );
M_.params( 33 ) = (-M_.params(27));
Gamma11_ss = M_.params( 33 );
F12_ss    =   -F1_ss/sigma*(1+(0.25*sigma^4-(log(omega_bar_ss))^2)/sigma^2);
F2_ss     =   (0.5*sigma^2-log(omega_bar_ss))/sigma^2*normpdf(tr_omega_bar_ss,0,1);
G12_ss    =   omega_bar_ss*F12_ss;
G2_ss     =   ((0.5*sigma^2-log(omega_bar_ss))/sigma^2-1)*normpdf(tr_omega_bar_ss-sigma,0,1);
Gamma2_ss   =   -omega_bar_ss*F2_ss+G2_ss;
Gamma12_ss  =   -F2_ss;
M_.params( 35 ) = M_.params(32)/(M_.params(32)-M_.params(13)*M_.params(29));
xi_ss = M_.params( 35 );
M_.params( 36 ) = M_.params(32)/(M_.params(32)-M_.params(13)*(M_.params(29)*(1-M_.params(31))+M_.params(28)*M_.params(32)));
spread_RkRb_ss = M_.params( 36 );
M_.params( 37 ) = 1/(1-(M_.params(31)-M_.params(28)*M_.params(13))*M_.params(36));
phi_e_ss = M_.params( 37 );
M_.params( 42 ) = M_.params(77)*M_.params(39);
Rb_ss = M_.params( 42 );
M_.params( 41 ) = M_.params(36)*M_.params(42);
Rk_ss = M_.params( 41 );
M_.params( 40 ) = M_.params(25)*M_.params(41)/(1-1/M_.params(37));
Rl_ss = M_.params( 40 );
M_.params( 43 ) = M_.params(7)/(M_.params(7)-1);
X_ss = M_.params( 43 );
M_.params( 44 ) = (M_.params(7)-1)/M_.params(7);
mc_ss = M_.params( 44 );
M_.params( 45 ) = 1;
Q_ss = M_.params( 45 );
M_.params( 46 ) = M_.params(41)/M_.params(38)-(1-M_.params(5));
rk_ss = M_.params( 46 );
M_.params( 47 ) = (M_.params(4)/(M_.params(43)*(1+M_.params(11)*(M_.params(39)-1))*M_.params(46)))^(1/(1-M_.params(4)));
K_over_l = M_.params( 47 );
M_.params( 48 ) = (1-M_.params(4))*M_.params(47)^M_.params(4)/(M_.params(43)*(1+(M_.params(39)-1)*M_.params(10)));
w_ss = M_.params( 48 );
Y_over_K = X_ss/alpha*(rk_ss)*(1+psi_K*(R_ss-1));      
M_.params( 49 ) = 0.3333333333333333;
l_ss = M_.params( 49 );
M_.params( 50 ) = M_.params(47)*M_.params(49);
K_ss = M_.params( 50 );
M_.params( 51 ) = Y_over_K*M_.params(50);
Y_ss = M_.params( 51 );
M_.params( 52 ) = M_.params(23)*M_.params(51);
Gov_ss = M_.params( 52 );
M_.params( 53 ) = M_.params(5)*M_.params(50);
I_ss = M_.params( 53 );
YK_ss   =   X_ss/alpha*(rk_ss)*(1+psi_K*(R_ss-1));
M_.params( 54 ) = M_.params(25)*M_.params(41);
omega_bar_prime_ss = M_.params( 54 );
M_.params( 55 ) = (1-M_.params(31))*M_.params(41)*M_.params(50)/M_.params(38);
V_ss = M_.params( 55 );
M_.params( 56 ) = M_.params(50)/M_.params(37);
N_ss = M_.params( 56 );
M_.params( 57 ) = M_.params(50)-M_.params(56);
Le_ss = M_.params( 57 );
M_.params( 58 ) = M_.params(49)*M_.params(10)*M_.params(48)+M_.params(50)*M_.params(11)*M_.params(46);
Lr_ss = M_.params( 58 );
M_.params( 59 ) = M_.params(57)+M_.params(58);
L_ss = M_.params( 59 );
M_.params( 60 ) = (M_.params(56)+M_.params(59))/M_.params(56);
phi_ss = M_.params( 60 );
We = N_ss-gamma*V_ss;                       
M_.params( 61 ) = (1-M_.params(14))*M_.params(55);
Ce_ss = M_.params( 61 );
M_.params( 63 ) = (M_.params(39)+(M_.params(42)-M_.params(39))*M_.params(62))/M_.params(38);
z_ss = M_.params( 63 );
M_.params( 64 ) = M_.params(63);
x_ss = M_.params( 64 );
M_.params( 65 ) = (1-M_.params(9))/(1-M_.params(1)*M_.params(9)*M_.params(64));
eta_ss = M_.params( 65 );
M_.params( 66 ) = (1-M_.params(9))*(M_.params(42)-M_.params(39))/M_.params(39)/(1-M_.params(63)*M_.params(1)*M_.params(9));
nu_ss = M_.params( 66 );
M_.params( 15 ) = (M_.params(65)+M_.params(62)*M_.params(66))/M_.params(62);
lambda = M_.params( 15 );
M_.params( 67 ) = M_.params(57)/M_.params(62);
Nb_ss = M_.params( 67 );
M_.params( 68 ) = M_.params(63)*M_.params(9)*M_.params(67);
Nb_e_ss = M_.params( 68 );
M_.params( 16 ) = M_.params(67)-M_.params(68);
N_nb = M_.params( 16 );
M_.params( 69 ) = M_.params(67)*M_.params(63)*(1-M_.params(9));
Cb_ss = M_.params( 69 );
M_.params( 70 ) = M_.params(51)-M_.params(53)-M_.params(61)-M_.params(69)-M_.params(52)-M_.params(50)*M_.params(28)*M_.params(13)*M_.params(41)/M_.params(38);
C_ss = M_.params( 70 );
M_.params( 71 ) = M_.params(69)+M_.params(61)+M_.params(70);
Cp_ss = M_.params( 71 );
M_.params( 72 ) = M_.params(52)+M_.params(53)+M_.params(71);
GDP_ss = M_.params( 72 );
M_.params( 73 ) = (-1)/(M_.params(70)-M_.params(70)*M_.params(3));
varrho_ss = M_.params( 73 );
M_.params( 74 ) = M_.params(48)*M_.params(73)/M_.params(49)^M_.params(2);
chi = M_.params( 74 );
Upsilon     =   1-Gamma_ss+xi_ss*(Gamma_ss-mu*G_ss); 
domegabards1=-(Gamma_ss-mu*G_ss)/((Gamma1_ss-mu*G1_ss)*spread_RkRb_ss);
domegabardphi_e=(1-(Gamma_ss-mu*G_ss)*spread_RkRb_ss)/((Gamma1_ss-mu*G1_ss)*spread_RkRb_ss*phi_e_ss);
domegabardsigma=-(Gamma2_ss-mu*G2_ss)/(Gamma1_ss-mu*G1_ss);
psi_1  =   mu*(Gamma1_ss*G11_ss-Gamma11_ss*G1_ss)/((Gamma1_ss-mu*G1_ss)^2);
psi_2  =   mu*(Gamma1_ss*G12_ss-Gamma12_ss*G1_ss)/((Gamma1_ss-mu*G1_ss)^2);
Upsilon_1   =   psi_1*(Gamma_ss-mu*G_ss);
Upsilon_2   =   -Gamma2_ss+psi_2*(Gamma_ss-mu*G_ss)+xi_ss*(Gamma2_ss-mu*G2_ss);
dphi_eds1=((spread_RkRb_ss*Upsilon_1-psi_1)*domegabards1+Upsilon)/((psi_1-spread_RkRb_ss*Upsilon_1)*domegabardphi_e);
M_.params( 78 ) = M_.params(37)/dphi_eds1*1/M_.params(36);
chi_e = M_.params( 78 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 33 ) = 0;
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(21)^2;
M_.Sigma_e(2, 2) = M_.params(22)^2;
M_.Sigma_e(3, 3) = sigma_g^2;
options_.irf = 40;
options_.order = 1;
var_list_=[];
var_list_ = 'Y';
var_list_ = char(var_list_, 'Y_fe');
var_list_ = char(var_list_, 'outputgap');
info = stoch_simul(var_list_);
save('NK_RA16_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_RA16_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_RA16_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_RA16_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_RA16_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
