function [ys_, params, info] = NK_AFL15_rep_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=params(8);
    ys_(2)=params(7);
    ys_(3)=params(9);
    ys_(4)=params(10);
    ys_(5)=params(11);
    ys_(6)=params(12)+params(30);
    ys_(7)=params(13);
    ys_(8)=params(14);
    ys_(9)=params(15);
    ys_(10)=params(16);
    ys_(11)=params(17);
    ys_(12)=params(53);
    ys_(13)=params(18);
    ys_(14)=params(19);
    ys_(15)=params(20);
    ys_(16)=params(21);
    ys_(17)=params(22);
    ys_(18)=params(23);
    ys_(19)=params(24);
    ys_(20)=params(25);
    ys_(21)=params(26);
    ys_(22)=params(27);
    ys_(23)=params(28);
    ys_(24)=params(29);
    ys_(25)=params(30);
    ys_(26)=params(31);
    ys_(27)=0;
    % Auxiliary equations
    check_=0;
end
