%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_FLMF18';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_FLMF18.log');
M_.exo_names = 'EZ';
M_.exo_names_tex = 'EZ';
M_.exo_names_long = 'EZ';
M_.exo_names = char(M_.exo_names, 'EOMEGA');
M_.exo_names_tex = char(M_.exo_names_tex, 'EOMEGA');
M_.exo_names_long = char(M_.exo_names_long, 'EOMEGA');
M_.exo_names = char(M_.exo_names, 'EA');
M_.exo_names_tex = char(M_.exo_names_tex, 'EA');
M_.exo_names_long = char(M_.exo_names_long, 'EA');
M_.exo_names = char(M_.exo_names, 'EG');
M_.exo_names_tex = char(M_.exo_names_tex, 'EG');
M_.exo_names_long = char(M_.exo_names_long, 'EG');
M_.exo_names = char(M_.exo_names, 'EERR');
M_.exo_names_tex = char(M_.exo_names_tex, 'EERR');
M_.exo_names_long = char(M_.exo_names_long, 'EERR');
M_.exo_names = char(M_.exo_names, 'EGG');
M_.exo_names_tex = char(M_.exo_names_tex, 'EGG');
M_.exo_names_long = char(M_.exo_names_long, 'EGG');
M_.endo_names = 'GG';
M_.endo_names_tex = 'GG';
M_.endo_names_long = 'GG';
M_.endo_names = char(M_.endo_names, 'NGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'NGG');
M_.endo_names_long = char(M_.endo_names_long, 'NGG');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'CY');
M_.endo_names_tex = char(M_.endo_names_tex, 'CY');
M_.endo_names_long = char(M_.endo_names_long, 'CY');
M_.endo_names = char(M_.endo_names, 'TY');
M_.endo_names_tex = char(M_.endo_names_tex, 'TY');
M_.endo_names_long = char(M_.endo_names_long, 'TY');
M_.endo_names = char(M_.endo_names, 'PI');
M_.endo_names_tex = char(M_.endo_names_tex, 'PI');
M_.endo_names_long = char(M_.endo_names_long, 'PI');
M_.endo_names = char(M_.endo_names, 'PIY');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIY');
M_.endo_names_long = char(M_.endo_names_long, 'PIY');
M_.endo_names = char(M_.endo_names, 'MC');
M_.endo_names_tex = char(M_.endo_names_tex, 'MC');
M_.endo_names_long = char(M_.endo_names_long, 'MC');
M_.endo_names = char(M_.endo_names, 'WP');
M_.endo_names_tex = char(M_.endo_names_tex, 'WP');
M_.endo_names_long = char(M_.endo_names_long, 'WP');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'O');
M_.endo_names_tex = char(M_.endo_names_tex, 'O');
M_.endo_names_long = char(M_.endo_names_long, 'O');
M_.endo_names = char(M_.endo_names, 'OC');
M_.endo_names_tex = char(M_.endo_names_tex, 'OC');
M_.endo_names_long = char(M_.endo_names_long, 'OC');
M_.endo_names = char(M_.endo_names, 'OY');
M_.endo_names_tex = char(M_.endo_names_tex, 'OY');
M_.endo_names_long = char(M_.endo_names_long, 'OY');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'OMEGA');
M_.endo_names_tex = char(M_.endo_names_tex, 'OMEGA');
M_.endo_names_long = char(M_.endo_names_long, 'OMEGA');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'ETA');
M_.endo_names_tex = char(M_.endo_names_tex, 'ETA');
M_.endo_names_long = char(M_.endo_names_long, 'ETA');
M_.endo_names = char(M_.endo_names, 'NY');
M_.endo_names_tex = char(M_.endo_names_tex, 'NY');
M_.endo_names_long = char(M_.endo_names_long, 'NY');
M_.endo_names = char(M_.endo_names, 'NC');
M_.endo_names_tex = char(M_.endo_names_tex, 'NC');
M_.endo_names_long = char(M_.endo_names_long, 'NC');
M_.endo_names = char(M_.endo_names, 'NCY');
M_.endo_names_tex = char(M_.endo_names_tex, 'NCY');
M_.endo_names_long = char(M_.endo_names_long, 'NCY');
M_.endo_names = char(M_.endo_names, 'NTY');
M_.endo_names_tex = char(M_.endo_names_tex, 'NTY');
M_.endo_names_long = char(M_.endo_names_long, 'NTY');
M_.endo_names = char(M_.endo_names, 'NPI');
M_.endo_names_tex = char(M_.endo_names_tex, 'NPI');
M_.endo_names_long = char(M_.endo_names_long, 'NPI');
M_.endo_names = char(M_.endo_names, 'NN');
M_.endo_names_tex = char(M_.endo_names_tex, 'NN');
M_.endo_names_long = char(M_.endo_names_long, 'NN');
M_.endo_names = char(M_.endo_names, 'DD');
M_.endo_names_tex = char(M_.endo_names_tex, 'DD');
M_.endo_names_long = char(M_.endo_names_long, 'DD');
M_.endo_names = char(M_.endo_names, 'NPIY');
M_.endo_names_tex = char(M_.endo_names_tex, 'NPIY');
M_.endo_names_long = char(M_.endo_names_long, 'NPIY');
M_.endo_names = char(M_.endo_names, 'DELTA');
M_.endo_names_tex = char(M_.endo_names_tex, 'DELTA');
M_.endo_names_long = char(M_.endo_names_long, 'DELTA');
M_.endo_names = char(M_.endo_names, 'NMC');
M_.endo_names_tex = char(M_.endo_names_tex, 'NMC');
M_.endo_names_long = char(M_.endo_names_long, 'NMC');
M_.endo_names = char(M_.endo_names, 'NWP');
M_.endo_names_tex = char(M_.endo_names_tex, 'NWP');
M_.endo_names_long = char(M_.endo_names_long, 'NWP');
M_.endo_names = char(M_.endo_names, 'NL');
M_.endo_names_tex = char(M_.endo_names_tex, 'NL');
M_.endo_names_long = char(M_.endo_names_long, 'NL');
M_.endo_names = char(M_.endo_names, 'NR');
M_.endo_names_tex = char(M_.endo_names_tex, 'NR');
M_.endo_names_long = char(M_.endo_names_long, 'NR');
M_.endo_names = char(M_.endo_names, 'NO');
M_.endo_names_tex = char(M_.endo_names_tex, 'NO');
M_.endo_names_long = char(M_.endo_names_long, 'NO');
M_.endo_names = char(M_.endo_names, 'NOC');
M_.endo_names_tex = char(M_.endo_names_tex, 'NOC');
M_.endo_names_long = char(M_.endo_names_long, 'NOC');
M_.endo_names = char(M_.endo_names, 'NOY');
M_.endo_names_tex = char(M_.endo_names_tex, 'NOY');
M_.endo_names_long = char(M_.endo_names_long, 'NOY');
M_.endo_names = char(M_.endo_names, 'NX');
M_.endo_names_tex = char(M_.endo_names_tex, 'NX');
M_.endo_names_long = char(M_.endo_names_long, 'NX');
M_.endo_names = char(M_.endo_names, 'NQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'NQ');
M_.endo_names_long = char(M_.endo_names_long, 'NQ');
M_.endo_names = char(M_.endo_names, 'NZ');
M_.endo_names_tex = char(M_.endo_names_tex, 'NZ');
M_.endo_names_long = char(M_.endo_names_long, 'NZ');
M_.endo_names = char(M_.endo_names, 'NOMEGA');
M_.endo_names_tex = char(M_.endo_names_tex, 'NOMEGA');
M_.endo_names_long = char(M_.endo_names_long, 'NOMEGA');
M_.endo_names = char(M_.endo_names, 'NA');
M_.endo_names_tex = char(M_.endo_names_tex, 'NA');
M_.endo_names_long = char(M_.endo_names_long, 'NA');
M_.endo_names = char(M_.endo_names, 'NETA');
M_.endo_names_tex = char(M_.endo_names_tex, 'NETA');
M_.endo_names_long = char(M_.endo_names_long, 'NETA');
M_.endo_names = char(M_.endo_names, 'NY_aux');
M_.endo_names_tex = char(M_.endo_names_tex, 'NY\_aux');
M_.endo_names_long = char(M_.endo_names_long, 'NY_aux');
M_.endo_names = char(M_.endo_names, 'Y_aux');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_aux');
M_.endo_names_long = char(M_.endo_names_long, 'Y_aux');
M_.endo_names = char(M_.endo_names, 'NYn');
M_.endo_names_tex = char(M_.endo_names_tex, 'NYn');
M_.endo_names_long = char(M_.endo_names_long, 'NYn');
M_.endo_names = char(M_.endo_names, 'Yn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yn');
M_.endo_names_long = char(M_.endo_names_long, 'Yn');
M_.endo_names = char(M_.endo_names, 'Yn_gap');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yn\_gap');
M_.endo_names_long = char(M_.endo_names_long, 'Yn_gap');
M_.endo_names = char(M_.endo_names, 'Y_gap');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_gap');
M_.endo_names_long = char(M_.endo_names_long, 'Y_gap');
M_.endo_names = char(M_.endo_names, 'NYe');
M_.endo_names_tex = char(M_.endo_names_tex, 'NYe');
M_.endo_names_long = char(M_.endo_names_long, 'NYe');
M_.endo_names = char(M_.endo_names, 'Ye');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ye');
M_.endo_names_long = char(M_.endo_names_long, 'Ye');
M_.endo_names = char(M_.endo_names, 'NYfe');
M_.endo_names_tex = char(M_.endo_names_tex, 'NYfe');
M_.endo_names_long = char(M_.endo_names_long, 'NYfe');
M_.endo_names = char(M_.endo_names, 'Yfe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yfe');
M_.endo_names_long = char(M_.endo_names_long, 'Yfe');
M_.endo_names = char(M_.endo_names, 'NRn');
M_.endo_names_tex = char(M_.endo_names_tex, 'NRn');
M_.endo_names_long = char(M_.endo_names_long, 'NRn');
M_.endo_names = char(M_.endo_names, 'Rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rn');
M_.endo_names_long = char(M_.endo_names_long, 'Rn');
M_.endo_names = char(M_.endo_names, 'NRe');
M_.endo_names_tex = char(M_.endo_names_tex, 'NRe');
M_.endo_names_long = char(M_.endo_names_long, 'NRe');
M_.endo_names = char(M_.endo_names, 'Re');
M_.endo_names_tex = char(M_.endo_names_tex, 'Re');
M_.endo_names_long = char(M_.endo_names_long, 'Re');
M_.endo_names = char(M_.endo_names, 'NRfe');
M_.endo_names_tex = char(M_.endo_names_tex, 'NRfe');
M_.endo_names_long = char(M_.endo_names_long, 'NRfe');
M_.endo_names = char(M_.endo_names, 'Rfe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rfe');
M_.endo_names_long = char(M_.endo_names_long, 'Rfe');
M_.endo_names = char(M_.endo_names, 'UTIL');
M_.endo_names_tex = char(M_.endo_names_tex, 'UTIL');
M_.endo_names_long = char(M_.endo_names_long, 'UTIL');
M_.endo_names = char(M_.endo_names, 'WELF');
M_.endo_names_tex = char(M_.endo_names_tex, 'WELF');
M_.endo_names_long = char(M_.endo_names_long, 'WELF');
M_.endo_names = char(M_.endo_names, 'ERR');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERR');
M_.endo_names_long = char(M_.endo_names_long, 'ERR');
M_.endo_names = char(M_.endo_names, 'Z_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'Z_CB');
M_.endo_names = char(M_.endo_names, 'ETA_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'ETA\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'ETA_CB');
M_.endo_names = char(M_.endo_names, 'A_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'A\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'A_CB');
M_.endo_names = char(M_.endo_names, 'G_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'G_CB');
M_.endo_names = char(M_.endo_names, 'Yfe_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yfe\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'Yfe_CB');
M_.endo_names = char(M_.endo_names, 'Y_gap_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_gap\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'Y_gap_CB');
M_.endo_names = char(M_.endo_names, 'Rfe_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rfe\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'Rfe_CB');
M_.endo_names = char(M_.endo_names, 'ERR_CB');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERR\_CB');
M_.endo_names_long = char(M_.endo_names_long, 'ERR_CB');
M_.endo_names = char(M_.endo_names, 'ERR_CBS');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERR\_CBS');
M_.endo_names_long = char(M_.endo_names_long, 'ERR_CBS');
M_.endo_names = char(M_.endo_names, 'EYG');
M_.endo_names_tex = char(M_.endo_names_tex, 'EYG');
M_.endo_names_long = char(M_.endo_names_long, 'EYG');
M_.endo_names = char(M_.endo_names, 'EPI');
M_.endo_names_tex = char(M_.endo_names_tex, 'EPI');
M_.endo_names_long = char(M_.endo_names_long, 'EPI');
M_.endo_names = char(M_.endo_names, 'ERE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERE');
M_.endo_names_long = char(M_.endo_names_long, 'ERE');
M_.endo_names = char(M_.endo_names, 'EPIC');
M_.endo_names_tex = char(M_.endo_names_tex, 'EPIC');
M_.endo_names_long = char(M_.endo_names_long, 'EPIC');
M_.endo_names = char(M_.endo_names, 'R1');
M_.endo_names_tex = char(M_.endo_names_tex, 'R1');
M_.endo_names_long = char(M_.endo_names_long, 'R1');
M_.endo_names = char(M_.endo_names, 'R2');
M_.endo_names_tex = char(M_.endo_names_tex, 'R2');
M_.endo_names_long = char(M_.endo_names_long, 'R2');
M_.endo_names = char(M_.endo_names, 'ERN');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERN');
M_.endo_names_long = char(M_.endo_names_long, 'ERN');
M_.endo_names = char(M_.endo_names, 'EY');
M_.endo_names_tex = char(M_.endo_names_tex, 'EY');
M_.endo_names_long = char(M_.endo_names_long, 'EY');
M_.endo_names = char(M_.endo_names, 'EYNG');
M_.endo_names_tex = char(M_.endo_names_tex, 'EYNG');
M_.endo_names_long = char(M_.endo_names_long, 'EYNG');
M_.endo_partitions = struct();
M_.param_names = 'scale_Y';
M_.param_names_tex = 'scale\_Y';
M_.param_names_long = 'scale_Y';
M_.param_names = char(M_.param_names, 'XI');
M_.param_names_tex = char(M_.param_names_tex, 'XI');
M_.param_names_long = char(M_.param_names_long, 'XI');
M_.param_names = char(M_.param_names, 'GAMMA');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMA');
M_.param_names_long = char(M_.param_names_long, 'GAMMA');
M_.param_names = char(M_.param_names, 'KAPPA');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPA');
M_.param_names_long = char(M_.param_names_long, 'KAPPA');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'NU');
M_.param_names_tex = char(M_.param_names_tex, 'NU');
M_.param_names_long = char(M_.param_names_long, 'NU');
M_.param_names = char(M_.param_names, 'PHI_HEAD');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_HEAD');
M_.param_names_long = char(M_.param_names_long, 'PHI_HEAD');
M_.param_names = char(M_.param_names, 'PHI_CORE');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_CORE');
M_.param_names_long = char(M_.param_names_long, 'PHI_CORE');
M_.param_names = char(M_.param_names, 'PHI_COMM');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_COMM');
M_.param_names_long = char(M_.param_names_long, 'PHI_COMM');
M_.param_names = char(M_.param_names, 'RHO_Z');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_Z');
M_.param_names_long = char(M_.param_names_long, 'RHO_Z');
M_.param_names = char(M_.param_names, 'RHO_OMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_OMEGA');
M_.param_names_long = char(M_.param_names_long, 'RHO_OMEGA');
M_.param_names = char(M_.param_names, 'RHO_A');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_A');
M_.param_names_long = char(M_.param_names_long, 'RHO_A');
M_.param_names = char(M_.param_names, 'RHO_ERR');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_ERR');
M_.param_names_long = char(M_.param_names_long, 'RHO_ERR');
M_.param_names = char(M_.param_names, 'SZ');
M_.param_names_tex = char(M_.param_names_tex, 'SZ');
M_.param_names_long = char(M_.param_names_long, 'SZ');
M_.param_names = char(M_.param_names, 'SOMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'SOMEGA');
M_.param_names_long = char(M_.param_names_long, 'SOMEGA');
M_.param_names = char(M_.param_names, 'SA');
M_.param_names_tex = char(M_.param_names_tex, 'SA');
M_.param_names_long = char(M_.param_names_long, 'SA');
M_.param_names = char(M_.param_names, 'SERR');
M_.param_names_tex = char(M_.param_names_tex, 'SERR');
M_.param_names_long = char(M_.param_names_long, 'SERR');
M_.param_names = char(M_.param_names, 'SERR_Z');
M_.param_names_tex = char(M_.param_names_tex, 'SERR\_Z');
M_.param_names_long = char(M_.param_names_long, 'SERR_Z');
M_.param_names = char(M_.param_names, 'SERR_OMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'SERR\_OMEGA');
M_.param_names_long = char(M_.param_names_long, 'SERR_OMEGA');
M_.param_names = char(M_.param_names, 'SERR_A');
M_.param_names_tex = char(M_.param_names_tex, 'SERR\_A');
M_.param_names_long = char(M_.param_names_long, 'SERR_A');
M_.param_names = char(M_.param_names, 'SERR_G');
M_.param_names_tex = char(M_.param_names_tex, 'SERR\_G');
M_.param_names_long = char(M_.param_names_long, 'SERR_G');
M_.param_names = char(M_.param_names, 'ES');
M_.param_names_tex = char(M_.param_names_tex, 'ES');
M_.param_names_long = char(M_.param_names_long, 'ES');
M_.param_names = char(M_.param_names, 'MU');
M_.param_names_tex = char(M_.param_names_tex, 'MU');
M_.param_names_long = char(M_.param_names_long, 'MU');
M_.param_names = char(M_.param_names, 'EPS');
M_.param_names_tex = char(M_.param_names_tex, 'EPS');
M_.param_names_long = char(M_.param_names_long, 'EPS');
M_.param_names = char(M_.param_names, 'BETA');
M_.param_names_tex = char(M_.param_names_tex, 'BETA');
M_.param_names_long = char(M_.param_names_long, 'BETA');
M_.param_names = char(M_.param_names, 'THETA');
M_.param_names_tex = char(M_.param_names_tex, 'THETA');
M_.param_names_long = char(M_.param_names_long, 'THETA');
M_.param_names = char(M_.param_names, 'ZS');
M_.param_names_tex = char(M_.param_names_tex, 'ZS');
M_.param_names_long = char(M_.param_names_long, 'ZS');
M_.param_names = char(M_.param_names, 'AS');
M_.param_names_tex = char(M_.param_names_tex, 'AS');
M_.param_names_long = char(M_.param_names_long, 'AS');
M_.param_names = char(M_.param_names, 'RHO_G');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_G');
M_.param_names_long = char(M_.param_names_long, 'RHO_G');
M_.param_names = char(M_.param_names, 'SG');
M_.param_names_tex = char(M_.param_names_tex, 'SG');
M_.param_names_long = char(M_.param_names_long, 'SG');
M_.param_names = char(M_.param_names, 'PHI_BENCH');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_BENCH');
M_.param_names_long = char(M_.param_names_long, 'PHI_BENCH');
M_.param_names = char(M_.param_names, 'PHI_NAT');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_NAT');
M_.param_names_long = char(M_.param_names_long, 'PHI_NAT');
M_.param_names = char(M_.param_names, 'PHI_EFF');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_EFF');
M_.param_names_long = char(M_.param_names_long, 'PHI_EFF');
M_.param_names = char(M_.param_names, 'PHI_Y');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_Y');
M_.param_names_long = char(M_.param_names_long, 'PHI_Y');
M_.param_names = char(M_.param_names, 'PHI_Yn');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_Yn');
M_.param_names_long = char(M_.param_names_long, 'PHI_Yn');
M_.param_names = char(M_.param_names, 'PHI_Yfe');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_Yfe');
M_.param_names_long = char(M_.param_names_long, 'PHI_Yfe');
M_.param_names = char(M_.param_names, 'Y_gapS');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_gapS');
M_.param_names_long = char(M_.param_names_long, 'Y_gapS');
M_.param_names = char(M_.param_names, 'M1_a');
M_.param_names_tex = char(M_.param_names_tex, 'M1\_a');
M_.param_names_long = char(M_.param_names_long, 'M1_a');
M_.param_names = char(M_.param_names, 'M1_b');
M_.param_names_tex = char(M_.param_names_tex, 'M1\_b');
M_.param_names_long = char(M_.param_names_long, 'M1_b');
M_.param_names = char(M_.param_names, 'M1_c');
M_.param_names_tex = char(M_.param_names_tex, 'M1\_c');
M_.param_names_long = char(M_.param_names_long, 'M1_c');
M_.param_names = char(M_.param_names, 'M1');
M_.param_names_tex = char(M_.param_names_tex, 'M1');
M_.param_names_long = char(M_.param_names_long, 'M1');
M_.param_names = char(M_.param_names, 'M2_a');
M_.param_names_tex = char(M_.param_names_tex, 'M2\_a');
M_.param_names_long = char(M_.param_names_long, 'M2_a');
M_.param_names = char(M_.param_names, 'M2_b');
M_.param_names_tex = char(M_.param_names_tex, 'M2\_b');
M_.param_names_long = char(M_.param_names_long, 'M2_b');
M_.param_names = char(M_.param_names, 'M2_c');
M_.param_names_tex = char(M_.param_names_tex, 'M2\_c');
M_.param_names_long = char(M_.param_names_long, 'M2_c');
M_.param_names = char(M_.param_names, 'M2');
M_.param_names_tex = char(M_.param_names_tex, 'M2');
M_.param_names_long = char(M_.param_names_long, 'M2');
M_.param_names = char(M_.param_names, 'PHI_MISP_a');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_MISP\_a');
M_.param_names_long = char(M_.param_names_long, 'PHI_MISP_a');
M_.param_names = char(M_.param_names, 'PHI_MISP_b');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_MISP\_b');
M_.param_names_long = char(M_.param_names_long, 'PHI_MISP_b');
M_.param_names = char(M_.param_names, 'PHI_MISP_c');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_MISP\_c');
M_.param_names_long = char(M_.param_names_long, 'PHI_MISP_c');
M_.param_names = char(M_.param_names, 'CORR_Z_ETA');
M_.param_names_tex = char(M_.param_names_tex, 'CORR\_Z\_ETA');
M_.param_names_long = char(M_.param_names_long, 'CORR_Z_ETA');
M_.param_names = char(M_.param_names, 'S_Z_ETA');
M_.param_names_tex = char(M_.param_names_tex, 'S\_Z\_ETA');
M_.param_names_long = char(M_.param_names_long, 'S_Z_ETA');
M_.param_names = char(M_.param_names, 'PHI_CB');
M_.param_names_tex = char(M_.param_names_tex, 'PHI\_CB');
M_.param_names_long = char(M_.param_names_long, 'PHI_CB');
M_.param_names = char(M_.param_names, 'Z_CBS');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_CBS');
M_.param_names_long = char(M_.param_names_long, 'Z_CBS');
M_.param_names = char(M_.param_names, 'Yfe_CBS');
M_.param_names_tex = char(M_.param_names_tex, 'Yfe\_CBS');
M_.param_names_long = char(M_.param_names_long, 'Yfe_CBS');
M_.param_names = char(M_.param_names, 'YfeS');
M_.param_names_tex = char(M_.param_names_tex, 'YfeS');
M_.param_names_long = char(M_.param_names_long, 'YfeS');
M_.param_names = char(M_.param_names, 'Y_gap_CBS');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_gap\_CBS');
M_.param_names_long = char(M_.param_names_long, 'Y_gap_CBS');
M_.param_names = char(M_.param_names, 'Rfe_CBS');
M_.param_names_tex = char(M_.param_names_tex, 'Rfe\_CBS');
M_.param_names_long = char(M_.param_names_long, 'Rfe_CBS');
M_.param_names = char(M_.param_names, 'RfeS');
M_.param_names_tex = char(M_.param_names_tex, 'RfeS');
M_.param_names_long = char(M_.param_names_long, 'RfeS');
M_.param_names = char(M_.param_names, 'YS');
M_.param_names_tex = char(M_.param_names_tex, 'YS');
M_.param_names_long = char(M_.param_names_long, 'YS');
M_.param_names = char(M_.param_names, 'NOMEGAS');
M_.param_names_tex = char(M_.param_names_tex, 'NOMEGAS');
M_.param_names_long = char(M_.param_names_long, 'NOMEGAS');
M_.param_names = char(M_.param_names, 'isexp');
M_.param_names_tex = char(M_.param_names_tex, 'isexp');
M_.param_names_long = char(M_.param_names_long, 'isexp');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 6;
M_.endo_nbr = 81;
M_.param_nbr = 60;
M_.orig_endo_nbr = 81;
M_.aux_vars = [];
M_.Sigma_e = zeros(6, 6);
M_.Correlation_matrix = eye(6, 6);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_FLMF18_static');
erase_compiled_function('NK_FLMF18_dynamic');
M_.orig_eq_nbr = 81;
M_.eq_nbr = 81;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 18 0;
 0 19 0;
 0 20 99;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 100;
 0 25 101;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 2 34 0;
 3 35 0;
 4 36 0;
 5 37 0;
 6 38 102;
 0 39 0;
 0 40 0;
 0 41 103;
 0 42 0;
 0 43 0;
 0 44 104;
 0 45 105;
 0 46 106;
 0 47 107;
 7 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 8 57 108;
 0 58 109;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 110;
 0 65 0;
 0 66 111;
 0 67 112;
 0 68 113;
 0 69 0;
 0 70 114;
 0 71 0;
 0 72 0;
 0 73 115;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 116;
 0 78 0;
 0 79 117;
 9 80 0;
 0 81 118;
 0 82 0;
 0 83 0;
 0 84 119;
 0 85 120;
 0 86 121;
 0 87 122;
 10 88 0;
 0 89 0;
 11 90 0;
 12 91 0;
 13 92 0;
 14 93 0;
 0 94 0;
 0 95 0;
 15 96 0;
 16 97 0;
 17 98 0;]';
M_.nstatic = 42;
M_.nfwrd   = 22;
M_.npred   = 15;
M_.nboth   = 2;
M_.nsfwrd   = 24;
M_.nspred   = 17;
M_.ndynamic   = 39;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:6];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(81, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(6, 1);
M_.params = NaN(60, 1);
M_.NNZDerivatives = [265; -1; -1];
M_.params( 1 ) = 1;
scale_Y = M_.params( 1 );
M_.params( 3 ) = 0.1;
GAMMA = M_.params( 3 );
M_.params( 2 ) = 1-M_.params(3);
XI = M_.params( 2 );
M_.params( 5 ) = 0.1;
ALPHA = M_.params( 5 );
M_.params( 6 ) = 0.5;
NU = M_.params( 6 );
M_.params( 24 ) = 7.67;
EPS = M_.params( 24 );
M_.params( 23 ) = M_.params(24)/(M_.params(24)-1);
MU = M_.params( 23 );
M_.params( 25 ) = 0.99;
BETA = M_.params( 25 );
M_.params( 26 ) = 0.75;
THETA = M_.params( 26 );
M_.params( 4 ) = (1-M_.params(26))/M_.params(26)*(1-M_.params(26)*M_.params(25));
KAPPA = M_.params( 4 );
M_.params( 60 ) = 1;
isexp = M_.params( 60 );
M_.params( 7 ) = 0;
PHI_HEAD = M_.params( 7 );
M_.params( 8 ) = 1.5;
PHI_CORE = M_.params( 8 );
M_.params( 9 ) = 0.05;
PHI_COMM = M_.params( 9 );
M_.params( 35 ) = 0.5*M_.params(1);
PHI_Yn = M_.params( 35 );
M_.params( 36 ) = 0.5*M_.params(1);
PHI_Yfe = M_.params( 36 );
M_.params( 34 ) = 0.5*M_.params(1);
PHI_Y = M_.params( 34 );
M_.params( 51 ) = 0;
PHI_CB = M_.params( 51 );
M_.params( 31 ) = 0;
PHI_BENCH = M_.params( 31 );
M_.params( 32 ) = 0;
PHI_NAT = M_.params( 32 );
M_.params( 33 ) = 1;
PHI_EFF = M_.params( 33 );
M_.params( 28 ) = 1;
AS = M_.params( 28 );
M_.params( 27 ) = 1;
ZS = M_.params( 27 );
M_.params( 22 ) = 0.01;
ES = M_.params( 22 );
M_.params( 10 ) = 0.95;
RHO_Z = M_.params( 10 );
M_.params( 11 ) = 0.5;
RHO_OMEGA = M_.params( 11 );
M_.params( 12 ) = 0.5;
RHO_A = M_.params( 12 );
M_.params( 29 ) = 0.5;
RHO_G = M_.params( 29 );
RHO_GG      = 0.5;        
M_.params( 13 ) = 0.5;
RHO_ERR = M_.params( 13 );
M_.params( 14 ) = 0.01;
SZ = M_.params( 14 );
M_.params( 15 ) = 0.01;
SOMEGA = M_.params( 15 );
M_.params( 16 ) = 0.01;
SA = M_.params( 16 );
M_.params( 30 ) = 0.01;
SG = M_.params( 30 );
M_.params( 17 ) = 0.01;
SERR = M_.params( 17 );
M_.params( 18 ) = 0;
SERR_Z = M_.params( 18 );
M_.params( 19 ) = 0;
SERR_OMEGA = M_.params( 19 );
M_.params( 20 ) = 0;
SERR_A = M_.params( 20 );
M_.params( 21 ) = 0;
SERR_G = M_.params( 21 );
M_.params( 46 ) = 0;
PHI_MISP_a = M_.params( 46 );
M_.params( 47 ) = 0;
PHI_MISP_b = M_.params( 47 );
M_.params( 48 ) = 0;
PHI_MISP_c = M_.params( 48 );
M_.params( 49 ) = 0.5;
CORR_Z_ETA = M_.params( 49 );
M_.params( 50 ) = 0.5;
S_Z_ETA = M_.params( 50 );
M_.params( 38 ) = 0;
M1_a = M_.params( 38 );
M_.params( 42 ) = (1-oo_.steady_state(44))/oo_.steady_state(44);
M2_a = M_.params( 42 );
M_.params( 39 ) = (-1);
M1_b = M_.params( 39 );
M_.params( 43 ) = 0;
M2_b = M_.params( 43 );
M_.params( 40 ) = (-0.5);
M1_c = M_.params( 40 );
M_.params( 44 ) = 0.5;
M2_c = M_.params( 44 );
M_.params( 41 ) = M_.params(38)*M_.params(46)+M_.params(39)*M_.params(47)+M_.params(40)*M_.params(48);
M1 = M_.params( 41 );
M_.params( 45 ) = M_.params(46)*M_.params(42)+M_.params(47)*M_.params(43)+M_.params(48)*M_.params(44);
M2 = M_.params( 45 );
M_.params( 37 ) = oo_.steady_state(50);
Y_gapS = M_.params( 37 );
M_.params( 52 ) = oo_.steady_state(64);
Z_CBS = M_.params( 52 );
M_.params( 53 ) = oo_.steady_state(68);
Yfe_CBS = M_.params( 53 );
M_.params( 54 ) = oo_.steady_state(54);
YfeS = M_.params( 54 );
M_.params( 55 ) = oo_.steady_state(69);
Y_gap_CBS = M_.params( 55 );
M_.params( 56 ) = oo_.steady_state(70);
Rfe_CBS = M_.params( 56 );
M_.params( 57 ) = oo_.steady_state(60);
RfeS = M_.params( 57 );
M_.params( 58 ) = oo_.steady_state(3);
YS = M_.params( 58 );
M_.params( 59 ) = oo_.steady_state(42);
NOMEGAS = M_.params( 59 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(14))^2;
M_.Sigma_e(6, 6) = (M_.params(30))^2;
options_.irf = 20;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_ = char('NY','X','Q','R','PI','Y','Y_gap');
info = stoch_simul(var_list_);
save('NK_FLMF18_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_FLMF18_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_FLMF18_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_FLMF18_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_FLMF18_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_FLMF18_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_FLMF18_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
