%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_FV10_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_FV10_rep.log');
M_.exo_names = 'epsd';
M_.exo_names_tex = 'epsd';
M_.exo_names_long = 'epsd';
M_.exo_names = char(M_.exo_names, 'epsphi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsphi');
M_.exo_names_long = char(M_.exo_names_long, 'epsphi');
M_.exo_names = char(M_.exo_names, 'epsmu_I');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsmu\_I');
M_.exo_names_long = char(M_.exo_names_long, 'epsmu_I');
M_.exo_names = char(M_.exo_names, 'epsA');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsA');
M_.exo_names_long = char(M_.exo_names_long, 'epsA');
M_.exo_names = char(M_.exo_names, 'epsm');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsm');
M_.exo_names_long = char(M_.exo_names_long, 'epsm');
M_.endo_names = 'd';
M_.endo_names_tex = 'd';
M_.endo_names_long = 'd';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'mu_z');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_z');
M_.endo_names_long = char(M_.endo_names_long, 'mu_z');
M_.endo_names = char(M_.endo_names, 'mu_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_I');
M_.endo_names_long = char(M_.endo_names_long, 'mu_I');
M_.endo_names = char(M_.endo_names, 'mu_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_A');
M_.endo_names_long = char(M_.endo_names_long, 'mu_A');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'PI');
M_.endo_names_tex = char(M_.endo_names_tex, 'PI');
M_.endo_names_long = char(M_.endo_names_long, 'PI');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'ld');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld');
M_.endo_names_long = char(M_.endo_names_long, 'ld');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names_long = char(M_.endo_names_long, 'wstar');
M_.endo_names = char(M_.endo_names, 'PIstarw');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstarw');
M_.endo_names_long = char(M_.endo_names_long, 'PIstarw');
M_.endo_names = char(M_.endo_names, 'PIstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIstar');
M_.endo_names_long = char(M_.endo_names_long, 'PIstar');
M_.endo_names = char(M_.endo_names, 'g1');
M_.endo_names_tex = char(M_.endo_names_tex, 'g1');
M_.endo_names_long = char(M_.endo_names_long, 'g1');
M_.endo_names = char(M_.endo_names, 'g2');
M_.endo_names_tex = char(M_.endo_names_tex, 'g2');
M_.endo_names_long = char(M_.endo_names_long, 'g2');
M_.endo_names = char(M_.endo_names, 'yd');
M_.endo_names_tex = char(M_.endo_names_tex, 'yd');
M_.endo_names_long = char(M_.endo_names_long, 'yd');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'vp');
M_.endo_names_tex = char(M_.endo_names_tex, 'vp');
M_.endo_names_long = char(M_.endo_names_long, 'vp');
M_.endo_names = char(M_.endo_names, 'vw');
M_.endo_names_tex = char(M_.endo_names_tex, 'vw');
M_.endo_names_long = char(M_.endo_names_long, 'vw');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'yg');
M_.endo_names_tex = char(M_.endo_names_tex, 'yg');
M_.endo_names_long = char(M_.endo_names_long, 'yg');
M_.param_names = 'h';
M_.param_names_tex = 'h';
M_.param_names_long = 'h';
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'gammma1');
M_.param_names_tex = char(M_.param_names_tex, 'gammma1');
M_.param_names_long = char(M_.param_names_long, 'gammma1');
M_.param_names = char(M_.param_names, 'gammma2');
M_.param_names_tex = char(M_.param_names_tex, 'gammma2');
M_.param_names_long = char(M_.param_names_long, 'gammma2');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'varpsi');
M_.param_names_tex = char(M_.param_names_tex, 'varpsi');
M_.param_names_long = char(M_.param_names_long, 'varpsi');
M_.param_names = char(M_.param_names, 'gammma');
M_.param_names_tex = char(M_.param_names_tex, 'gammma');
M_.param_names_long = char(M_.param_names_long, 'gammma');
M_.param_names = char(M_.param_names, 'chiw');
M_.param_names_tex = char(M_.param_names_tex, 'chiw');
M_.param_names_long = char(M_.param_names_long, 'chiw');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'thetap');
M_.param_names_tex = char(M_.param_names_tex, 'thetap');
M_.param_names_long = char(M_.param_names_long, 'thetap');
M_.param_names = char(M_.param_names, 'thetaw');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw');
M_.param_names_long = char(M_.param_names_long, 'thetaw');
M_.param_names = char(M_.param_names, 'alppha');
M_.param_names_tex = char(M_.param_names_tex, 'alppha');
M_.param_names_long = char(M_.param_names_long, 'alppha');
M_.param_names = char(M_.param_names, 'Rbar');
M_.param_names_tex = char(M_.param_names_tex, 'Rbar');
M_.param_names_long = char(M_.param_names_long, 'Rbar');
M_.param_names = char(M_.param_names, 'PIbar');
M_.param_names_tex = char(M_.param_names_tex, 'PIbar');
M_.param_names_long = char(M_.param_names_long, 'PIbar');
M_.param_names = char(M_.param_names, 'gammmaR');
M_.param_names_tex = char(M_.param_names_tex, 'gammmaR');
M_.param_names_long = char(M_.param_names_long, 'gammmaR');
M_.param_names = char(M_.param_names, 'gammmaPI');
M_.param_names_tex = char(M_.param_names_tex, 'gammmaPI');
M_.param_names_long = char(M_.param_names_long, 'gammmaPI');
M_.param_names = char(M_.param_names, 'gammmay');
M_.param_names_tex = char(M_.param_names_tex, 'gammmay');
M_.param_names_long = char(M_.param_names_long, 'gammmay');
M_.param_names = char(M_.param_names, 'Phi');
M_.param_names_tex = char(M_.param_names_tex, 'Phi');
M_.param_names_long = char(M_.param_names_long, 'Phi');
M_.param_names = char(M_.param_names, 'rhod');
M_.param_names_tex = char(M_.param_names_tex, 'rhod');
M_.param_names_long = char(M_.param_names_long, 'rhod');
M_.param_names = char(M_.param_names, 'rhophi');
M_.param_names_tex = char(M_.param_names_tex, 'rhophi');
M_.param_names_long = char(M_.param_names_long, 'rhophi');
M_.param_names = char(M_.param_names, 'Lambdamu');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdamu');
M_.param_names_long = char(M_.param_names_long, 'Lambdamu');
M_.param_names = char(M_.param_names, 'LambdaA');
M_.param_names_tex = char(M_.param_names_tex, 'LambdaA');
M_.param_names_long = char(M_.param_names_long, 'LambdaA');
M_.param_names = char(M_.param_names, 'Lambdax');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdax');
M_.param_names_long = char(M_.param_names_long, 'Lambdax');
M_.param_names = char(M_.param_names, 'LambdaYd');
M_.param_names_tex = char(M_.param_names_tex, 'LambdaYd');
M_.param_names_long = char(M_.param_names_long, 'LambdaYd');
M_.param_names = char(M_.param_names, 'sigma_d');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_d');
M_.param_names_long = char(M_.param_names_long, 'sigma_d');
M_.param_names = char(M_.param_names, 'sigma_phi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_phi');
M_.param_names_long = char(M_.param_names_long, 'sigma_phi');
M_.param_names = char(M_.param_names, 'sigma_mu');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_mu');
M_.param_names_long = char(M_.param_names_long, 'sigma_mu');
M_.param_names = char(M_.param_names, 'sigma_A');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_A');
M_.param_names_long = char(M_.param_names_long, 'sigma_A');
M_.param_names = char(M_.param_names, 'sigma_m');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_m');
M_.param_names_long = char(M_.param_names_long, 'sigma_m');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 29;
M_.param_nbr = 32;
M_.orig_endo_nbr = 29;
M_.aux_vars = [];
M_.predetermined_variables = [ 23 ];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_FV10_rep_static');
erase_compiled_function('US_FV10_rep_dynamic');
M_.lead_lag_incidence = [
 1 12 41;
 2 13 42;
 0 14 43;
 0 15 44;
 0 16 0;
 0 17 45;
 3 18 0;
 4 19 46;
 0 20 47;
 5 21 48;
 0 22 49;
 0 23 50;
 0 24 51;
 0 25 0;
 6 26 0;
 0 27 52;
 0 28 0;
 0 29 53;
 0 30 54;
 0 31 55;
 7 32 0;
 0 33 0;
 8 34 0;
 9 35 0;
 10 36 0;
 0 37 0;
 11 38 0;
 0 39 0;
 0 40 0;]';
M_.nstatic = 7;
M_.nfwrd   = 11;
M_.npred   = 7;
M_.nboth   = 4;
M_.nsfwrd   = 15;
M_.nspred   = 11;
M_.ndynamic   = 22;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(29, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(32, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 156;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 5 ) = 0.025;
delta = M_.params( 5 );
M_.params( 8 ) = 10;
epsilon = M_.params( 8 );
M_.params( 7 ) = 10;
eta = M_.params( 7 );
M_.params( 21 ) = 0;
Phi = M_.params( 21 );
M_.params( 4 ) = 0.001;
gammma2 = M_.params( 4 );
M_.params( 2 ) = 0.998;
betta = M_.params( 2 );
M_.params( 1 ) = 0.97;
h = M_.params( 1 );
M_.params( 9 ) = 8.92;
varpsi = M_.params( 9 );
M_.params( 10 ) = 1.17;
gammma = M_.params( 10 );
M_.params( 6 ) = 9.51;
kappa = M_.params( 6 );
M_.params( 15 ) = 0.21;
alppha = M_.params( 15 );
M_.params( 13 ) = 0.82;
thetap = M_.params( 13 );
M_.params( 12 ) = 0.63;
chi = M_.params( 12 );
M_.params( 14 ) = 0.68;
thetaw = M_.params( 14 );
M_.params( 11 ) = 0.62;
chiw = M_.params( 11 );
M_.params( 18 ) = 0.77;
gammmaR = M_.params( 18 );
M_.params( 20 ) = 0.19;
gammmay = M_.params( 20 );
M_.params( 19 ) = 1.29;
gammmaPI = M_.params( 19 );
M_.params( 17 ) = 1.01;
PIbar = M_.params( 17 );
M_.params( 22 ) = 0.12;
rhod = M_.params( 22 );
M_.params( 23 ) = 0.93;
rhophi = M_.params( 23 );
M_.params( 31 ) = 0.01887343313515149;
sigma_A = M_.params( 31 );
M_.params( 28 ) = 0.2209099779593782;
sigma_d = M_.params( 28 );
M_.params( 29 ) = 0.09442022319630235;
sigma_phi = M_.params( 29 );
M_.params( 30 ) = 0.004383095802668776;
sigma_mu = M_.params( 30 );
M_.params( 32 ) = 0.002879899158088243;
sigma_m = M_.params( 32 );
M_.params( 24 ) = 3.4e-3;
Lambdamu = M_.params( 24 );
M_.params( 25 ) = 2.8e-3;
LambdaA = M_.params( 25 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
M_.Sigma_e(5, 5) = (1)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 21;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
var_list_ = 'yd';
var_list_ = char(var_list_, 'yg');
var_list_ = char(var_list_, 'c');
var_list_ = char(var_list_, 'R');
var_list_ = char(var_list_, 'PI');
info = stoch_simul(var_list_);
save('US_FV10_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_FV10_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_FV10_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_FV10_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_FV10_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
