%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_CET15_rep';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_CET15_rep.log');
M_.exo_names = 'epsR_eps';
M_.exo_names_tex = 'epsR\_eps';
M_.exo_names_long = 'epsR_eps';
M_.exo_names = char(M_.exo_names, 'muz_eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'muz\_eps');
M_.exo_names_long = char(M_.exo_names_long, 'muz_eps');
M_.exo_names = char(M_.exo_names, 'mupsi_eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'mupsi\_eps');
M_.exo_names_long = char(M_.exo_names_long, 'mupsi_eps');
M_.endo_names = 'lambda_CR';
M_.endo_names_tex = 'lambda\_CR';
M_.endo_names_long = 'lambda_CR';
M_.endo_names = char(M_.endo_names, 'cR');
M_.endo_names_tex = char(M_.endo_names_tex, 'cR');
M_.endo_names_long = char(M_.endo_names_long, 'cR');
M_.endo_names = char(M_.endo_names, 'RR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RR');
M_.endo_names_long = char(M_.endo_names_long, 'RR');
M_.endo_names = char(M_.endo_names, 'piR');
M_.endo_names_tex = char(M_.endo_names_tex, 'piR');
M_.endo_names_long = char(M_.endo_names_long, 'piR');
M_.endo_names = char(M_.endo_names, 'iR');
M_.endo_names_tex = char(M_.endo_names_tex, 'iR');
M_.endo_names_long = char(M_.endo_names_long, 'iR');
M_.endo_names = char(M_.endo_names, 'pkR');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkR');
M_.endo_names_long = char(M_.endo_names_long, 'pkR');
M_.endo_names = char(M_.endo_names, 'FR');
M_.endo_names_tex = char(M_.endo_names_tex, 'FR');
M_.endo_names_long = char(M_.endo_names_long, 'FR');
M_.endo_names = char(M_.endo_names, 'KR');
M_.endo_names_tex = char(M_.endo_names_tex, 'KR');
M_.endo_names_long = char(M_.endo_names_long, 'KR');
M_.endo_names = char(M_.endo_names, 'ukR');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukR');
M_.endo_names_long = char(M_.endo_names_long, 'ukR');
M_.endo_names = char(M_.endo_names, 'wR');
M_.endo_names_tex = char(M_.endo_names_tex, 'wR');
M_.endo_names_long = char(M_.endo_names_long, 'wR');
M_.endo_names = char(M_.endo_names, 'kststR');
M_.endo_names_tex = char(M_.endo_names_tex, 'kststR');
M_.endo_names_long = char(M_.endo_names_long, 'kststR');
M_.endo_names = char(M_.endo_names, 'lR');
M_.endo_names_tex = char(M_.endo_names_tex, 'lR');
M_.endo_names_long = char(M_.endo_names_long, 'lR');
M_.endo_names = char(M_.endo_names, 'xR');
M_.endo_names_tex = char(M_.endo_names_tex, 'xR');
M_.endo_names_long = char(M_.endo_names_long, 'xR');
M_.endo_names = char(M_.endo_names, 'varthetR');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetR');
M_.endo_names_long = char(M_.endo_names_long, 'varthetR');
M_.endo_names = char(M_.endo_names, 'DispR');
M_.endo_names_tex = char(M_.endo_names_tex, 'DispR');
M_.endo_names_long = char(M_.endo_names_long, 'DispR');
M_.endo_names = char(M_.endo_names, 'yR');
M_.endo_names_tex = char(M_.endo_names_tex, 'yR');
M_.endo_names_long = char(M_.endo_names_long, 'yR');
M_.endo_names = char(M_.endo_names, 'JR');
M_.endo_names_tex = char(M_.endo_names_tex, 'JR');
M_.endo_names_long = char(M_.endo_names_long, 'JR');
M_.endo_names = char(M_.endo_names, 'UR');
M_.endo_names_tex = char(M_.endo_names_tex, 'UR');
M_.endo_names_long = char(M_.endo_names_long, 'UR');
M_.endo_names = char(M_.endo_names, 'GDPR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPR');
M_.endo_names_long = char(M_.endo_names_long, 'GDPR');
M_.endo_names = char(M_.endo_names, 'fR');
M_.endo_names_tex = char(M_.endo_names_tex, 'fR');
M_.endo_names_long = char(M_.endo_names_long, 'fR');
M_.endo_names = char(M_.endo_names, 'vR');
M_.endo_names_tex = char(M_.endo_names_tex, 'vR');
M_.endo_names_long = char(M_.endo_names_long, 'vR');
M_.endo_names = char(M_.endo_names, 'unempR');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempR');
M_.endo_names_long = char(M_.endo_names_long, 'unempR');
M_.endo_names = char(M_.endo_names, 'VR');
M_.endo_names_tex = char(M_.endo_names_tex, 'VR');
M_.endo_names_long = char(M_.endo_names_long, 'VR');
M_.endo_names = char(M_.endo_names, 'A_R');
M_.endo_names_tex = char(M_.endo_names_tex, 'A\_R');
M_.endo_names_long = char(M_.endo_names_long, 'A_R');
M_.endo_names = char(M_.endo_names, 'vTotR');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotR');
M_.endo_names_long = char(M_.endo_names_long, 'vTotR');
M_.endo_names = char(M_.endo_names, 'QR');
M_.endo_names_tex = char(M_.endo_names_tex, 'QR');
M_.endo_names_long = char(M_.endo_names_long, 'QR');
M_.endo_names = char(M_.endo_names, 'wpR');
M_.endo_names_tex = char(M_.endo_names_tex, 'wpR');
M_.endo_names_long = char(M_.endo_names_long, 'wpR');
M_.endo_names = char(M_.endo_names, 'varthetpR');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetpR');
M_.endo_names_long = char(M_.endo_names_long, 'varthetpR');
M_.endo_names = char(M_.endo_names, 'eR');
M_.endo_names_tex = char(M_.endo_names_tex, 'eR');
M_.endo_names_long = char(M_.endo_names_long, 'eR');
M_.endo_names = char(M_.endo_names, 'NR');
M_.endo_names_tex = char(M_.endo_names_tex, 'NR');
M_.endo_names_long = char(M_.endo_names_long, 'NR');
M_.endo_names = char(M_.endo_names, 'LR');
M_.endo_names_tex = char(M_.endo_names_tex, 'LR');
M_.endo_names_long = char(M_.endo_names_long, 'LR');
M_.endo_names = char(M_.endo_names, 'cHR');
M_.endo_names_tex = char(M_.endo_names_tex, 'cHR');
M_.endo_names_long = char(M_.endo_names_long, 'cHR');
M_.endo_names = char(M_.endo_names, 'UcHR');
M_.endo_names_tex = char(M_.endo_names_tex, 'UcHR');
M_.endo_names_long = char(M_.endo_names_long, 'UcHR');
M_.endo_names = char(M_.endo_names, 'plR');
M_.endo_names_tex = char(M_.endo_names_tex, 'plR');
M_.endo_names_long = char(M_.endo_names_long, 'plR');
M_.endo_names = char(M_.endo_names, 'LcalR');
M_.endo_names_tex = char(M_.endo_names_tex, 'LcalR');
M_.endo_names_long = char(M_.endo_names_long, 'LcalR');
M_.endo_names = char(M_.endo_names, 'nGR');
M_.endo_names_tex = char(M_.endo_names_tex, 'nGR');
M_.endo_names_long = char(M_.endo_names_long, 'nGR');
M_.endo_names = char(M_.endo_names, 'lambda_CF');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_CF');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_CF');
M_.endo_names = char(M_.endo_names, 'cF');
M_.endo_names_tex = char(M_.endo_names_tex, 'cF');
M_.endo_names_long = char(M_.endo_names_long, 'cF');
M_.endo_names = char(M_.endo_names, 'RF');
M_.endo_names_tex = char(M_.endo_names_tex, 'RF');
M_.endo_names_long = char(M_.endo_names_long, 'RF');
M_.endo_names = char(M_.endo_names, 'piF');
M_.endo_names_tex = char(M_.endo_names_tex, 'piF');
M_.endo_names_long = char(M_.endo_names_long, 'piF');
M_.endo_names = char(M_.endo_names, 'iF');
M_.endo_names_tex = char(M_.endo_names_tex, 'iF');
M_.endo_names_long = char(M_.endo_names_long, 'iF');
M_.endo_names = char(M_.endo_names, 'pkF');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkF');
M_.endo_names_long = char(M_.endo_names_long, 'pkF');
M_.endo_names = char(M_.endo_names, 'FF');
M_.endo_names_tex = char(M_.endo_names_tex, 'FF');
M_.endo_names_long = char(M_.endo_names_long, 'FF');
M_.endo_names = char(M_.endo_names, 'KF');
M_.endo_names_tex = char(M_.endo_names_tex, 'KF');
M_.endo_names_long = char(M_.endo_names_long, 'KF');
M_.endo_names = char(M_.endo_names, 'ukF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukF');
M_.endo_names_long = char(M_.endo_names_long, 'ukF');
M_.endo_names = char(M_.endo_names, 'wF');
M_.endo_names_tex = char(M_.endo_names_tex, 'wF');
M_.endo_names_long = char(M_.endo_names_long, 'wF');
M_.endo_names = char(M_.endo_names, 'kststF');
M_.endo_names_tex = char(M_.endo_names_tex, 'kststF');
M_.endo_names_long = char(M_.endo_names_long, 'kststF');
M_.endo_names = char(M_.endo_names, 'lF');
M_.endo_names_tex = char(M_.endo_names_tex, 'lF');
M_.endo_names_long = char(M_.endo_names_long, 'lF');
M_.endo_names = char(M_.endo_names, 'xF');
M_.endo_names_tex = char(M_.endo_names_tex, 'xF');
M_.endo_names_long = char(M_.endo_names_long, 'xF');
M_.endo_names = char(M_.endo_names, 'varthetF');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetF');
M_.endo_names_long = char(M_.endo_names_long, 'varthetF');
M_.endo_names = char(M_.endo_names, 'DispF');
M_.endo_names_tex = char(M_.endo_names_tex, 'DispF');
M_.endo_names_long = char(M_.endo_names_long, 'DispF');
M_.endo_names = char(M_.endo_names, 'yF');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF');
M_.endo_names_long = char(M_.endo_names_long, 'yF');
M_.endo_names = char(M_.endo_names, 'JF');
M_.endo_names_tex = char(M_.endo_names_tex, 'JF');
M_.endo_names_long = char(M_.endo_names_long, 'JF');
M_.endo_names = char(M_.endo_names, 'UF');
M_.endo_names_tex = char(M_.endo_names_tex, 'UF');
M_.endo_names_long = char(M_.endo_names_long, 'UF');
M_.endo_names = char(M_.endo_names, 'GDPF');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPF');
M_.endo_names_long = char(M_.endo_names_long, 'GDPF');
M_.endo_names = char(M_.endo_names, 'fF');
M_.endo_names_tex = char(M_.endo_names_tex, 'fF');
M_.endo_names_long = char(M_.endo_names_long, 'fF');
M_.endo_names = char(M_.endo_names, 'vF');
M_.endo_names_tex = char(M_.endo_names_tex, 'vF');
M_.endo_names_long = char(M_.endo_names_long, 'vF');
M_.endo_names = char(M_.endo_names, 'unempF');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempF');
M_.endo_names_long = char(M_.endo_names_long, 'unempF');
M_.endo_names = char(M_.endo_names, 'VF');
M_.endo_names_tex = char(M_.endo_names_tex, 'VF');
M_.endo_names_long = char(M_.endo_names_long, 'VF');
M_.endo_names = char(M_.endo_names, 'AF');
M_.endo_names_tex = char(M_.endo_names_tex, 'AF');
M_.endo_names_long = char(M_.endo_names_long, 'AF');
M_.endo_names = char(M_.endo_names, 'vTotF');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotF');
M_.endo_names_long = char(M_.endo_names_long, 'vTotF');
M_.endo_names = char(M_.endo_names, 'QF');
M_.endo_names_tex = char(M_.endo_names_tex, 'QF');
M_.endo_names_long = char(M_.endo_names_long, 'QF');
M_.endo_names = char(M_.endo_names, 'wpF');
M_.endo_names_tex = char(M_.endo_names_tex, 'wpF');
M_.endo_names_long = char(M_.endo_names_long, 'wpF');
M_.endo_names = char(M_.endo_names, 'varthetpF');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetpF');
M_.endo_names_long = char(M_.endo_names_long, 'varthetpF');
M_.endo_names = char(M_.endo_names, 'eF');
M_.endo_names_tex = char(M_.endo_names_tex, 'eF');
M_.endo_names_long = char(M_.endo_names_long, 'eF');
M_.endo_names = char(M_.endo_names, 'NF');
M_.endo_names_tex = char(M_.endo_names_tex, 'NF');
M_.endo_names_long = char(M_.endo_names_long, 'NF');
M_.endo_names = char(M_.endo_names, 'LF');
M_.endo_names_tex = char(M_.endo_names_tex, 'LF');
M_.endo_names_long = char(M_.endo_names_long, 'LF');
M_.endo_names = char(M_.endo_names, 'cHF');
M_.endo_names_tex = char(M_.endo_names_tex, 'cHF');
M_.endo_names_long = char(M_.endo_names_long, 'cHF');
M_.endo_names = char(M_.endo_names, 'UcHF');
M_.endo_names_tex = char(M_.endo_names_tex, 'UcHF');
M_.endo_names_long = char(M_.endo_names_long, 'UcHF');
M_.endo_names = char(M_.endo_names, 'plF');
M_.endo_names_tex = char(M_.endo_names_tex, 'plF');
M_.endo_names_long = char(M_.endo_names_long, 'plF');
M_.endo_names = char(M_.endo_names, 'LcalF');
M_.endo_names_tex = char(M_.endo_names_tex, 'LcalF');
M_.endo_names_long = char(M_.endo_names_long, 'LcalF');
M_.endo_names = char(M_.endo_names, 'muzF');
M_.endo_names_tex = char(M_.endo_names_tex, 'muzF');
M_.endo_names_long = char(M_.endo_names_long, 'muzF');
M_.endo_names = char(M_.endo_names, 'mupsiF');
M_.endo_names_tex = char(M_.endo_names_tex, 'mupsiF');
M_.endo_names_long = char(M_.endo_names_long, 'mupsiF');
M_.endo_names = char(M_.endo_names, 'muF');
M_.endo_names_tex = char(M_.endo_names_tex, 'muF');
M_.endo_names_long = char(M_.endo_names_long, 'muF');
M_.endo_names = char(M_.endo_names, 'nGF');
M_.endo_names_tex = char(M_.endo_names_tex, 'nGF');
M_.endo_names_long = char(M_.endo_names_long, 'nGF');
M_.endo_names = char(M_.endo_names, 'pi4F');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi4F');
M_.endo_names_long = char(M_.endo_names_long, 'pi4F');
M_.endo_names = char(M_.endo_names, 'GDPAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDPAGG');
M_.endo_names_long = char(M_.endo_names_long, 'GDPAGG');
M_.endo_names = char(M_.endo_names, 'piAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'piAGG');
M_.endo_names_long = char(M_.endo_names_long, 'piAGG');
M_.endo_names = char(M_.endo_names, 'RAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'RAGG');
M_.endo_names_long = char(M_.endo_names_long, 'RAGG');
M_.endo_names = char(M_.endo_names, 'ukAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'ukAGG');
M_.endo_names_long = char(M_.endo_names_long, 'ukAGG');
M_.endo_names = char(M_.endo_names, 'lAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'lAGG');
M_.endo_names_long = char(M_.endo_names_long, 'lAGG');
M_.endo_names = char(M_.endo_names, 'wAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'wAGG');
M_.endo_names_long = char(M_.endo_names_long, 'wAGG');
M_.endo_names = char(M_.endo_names, 'cAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'cAGG');
M_.endo_names_long = char(M_.endo_names_long, 'cAGG');
M_.endo_names = char(M_.endo_names, 'iAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'iAGG');
M_.endo_names_long = char(M_.endo_names_long, 'iAGG');
M_.endo_names = char(M_.endo_names, 'unempAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'unempAGG');
M_.endo_names_long = char(M_.endo_names_long, 'unempAGG');
M_.endo_names = char(M_.endo_names, 'vTotAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'vTotAGG');
M_.endo_names_long = char(M_.endo_names_long, 'vTotAGG');
M_.endo_names = char(M_.endo_names, 'fAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'fAGG');
M_.endo_names_long = char(M_.endo_names_long, 'fAGG');
M_.endo_names = char(M_.endo_names, 'pinvestAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinvestAGG');
M_.endo_names_long = char(M_.endo_names_long, 'pinvestAGG');
M_.endo_names = char(M_.endo_names, 'LAGG');
M_.endo_names_tex = char(M_.endo_names_tex, 'LAGG');
M_.endo_names_long = char(M_.endo_names_long, 'LAGG');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_23');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_23');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_23');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_25');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_25');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_25');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_27');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_27');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_27');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_29');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_29');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_29');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_31');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_31');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_31');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_33');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_33');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_33');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_35');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_35');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_35');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_37');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_37');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_37');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_39');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_39');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_39');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_41');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_41');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_41');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_43');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_43');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_43');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_45');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_45');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_45');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_47');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_47');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_47');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_49');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_49');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_49');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_51');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_51');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_51');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_53');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_53');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_53');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_55');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_55');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_55');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_57');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_57');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_57');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_59');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_59');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_59');
M_.endo_names = char(M_.endo_names, 'AUX_EXPECT_LAG_1_61');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXPECT\_LAG\_1\_61');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXPECT_LAG_1_61');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1352');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1352');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1352');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1356');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1356');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1356');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1360');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1360');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1360');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1364');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1364');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1364');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1368');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1368');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1368');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1372');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1372');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1372');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1376');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1376');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1376');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1380');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1380');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1380');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1384');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1384');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1384');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1388');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1388');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1388');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1392');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1392');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1392');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1396');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1396');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1396');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1400');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1400');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1400');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1408');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1408');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1408');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1412');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1412');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1412');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1416');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1416');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1416');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1420');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1420');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1420');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1424');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1424');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1424');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1428');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1428');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1428');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_73_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_73\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_73_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_73_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_73\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_73_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_39_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_39\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_39_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_39_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_39\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_39_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_1');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_90_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_90\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_90_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_90_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_90\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_90_1');
M_.endo_partitions = struct();
M_.param_names = 'u';
M_.param_names_tex = 'u';
M_.param_names_long = 'u';
M_.param_names = char(M_.param_names, 'L');
M_.param_names_tex = char(M_.param_names_tex, 'L');
M_.param_names_long = char(M_.param_names_long, 'L');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'Q');
M_.param_names_tex = char(M_.param_names_tex, 'Q');
M_.param_names_long = char(M_.param_names_long, 'Q');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'recSHAREpercent');
M_.param_names_tex = char(M_.param_names_tex, 'recSHAREpercent');
M_.param_names_long = char(M_.param_names_long, 'recSHAREpercent');
M_.param_names = char(M_.param_names, 'DSHARE');
M_.param_names_tex = char(M_.param_names_tex, 'DSHARE');
M_.param_names_long = char(M_.param_names_long, 'DSHARE');
M_.param_names = char(M_.param_names, 'M');
M_.param_names_tex = char(M_.param_names_tex, 'M');
M_.param_names_long = char(M_.param_names_long, 'M');
M_.param_names = char(M_.param_names, 'phiL');
M_.param_names_tex = char(M_.param_names_tex, 'phiL');
M_.param_names_long = char(M_.param_names_long, 'phiL');
M_.param_names = char(M_.param_names, 'elasttarget');
M_.param_names_tex = char(M_.param_names_tex, 'elasttarget');
M_.param_names_long = char(M_.param_names_long, 'elasttarget');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'pibar');
M_.param_names_tex = char(M_.param_names_tex, 'pibar');
M_.param_names_long = char(M_.param_names_long, 'pibar');
M_.param_names = char(M_.param_names, 'kappaf');
M_.param_names_tex = char(M_.param_names_tex, 'kappaf');
M_.param_names_long = char(M_.param_names_long, 'kappaf');
M_.param_names = char(M_.param_names, 'varkappaf');
M_.param_names_tex = char(M_.param_names_tex, 'varkappaf');
M_.param_names_long = char(M_.param_names_long, 'varkappaf');
M_.param_names = char(M_.param_names, 'pibreve');
M_.param_names_tex = char(M_.param_names_tex, 'pibreve');
M_.param_names_long = char(M_.param_names_long, 'pibreve');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'nuf');
M_.param_names_tex = char(M_.param_names_tex, 'nuf');
M_.param_names_long = char(M_.param_names_long, 'nuf');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'deltak');
M_.param_names_tex = char(M_.param_names_tex, 'deltak');
M_.param_names_long = char(M_.param_names_long, 'deltak');
M_.param_names = char(M_.param_names, 'Spp');
M_.param_names_tex = char(M_.param_names_tex, 'Spp');
M_.param_names_long = char(M_.param_names_long, 'Spp');
M_.param_names = char(M_.param_names, 'sigmaa');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaa');
M_.param_names_long = char(M_.param_names_long, 'sigmaa');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'rhoR');
M_.param_names_tex = char(M_.param_names_tex, 'rhoR');
M_.param_names_long = char(M_.param_names_long, 'rhoR');
M_.param_names = char(M_.param_names, 'rpi');
M_.param_names_tex = char(M_.param_names_tex, 'rpi');
M_.param_names_long = char(M_.param_names_long, 'rpi');
M_.param_names = char(M_.param_names, 'rdeltay');
M_.param_names_tex = char(M_.param_names_tex, 'rdeltay');
M_.param_names_long = char(M_.param_names_long, 'rdeltay');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'thetaG');
M_.param_names_tex = char(M_.param_names_tex, 'thetaG');
M_.param_names_long = char(M_.param_names_long, 'thetaG');
M_.param_names = char(M_.param_names, 'profits');
M_.param_names_tex = char(M_.param_names_tex, 'profits');
M_.param_names_long = char(M_.param_names_long, 'profits');
M_.param_names = char(M_.param_names, 'sig_mupsi');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_mupsi');
M_.param_names_long = char(M_.param_names_long, 'sig_mupsi');
M_.param_names = char(M_.param_names, 'sig_epsR');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_epsR');
M_.param_names_long = char(M_.param_names_long, 'sig_epsR');
M_.param_names = char(M_.param_names, 'sig_muz');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_muz');
M_.param_names_long = char(M_.param_names_long, 'sig_muz');
M_.param_names = char(M_.param_names, 'sigmuzTPratio');
M_.param_names_tex = char(M_.param_names_tex, 'sigmuzTPratio');
M_.param_names_long = char(M_.param_names_long, 'sigmuzTPratio');
M_.param_names = char(M_.param_names, 'sigmuzT');
M_.param_names_tex = char(M_.param_names_tex, 'sigmuzT');
M_.param_names_long = char(M_.param_names_long, 'sigmuzT');
M_.param_names = char(M_.param_names, 'rhomupsi');
M_.param_names_tex = char(M_.param_names_tex, 'rhomupsi');
M_.param_names_long = char(M_.param_names_long, 'rhomupsi');
M_.param_names = char(M_.param_names, 'rhomuz');
M_.param_names_tex = char(M_.param_names_tex, 'rhomuz');
M_.param_names_long = char(M_.param_names_long, 'rhomuz');
M_.param_names = char(M_.param_names, 'rhomuzT');
M_.param_names_tex = char(M_.param_names_tex, 'rhomuzT');
M_.param_names_long = char(M_.param_names_long, 'rhomuzT');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'mupsi');
M_.param_names_tex = char(M_.param_names_tex, 'mupsi');
M_.param_names_long = char(M_.param_names_long, 'mupsi');
M_.param_names = char(M_.param_names, 'muz');
M_.param_names_tex = char(M_.param_names_tex, 'muz');
M_.param_names_long = char(M_.param_names_long, 'muz');
M_.param_names = char(M_.param_names, 'nG');
M_.param_names_tex = char(M_.param_names_tex, 'nG');
M_.param_names_long = char(M_.param_names_long, 'nG');
M_.param_names = char(M_.param_names, 'nKAP');
M_.param_names_tex = char(M_.param_names_tex, 'nKAP');
M_.param_names_long = char(M_.param_names_long, 'nKAP');
M_.param_names = char(M_.param_names, 'nD');
M_.param_names_tex = char(M_.param_names_tex, 'nD');
M_.param_names_long = char(M_.param_names_long, 'nD');
M_.param_names = char(M_.param_names, 'nGAM');
M_.param_names_tex = char(M_.param_names_tex, 'nGAM');
M_.param_names_long = char(M_.param_names_long, 'nGAM');
M_.param_names = char(M_.param_names, 'nL');
M_.param_names_tex = char(M_.param_names_tex, 'nL');
M_.param_names_long = char(M_.param_names_long, 'nL');
M_.param_names = char(M_.param_names, 'nH');
M_.param_names_tex = char(M_.param_names_tex, 'nH');
M_.param_names_long = char(M_.param_names_long, 'nH');
M_.param_names = char(M_.param_names, 'uk');
M_.param_names_tex = char(M_.param_names_tex, 'uk');
M_.param_names_long = char(M_.param_names_long, 'uk');
M_.param_names = char(M_.param_names, 'S');
M_.param_names_tex = char(M_.param_names_tex, 'S');
M_.param_names_long = char(M_.param_names_long, 'S');
M_.param_names = char(M_.param_names, 'Sprime');
M_.param_names_tex = char(M_.param_names_tex, 'Sprime');
M_.param_names_long = char(M_.param_names_long, 'Sprime');
M_.param_names = char(M_.param_names, 'Fcal');
M_.param_names_tex = char(M_.param_names_tex, 'Fcal');
M_.param_names_long = char(M_.param_names_long, 'Fcal');
M_.param_names = char(M_.param_names, 'Fcalprime');
M_.param_names_tex = char(M_.param_names_tex, 'Fcalprime');
M_.param_names_long = char(M_.param_names_long, 'Fcalprime');
M_.param_names = char(M_.param_names, 'm');
M_.param_names_tex = char(M_.param_names_tex, 'm');
M_.param_names_long = char(M_.param_names_long, 'm');
M_.param_names = char(M_.param_names, 'l');
M_.param_names_tex = char(M_.param_names_tex, 'l');
M_.param_names_long = char(M_.param_names_long, 'l');
M_.param_names = char(M_.param_names, 'R');
M_.param_names_tex = char(M_.param_names_tex, 'R');
M_.param_names_long = char(M_.param_names_long, 'R');
M_.param_names = char(M_.param_names, 'pk');
M_.param_names_tex = char(M_.param_names_tex, 'pk');
M_.param_names_long = char(M_.param_names_long, 'pk');
M_.param_names = char(M_.param_names, 'Rk');
M_.param_names_tex = char(M_.param_names_tex, 'Rk');
M_.param_names_long = char(M_.param_names_long, 'Rk');
M_.param_names = char(M_.param_names, 'sigmab');
M_.param_names_tex = char(M_.param_names_tex, 'sigmab');
M_.param_names_long = char(M_.param_names_long, 'sigmab');
M_.param_names = char(M_.param_names, 'pitilde');
M_.param_names_tex = char(M_.param_names_tex, 'pitilde');
M_.param_names_long = char(M_.param_names_long, 'pitilde');
M_.param_names = char(M_.param_names, 'mc');
M_.param_names_tex = char(M_.param_names_tex, 'mc');
M_.param_names_long = char(M_.param_names_long, 'mc');
M_.param_names = char(M_.param_names, 'Disp');
M_.param_names_tex = char(M_.param_names_tex, 'Disp');
M_.param_names_long = char(M_.param_names_long, 'Disp');
M_.param_names = char(M_.param_names, 'kl');
M_.param_names_tex = char(M_.param_names_tex, 'kl');
M_.param_names_long = char(M_.param_names_long, 'kl');
M_.param_names = char(M_.param_names, 'varthet');
M_.param_names_tex = char(M_.param_names_tex, 'varthet');
M_.param_names_long = char(M_.param_names_long, 'varthet');
M_.param_names = char(M_.param_names, 'y');
M_.param_names_tex = char(M_.param_names_tex, 'y');
M_.param_names_long = char(M_.param_names_long, 'y');
M_.param_names = char(M_.param_names, 'k');
M_.param_names_tex = char(M_.param_names_tex, 'k');
M_.param_names_long = char(M_.param_names_long, 'k');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'i');
M_.param_names_tex = char(M_.param_names_tex, 'i');
M_.param_names_long = char(M_.param_names_long, 'i');
M_.param_names = char(M_.param_names, 'c');
M_.param_names_tex = char(M_.param_names_tex, 'c');
M_.param_names_long = char(M_.param_names_long, 'c');
M_.param_names = char(M_.param_names, 'g');
M_.param_names_tex = char(M_.param_names_tex, 'g');
M_.param_names_long = char(M_.param_names_long, 'g');
M_.param_names = char(M_.param_names, 'GDP');
M_.param_names_tex = char(M_.param_names_tex, 'GDP');
M_.param_names_long = char(M_.param_names_long, 'GDP');
M_.param_names = char(M_.param_names, 'x');
M_.param_names_tex = char(M_.param_names_tex, 'x');
M_.param_names_long = char(M_.param_names_long, 'x');
M_.param_names = char(M_.param_names, 'f');
M_.param_names_tex = char(M_.param_names_tex, 'f');
M_.param_names_long = char(M_.param_names_long, 'f');
M_.param_names = char(M_.param_names, 'v');
M_.param_names_tex = char(M_.param_names_tex, 'v');
M_.param_names_long = char(M_.param_names_long, 'v');
M_.param_names = char(M_.param_names, 'sigmam');
M_.param_names_tex = char(M_.param_names_tex, 'sigmam');
M_.param_names_long = char(M_.param_names_long, 'sigmam');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'J');
M_.param_names_tex = char(M_.param_names_tex, 'J');
M_.param_names_long = char(M_.param_names_long, 'J');
M_.param_names = char(M_.param_names, 'varthetp');
M_.param_names_tex = char(M_.param_names_tex, 'varthetp');
M_.param_names_long = char(M_.param_names_long, 'varthetp');
M_.param_names = char(M_.param_names, 'wp');
M_.param_names_tex = char(M_.param_names_tex, 'wp');
M_.param_names_long = char(M_.param_names_long, 'wp');
M_.param_names = char(M_.param_names, 'w');
M_.param_names_tex = char(M_.param_names_tex, 'w');
M_.param_names_long = char(M_.param_names_long, 'w');
M_.param_names = char(M_.param_names, 'D');
M_.param_names_tex = char(M_.param_names_tex, 'D');
M_.param_names_long = char(M_.param_names_long, 'D');
M_.param_names = char(M_.param_names, 'e');
M_.param_names_tex = char(M_.param_names_tex, 'e');
M_.param_names_long = char(M_.param_names_long, 'e');
M_.param_names = char(M_.param_names, 'unemp_stst');
M_.param_names_tex = char(M_.param_names_tex, 'unemp\_stst');
M_.param_names_long = char(M_.param_names_long, 'unemp_stst');
M_.param_names = char(M_.param_names, 'vTot_stst');
M_.param_names_tex = char(M_.param_names_tex, 'vTot\_stst');
M_.param_names_long = char(M_.param_names_long, 'vTot_stst');
M_.param_names = char(M_.param_names, 'cH');
M_.param_names_tex = char(M_.param_names_tex, 'cH');
M_.param_names_long = char(M_.param_names_long, 'cH');
M_.param_names = char(M_.param_names, 'alp1');
M_.param_names_tex = char(M_.param_names_tex, 'alp1');
M_.param_names_long = char(M_.param_names_long, 'alp1');
M_.param_names = char(M_.param_names, 'alp2');
M_.param_names_tex = char(M_.param_names_tex, 'alp2');
M_.param_names_long = char(M_.param_names_long, 'alp2');
M_.param_names = char(M_.param_names, 'alp3');
M_.param_names_tex = char(M_.param_names_tex, 'alp3');
M_.param_names_long = char(M_.param_names_long, 'alp3');
M_.param_names = char(M_.param_names, 'alp4');
M_.param_names_tex = char(M_.param_names_tex, 'alp4');
M_.param_names_long = char(M_.param_names_long, 'alp4');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'lambda_C');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_C');
M_.param_names_long = char(M_.param_names_long, 'lambda_C');
M_.param_names = char(M_.param_names, 'UcH');
M_.param_names_tex = char(M_.param_names_tex, 'UcH');
M_.param_names_long = char(M_.param_names_long, 'UcH');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'F');
M_.param_names_tex = char(M_.param_names_tex, 'F');
M_.param_names_long = char(M_.param_names_long, 'F');
M_.param_names = char(M_.param_names, 'K');
M_.param_names_tex = char(M_.param_names_tex, 'K');
M_.param_names_long = char(M_.param_names_long, 'K');
M_.param_names = char(M_.param_names, 'U');
M_.param_names_tex = char(M_.param_names_tex, 'U');
M_.param_names_long = char(M_.param_names_long, 'U');
M_.param_names = char(M_.param_names, 'N');
M_.param_names_tex = char(M_.param_names_tex, 'N');
M_.param_names_long = char(M_.param_names_long, 'N');
M_.param_names = char(M_.param_names, 'A');
M_.param_names_tex = char(M_.param_names_tex, 'A');
M_.param_names_long = char(M_.param_names_long, 'A');
M_.param_names = char(M_.param_names, 'V');
M_.param_names_tex = char(M_.param_names_tex, 'V');
M_.param_names_long = char(M_.param_names_long, 'V');
M_.param_names = char(M_.param_names, 'pl');
M_.param_names_tex = char(M_.param_names_tex, 'pl');
M_.param_names_long = char(M_.param_names_long, 'pl');
M_.param_names = char(M_.param_names, 'sig_eta');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_eta');
M_.param_names_long = char(M_.param_names_long, 'sig_eta');
M_.param_names = char(M_.param_names, 'theta1');
M_.param_names_tex = char(M_.param_names_tex, 'theta1');
M_.param_names_long = char(M_.param_names_long, 'theta1');
M_.param_names = char(M_.param_names, 'theta2');
M_.param_names_tex = char(M_.param_names_tex, 'theta2');
M_.param_names_long = char(M_.param_names_long, 'theta2');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 143;
M_.param_nbr = 104;
M_.orig_endo_nbr = 89;
M_.aux_vars(1).endo_index = 90;
M_.aux_vars(1).type = 4;
M_.aux_vars(1).orig_expr = '\mathbb{E}_{t-1}({piR_{t+1}})';
M_.aux_vars(2).endo_index = 91;
M_.aux_vars(2).type = 4;
M_.aux_vars(2).orig_expr = '\mathbb{E}_{t-1}({FR_{t+1}})';
M_.aux_vars(3).endo_index = 92;
M_.aux_vars(3).type = 4;
M_.aux_vars(3).orig_expr = '\mathbb{E}_{t-1}({KR_{t+1}})';
M_.aux_vars(4).endo_index = 93;
M_.aux_vars(4).type = 4;
M_.aux_vars(4).orig_expr = '\mathbb{E}_{t-1}({lambda\_CR_{t+1}})';
M_.aux_vars(5).endo_index = 94;
M_.aux_vars(5).type = 4;
M_.aux_vars(5).orig_expr = '\mathbb{E}_{t-1}({pkR_{t+1}})';
M_.aux_vars(6).endo_index = 95;
M_.aux_vars(6).type = 4;
M_.aux_vars(6).orig_expr = '\mathbb{E}_{t-1}({iR_{t+1}})';
M_.aux_vars(7).endo_index = 96;
M_.aux_vars(7).type = 4;
M_.aux_vars(7).orig_expr = '\mathbb{E}_{t-1}({UR_{t+1}})';
M_.aux_vars(8).endo_index = 97;
M_.aux_vars(8).type = 4;
M_.aux_vars(8).orig_expr = '\mathbb{E}_{t-1}({fR_{t+1}})';
M_.aux_vars(9).endo_index = 98;
M_.aux_vars(9).type = 4;
M_.aux_vars(9).orig_expr = '\mathbb{E}_{t-1}({VR_{t+1}})';
M_.aux_vars(10).endo_index = 99;
M_.aux_vars(10).type = 4;
M_.aux_vars(10).orig_expr = '\mathbb{E}_{t-1}({ukR_{t+1}})';
M_.aux_vars(11).endo_index = 100;
M_.aux_vars(11).type = 4;
M_.aux_vars(11).orig_expr = '\mathbb{E}_{t-1}({wpR_{t+1}})';
M_.aux_vars(12).endo_index = 101;
M_.aux_vars(12).type = 4;
M_.aux_vars(12).orig_expr = '\mathbb{E}_{t-1}({varthetpR_{t+1}})';
M_.aux_vars(13).endo_index = 102;
M_.aux_vars(13).type = 4;
M_.aux_vars(13).orig_expr = '\mathbb{E}_{t-1}({A\_R_{t+1}})';
M_.aux_vars(14).endo_index = 103;
M_.aux_vars(14).type = 4;
M_.aux_vars(14).orig_expr = '\mathbb{E}_{t-1}({RR_{t}})';
M_.aux_vars(15).endo_index = 104;
M_.aux_vars(15).type = 4;
M_.aux_vars(15).orig_expr = '\mathbb{E}_{t-1}({LR_{t+1}})';
M_.aux_vars(16).endo_index = 105;
M_.aux_vars(16).type = 4;
M_.aux_vars(16).orig_expr = '\mathbb{E}_{t-1}({NR_{t+1}})';
M_.aux_vars(17).endo_index = 106;
M_.aux_vars(17).type = 4;
M_.aux_vars(17).orig_expr = '\mathbb{E}_{t-1}({eR_{t+1}})';
M_.aux_vars(18).endo_index = 107;
M_.aux_vars(18).type = 4;
M_.aux_vars(18).orig_expr = '\mathbb{E}_{t-1}({plR_{t+1}})';
M_.aux_vars(19).endo_index = 108;
M_.aux_vars(19).type = 4;
M_.aux_vars(19).orig_expr = '\mathbb{E}_{t-1}({UcHR_{t+1}})';
M_.aux_vars(20).endo_index = 109;
M_.aux_vars(20).type = 4;
M_.aux_vars(20).orig_expr = '\mathbb{E}_{t-1}({LcalR_{t+1}})';
M_.aux_vars(21).endo_index = 110;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 111;
M_.aux_vars(22).type = 0;
M_.aux_vars(23).endo_index = 112;
M_.aux_vars(23).type = 0;
M_.aux_vars(24).endo_index = 113;
M_.aux_vars(24).type = 0;
M_.aux_vars(25).endo_index = 114;
M_.aux_vars(25).type = 0;
M_.aux_vars(26).endo_index = 115;
M_.aux_vars(26).type = 0;
M_.aux_vars(27).endo_index = 116;
M_.aux_vars(27).type = 0;
M_.aux_vars(28).endo_index = 117;
M_.aux_vars(28).type = 0;
M_.aux_vars(29).endo_index = 118;
M_.aux_vars(29).type = 0;
M_.aux_vars(30).endo_index = 119;
M_.aux_vars(30).type = 0;
M_.aux_vars(31).endo_index = 120;
M_.aux_vars(31).type = 0;
M_.aux_vars(32).endo_index = 121;
M_.aux_vars(32).type = 0;
M_.aux_vars(33).endo_index = 122;
M_.aux_vars(33).type = 0;
M_.aux_vars(34).endo_index = 123;
M_.aux_vars(34).type = 0;
M_.aux_vars(35).endo_index = 124;
M_.aux_vars(35).type = 0;
M_.aux_vars(36).endo_index = 125;
M_.aux_vars(36).type = 0;
M_.aux_vars(37).endo_index = 126;
M_.aux_vars(37).type = 0;
M_.aux_vars(38).endo_index = 127;
M_.aux_vars(38).type = 0;
M_.aux_vars(39).endo_index = 128;
M_.aux_vars(39).type = 0;
M_.aux_vars(40).endo_index = 129;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 4;
M_.aux_vars(40).orig_lead_lag = -1;
M_.aux_vars(41).endo_index = 130;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 4;
M_.aux_vars(41).orig_lead_lag = -2;
M_.aux_vars(42).endo_index = 131;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 19;
M_.aux_vars(42).orig_lead_lag = -1;
M_.aux_vars(43).endo_index = 132;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 19;
M_.aux_vars(43).orig_lead_lag = -2;
M_.aux_vars(44).endo_index = 133;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 19;
M_.aux_vars(44).orig_lead_lag = -3;
M_.aux_vars(45).endo_index = 134;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 55;
M_.aux_vars(45).orig_lead_lag = -1;
M_.aux_vars(46).endo_index = 135;
M_.aux_vars(46).type = 1;
M_.aux_vars(46).orig_index = 55;
M_.aux_vars(46).orig_lead_lag = -2;
M_.aux_vars(47).endo_index = 136;
M_.aux_vars(47).type = 1;
M_.aux_vars(47).orig_index = 55;
M_.aux_vars(47).orig_lead_lag = -3;
M_.aux_vars(48).endo_index = 137;
M_.aux_vars(48).type = 1;
M_.aux_vars(48).orig_index = 74;
M_.aux_vars(48).orig_lead_lag = -1;
M_.aux_vars(49).endo_index = 138;
M_.aux_vars(49).type = 1;
M_.aux_vars(49).orig_index = 74;
M_.aux_vars(49).orig_lead_lag = -2;
M_.aux_vars(50).endo_index = 139;
M_.aux_vars(50).type = 1;
M_.aux_vars(50).orig_index = 40;
M_.aux_vars(50).orig_lead_lag = -1;
M_.aux_vars(51).endo_index = 140;
M_.aux_vars(51).type = 1;
M_.aux_vars(51).orig_index = 40;
M_.aux_vars(51).orig_lead_lag = -2;
M_.aux_vars(52).endo_index = 141;
M_.aux_vars(52).type = 1;
M_.aux_vars(52).orig_index = 72;
M_.aux_vars(52).orig_lead_lag = -1;
M_.aux_vars(53).endo_index = 142;
M_.aux_vars(53).type = 3;
M_.aux_vars(53).orig_index = 2;
M_.aux_vars(53).orig_lead_lag = 0;
M_.aux_vars(54).endo_index = 143;
M_.aux_vars(54).type = 3;
M_.aux_vars(54).orig_index = 2;
M_.aux_vars(54).orig_lead_lag = -1;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_CET15_rep_static');
erase_compiled_function('US_CET15_rep_dynamic');
M_.orig_eq_nbr = 109;
M_.eq_nbr = 143;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 60 203;
 1 61 0;
 2 62 204;
 3 63 205;
 4 64 206;
 0 65 207;
 0 66 208;
 0 67 209;
 0 68 210;
 0 69 0;
 5 70 0;
 6 71 0;
 0 72 0;
 0 73 0;
 7 74 0;
 0 75 0;
 0 76 0;
 0 77 211;
 8 78 0;
 0 79 212;
 0 80 0;
 0 81 0;
 0 82 213;
 0 83 214;
 0 84 0;
 0 85 0;
 0 86 215;
 0 87 216;
 0 88 217;
 0 89 218;
 9 90 219;
 10 91 0;
 0 92 220;
 0 93 221;
 0 94 222;
 0 95 0;
 0 96 223;
 11 97 0;
 12 98 0;
 13 99 224;
 14 100 225;
 0 101 226;
 0 102 227;
 0 103 228;
 0 104 229;
 0 105 0;
 15 106 0;
 16 107 0;
 0 108 0;
 0 109 0;
 17 110 0;
 0 111 0;
 0 112 0;
 0 113 230;
 18 114 0;
 0 115 231;
 0 116 0;
 0 117 0;
 0 118 232;
 0 119 233;
 0 120 0;
 0 121 0;
 0 122 234;
 0 123 235;
 0 124 236;
 0 125 237;
 19 126 238;
 20 127 0;
 0 128 239;
 0 129 240;
 0 130 241;
 21 131 242;
 22 132 243;
 23 133 0;
 24 134 244;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 25 149 0;
 26 150 0;
 27 151 0;
 28 152 0;
 29 153 0;
 30 154 0;
 31 155 0;
 32 156 0;
 33 157 0;
 34 158 0;
 35 159 0;
 36 160 0;
 37 161 0;
 38 162 0;
 39 163 0;
 40 164 0;
 41 165 0;
 42 166 0;
 43 167 0;
 44 168 0;
 0 169 245;
 0 170 246;
 0 171 247;
 0 172 248;
 0 173 249;
 0 174 250;
 0 175 251;
 0 176 252;
 0 177 253;
 0 178 254;
 0 179 255;
 0 180 256;
 0 181 257;
 0 182 258;
 0 183 259;
 0 184 260;
 0 185 261;
 0 186 262;
 0 187 263;
 45 188 0;
 46 189 0;
 47 190 0;
 48 191 0;
 49 192 0;
 50 193 0;
 51 194 0;
 52 195 0;
 53 196 0;
 54 197 0;
 55 198 0;
 56 199 0;
 57 200 0;
 58 201 0;
 59 202 0;]';
M_.nstatic = 33;
M_.nfwrd   = 51;
M_.npred   = 49;
M_.nboth   = 10;
M_.nsfwrd   = 61;
M_.nspred   = 59;
M_.ndynamic   = 110;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(143, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(104, 1);
M_.NNZDerivatives = [597; -1; -1];
M_.params( 20 ) = 0.025;
deltak = M_.params( 20 );
M_.params( 23 ) = 0.996773254690569;
betta = M_.params( 23 );
M_.params( 4 ) = 0.9;
rho = M_.params( 4 );
M_.params( 9 ) = 60;
M = M_.params( 9 );
M_.params( 11 ) = 3;
elasttarget = M_.params( 11 );
M_.params( 13 ) = 1.005;
pibar = M_.params( 13 );
M_.params( 41 ) = 1.004259044057876;
mu = M_.params( 41 );
M_.params( 42 ) = 1.007276344878305/M_.params(41);
mupsi = M_.params( 42 );
M_.params( 30 ) = 0;
profits = M_.params( 30 );
M_.params( 5 ) = 0.7;
Q = M_.params( 5 );
M_.params( 1 ) = 0.055;
u = M_.params( 1 );
M_.params( 2 ) = 0.67;
L = M_.params( 2 );
M_.params( 28 ) = 0.2;
G_over_Y = M_.params( 28 );
M_.params( 12 ) = 0.7545;
xi = M_.params( 12 );
M_.params( 17 ) = 1.3639;
lambda = M_.params( 17 );
M_.params( 18 ) = 0.5619;
nuf = M_.params( 18 );
M_.params( 25 ) = 0.7503;
rhoR = M_.params( 25 );
M_.params( 26 ) = 1.6663;
rpi = M_.params( 26 );
M_.params( 27 ) = 0.2471;
rdeltay = M_.params( 27 );
M_.params( 24 ) = 0.8992;
b = M_.params( 24 );
M_.params( 22 ) = 0.0530;
sigmaa = M_.params( 22 );
M_.params( 21 ) = 4.3546;
Spp = M_.params( 21 );
M_.params( 19 ) = 0.2273;
alfa = M_.params( 19 );
M_.params( 29 ) = 0.1085;
thetaG = M_.params( 29 );
M_.params( 40 ) = 0.001298;
delta = M_.params( 40 );
M_.params( 8 ) = 0.3151;
DSHARE = M_.params( 8 );
M_.params( 7 ) = 0.4945;
recSHAREpercent = M_.params( 7 );
M_.params( 10 ) = 127.45;
phiL = M_.params( 10 );
M_.params( 3 ) = 0.8395;
s = M_.params( 3 );
M_.params( 6 ) = 0.4904;
sigma = M_.params( 6 );
M_.params( 37 ) = 0.7652;
rhomuz = M_.params( 37 );
M_.params( 38 ) = 0.8475;
rhomuzT = M_.params( 38 );
M_.params( 34 ) = 4.8476;
sigmuzTPratio = M_.params( 34 );
M_.params( 36 ) = 0.6623;
rhomupsi = M_.params( 36 );
M_.params( 31 ) = 0.1286;
sig_mupsi = M_.params( 31 );
M_.params( 32 ) = 0.6555;
sig_epsR = M_.params( 32 );
M_.params( 33 ) = 0.0384;
sig_muz = M_.params( 33 );
M_.params( 35 ) = M_.params(33)*M_.params(34);
sigmuzT = M_.params( 35 );
M_.params( 14 ) = 0;
kappaf = M_.params( 14 );
M_.params( 15 ) = 1;
varkappaf = M_.params( 15 );
M_.params( 16 ) = 1;
pibreve = M_.params( 16 );
M_.params( 39 ) = 1-(1-M_.params(24))/M_.params(11);
chi = M_.params( 39 );
M_.params( 43 ) = M_.params(41)/M_.params(42)^(M_.params(19)/(1-M_.params(19)));
muz = M_.params( 43 );
M_.params( 44 ) = M_.params(41)^((-1)/M_.params(29));
nG = M_.params( 44 );
M_.params( 45 ) = M_.params(41)^((-1)/M_.params(29));
nKAP = M_.params( 45 );
M_.params( 46 ) = M_.params(41)^((-1)/M_.params(29));
nD = M_.params( 46 );
M_.params( 47 ) = M_.params(41)^((-1)/M_.params(29));
nGAM = M_.params( 47 );
nPHI=mu^(-1/thetaG);            
M_.params( 48 ) = M_.params(41)^((-1)/M_.params(29));
nL = M_.params( 48 );
M_.params( 49 ) = M_.params(41)^((-1)/M_.params(29));
nH = M_.params( 49 );
M_.params( 50 ) = 1;
uk = M_.params( 50 );
a_uk=0;                         
M_.params( 51 ) = 0;
S = M_.params( 51 );
M_.params( 52 ) = 0;
Sprime = M_.params( 52 );
M_.params( 53 ) = 0;
Fcal = M_.params( 53 );
M_.params( 54 ) = 0;
Fcalprime = M_.params( 54 );
M_.params( 55 ) = M_.params(23)/M_.params(41);
m = M_.params( 55 );
M_.params( 56 ) = M_.params(2)*(1-M_.params(1));
l = M_.params( 56 );
M_.params( 57 ) = M_.params(13)/M_.params(55);
R = M_.params( 57 );
M_.params( 58 ) = 1;
pk = M_.params( 58 );
M_.params( 59 ) = M_.params(57);
Rk = M_.params( 59 );
M_.params( 60 ) = M_.params(42)*M_.params(59)*M_.params(58)/M_.params(13)-M_.params(58)*(1-M_.params(20));
sigmab = M_.params( 60 );
M_.params( 61 ) = M_.params(13)^M_.params(14)*M_.params(13)^(1-M_.params(14)-M_.params(15))*M_.params(16)^M_.params(15);
pitilde = M_.params( 61 );
M_.params( 62 ) = 1/M_.params(17)*(1-M_.params(23)*M_.params(12)*(M_.params(61)/M_.params(13))^(M_.params(17)/(1-M_.params(17))))/(1-M_.params(23)*M_.params(12)*(M_.params(61)/M_.params(13))^(1/(1-M_.params(17))))*((1-M_.params(12)*(M_.params(61)/M_.params(13))^(1/(1-M_.params(17))))/(1-M_.params(12)))^(1-M_.params(17));
mc = M_.params( 62 );
M_.params( 63 ) = ((1-M_.params(12)*(M_.params(61)/M_.params(13))^(1/(1-M_.params(17))))/(1-M_.params(12)))^(1-M_.params(17))/((1-M_.params(12)*(M_.params(61)/M_.params(13))^(M_.params(17)/(1-M_.params(17))))/(1-M_.params(12)))^((1-M_.params(17))/M_.params(17));
Disp = M_.params( 63 );
M_.params( 64 ) = (M_.params(19)*(M_.params(41)*M_.params(42))^(1-M_.params(19))*M_.params(62)/M_.params(60))^(1/(1-M_.params(19)));
kl = M_.params( 64 );
M_.params( 65 ) = (1-M_.params(19))*M_.params(62)/((M_.params(41)*M_.params(42))^M_.params(19)*(1+M_.params(57)*M_.params(18)-M_.params(18)))*M_.params(64)^M_.params(19);
varthet = M_.params( 65 );
M_.params( 66 ) = M_.params(62)/(1+M_.params(62)*(M_.params(63)^(M_.params(17)/(1-M_.params(17)))-1)-M_.params(30))*(M_.params(64)/(M_.params(41)*M_.params(42)))^M_.params(19)*M_.params(56);
y = M_.params( 66 );
M_.params( 67 ) = M_.params(64)*M_.params(56);
k = M_.params( 67 );
M_.params( 68 ) = (M_.params(56)*(M_.params(67)/M_.params(56)/(M_.params(41)*M_.params(42)))^M_.params(19)-M_.params(63)^(M_.params(17)/(1-M_.params(17)))*M_.params(66))/nPHI;
phi = M_.params( 68 );
M_.params( 69 ) = M_.params(67)*(1-(1-M_.params(20))/(M_.params(41)*M_.params(42)));
i = M_.params( 69 );
M_.params( 70 ) = M_.params(66)*(1-M_.params(28))-M_.params(69)-M_.params(66)*M_.params(7)/100;
c = M_.params( 70 );
M_.params( 71 ) = M_.params(66)*M_.params(28)/M_.params(44);
g = M_.params( 71 );
M_.params( 72 ) = M_.params(69)+M_.params(44)*M_.params(71)+M_.params(70);
GDP = M_.params( 72 );
M_.params( 73 ) = 1-M_.params(4);
x = M_.params( 73 );
M_.params( 74 ) = M_.params(56)*M_.params(73)/(M_.params(2)-M_.params(56)*M_.params(4));
f = M_.params( 74 );
M_.params( 75 ) = M_.params(73)/M_.params(5);
v = M_.params( 75 );
M_.params( 76 ) = M_.params(56)*M_.params(73)*(M_.params(2)-M_.params(56)*M_.params(4))^(-M_.params(6))*(M_.params(56)*M_.params(75))^(M_.params(6)-1);
sigmam = M_.params( 76 );
M_.params( 77 ) = M_.params(66)*M_.params(7)/100/M_.params(73)/M_.params(56)/M_.params(45);
kappa = M_.params( 77 );
M_.params( 78 ) = M_.params(45)*M_.params(77);
J = M_.params( 78 );
M_.params( 79 ) = M_.params(65)/(1-M_.params(41)*M_.params(55)*M_.params(4));
varthetp = M_.params( 79 );
M_.params( 80 ) = M_.params(79)-M_.params(78);
wp = M_.params( 80 );
M_.params( 81 ) = (1-M_.params(41)*M_.params(55)*M_.params(4))*M_.params(80);
w = M_.params( 81 );
M_.params( 82 ) = M_.params(8)*M_.params(81)/M_.params(46);
D = M_.params( 82 );
M_.params( 83 ) = (M_.params(2)-(M_.params(2)-M_.params(56)*M_.params(4))*M_.params(3)-M_.params(56)*M_.params(4))/(1-M_.params(2));
e = M_.params( 83 );
M_.params( 84 ) = 1-M_.params(56);
unemp_stst = M_.params( 84 );
M_.params( 85 ) = M_.params(56)*M_.params(75);
vTot_stst = M_.params( 85 );
M_.params( 86 ) = (1-M_.params(2))*M_.params(49)-M_.params(53);
cH = M_.params( 86 );
M_.params( 91 ) = 0.4654694262;
omega = M_.params( 91 );
ctilde=( (1-omega)*(c*(1-b/mu))^chi+omega*(cH*(1-b/mu))^chi )^(1/chi);  
M_.params( 92 ) = (1-M_.params(91))*ctilde^(1-M_.params(39)-1)*(M_.params(70)*(1-M_.params(24)/M_.params(41)))^(M_.params(39)-1);
lambda_C = M_.params( 92 );
M_.params( 93 ) = M_.params(91)/(1-M_.params(91))*((1-M_.params(24)/M_.params(41))*M_.params(86)/(M_.params(70)*(1-M_.params(24)/M_.params(41))))^(M_.params(39)-1)*M_.params(92);
UcH = M_.params( 93 );
M_.params( 96 ) = M_.params(62)*M_.params(66)*M_.params(17)*M_.params(92)/(1-M_.params(23)*M_.params(12)*(M_.params(61)/M_.params(13))^(M_.params(17)/(1-M_.params(17))));
K = M_.params( 96 );
M_.params( 95 ) = M_.params(66)*M_.params(92)/(1-M_.params(23)*M_.params(12)*(M_.params(61)/M_.params(13))^(1/(1-M_.params(17))));
F = M_.params( 95 );
Emat=zeros(4,4);                                                        
Emat(1,2)=1;                                                            
Emat(2,1)=(1-rho)*m*mu*s*f/(1-rho*m*mu);                                
Emat(2,3)=(1-rho)*m*mu*s*(1-f)/(1-rho*m*mu);                            
Emat(2,4)=(1-rho)*m*mu*(1-s)/(1-rho*m*mu);                              
Emat(3,1)=m*mu*s*f;                                                     
Emat(3,3)=m*mu*s*(1-f);                                                 
Emat(3,4)=m*mu*(1-s);                                                   
Emat(4,1)=m*mu*e*f/(1-m*mu*(1-e));                                      
Emat(4,3)=m*mu*e*(1-f)/(1-m*mu*(1-e));                                  
sol=inv(eye(4)-Emat)*[wp;0;nD*D;(UcH/lambda_C*nH)/(1-m*mu*(1-e))];      
M_.params( 100 ) = sol(1);
V = M_.params( 100 );
M_.params( 99 ) = sol(2);
A = M_.params( 99 );
M_.params( 97 ) = sol(3);
U = M_.params( 97 );
M_.params( 98 ) = sol(4);
N = M_.params( 98 );
M_.params( 101 ) = (M_.params(81)-M_.params(44)*M_.params(82))/(1-M_.params(4)*M_.params(41)*M_.params(55)*(1-M_.params(74)));
pl = M_.params( 101 );
M_.params( 87 ) = 1-M_.params(40)+(1-M_.params(40))^M_.params(9);
alp1 = M_.params( 87 );
M_.params( 88 ) = 1-(1-M_.params(40))^M_.params(9);
alp2 = M_.params( 88 );
M_.params( 89 ) = (1-M_.params(40))*M_.params(88)/M_.params(40)-M_.params(87);
alp3 = M_.params( 89 );
M_.params( 90 ) = 1+M_.params(88)*(1-M_.params(40))/(2-M_.params(40))/M_.params(9)-M_.params(88);
alp4 = M_.params( 90 );
M_.params( 94 ) = (M_.params(88)*(M_.params(100)-M_.params(97))-M_.params(78)*M_.params(87)+M_.params(90)*(M_.params(65)-M_.params(46)*M_.params(82)))/(M_.params(47)*M_.params(89));
gamma = M_.params( 94 );
M_.params( 102 ) = 1000;
sig_eta = M_.params( 102 );
M_.params( 103 ) = 0;
theta1 = M_.params( 103 );
M_.params( 104 ) = 0;
theta2 = M_.params( 104 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(92));
oo_.steady_state( 2 ) = log(M_.params(70));
oo_.steady_state( 3 ) = log(M_.params(57));
oo_.steady_state( 4 ) = log(M_.params(13));
oo_.steady_state( 5 ) = log(M_.params(69));
oo_.steady_state( 6 ) = log(M_.params(58));
oo_.steady_state( 7 ) = log(M_.params(95));
oo_.steady_state( 8 ) = log(M_.params(96));
oo_.steady_state( 9 ) = log(M_.params(50));
oo_.steady_state( 10 ) = log(M_.params(81));
oo_.steady_state( 11 ) = log(M_.params(67));
oo_.steady_state( 12 ) = log(M_.params(56));
oo_.steady_state( 13 ) = log(M_.params(73));
oo_.steady_state( 14 ) = log(M_.params(65));
oo_.steady_state( 15 ) = log(M_.params(63));
oo_.steady_state( 16 ) = log(M_.params(66));
oo_.steady_state( 17 ) = log(M_.params(78));
oo_.steady_state( 18 ) = log(M_.params(97));
oo_.steady_state( 19 ) = log(M_.params(72));
oo_.steady_state( 20 ) = log(M_.params(74));
oo_.steady_state( 21 ) = log(M_.params(75));
oo_.steady_state( 22 ) = log(M_.params(1));
oo_.steady_state( 23 ) = log(M_.params(100));
oo_.steady_state( 24 ) = log(M_.params(99));
oo_.steady_state( 25 ) = log(M_.params(56)*M_.params(75));
oo_.steady_state( 26 ) = log(M_.params(5));
oo_.steady_state( 27 ) = log(M_.params(80));
oo_.steady_state( 28 ) = log(M_.params(79));
oo_.steady_state( 29 ) = log(M_.params(83));
oo_.steady_state( 30 ) = log(M_.params(98));
oo_.steady_state( 31 ) = log(M_.params(2));
oo_.steady_state( 32 ) = log(M_.params(86));
oo_.steady_state( 33 ) = log(M_.params(93));
oo_.steady_state( 34 ) = log(M_.params(101));
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = log(M_.params(44));
oo_.steady_state( 37 ) = log(M_.params(92));
oo_.steady_state( 38 ) = log(M_.params(70));
oo_.steady_state( 39 ) = log(M_.params(57));
oo_.steady_state( 40 ) = log(M_.params(13));
oo_.steady_state( 41 ) = log(M_.params(69));
oo_.steady_state( 42 ) = log(M_.params(58));
oo_.steady_state( 43 ) = log(M_.params(95));
oo_.steady_state( 44 ) = log(M_.params(96));
oo_.steady_state( 45 ) = log(M_.params(50));
oo_.steady_state( 46 ) = log(M_.params(81));
oo_.steady_state( 47 ) = log(M_.params(67));
oo_.steady_state( 48 ) = log(M_.params(56));
oo_.steady_state( 49 ) = log(M_.params(73));
oo_.steady_state( 50 ) = log(M_.params(65));
oo_.steady_state( 51 ) = log(M_.params(63));
oo_.steady_state( 52 ) = log(M_.params(66));
oo_.steady_state( 53 ) = log(M_.params(78));
oo_.steady_state( 54 ) = log(M_.params(97));
oo_.steady_state( 55 ) = log(M_.params(72));
oo_.steady_state( 56 ) = log(M_.params(74));
oo_.steady_state( 57 ) = log(M_.params(75));
oo_.steady_state( 58 ) = log(M_.params(1));
oo_.steady_state( 59 ) = log(M_.params(100));
oo_.steady_state( 60 ) = log(M_.params(99));
oo_.steady_state( 61 ) = log(M_.params(56)*M_.params(75));
oo_.steady_state( 62 ) = log(M_.params(5));
oo_.steady_state( 63 ) = log(M_.params(80));
oo_.steady_state( 64 ) = log(M_.params(79));
oo_.steady_state( 65 ) = log(M_.params(83));
oo_.steady_state( 66 ) = log(M_.params(98));
oo_.steady_state( 67 ) = log(M_.params(2));
oo_.steady_state( 68 ) = log(M_.params(86));
oo_.steady_state( 69 ) = log(M_.params(93));
oo_.steady_state( 70 ) = log(M_.params(101));
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = log(M_.params(43));
oo_.steady_state( 73 ) = log(M_.params(42));
oo_.steady_state( 74 ) = log(M_.params(41));
oo_.steady_state( 75 ) = log(M_.params(44));
oo_.steady_state( 76 ) = 4*log(M_.params(13));
oo_.steady_state( 77 ) = log(M_.params(72));
oo_.steady_state( 78 ) = log(M_.params(13));
oo_.steady_state( 79 ) = log(M_.params(57));
oo_.steady_state( 80 ) = log(M_.params(50));
oo_.steady_state( 81 ) = log(M_.params(56));
oo_.steady_state( 82 ) = log(M_.params(81));
oo_.steady_state( 83 ) = log(M_.params(70));
oo_.steady_state( 84 ) = log(M_.params(69));
oo_.steady_state( 85 ) = log(M_.params(1));
oo_.steady_state( 86 ) = log(M_.params(56)*M_.params(75));
oo_.steady_state( 87 ) = log(M_.params(74));
oo_.steady_state( 88 ) = (-log(M_.params(42)));
oo_.steady_state( 89 ) = log(M_.params(2));
oo_.steady_state(90)=oo_.steady_state(110);
oo_.steady_state(91)=oo_.steady_state(111);
oo_.steady_state(92)=oo_.steady_state(112);
oo_.steady_state(93)=oo_.steady_state(113);
oo_.steady_state(94)=oo_.steady_state(114);
oo_.steady_state(95)=oo_.steady_state(115);
oo_.steady_state(96)=oo_.steady_state(116);
oo_.steady_state(97)=oo_.steady_state(117);
oo_.steady_state(98)=oo_.steady_state(118);
oo_.steady_state(99)=oo_.steady_state(119);
oo_.steady_state(100)=oo_.steady_state(120);
oo_.steady_state(101)=oo_.steady_state(121);
oo_.steady_state(102)=oo_.steady_state(122);
oo_.steady_state(103)=oo_.steady_state(3);
oo_.steady_state(104)=oo_.steady_state(123);
oo_.steady_state(105)=oo_.steady_state(124);
oo_.steady_state(106)=oo_.steady_state(125);
oo_.steady_state(107)=oo_.steady_state(126);
oo_.steady_state(108)=oo_.steady_state(127);
oo_.steady_state(109)=oo_.steady_state(128);
oo_.steady_state(110)=oo_.steady_state(4);
oo_.steady_state(111)=oo_.steady_state(7);
oo_.steady_state(112)=oo_.steady_state(8);
oo_.steady_state(113)=oo_.steady_state(1);
oo_.steady_state(114)=oo_.steady_state(6);
oo_.steady_state(115)=oo_.steady_state(5);
oo_.steady_state(116)=oo_.steady_state(18);
oo_.steady_state(117)=oo_.steady_state(20);
oo_.steady_state(118)=oo_.steady_state(23);
oo_.steady_state(119)=oo_.steady_state(9);
oo_.steady_state(120)=oo_.steady_state(27);
oo_.steady_state(121)=oo_.steady_state(28);
oo_.steady_state(122)=oo_.steady_state(24);
oo_.steady_state(123)=oo_.steady_state(31);
oo_.steady_state(124)=oo_.steady_state(30);
oo_.steady_state(125)=oo_.steady_state(29);
oo_.steady_state(126)=oo_.steady_state(34);
oo_.steady_state(127)=oo_.steady_state(33);
oo_.steady_state(128)=oo_.steady_state(35);
oo_.steady_state(129)=oo_.steady_state(4);
oo_.steady_state(130)=oo_.steady_state(129);
oo_.steady_state(131)=oo_.steady_state(19);
oo_.steady_state(132)=oo_.steady_state(131);
oo_.steady_state(133)=oo_.steady_state(132);
oo_.steady_state(134)=oo_.steady_state(55);
oo_.steady_state(135)=oo_.steady_state(134);
oo_.steady_state(136)=oo_.steady_state(135);
oo_.steady_state(137)=oo_.steady_state(74);
oo_.steady_state(138)=oo_.steady_state(137);
oo_.steady_state(139)=oo_.steady_state(40);
oo_.steady_state(140)=oo_.steady_state(139);
oo_.steady_state(141)=oo_.steady_state(72);
oo_.steady_state(142)=oo_.exo_steady_state(2);
oo_.steady_state(143)=oo_.steady_state(142);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 15;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_ = char('GDPAGG','unempAGG','piAGG','RAGG','lAGG','wAGG','cAGG','LAGG','iAGG','ukAGG','fAGG','vTotAGG');
info = stoch_simul(var_list_);
figure;
suptitle('Monetary Policy Shock')
subplot(3,4,1);
plot(GDPAGG_epsR_eps);
title('GDP');
subplot(3,4,2);
plot(unempAGG_epsR_eps);
title('Unemployment rate');
subplot(3,4,3);
plot(piAGG_epsR_eps);
title('Inflation');
subplot(3,4,4);
plot(RAGG_epsR_eps);
title('Fed Fund Rate');
subplot(3,4,5);
plot(lAGG_epsR_eps);
title('Hours');
subplot(3,4,6);
plot(wAGG_epsR_eps);
title('Real Wage');
subplot(3,4,7);
plot(cAGG_epsR_eps);
title('Consumption');
subplot(3,4,8);
plot(LAGG_epsR_eps);
title('Labor Force');
subplot(3,4,9);
plot(iAGG_epsR_eps);
title('Investment');
subplot(3,4,10);
plot(ukAGG_epsR_eps);
title('Capacity utilization');
subplot(3,4,11);
plot(fAGG_epsR_eps);
title('Job finding rate');
subplot(3,4,12);
plot(vTotAGG_epsR_eps);
title('Vacancies');
saveas(gcf,'IRF_MonPol.pdf');
save('US_CET15_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_CET15_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_CET15_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_CET15_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_CET15_rep_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_CET15_rep_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_CET15_rep_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
