%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EA_VI16_rep_orig';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_VI16_rep_orig.log');
M_.exo_names = 'e_x';
M_.exo_names_tex = 'e\_x';
M_.exo_names_long = 'e_x';
M_.exo_names = char(M_.exo_names, 'e_r');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_r');
M_.exo_names_long = char(M_.exo_names_long, 'e_r');
M_.exo_names = char(M_.exo_names, 'e_k');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_k');
M_.exo_names_long = char(M_.exo_names_long, 'e_k');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'e_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w');
M_.exo_names_long = char(M_.exo_names_long, 'e_w');
M_.exo_names = char(M_.exo_names, 'e_p');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_p');
M_.exo_names_long = char(M_.exo_names_long, 'e_p');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'ext_pr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_pr');
M_.endo_names_long = char(M_.endo_names_long, 'ext_pr');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'lev');
M_.endo_names_tex = char(M_.endo_names_tex, 'lev');
M_.endo_names_long = char(M_.endo_names_long, 'lev');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'nn');
M_.endo_names_tex = char(M_.endo_names_tex, 'nn');
M_.endo_names_long = char(M_.endo_names_long, 'nn');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'ne');
M_.endo_names_long = char(M_.endo_names_long, 'ne');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'zk');
M_.endo_names_tex = char(M_.endo_names_tex, 'zk');
M_.endo_names_long = char(M_.endo_names_long, 'zk');
M_.endo_names = char(M_.endo_names, 'rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'rn');
M_.endo_names_long = char(M_.endo_names_long, 'rn');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'i_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_f');
M_.endo_names_long = char(M_.endo_names_long, 'i_f');
M_.endo_names = char(M_.endo_names, 'ext_prf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ext\_prf');
M_.endo_names_long = char(M_.endo_names_long, 'ext_prf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'levf');
M_.endo_names_tex = char(M_.endo_names_tex, 'levf');
M_.endo_names_long = char(M_.endo_names_long, 'levf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'Lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'Lambdaf');
M_.endo_names = char(M_.endo_names, 'lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf');
M_.endo_names_long = char(M_.endo_names_long, 'lf');
M_.endo_names = char(M_.endo_names, 'df');
M_.endo_names_tex = char(M_.endo_names_tex, 'df');
M_.endo_names_long = char(M_.endo_names_long, 'df');
M_.endo_names = char(M_.endo_names, 'vf');
M_.endo_names_tex = char(M_.endo_names_tex, 'vf');
M_.endo_names_long = char(M_.endo_names_long, 'vf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zf');
M_.endo_names_long = char(M_.endo_names_long, 'zf');
M_.endo_names = char(M_.endo_names, 'nnf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nnf');
M_.endo_names_long = char(M_.endo_names_long, 'nnf');
M_.endo_names = char(M_.endo_names, 'muf');
M_.endo_names_tex = char(M_.endo_names_tex, 'muf');
M_.endo_names_long = char(M_.endo_names_long, 'muf');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'nef');
M_.endo_names_tex = char(M_.endo_names_tex, 'nef');
M_.endo_names_long = char(M_.endo_names_long, 'nef');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf');
M_.endo_names_long = char(M_.endo_names_long, 'uf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'zkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkf');
M_.endo_names_long = char(M_.endo_names_long, 'zkf');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'eps_p');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_p');
M_.endo_names_long = char(M_.endo_names_long, 'eps_p');
M_.endo_names = char(M_.endo_names, 'eps_w');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_w');
M_.endo_names_long = char(M_.endo_names_long, 'eps_w');
M_.endo_names = char(M_.endo_names, 'eps_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_k');
M_.endo_names_long = char(M_.endo_names_long, 'eps_k');
M_.endo_names = char(M_.endo_names, 'eps_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_r');
M_.endo_names_long = char(M_.endo_names_long, 'eps_r');
M_.endo_names = char(M_.endo_names, 'eps_x');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_x');
M_.endo_names_long = char(M_.endo_names_long, 'eps_x');
M_.endo_names = char(M_.endo_names, 'emp');
M_.endo_names_tex = char(M_.endo_names_tex, 'emp');
M_.endo_names_long = char(M_.endo_names_long, 'emp');
M_.endo_names = char(M_.endo_names, 'robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'robs');
M_.endo_names_long = char(M_.endo_names_long, 'robs');
M_.endo_names = char(M_.endo_names, 'piobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'piobs');
M_.endo_names_long = char(M_.endo_names_long, 'piobs');
M_.endo_names = char(M_.endo_names, 'dy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy');
M_.endo_names_long = char(M_.endo_names_long, 'dy');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names_long = char(M_.endo_names_long, 'dc');
M_.endo_names = char(M_.endo_names, 'dfi');
M_.endo_names_tex = char(M_.endo_names_tex, 'dfi');
M_.endo_names_long = char(M_.endo_names_long, 'dfi');
M_.endo_names = char(M_.endo_names, 'dw');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw');
M_.endo_names_long = char(M_.endo_names_long, 'dw');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'epsilon_w');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon\_w');
M_.param_names_long = char(M_.param_names_long, 'epsilon_w');
M_.param_names = char(M_.param_names, 'G_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_Y');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'zeta');
M_.param_names_tex = char(M_.param_names_tex, 'zeta');
M_.param_names_long = char(M_.param_names_long, 'zeta');
M_.param_names = char(M_.param_names, 'ksi');
M_.param_names_tex = char(M_.param_names_tex, 'ksi');
M_.param_names_long = char(M_.param_names_long, 'ksi');
M_.param_names = char(M_.param_names, 'sig_p');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_p');
M_.param_names_long = char(M_.param_names_long, 'sig_p');
M_.param_names = char(M_.param_names, 'sig_pi');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_pi');
M_.param_names_long = char(M_.param_names_long, 'sig_pi');
M_.param_names = char(M_.param_names, 'sig_w');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_w');
M_.param_names_long = char(M_.param_names_long, 'sig_w');
M_.param_names = char(M_.param_names, 'sig_wi');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_wi');
M_.param_names_long = char(M_.param_names_long, 'sig_wi');
M_.param_names = char(M_.param_names, 'sig_E');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_E');
M_.param_names_long = char(M_.param_names_long, 'sig_E');
M_.param_names = char(M_.param_names, 'M');
M_.param_names_tex = char(M_.param_names_tex, 'M');
M_.param_names_long = char(M_.param_names_long, 'M');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'rho_ri');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ri');
M_.param_names_long = char(M_.param_names_long, 'rho_ri');
M_.param_names = char(M_.param_names, 'rho_PI');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_PI');
M_.param_names_long = char(M_.param_names_long, 'rho_PI');
M_.param_names = char(M_.param_names, 'rho_Y');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Y');
M_.param_names_long = char(M_.param_names_long, 'rho_Y');
M_.param_names = char(M_.param_names, 'rho_A');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_A');
M_.param_names_long = char(M_.param_names_long, 'rho_A');
M_.param_names = char(M_.param_names, 'rho_G');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_G');
M_.param_names_long = char(M_.param_names_long, 'rho_G');
M_.param_names = char(M_.param_names, 'rho_X');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_X');
M_.param_names_long = char(M_.param_names_long, 'rho_X');
M_.param_names = char(M_.param_names, 'rho_k');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_k');
M_.param_names_long = char(M_.param_names_long, 'rho_k');
M_.param_names = char(M_.param_names, 'rho_W');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_W');
M_.param_names_long = char(M_.param_names_long, 'rho_W');
M_.param_names = char(M_.param_names, 'rho_P');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_P');
M_.param_names_long = char(M_.param_names_long, 'rho_P');
M_.param_names = char(M_.param_names, 'THETA');
M_.param_names_tex = char(M_.param_names_tex, 'THETA');
M_.param_names_long = char(M_.param_names_long, 'THETA');
M_.param_names = char(M_.param_names, 'rho_DY');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_DY');
M_.param_names_long = char(M_.param_names_long, 'rho_DY');
M_.param_names = char(M_.param_names, 'RK');
M_.param_names_tex = char(M_.param_names_tex, 'RK');
M_.param_names_long = char(M_.param_names_long, 'RK');
M_.param_names = char(M_.param_names, 'constelab');
M_.param_names_tex = char(M_.param_names_tex, 'constelab');
M_.param_names_long = char(M_.param_names_long, 'constelab');
M_.param_names = char(M_.param_names, 'picbar');
M_.param_names_tex = char(M_.param_names_tex, 'picbar');
M_.param_names_long = char(M_.param_names_long, 'picbar');
M_.param_names = char(M_.param_names, 'trend');
M_.param_names_tex = char(M_.param_names_tex, 'trend');
M_.param_names_long = char(M_.param_names_long, 'trend');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 60;
M_.param_nbr = 35;
M_.orig_endo_nbr = 60;
M_.aux_vars = [];
options_.varobs = cell(1);
options_.varobs(1)  = {'dy'};
options_.varobs(2)  = {'dc'};
options_.varobs(3)  = {'dfi'};
options_.varobs(4)  = {'emp'};
options_.varobs(5)  = {'piobs'};
options_.varobs(6)  = {'dw'};
options_.varobs(7)  = {'robs'};
options_.varobs_id = [ 57 58 59 54 56 60 55  ];
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('EA_VI16_rep_orig_static');
erase_compiled_function('EA_VI16_rep_orig_dynamic');
M_.orig_eq_nbr = 60;
M_.eq_nbr = 60;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 30 0;
 2 31 90;
 0 32 0;
 3 33 0;
 4 34 0;
 5 35 0;
 0 36 91;
 0 37 0;
 0 38 92;
 0 39 93;
 0 40 94;
 0 41 0;
 0 42 0;
 0 43 0;
 6 44 0;
 7 45 0;
 0 46 0;
 8 47 95;
 0 48 0;
 9 49 96;
 10 50 0;
 0 51 0;
 11 52 0;
 12 53 97;
 13 54 0;
 14 55 98;
 0 56 0;
 15 57 0;
 16 58 0;
 17 59 0;
 0 60 99;
 0 61 0;
 0 62 100;
 0 63 101;
 0 64 102;
 0 65 0;
 0 66 0;
 0 67 0;
 18 68 0;
 19 69 0;
 0 70 0;
 20 71 103;
 0 72 0;
 0 73 0;
 21 74 0;
 0 75 0;
 22 76 0;
 23 77 0;
 24 78 0;
 25 79 0;
 26 80 0;
 27 81 0;
 28 82 0;
 29 83 104;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;]';
M_.nstatic = 23;
M_.nfwrd   = 8;
M_.npred   = 22;
M_.nboth   = 7;
M_.nsfwrd   = 15;
M_.nspred   = 29;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(60, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(35, 1);
M_.NNZDerivatives = [233; 0; -1];
M_.params( 4 ) = 0.33;
alpha = M_.params( 4 );
M_.params( 1 ) = 0.99;
beta = M_.params( 1 );
M_.params( 5 ) = 0.025;
delta = M_.params( 5 );
M_.params( 6 ) = 6;
epsilon = M_.params( 6 );
M_.params( 7 ) = 6;
epsilon_w = M_.params( 7 );
M_.params( 19 ) = M_.params(6)/(M_.params(6)-1);
M = M_.params( 19 );
M_.params( 8 ) = 0.20;
G_Y = M_.params( 8 );
M_.params( 2 ) = 1.49;
phi = M_.params( 2 );
M_.params( 9 ) = 0.65;
h = M_.params( 9 );
M_.params( 10 ) = 0.5152;
lambda = M_.params( 10 );
M_.params( 11 ) = 0.9715;
theta = M_.params( 11 );
M_.params( 3 ) = 0.001;
chi = M_.params( 3 );
M_.params( 30 ) = 1.40;
THETA = M_.params( 30 );
M_.params( 14 ) = 0.84;
sig_p = M_.params( 14 );
M_.params( 15 ) = 0.15;
sig_pi = M_.params( 15 );
M_.params( 16 ) = 0.78;
sig_w = M_.params( 16 );
M_.params( 17 ) = 0.39;
sig_wi = M_.params( 17 );
M_.params( 18 ) = 0.8;
sig_E = M_.params( 18 );
M_.params( 12 ) = 0.95;
zeta = M_.params( 12 );
M_.params( 13 ) = 4.95;
ksi = M_.params( 13 );
M_.params( 22 ) = 1.73;
rho_PI = M_.params( 22 );
M_.params( 23 ) = 0.09;
rho_Y = M_.params( 23 );
M_.params( 31 ) = 0.08;
rho_DY = M_.params( 31 );
M_.params( 20 ) = 0.89;
rho_r = M_.params( 20 );
M_.params( 24 ) = 0.90;
rho_A = M_.params( 24 );
M_.params( 26 ) = 0.97;
rho_X = M_.params( 26 );
M_.params( 25 ) = 0.92;
rho_G = M_.params( 25 );
M_.params( 28 ) = 0.72;
rho_W = M_.params( 28 );
M_.params( 29 ) = 0.58;
rho_P = M_.params( 29 );
M_.params( 27 ) = 0.99;
rho_k = M_.params( 27 );
M_.params( 21 ) = 0.24;
rho_ri = M_.params( 21 );
M_.params( 32 ) = 1.013860066271978;
RK = M_.params( 32 );
M_.params( 33 ) = 0;
constelab = M_.params( 33 );
M_.params( 34 ) = 0.63;
picbar = M_.params( 34 );
M_.params( 35 ) = 0.3;
trend = M_.params( 35 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (2.11)^2;
M_.Sigma_e(2, 2) = (0.11)^2;
M_.Sigma_e(3, 3) = (0.17)^2;
M_.Sigma_e(4, 4) = (1.47)^2;
M_.Sigma_e(5, 5) = (0.96)^2;
M_.Sigma_e(6, 6) = (0.12)^2;
M_.Sigma_e(7, 7) = (0.09)^2;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.3974, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 1.0534, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.1224, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.1705, 0.025, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 2.2030, 0.01, 50, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.1288, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.2806, 0.01, 25, 4, 0.1, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9493, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.9802, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9624, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.9914, .01, .9999999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.2154, (-0.02), .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.2101, .01, .99999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.1907, .001, .9999, 1, 0.5, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 3.8293, 0.0001, 15, 3, 4, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.4279, 0.1, 0.99, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.8453, 0.25, 0.99, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.8953, 0.5, 0.97, 1, 0.75, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 30, 1.3488, 1.0, 3, 3, 1.45, 0.125, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 1.6665, 0.1, 3.5, 2, 0.33, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.3078, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.4257, 0.01, 0.99, 1, 0.5, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.8554, 0.0001, 1, 1, 0.25, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 1.8855, 1.0, 3, 3, 1.7, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.8495, 0.35, 0.975, 1, 0.75, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.0743, (-0.065), 0.5, 2, .125, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 31, 0.2004, (-0.1), 0.5, 3, 0.0625, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, 0.6473, 0.1, 2.0, 2, 0.625, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, 0.3029, 0.001, 0.8, 3, 0.4, 0.10, NaN, NaN, NaN ];
options_.plot_priors=0;
options_.irf = 20;
options_.nograph = 1;
var_list_ = char('y','i','pi','n','ext_pr');
info = stoch_simul(var_list_);
save('EA_VI16_rep_orig_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('EA_VI16_rep_orig_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
