%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'main_code_FGKR';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('main_code_FGKR.log');
M_.exo_names = 'ect';
M_.exo_names_tex = 'ect';
M_.exo_names_long = 'ect';
M_.exo_names = char(M_.exo_names, 'edt');
M_.exo_names_tex = char(M_.exo_names_tex, 'edt');
M_.exo_names_long = char(M_.exo_names_long, 'edt');
M_.exo_names = char(M_.exo_names, 'egt');
M_.exo_names_tex = char(M_.exo_names_tex, 'egt');
M_.exo_names_long = char(M_.exo_names_long, 'egt');
M_.exo_names = char(M_.exo_names, 'ekt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ekt');
M_.exo_names_long = char(M_.exo_names_long, 'ekt');
M_.exo_names = char(M_.exo_names, 'emt');
M_.exo_names_tex = char(M_.exo_names_tex, 'emt');
M_.exo_names_long = char(M_.exo_names_long, 'emt');
M_.exo_names = char(M_.exo_names, 'ewt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ewt');
M_.exo_names_long = char(M_.exo_names_long, 'ewt');
M_.exo_names = char(M_.exo_names, 'ezt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ezt');
M_.exo_names_long = char(M_.exo_names_long, 'ezt');
M_.exo_names = char(M_.exo_names, 'uct');
M_.exo_names_tex = char(M_.exo_names_tex, 'uct');
M_.exo_names_long = char(M_.exo_names_long, 'uct');
M_.exo_names = char(M_.exo_names, 'ugt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ugt');
M_.exo_names_long = char(M_.exo_names_long, 'ugt');
M_.exo_names = char(M_.exo_names, 'ukt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ukt');
M_.exo_names_long = char(M_.exo_names_long, 'ukt');
M_.exo_names = char(M_.exo_names, 'uwt');
M_.exo_names_tex = char(M_.exo_names_tex, 'uwt');
M_.exo_names_long = char(M_.exo_names_long, 'uwt');
M_.endo_names = 'bdt';
M_.endo_names_tex = 'bdt';
M_.endo_names_long = 'bdt';
M_.endo_names = char(M_.endo_names, 'ct');
M_.endo_names_tex = char(M_.endo_names_tex, 'ct');
M_.endo_names_long = char(M_.endo_names_long, 'ct');
M_.endo_names = char(M_.endo_names, 'dt');
M_.endo_names_tex = char(M_.endo_names_tex, 'dt');
M_.endo_names_long = char(M_.endo_names_long, 'dt');
M_.endo_names = char(M_.endo_names, 'gt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gt');
M_.endo_names_long = char(M_.endo_names_long, 'gt');
M_.endo_names = char(M_.endo_names, 'ht');
M_.endo_names_tex = char(M_.endo_names_tex, 'ht');
M_.endo_names_long = char(M_.endo_names_long, 'ht');
M_.endo_names = char(M_.endo_names, 'inflt');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflt');
M_.endo_names_long = char(M_.endo_names_long, 'inflt');
M_.endo_names = char(M_.endo_names, 'invt');
M_.endo_names_tex = char(M_.endo_names_tex, 'invt');
M_.endo_names_long = char(M_.endo_names_long, 'invt');
M_.endo_names = char(M_.endo_names, 'kt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kt');
M_.endo_names_long = char(M_.endo_names_long, 'kt');
M_.endo_names = char(M_.endo_names, 'kbt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbt');
M_.endo_names_long = char(M_.endo_names_long, 'kbt');
M_.endo_names = char(M_.endo_names, 'lamt');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamt');
M_.endo_names_long = char(M_.endo_names_long, 'lamt');
M_.endo_names = char(M_.endo_names, 'mct');
M_.endo_names_tex = char(M_.endo_names_tex, 'mct');
M_.endo_names_long = char(M_.endo_names_long, 'mct');
M_.endo_names = char(M_.endo_names, 'miut');
M_.endo_names_tex = char(M_.endo_names_tex, 'miut');
M_.endo_names_long = char(M_.endo_names_long, 'miut');
M_.endo_names = char(M_.endo_names, 'miubt');
M_.endo_names_tex = char(M_.endo_names_tex, 'miubt');
M_.endo_names_long = char(M_.endo_names_long, 'miubt');
M_.endo_names = char(M_.endo_names, 'proft');
M_.endo_names_tex = char(M_.endo_names_tex, 'proft');
M_.endo_names_long = char(M_.endo_names_long, 'proft');
M_.endo_names = char(M_.endo_names, 'Rt');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rt');
M_.endo_names_long = char(M_.endo_names_long, 'Rt');
M_.endo_names = char(M_.endo_names, 'rkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkt');
M_.endo_names_long = char(M_.endo_names_long, 'rkt');
M_.endo_names = char(M_.endo_names, 'sigct');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigct');
M_.endo_names_long = char(M_.endo_names_long, 'sigct');
M_.endo_names = char(M_.endo_names, 'siggt');
M_.endo_names_tex = char(M_.endo_names_tex, 'siggt');
M_.endo_names_long = char(M_.endo_names_long, 'siggt');
M_.endo_names = char(M_.endo_names, 'sigkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigkt');
M_.endo_names_long = char(M_.endo_names_long, 'sigkt');
M_.endo_names = char(M_.endo_names, 'sigwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigwt');
M_.endo_names_long = char(M_.endo_names_long, 'sigwt');
M_.endo_names = char(M_.endo_names, 'tauct');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauct');
M_.endo_names_long = char(M_.endo_names_long, 'tauct');
M_.endo_names = char(M_.endo_names, 'taukt');
M_.endo_names_tex = char(M_.endo_names_tex, 'taukt');
M_.endo_names_long = char(M_.endo_names_long, 'taukt');
M_.endo_names = char(M_.endo_names, 'tauwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauwt');
M_.endo_names_long = char(M_.endo_names_long, 'tauwt');
M_.endo_names = char(M_.endo_names, 'utilt');
M_.endo_names_tex = char(M_.endo_names_tex, 'utilt');
M_.endo_names_long = char(M_.endo_names_long, 'utilt');
M_.endo_names = char(M_.endo_names, 'wt');
M_.endo_names_tex = char(M_.endo_names_tex, 'wt');
M_.endo_names_long = char(M_.endo_names_long, 'wt');
M_.endo_names = char(M_.endo_names, 'yt');
M_.endo_names_tex = char(M_.endo_names_tex, 'yt');
M_.endo_names_long = char(M_.endo_names_long, 'yt');
M_.endo_names = char(M_.endo_names, 'gzt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gzt');
M_.endo_names_long = char(M_.endo_names_long, 'gzt');
M_.endo_names = char(M_.endo_names, 'gyt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gyt');
M_.endo_names_long = char(M_.endo_names_long, 'gyt');
M_.endo_names = char(M_.endo_names, 'gct');
M_.endo_names_tex = char(M_.endo_names_tex, 'gct');
M_.endo_names_long = char(M_.endo_names_long, 'gct');
M_.endo_names = char(M_.endo_names, 'git');
M_.endo_names_tex = char(M_.endo_names_tex, 'git');
M_.endo_names_long = char(M_.endo_names_long, 'git');
M_.endo_names = char(M_.endo_names, 'gwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gwt');
M_.endo_names_long = char(M_.endo_names_long, 'gwt');
M_.param_names = 'alph';
M_.param_names_tex = 'alph';
M_.param_names_long = 'alph';
M_.param_names = char(M_.param_names, 'bds');
M_.param_names_tex = char(M_.param_names_tex, 'bds');
M_.param_names_long = char(M_.param_names_long, 'bds');
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, 'bet');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'cs');
M_.param_names_tex = char(M_.param_names_tex, 'cs');
M_.param_names_long = char(M_.param_names_long, 'cs');
M_.param_names = char(M_.param_names, 'phisigk');
M_.param_names_tex = char(M_.param_names_tex, 'phisigk');
M_.param_names_long = char(M_.param_names_long, 'phisigk');
M_.param_names = char(M_.param_names, 'deductdepr');
M_.param_names_tex = char(M_.param_names_tex, 'deductdepr');
M_.param_names_long = char(M_.param_names_long, 'deductdepr');
M_.param_names = char(M_.param_names, 'nom_depreciation');
M_.param_names_tex = char(M_.param_names_tex, 'nom\_depreciation');
M_.param_names_long = char(M_.param_names_long, 'nom_depreciation');
M_.param_names = char(M_.param_names, 'delt');
M_.param_names_tex = char(M_.param_names_tex, 'delt');
M_.param_names_long = char(M_.param_names_long, 'delt');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, 'epsw');
M_.param_names_long = char(M_.param_names_long, 'epsw');
M_.param_names = char(M_.param_names, 'deltau');
M_.param_names_tex = char(M_.param_names_tex, 'deltau');
M_.param_names_long = char(M_.param_names_long, 'deltau');
M_.param_names = char(M_.param_names, 'etac');
M_.param_names_tex = char(M_.param_names_tex, 'etac');
M_.param_names_long = char(M_.param_names_long, 'etac');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'etak');
M_.param_names_tex = char(M_.param_names_tex, 'etak');
M_.param_names_long = char(M_.param_names_long, 'etak');
M_.param_names = char(M_.param_names, 'etaw');
M_.param_names_tex = char(M_.param_names_tex, 'etaw');
M_.param_names_long = char(M_.param_names_long, 'etaw');
M_.param_names = char(M_.param_names, 'gamcb');
M_.param_names_tex = char(M_.param_names_tex, 'gamcb');
M_.param_names_long = char(M_.param_names_long, 'gamcb');
M_.param_names = char(M_.param_names, 'gamcy');
M_.param_names_tex = char(M_.param_names_tex, 'gamcy');
M_.param_names_long = char(M_.param_names_long, 'gamcy');
M_.param_names = char(M_.param_names, 'gamgb');
M_.param_names_tex = char(M_.param_names_tex, 'gamgb');
M_.param_names_long = char(M_.param_names_long, 'gamgb');
M_.param_names = char(M_.param_names, 'gamgy');
M_.param_names_tex = char(M_.param_names_tex, 'gamgy');
M_.param_names_long = char(M_.param_names_long, 'gamgy');
M_.param_names = char(M_.param_names, 'gamkb');
M_.param_names_tex = char(M_.param_names_tex, 'gamkb');
M_.param_names_long = char(M_.param_names_long, 'gamkb');
M_.param_names = char(M_.param_names, 'gamky');
M_.param_names_tex = char(M_.param_names_tex, 'gamky');
M_.param_names_long = char(M_.param_names_long, 'gamky');
M_.param_names = char(M_.param_names, 'gamwb');
M_.param_names_tex = char(M_.param_names_tex, 'gamwb');
M_.param_names_long = char(M_.param_names_long, 'gamwb');
M_.param_names = char(M_.param_names, 'gamwy');
M_.param_names_tex = char(M_.param_names_tex, 'gamwy');
M_.param_names_long = char(M_.param_names_long, 'gamwy');
M_.param_names = char(M_.param_names, 'gs');
M_.param_names_tex = char(M_.param_names_tex, 'gs');
M_.param_names_long = char(M_.param_names_long, 'gs');
M_.param_names = char(M_.param_names, 'hs');
M_.param_names_tex = char(M_.param_names_tex, 'hs');
M_.param_names_long = char(M_.param_names_long, 'hs');
M_.param_names = char(M_.param_names, 'infls');
M_.param_names_tex = char(M_.param_names_tex, 'infls');
M_.param_names_long = char(M_.param_names_long, 'infls');
M_.param_names = char(M_.param_names, 'invs');
M_.param_names_tex = char(M_.param_names_tex, 'invs');
M_.param_names_long = char(M_.param_names_long, 'invs');
M_.param_names = char(M_.param_names, 'ks');
M_.param_names_tex = char(M_.param_names_tex, 'ks');
M_.param_names_long = char(M_.param_names_long, 'ks');
M_.param_names = char(M_.param_names, 'kbs');
M_.param_names_tex = char(M_.param_names_tex, 'kbs');
M_.param_names_long = char(M_.param_names_long, 'kbs');
M_.param_names = char(M_.param_names, 'lams');
M_.param_names_tex = char(M_.param_names_tex, 'lams');
M_.param_names_long = char(M_.param_names_long, 'lams');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names_long = char(M_.param_names_long, 'mcs');
M_.param_names = char(M_.param_names, 'mius');
M_.param_names_tex = char(M_.param_names_tex, 'mius');
M_.param_names_long = char(M_.param_names_long, 'mius');
M_.param_names = char(M_.param_names, 'miubs');
M_.param_names_tex = char(M_.param_names_tex, 'miubs');
M_.param_names_long = char(M_.param_names_long, 'miubs');
M_.param_names = char(M_.param_names, 'mius_lams');
M_.param_names_tex = char(M_.param_names_tex, 'mius\_lams');
M_.param_names_long = char(M_.param_names_long, 'mius_lams');
M_.param_names = char(M_.param_names, 'miubs_lams');
M_.param_names_tex = char(M_.param_names_tex, 'miubs\_lams');
M_.param_names_long = char(M_.param_names_long, 'miubs_lams');
M_.param_names = char(M_.param_names, 'nomw');
M_.param_names_tex = char(M_.param_names_tex, 'nomw');
M_.param_names_long = char(M_.param_names_long, 'nomw');
M_.param_names = char(M_.param_names, 'ome');
M_.param_names_tex = char(M_.param_names_tex, 'ome');
M_.param_names_long = char(M_.param_names_long, 'ome');
M_.param_names = char(M_.param_names, 'phibd');
M_.param_names_tex = char(M_.param_names_tex, 'phibd');
M_.param_names_long = char(M_.param_names_long, 'phibd');
M_.param_names = char(M_.param_names, 'phil');
M_.param_names_tex = char(M_.param_names_tex, 'phil');
M_.param_names_long = char(M_.param_names_long, 'phil');
M_.param_names = char(M_.param_names, 'phiprof');
M_.param_names_tex = char(M_.param_names_tex, 'phiprof');
M_.param_names_long = char(M_.param_names_long, 'phiprof');
M_.param_names = char(M_.param_names, 'phips');
M_.param_names_tex = char(M_.param_names_tex, 'phips');
M_.param_names_long = char(M_.param_names_long, 'phips');
M_.param_names = char(M_.param_names, 'phiR');
M_.param_names_tex = char(M_.param_names_tex, 'phiR');
M_.param_names_long = char(M_.param_names_long, 'phiR');
M_.param_names = char(M_.param_names, 'phiRot');
M_.param_names_tex = char(M_.param_names_tex, 'phiRot');
M_.param_names_long = char(M_.param_names_long, 'phiRot');
M_.param_names = char(M_.param_names, 'phiRotw');
M_.param_names_tex = char(M_.param_names_tex, 'phiRotw');
M_.param_names_long = char(M_.param_names_long, 'phiRotw');
M_.param_names = char(M_.param_names, 'phiu1');
M_.param_names_tex = char(M_.param_names_tex, 'phiu1');
M_.param_names_long = char(M_.param_names_long, 'phiu1');
M_.param_names = char(M_.param_names, 'phiu2');
M_.param_names_tex = char(M_.param_names_tex, 'phiu2');
M_.param_names_long = char(M_.param_names_long, 'phiu2');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'profs');
M_.param_names_tex = char(M_.param_names_tex, 'profs');
M_.param_names_long = char(M_.param_names_long, 'profs');
M_.param_names = char(M_.param_names, 'rhoc');
M_.param_names_tex = char(M_.param_names_tex, 'rhoc');
M_.param_names_long = char(M_.param_names_long, 'rhoc');
M_.param_names = char(M_.param_names, 'rhod');
M_.param_names_tex = char(M_.param_names_tex, 'rhod');
M_.param_names_long = char(M_.param_names_long, 'rhod');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhogc');
M_.param_names_tex = char(M_.param_names_tex, 'rhogc');
M_.param_names_long = char(M_.param_names_long, 'rhogc');
M_.param_names = char(M_.param_names, 'rhogg');
M_.param_names_tex = char(M_.param_names_tex, 'rhogg');
M_.param_names_long = char(M_.param_names_long, 'rhogg');
M_.param_names = char(M_.param_names, 'rhogk');
M_.param_names_tex = char(M_.param_names_tex, 'rhogk');
M_.param_names_long = char(M_.param_names_long, 'rhogk');
M_.param_names = char(M_.param_names, 'rhogw');
M_.param_names_tex = char(M_.param_names_tex, 'rhogw');
M_.param_names_long = char(M_.param_names_long, 'rhogw');
M_.param_names = char(M_.param_names, 'rhok');
M_.param_names_tex = char(M_.param_names_tex, 'rhok');
M_.param_names_long = char(M_.param_names_long, 'rhok');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rks');
M_.param_names_tex = char(M_.param_names_tex, 'rks');
M_.param_names_long = char(M_.param_names_long, 'rks');
M_.param_names = char(M_.param_names, 'Rs');
M_.param_names_tex = char(M_.param_names_tex, 'Rs');
M_.param_names_long = char(M_.param_names_long, 'Rs');
M_.param_names = char(M_.param_names, 'sigcs');
M_.param_names_tex = char(M_.param_names_tex, 'sigcs');
M_.param_names_long = char(M_.param_names_long, 'sigcs');
M_.param_names = char(M_.param_names, 'sigd');
M_.param_names_tex = char(M_.param_names_tex, 'sigd');
M_.param_names_long = char(M_.param_names_long, 'sigd');
M_.param_names = char(M_.param_names, 'siggs');
M_.param_names_tex = char(M_.param_names_tex, 'siggs');
M_.param_names_long = char(M_.param_names_long, 'siggs');
M_.param_names = char(M_.param_names, 'sigks');
M_.param_names_tex = char(M_.param_names_tex, 'sigks');
M_.param_names_long = char(M_.param_names_long, 'sigks');
M_.param_names = char(M_.param_names, 'sigms');
M_.param_names_tex = char(M_.param_names_tex, 'sigms');
M_.param_names_long = char(M_.param_names_long, 'sigms');
M_.param_names = char(M_.param_names, 'sigws');
M_.param_names_tex = char(M_.param_names_tex, 'sigws');
M_.param_names_long = char(M_.param_names_long, 'sigws');
M_.param_names = char(M_.param_names, 'sigz');
M_.param_names_tex = char(M_.param_names_tex, 'sigz');
M_.param_names_long = char(M_.param_names_long, 'sigz');
M_.param_names = char(M_.param_names, 'taucs');
M_.param_names_tex = char(M_.param_names_tex, 'taucs');
M_.param_names_long = char(M_.param_names_long, 'taucs');
M_.param_names = char(M_.param_names, 'tauks');
M_.param_names_tex = char(M_.param_names_tex, 'tauks');
M_.param_names_long = char(M_.param_names_long, 'tauks');
M_.param_names = char(M_.param_names, 'tauws');
M_.param_names_tex = char(M_.param_names_tex, 'tauws');
M_.param_names_long = char(M_.param_names_long, 'tauws');
M_.param_names = char(M_.param_names, 'taxprofits');
M_.param_names_tex = char(M_.param_names_tex, 'taxprofits');
M_.param_names_long = char(M_.param_names_long, 'taxprofits');
M_.param_names = char(M_.param_names, 'tbd');
M_.param_names_tex = char(M_.param_names_tex, 'tbd');
M_.param_names_long = char(M_.param_names_long, 'tbd');
M_.param_names = char(M_.param_names, 'thetp');
M_.param_names_tex = char(M_.param_names_tex, 'thetp');
M_.param_names_long = char(M_.param_names_long, 'thetp');
M_.param_names = char(M_.param_names, 'thetw');
M_.param_names_tex = char(M_.param_names_tex, 'thetw');
M_.param_names_long = char(M_.param_names_long, 'thetw');
M_.param_names = char(M_.param_names, 'ups');
M_.param_names_tex = char(M_.param_names_tex, 'ups');
M_.param_names_long = char(M_.param_names_long, 'ups');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names_long = char(M_.param_names_long, 'ws');
M_.param_names = char(M_.param_names, 'ys');
M_.param_names_tex = char(M_.param_names_tex, 'ys');
M_.param_names_long = char(M_.param_names_long, 'ys');
M_.param_names = char(M_.param_names, 'habit');
M_.param_names_tex = char(M_.param_names_tex, 'habit');
M_.param_names_long = char(M_.param_names_long, 'habit');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'rspnd_y');
M_.param_names_tex = char(M_.param_names_tex, 'rspnd\_y');
M_.param_names_long = char(M_.param_names_long, 'rspnd_y');
M_.param_names = char(M_.param_names, 'rspnd_b');
M_.param_names_tex = char(M_.param_names_tex, 'rspnd\_b');
M_.param_names_long = char(M_.param_names_long, 'rspnd_b');
M_.param_names = char(M_.param_names, 'gzs');
M_.param_names_tex = char(M_.param_names_tex, 'gzs');
M_.param_names_long = char(M_.param_names_long, 'gzs');
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 31;
M_.param_nbr = 82;
M_.orig_endo_nbr = 31;
M_.aux_vars = [];
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('main_code_FGKR_static');
erase_compiled_function('main_code_FGKR_dynamic');
M_.lead_lag_incidence = [
 1 18 0;
 2 19 49;
 3 20 50;
 4 21 0;
 0 22 0;
 0 23 51;
 5 24 52;
 6 25 0;
 7 26 0;
 0 27 53;
 0 28 0;
 0 29 54;
 0 30 55;
 0 31 0;
 8 32 0;
 0 33 56;
 9 34 0;
 10 35 0;
 11 36 0;
 12 37 0;
 13 38 0;
 14 39 57;
 15 40 0;
 0 41 58;
 16 42 59;
 17 43 60;
 0 44 61;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;]';
M_.nstatic = 7;
M_.nfwrd   = 7;
M_.npred   = 11;
M_.nboth   = 6;
M_.nsfwrd   = 13;
M_.nspred   = 17;
M_.ndynamic   = 24;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(31, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(82, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 187;
M_.NNZDerivatives(2) = 509;
M_.NNZDerivatives(3) = 2120;
warning off ;
M_.params( 82 ) = 1.005;
gzs = M_.params( 82 );
M_.params( 37 ) = 2;
ome = M_.params( 37 );
M_.params( 3 ) = 0.9945*M_.params(82)^M_.params(37);
bet = M_.params( 3 );
M_.params( 75 ) = 1;
ups = M_.params( 75 );
M_.params( 74 ) = 0.75;
thetw = M_.params( 74 );
M_.params( 36 ) = 0;
nomw = M_.params( 36 );
M_.params( 9 ) = 21;
eps = M_.params( 9 );
M_.params( 78 ) = 0.75;
habit = M_.params( 78 );
M_.params( 46 ) = 0.01;
phiu2 = M_.params( 46 );
M_.params( 79 ) = 0.75;
kappa = M_.params( 79 );
M_.params( 1 ) = 0.36;
alph = M_.params( 1 );
M_.params( 8 ) = 0.010;
delt = M_.params( 8 );
M_.params( 11 ) = 0.010;
deltau = M_.params( 11 );
M_.params( 73 ) = 0.75;
thetp = M_.params( 73 );
M_.params( 10 ) = 21;
epsw = M_.params( 10 );
M_.params( 40 ) = 0.00;
phiprof = M_.params( 40 );
M_.params( 26 ) = 1.0045;
infls = M_.params( 26 );
M_.params( 42 ) = 0.7;
phiR = M_.params( 42 );
M_.params( 41 ) = 1.35;
phips = M_.params( 41 );
M_.params( 47 ) = 0.25;
phiy = M_.params( 47 );
M_.params( 5 ) = (-0.025);
phisigk = M_.params( 5 );
M_.params( 38 ) = 0.0005;
phibd = M_.params( 38 );
M_.params( 24 ) = 0.2;
gs = M_.params( 24 );
M_.params( 51 ) = 0.99;
rhog = M_.params( 51 );
M_.params( 19 ) = (-0.004);
gamgy = M_.params( 19 );
M_.params( 18 ) = (-0.008);
gamgb = M_.params( 18 );
M_.params( 63 ) = (-6.20);
siggs = M_.params( 63 );
M_.params( 53 ) = 0.92;
rhogg = M_.params( 53 );
M_.params( 13 ) = 0.18;
etag = M_.params( 13 );
M_.params( 69 ) = 0.38;
tauks = M_.params( 69 );
M_.params( 56 ) = 0.98;
rhok = M_.params( 56 );
M_.params( 21 ) = 0.040;
gamky = M_.params( 21 );
M_.params( 20 ) = 0.003;
gamkb = M_.params( 20 );
M_.params( 64 ) = (-4.90);
sigks = M_.params( 64 );
M_.params( 54 ) = 0.65;
rhogk = M_.params( 54 );
M_.params( 14 ) = 0.40;
etak = M_.params( 14 );
M_.params( 68 ) = 0.080;
taucs = M_.params( 68 );
M_.params( 49 ) = 0.99;
rhoc = M_.params( 49 );
M_.params( 17 ) = 0.001;
gamcy = M_.params( 17 );
M_.params( 16 ) = 1e-4;
gamcb = M_.params( 16 );
M_.params( 61 ) = (-7.12);
sigcs = M_.params( 61 );
M_.params( 52 ) = 0.73;
rhogc = M_.params( 52 );
M_.params( 12 ) = 0.45;
etac = M_.params( 12 );
M_.params( 70 ) = 0.21;
tauws = M_.params( 70 );
M_.params( 57 ) = 0.99;
rhow = M_.params( 57 );
M_.params( 23 ) = 0.040;
gamwy = M_.params( 23 );
M_.params( 22 ) = 0.003;
gamwb = M_.params( 22 );
M_.params( 66 ) = (-6.0);
sigws = M_.params( 66 );
M_.params( 55 ) = 0.46;
rhogw = M_.params( 55 );
M_.params( 15 ) = 0.82;
etaw = M_.params( 15 );
M_.params( 65 ) = 0.004086771438464067;
sigms = M_.params( 65 );
M_.params( 50 ) = 0.18;
rhod = M_.params( 50 );
M_.params( 62 ) = 0.08;
sigd = M_.params( 62 );
M_.params( 58 ) = 0.95;
rhoz = M_.params( 58 );
M_.params( 67 ) = 0.001;
sigz = M_.params( 67 );
M_.params( 6 ) = 1;
deductdepr = M_.params( 6 );
M_.params( 71 ) = 0;
taxprofits = M_.params( 71 );
M_.params( 7 ) = 0;
nom_depreciation = M_.params( 7 );
M_.params( 80 ) = 1.0;
rspnd_y = M_.params( 80 );
M_.params( 81 ) = 1.0;
rspnd_b = M_.params( 81 );
M_.params( 60 ) = M_.params(82)^M_.params(37)*M_.params(26)/M_.params(3);
Rs = M_.params( 60 );
M_.params( 35 ) = M_.params(3)*M_.params(11)*M_.params(69)*M_.params(6)/(M_.params(82)^M_.params(37)*M_.params(26)^M_.params(7))/(1-M_.params(3)*(1-M_.params(11))/M_.params(26)^M_.params(7)/M_.params(82)^M_.params(37));
miubs_lams = M_.params( 35 );
M_.params( 34 ) = 1-M_.params(35);
mius_lams = M_.params( 34 );
M_.params( 59 ) = M_.params(82)^M_.params(37)*(1-M_.params(3)*(1-M_.params(8))/M_.params(82)^M_.params(37))*M_.params(34)/M_.params(3)/(1-M_.params(69));
rks = M_.params( 59 );
M_.params( 31 ) = (M_.params(9)-1)/M_.params(9);
mcs = M_.params( 31 );
M_.params( 43 ) = M_.params(9)*M_.params(31)/M_.params(26)^2*M_.params(73)/(1-M_.params(73))/(1-M_.params(3)*M_.params(73)*M_.params(82)^(1-M_.params(37)));
phiRot = M_.params( 43 );
koverls = gzs*(rks/alph/mcs)^(1/(alph-1)); 
M_.params( 76 ) = M_.params(31)*(1-M_.params(1))*koverls^M_.params(1)/M_.params(82)^M_.params(1);
ws = M_.params( 76 );
lk      = (1-alph)*rks/alph/ws/gzs ;
M_.params( 25 ) = 0.3333333333333333;
hs = M_.params( 25 );
M_.params( 77 ) = lk^(-M_.params(1))*M_.params(25)/M_.params(82)^M_.params(1)-M_.params(40);
ys = M_.params( 77 );
M_.params( 28 ) = M_.params(25)/lk;
ks = M_.params( 28 );
M_.params( 27 ) = (1-(1-M_.params(8))/M_.params(82))*M_.params(28);
invs = M_.params( 27 );
M_.params( 29 ) = M_.params(26)^M_.params(7)/(M_.params(26)^M_.params(7)-(1-M_.params(11))/M_.params(82))*M_.params(27);
kbs = M_.params( 29 );
M_.params( 4 ) = M_.params(77)-M_.params(77)*M_.params(24)-M_.params(27);
cs = M_.params( 4 );
M_.params( 30 ) = (1/(1-M_.params(78)/M_.params(82))^M_.params(37)-M_.params(3)*M_.params(78)/(M_.params(82)-M_.params(78))^M_.params(37))/M_.params(4)^M_.params(37)/(1+M_.params(68));
lams = M_.params( 30 );
M_.params( 32 ) = M_.params(34)*M_.params(30);
mius = M_.params( 32 );
M_.params( 33 ) = M_.params(35)*M_.params(30);
miubs = M_.params( 33 );
M_.params( 39 ) = M_.params(30)*M_.params(76)*(M_.params(10)-1)*(1-M_.params(70))/M_.params(10)/M_.params(25)^M_.params(75);
phil = M_.params( 39 );
utils   = 1 ;
M_.params( 45 ) = (1-M_.params(69))*M_.params(30)*M_.params(59)/M_.params(32);
phiu1 = M_.params( 45 );
M_.params( 2 ) = M_.params(77)*1.6;
bds = M_.params( 2 );
M_.params( 48 ) = M_.params(77)-M_.params(25)*M_.params(76)-M_.params(28)*M_.params(59)*utils/M_.params(82)-M_.params(40);
profs = M_.params( 48 );
M_.params( 72 ) = M_.params(77)*M_.params(24)-(M_.params(70)*M_.params(25)*M_.params(76)+M_.params(69)*M_.params(28)*(M_.params(59)*utils-M_.params(11)*M_.params(6)/M_.params(26)^M_.params(7))/M_.params(82)+M_.params(69)*M_.params(71)*M_.params(48)+M_.params(4)*M_.params(68)+M_.params(2)*(1-M_.params(60)/M_.params(26)/M_.params(82)));
tbd = M_.params( 72 );
M_.params( 44 ) = M_.params(10)*M_.params(39)*M_.params(25)^(1+M_.params(75))*M_.params(74)*(1+M_.params(10)*M_.params(75))/M_.params(77)/M_.params(30)/(1-M_.params(82)^(1-M_.params(37))*M_.params(3)*M_.params(74))/(1-M_.params(74))/M_.params(26)^M_.params(36)/M_.params(82)^2;
phiRotw = M_.params( 44 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 2 ) = log(M_.params(4));
oo_.steady_state( 26 ) = log(M_.params(77));
oo_.steady_state( 16 ) = log(M_.params(59));
oo_.steady_state( 4 ) = M_.params(24);
oo_.steady_state( 8 ) = log(M_.params(28));
oo_.steady_state( 9 ) = log(M_.params(29));
oo_.steady_state( 5 ) = log(M_.params(25));
oo_.steady_state( 11 ) = log(M_.params(31));
oo_.steady_state( 25 ) = log(M_.params(76));
oo_.steady_state( 6 ) = log(M_.params(26));
oo_.steady_state( 15 ) = log(M_.params(60));
oo_.steady_state( 22 ) = M_.params(69);
oo_.steady_state( 23 ) = M_.params(70);
oo_.steady_state( 21 ) = M_.params(68);
oo_.steady_state( 10 ) = log(M_.params(30));
oo_.steady_state( 12 ) = log(M_.params(32));
oo_.steady_state( 13 ) = M_.params(33);
oo_.steady_state( 7 ) = log(M_.params(27));
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 19 ) = M_.params(64);
oo_.steady_state( 20 ) = M_.params(66);
oo_.steady_state( 17 ) = M_.params(61);
oo_.steady_state( 18 ) = M_.params(63);
oo_.steady_state( 14 ) = M_.params(48);
oo_.steady_state( 1 ) = M_.params(2);
oo_.steady_state( 27 ) = log(M_.params(82));
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 28 ) = log(M_.params(82));
oo_.steady_state( 29 ) = log(M_.params(82));
oo_.steady_state( 30 ) = log(M_.params(82));
oo_.steady_state( 31 ) = log(M_.params(82));
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = M_.params(62)^2;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(5, 5) = M_.params(65)^2;
M_.Sigma_e(6, 6) = 1;
M_.Sigma_e(7, 7) = M_.params(67)^2;
M_.Sigma_e(8, 8) = 1;
M_.Sigma_e(9, 9) = 1;
M_.Sigma_e(10, 10) = 1;
M_.Sigma_e(11, 11) = 1;
options_.irf = 0;
options_.nomoments = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
info = stoch_simul(var_list_);
f_11 = [oo_.dr.ghx oo_.dr.ghu];
options_.irf = 0;
options_.nomoments = 1;
options_.noprint = 1;
options_.order = 3;
var_list_=[];
info = stoch_simul(var_list_);
optPruning.numSim         = 1;                    
optPruning.seedNum        = 1;  
optPruning.IRFlength      = 21;
optPruning.computeIRF     = 0;
optPruning.computeMoments = 0;
optPruning.orderApp       = options_.order;   
tic                                   
outDynare = RunDynarePruning(optPruning,oo_,M_,f_11);
toc
outDynare.opt
nx      = size(outDynare.hv,1);
ny      = size(outDynare.gv,1);       
ne      = size(outDynare.eta,2);      
HHxxtil  = 1/2*reshape(outDynare.hvv,nx,nx^2);
HHxxxtil = 1/6*reshape(outDynare.hvvv,nx,nx^3);
GGxxtil  = 1/2*reshape(outDynare.gvv,ny,nx^2);
GGxxxtil = 1/6*reshape(outDynare.gvvv,ny,nx^3);
numSimirfs = 2000 ;
optPruning.numSim = 1000 ;
xfpath=zeros(nx,optPruning.numSim+numSimirfs);
xspath=zeros(nx,optPruning.numSim+numSimirfs);
xrdpath=zeros(nx,optPruning.numSim+numSimirfs);
for jx=2:optPruning.numSim+numSimirfs ;
jx;
AA          =   kron(xfpath(:,jx-1),xfpath(:,jx-1)) ;
xfpath(:,jx)=   outDynare.hv*xfpath(:,jx-1) ;
xspath(:,jx)=   outDynare.hv*xspath(:,jx-1) + HHxxtil*AA + 0.5*outDynare.hss;
xrdpath(:,jx)=  outDynare.hv*xrdpath(:,jx-1)+ 2*HHxxtil*(kron(xfpath(:,jx-1),xspath(:,jx-1)))+HHxxxtil*(kron(AA,xfpath(:,jx-1))) + 3/6*outDynare.hssv*xfpath(:,jx-1) + 1/6*outDynare.hsss;
end
xfpath(:,1)=xfpath(:,optPruning.numSim+numSimirfs);
xspath(:,1)=xspath(:,optPruning.numSim+numSimirfs);
xrdpath(:,1)=xrdpath(:,optPruning.numSim+numSimirfs);
randn('seed',123430);
xfpath(:,2:optPruning.numSim+numSimirfs)=zeros(nx,optPruning.numSim+numSimirfs-1);
xspath(:,2:optPruning.numSim+numSimirfs)=zeros(nx,optPruning.numSim+numSimirfs-1);
xrdpath(:,2:optPruning.numSim+numSimirfs)=zeros(nx,optPruning.numSim+numSimirfs-1);
y3rdpath(:,2:optPruning.numSim+numSimirfs)=zeros(ny,optPruning.numSim+numSimirfs-1);
epsilons       = randn(ne,optPruning.numSim+numSimirfs);
for jx=2:optPruning.numSim+numSimirfs ;
jx;
innovacion  =   epsilons(:,jx) ;
AA          =   kron(xfpath(:,jx-1),xfpath(:,jx-1)) ;
AAsf         =   kron(xfpath(:,jx-1),xspath(:,jx-1)) ;
AAA          =   kron(AA,xfpath(:,jx-1)) ;
xfpath(:,jx)=   outDynare.hv*xfpath(:,jx-1) + outDynare.eta*innovacion;
xspath(:,jx)=   outDynare.hv*xspath(:,jx-1) + HHxxtil*AA + 0.5*outDynare.hss;
xrdpath(:,jx)=  outDynare.hv*xrdpath(:,jx-1)+ 2*HHxxtil*(kron(xfpath(:,jx-1),xspath(:,jx-1)))+HHxxxtil*(kron(AA,xfpath(:,jx-1))) + 3/6*outDynare.hssv*xfpath(:,jx-1) + 1/6*outDynare.hsss;
y3rdpath(:,jx) = outDynare.gv*(xfpath(:,jx-1)+xspath(:,jx-1)+xrdpath(:,jx-1)) + GGxxtil*(AA+2*AAsf) + GGxxxtil*AAA + 0.5*outDynare.gss + 3/6*outDynare.gssv*xfpath(:,jx-1) + 1/6*outDynare.gsss ;
end
x3formoments = xfpath + xspath + xrdpath ;
locx = 5 ;
x3formomentsshort = x3formoments(:,optPruning.numSim+numSimirfs-numSimirfs+1:optPruning.numSim+numSimirfs) ;
hpx = x3formomentsshort;
hpx(locx(1),:) = Rs*exp(hpx(locx(1),:));
disp(sprintf('std:        %6.5f ',100*std(hpx(locx,:)')))
y3rdpathformoments = y3rdpath(:,optPruning.numSim+numSimirfs-numSimirfs+1:optPruning.numSim+numSimirfs) ;
locy = [4 5 6 7 1 13 2 8];
varinlevels         = zeros(4,size(y3rdpathformoments,2)) ;
varinlevels(:,1)    = 1 ;
for tmx = 2:size(y3rdpathformoments,2) ;
varinlevels(:,tmx) = varinlevels(:,tmx-1) + y3rdpathformoments(locy(1:4),tmx) ;
end 
hpy = varinlevels - hpf(varinlevels',1600)';
varalrlevels        = y3rdpathformoments(locy(5:8),:) ;
hpy = [hpy;varalrlevels(1:3,:) - hpf(varalrlevels(1:3,:)',1600)'];
hpy = [hpy;varalrlevels(4,:)];
hpy(8,:) = infls*exp(hpy(8,:));
outDynare.label_y(locy)'
disp(sprintf('std:        %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f', 100*std(hpy(:,:)')))
basu = [] ;
for jk = 1:length(locy)
basi = corrcoef(hpy(jk,1:end-1)',hpy(jk,2:end)') ;
basu(jk) = basi(2,1) ;
end
disp(sprintf('AR:         %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f', basu))
tema = corrcoef([hpy(:,:)']);
disp(sprintf('corr coeff: %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f %6.5f', tema(2:end,1)'))
basur = corrcoef(hpy(1,:)',hpx(locx,:)') ;
disp(sprintf('Corr R with output:  %6.5f ',basur(2,1))) ;
numperiodsrfs=optPruning.IRFlength+1;
xfirf=zeros(nx,numSimirfs,numperiodsrfs);
xsirf=zeros(nx,numSimirfs,numperiodsrfs);
xrdirf=zeros(nx,numSimirfs,numperiodsrfs);
xfirfref=zeros(nx,numSimirfs,numperiodsrfs);
xsirfref=zeros(nx,numSimirfs,numperiodsrfs);
xrdirfref=zeros(nx,numSimirfs,numperiodsrfs);
y3rdirf=zeros(ny,numSimirfs,numperiodsrfs);
y3rdirfref=zeros(ny,numSimirfs,numperiodsrfs);
xfirf(:,:,1)    = xfpath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
xfirfref(:,:,1) = xfpath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
xsirf(:,:,1)    = xspath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
xsirfref(:,:,1) = xspath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
xrdirf(:,:,1)   = xrdpath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
xrdirfref(:,:,1)= xrdpath(:,optPruning.numSim+1:optPruning.numSim+numSimirfs);
epsValues       = randn(ne,numSimirfs,numperiodsrfs);
locsigma =  10 ;
for j=2:numperiodsrfs;
j
for i=1:numSimirfs;
innovacionref   =   epsValues(:,i,j);
innovacion      =   innovacionref;
if j == 2  
innovacion(locsigma,1) = 2 ;
end
AA           =   kron(xfirf(:,i,j-1),xfirf(:,i,j-1));
AAsf         =   kron(xfirf(:,i,j-1),xsirf(:,i,j-1)) ;
AAA          =   kron(AA,xfirf(:,i,j-1)) ;
xfirf(:,i,j) =   outDynare.hv*xfirf(:,i,j-1) + outDynare.eta*innovacion;
xsirf(:,i,j) =   outDynare.hv*xsirf(:,i,j-1) + HHxxtil*AA+0.5*outDynare.hss;
xrdirf(:,i,j)=   outDynare.hv*xrdirf(:,i,j-1) + 2*HHxxtil*AAsf + HHxxxtil*AAA + 3/6*outDynare.hssv*xfirf(:,i,j-1) + 1/6*outDynare.hsss;
y3rdirf(:,i,j) = outDynare.gv*(xfirf(:,i,j-1)+xsirf(:,i,j-1)+xrdirf(:,i,j-1)) + GGxxtil*(AA+2*AAsf) + GGxxxtil*AAA + 0.5*outDynare.gss + 3/6*outDynare.gssv*xfirf(:,i,j-1) + 1/6*outDynare.gsss ;
AAref             =   kron(xfirfref(:,i,j-1),xfirfref(:,i,j-1));
AAsfref           =   kron(xfirfref(:,i,j-1),xsirfref(:,i,j-1)) ;
AAAref            =   kron(AAref,xfirfref(:,i,j-1)) ;
xfirfref(:,i,j)   =   outDynare.hv*xfirfref(:,i,j-1) + outDynare.eta*innovacionref;
xsirfref(:,i,j)   =   outDynare.hv*xsirfref(:,i,j-1) + HHxxtil*AAref + 0.5*outDynare.hss;
xrdirfref(:,i,j)  =   outDynare.hv*xrdirfref(:,i,j-1) + 2*HHxxtil*AAsfref + HHxxxtil*AAAref + 3/6*outDynare.hssv*xfirfref(:,i,j-1) + 1/6*outDynare.hsss;
y3rdirfref(:,i,j) =   outDynare.gv*(xfirfref(:,i,j-1)+xsirfref(:,i,j-1)+xrdirfref(:,i,j-1)) + GGxxtil*(AAref+2*AAsfref) + GGxxxtil*AAAref + 0.5*outDynare.gss + 3/6*outDynare.gssv*xfirfref(:,i,j-1) + 1/6*outDynare.gsss ;
end
end
irfxf=zeros(nx,numperiodsrfs);
irfxs=zeros(nx,numperiodsrfs);
irfxrd=zeros(nx,numperiodsrfs);
for j=1:numperiodsrfs;
irfxf(:,j)   = mean(xfirf(:,:,j),2)-mean(xfirfref(:,:,j),2);
irfxs(:,j)   = mean(xsirf(:,:,j),2)-mean(xsirfref(:,:,j),2);
irfxrd(:,j)  = mean(xrdirf(:,:,j),2)-mean(xrdirfref(:,:,j),2);
irfy3rd(:,j) = mean(y3rdirf(:,:,j),2)-mean(y3rdirfref(:,:,j),2);
end
for j=1:numperiodsrfs;
irfxf(locx,j)   = mean(exp(xfirf(locx,:,j)),2)-mean(exp(xfirfref(locx,:,j)),2);
irfxs(locx,j)   = mean(exp(xsirf(locx,:,j)),2)-mean(exp(xsirfref(locx,:,j)),2);
irfxrd(locx,j)  = mean(exp(xrdirf(locx,:,j)),2)-mean(exp(xrdirfref(locx,:,j)),2);
irfy3rd(8,j) = mean(exp(y3rdirf(8,:,j)),2)-mean(exp(y3rdirfref(8,:,j)),2);
end
irf3rd=irfxf+irfxs+irfxrd;
irf2nd=irfxf+irfxs;
irf1st=irfxf;
for ix = 1:size(locy,2);
irf3rds=smooth(irfy3rd(locy(ix),:)) ;   
if locy(ix) == 8
irf3rds = 400*(irf3rds)*infls;
inflat  = irf3rds ;
end
if ix <= 4
yirf(ix,:) = 100*cumsum(irf3rds(2:end)) ;
else
yirf(ix,:) = 100*irf3rds(2:end) ;
end
end
for ix = 1:4 ;
irf3rds=smooth(irfy3rd(locy(ix),:)) ;   
end
yirf = [yirf(1:3,:);yirf(5,:);yirf(7,:);yirf(8,:);400*100*Rs*smooth(irf3rd(locx,2:end))';yirf(4,:)];
yirf = yirf(:,1:end) ;
which_ = strvcat('Output','Consumption','Investment','Hours','Marginal Cost','Inflation (BPS)','Nominal Rate (BPS)','Wages') ;
endogz_ = which_ ;
fignum = 2 ;
print_name_= ['taxkcapvola_2std'] ;
make_irfs(yirf, which_, endogz_, fignum, print_name_)
save('main_code_FGKR_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('main_code_FGKR_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('main_code_FGKR_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('main_code_FGKR_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('main_code_FGKR_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
