%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GHP16';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GHP16.log');
M_.exo_names = 'interest_';
M_.exo_names_tex = 'interest\_';
M_.exo_names_long = 'interest_';
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'C';
M_.endo_names_tex = 'C';
M_.endo_names_long = 'C';
M_.endo_names = char(M_.endo_names, 'C_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_m');
M_.endo_names_long = char(M_.endo_names_long, 'C_m');
M_.endo_names = char(M_.endo_names, 'C_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_n');
M_.endo_names_long = char(M_.endo_names_long, 'C_n');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'K_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_m');
M_.endo_names_long = char(M_.endo_names_long, 'K_m');
M_.endo_names = char(M_.endo_names, 'K_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_n');
M_.endo_names_long = char(M_.endo_names_long, 'K_n');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'W');
M_.endo_names_tex = char(M_.endo_names_tex, 'W');
M_.endo_names_long = char(M_.endo_names_long, 'W');
M_.endo_names = char(M_.endo_names, 'h_m');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_m');
M_.endo_names_long = char(M_.endo_names_long, 'h_m');
M_.endo_names = char(M_.endo_names, 'h_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_n');
M_.endo_names_long = char(M_.endo_names_long, 'h_n');
M_.endo_names = char(M_.endo_names, 'r_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_k');
M_.endo_names_long = char(M_.endo_names_long, 'r_k');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'x_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_1');
M_.endo_names_long = char(M_.endo_names_long, 'x_1');
M_.endo_names = char(M_.endo_names, 'x_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_2');
M_.endo_names_long = char(M_.endo_names_long, 'x_2');
M_.endo_names = char(M_.endo_names, 'RMC');
M_.endo_names_tex = char(M_.endo_names_tex, 'RMC');
M_.endo_names_long = char(M_.endo_names_long, 'RMC');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'C_mf');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_mf');
M_.endo_names_long = char(M_.endo_names_long, 'C_mf');
M_.endo_names = char(M_.endo_names, 'C_nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_nf');
M_.endo_names_long = char(M_.endo_names_long, 'C_nf');
M_.endo_names = char(M_.endo_names, 'Kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kf');
M_.endo_names_long = char(M_.endo_names_long, 'Kf');
M_.endo_names = char(M_.endo_names, 'K_mf');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_mf');
M_.endo_names_long = char(M_.endo_names_long, 'K_mf');
M_.endo_names = char(M_.endo_names, 'K_nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_nf');
M_.endo_names_long = char(M_.endo_names_long, 'K_nf');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'Wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Wf');
M_.endo_names_long = char(M_.endo_names_long, 'Wf');
M_.endo_names = char(M_.endo_names, 'h_mf');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_mf');
M_.endo_names_long = char(M_.endo_names_long, 'h_mf');
M_.endo_names = char(M_.endo_names, 'h_nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_nf');
M_.endo_names_long = char(M_.endo_names_long, 'h_nf');
M_.endo_names = char(M_.endo_names, 'r_kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_kf');
M_.endo_names_long = char(M_.endo_names_long, 'r_kf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'lambdaf');
M_.endo_names = char(M_.endo_names, 'inflf');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflf');
M_.endo_names_long = char(M_.endo_names_long, 'inflf');
M_.endo_names = char(M_.endo_names, 'inflstarf');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstarf');
M_.endo_names_long = char(M_.endo_names_long, 'inflstarf');
M_.endo_names = char(M_.endo_names, 'x_1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_1f');
M_.endo_names_long = char(M_.endo_names_long, 'x_1f');
M_.endo_names = char(M_.endo_names, 'x_2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_2f');
M_.endo_names_long = char(M_.endo_names_long, 'x_2f');
M_.endo_names = char(M_.endo_names, 'RMCf');
M_.endo_names_tex = char(M_.endo_names_tex, 'RMCf');
M_.endo_names_long = char(M_.endo_names_long, 'RMCf');
M_.endo_names = char(M_.endo_names, 'Gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gf');
M_.endo_names_long = char(M_.endo_names_long, 'Gf');
M_.endo_names = char(M_.endo_names, 'gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gf');
M_.endo_names_long = char(M_.endo_names_long, 'gf');
M_.endo_names = char(M_.endo_names, 'Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yf');
M_.endo_names_long = char(M_.endo_names_long, 'Yf');
M_.endo_names = char(M_.endo_names, 'Df');
M_.endo_names_tex = char(M_.endo_names_tex, 'Df');
M_.endo_names_long = char(M_.endo_names_long, 'Df');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'e_gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_gf');
M_.endo_names_long = char(M_.endo_names_long, 'e_gf');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'g_ratio');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ratio');
M_.param_names_long = char(M_.param_names_long, 'g_ratio');
M_.param_names = char(M_.param_names, 'taup');
M_.param_names_tex = char(M_.param_names_tex, 'taup');
M_.param_names_long = char(M_.param_names_long, 'taup');
M_.param_names = char(M_.param_names, 'b_1');
M_.param_names_tex = char(M_.param_names_tex, 'b\_1');
M_.param_names_long = char(M_.param_names_long, 'b_1');
M_.param_names = char(M_.param_names, 'alpha_1');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_1');
M_.param_names_long = char(M_.param_names_long, 'alpha_1');
M_.param_names = char(M_.param_names, 'alpha_2');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_2');
M_.param_names_long = char(M_.param_names_long, 'alpha_2');
M_.param_names = char(M_.param_names, 'alpha_3');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_3');
M_.param_names_long = char(M_.param_names_long, 'alpha_3');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'phi_infl');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_infl');
M_.param_names_long = char(M_.param_names_long, 'phi_infl');
M_.param_names = char(M_.param_names, 'RMC_ss');
M_.param_names_tex = char(M_.param_names_tex, 'RMC\_ss');
M_.param_names_long = char(M_.param_names_long, 'RMC_ss');
M_.param_names = char(M_.param_names, 'h_n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_n\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_n_ss');
M_.param_names = char(M_.param_names, 'h_m_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_m\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_m_ss');
M_.param_names = char(M_.param_names, 'kn_y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'kn\_y\_ss');
M_.param_names_long = char(M_.param_names_long, 'kn_y_ss');
M_.param_names = char(M_.param_names, 'km_y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'km\_y\_ss');
M_.param_names_long = char(M_.param_names_long, 'km_y_ss');
M_.param_names = char(M_.param_names, 'i_ratio_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_ratio\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_ratio_ss');
M_.param_names = char(M_.param_names, 'r_k_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r\_k\_ss');
M_.param_names_long = char(M_.param_names_long, 'r_k_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'C_m_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_m\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_m_ss');
M_.param_names = char(M_.param_names, 'C_n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_n\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_n_ss');
M_.param_names = char(M_.param_names, 'W_ss');
M_.param_names_tex = char(M_.param_names_tex, 'W\_ss');
M_.param_names_long = char(M_.param_names_long, 'W_ss');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_names = char(M_.param_names, 'l_ss');
M_.param_names_tex = char(M_.param_names_tex, 'l\_ss');
M_.param_names_long = char(M_.param_names_long, 'l_ss');
M_.param_names = char(M_.param_names, 'thetaf');
M_.param_names_tex = char(M_.param_names_tex, 'thetaf');
M_.param_names_long = char(M_.param_names_long, 'thetaf');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 54;
M_.param_nbr = 65;
M_.orig_endo_nbr = 52;
M_.aux_vars(1).endo_index = 53;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 14;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 54;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 14;
M_.aux_vars(2).orig_lead_lag = -2;
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_GHP16_static');
erase_compiled_function('NK_GHP16_dynamic');
M_.orig_eq_nbr = 52;
M_.eq_nbr = 54;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 14 0;
 0 15 0;
 0 16 0;
 1 17 68;
 2 18 0;
 3 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 69;
 0 25 0;
 0 26 70;
 4 27 71;
 0 28 0;
 0 29 72;
 0 30 73;
 0 31 0;
 0 32 0;
 5 33 0;
 0 34 0;
 6 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 7 39 74;
 8 40 0;
 9 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 75;
 0 47 0;
 0 48 76;
 0 49 77;
 0 50 0;
 0 51 78;
 0 52 79;
 0 53 0;
 0 54 0;
 10 55 0;
 0 56 0;
 11 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 12 66 0;
 13 67 0;]';
M_.nstatic = 32;
M_.nfwrd   = 9;
M_.npred   = 10;
M_.nboth   = 3;
M_.nsfwrd   = 12;
M_.nspred   = 13;
M_.ndynamic   = 22;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(54, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(65, 1);
M_.NNZDerivatives = [206; -1; -1];
M_.params( 44 ) = 0.99;
beta = M_.params( 44 );
M_.params( 46 ) = 11;
eps = M_.params( 46 );
M_.params( 47 ) = 0.75;
theta = M_.params( 47 );
M_.params( 65 ) = 0.00000001;
thetaf = M_.params( 65 );
M_.params( 42 ) = 252.5;
xi = M_.params( 42 );
M_.params( 45 ) = 2;
sigma = M_.params( 45 );
M_.params( 50 ) = 0.8;
rho_g = M_.params( 50 );
M_.params( 41 ) = 0.0241;
delta = M_.params( 41 );
M_.params( 48 ) = 0;
tau = M_.params( 48 );
M_.params( 36 ) = 1/M_.params(46);
taup = M_.params( 36 );
M_.params( 51 ) = 1.5;
phi_infl = M_.params( 51 );
M_.params( 35 ) = 0.18;
g_ratio = M_.params( 35 );
M_.params( 52 ) = (M_.params(46)-1)/(M_.params(46)*(1-M_.params(48)));
RMC_ss = M_.params( 52 );
M_.params( 53 ) = 0.19;
h_n_ss = M_.params( 53 );
M_.params( 54 ) = 0.33;
h_m_ss = M_.params( 54 );
M_.params( 55 ) = 6.76;
kn_y_ss = M_.params( 55 );
M_.params( 56 ) = 5.16;
km_y_ss = M_.params( 56 );
M_.params( 37 ) = 0.636;
b_1 = M_.params( 37 );
M_.params( 57 ) = M_.params(41);
i_ratio_ss = M_.params( 57 );
M_.params( 58 ) = (1-M_.params(44)*(1-M_.params(41)))/M_.params(44);
r_k_ss = M_.params( 58 );
M_.params( 40 ) = M_.params(58)*M_.params(56);
alpha_3 = M_.params( 40 );
M_.params( 59 ) = M_.params(56)^(M_.params(40)/(1-M_.params(40)))*M_.params(54);
Y_ss = M_.params( 59 );
M_.params( 60 ) = M_.params(59)*(1-M_.params(35)-M_.params(41)*(M_.params(56)+M_.params(55)));
C_m_ss = M_.params( 60 );
M_.params( 49 ) = M_.params(59)*M_.params(35);
G_ss = M_.params( 49 );
M_.params( 62 ) = (1-M_.params(40))*M_.params(59)/M_.params(54);
W_ss = M_.params( 62 );
M_.params( 39 ) = M_.params(59)*M_.params(58)*M_.params(55)/(M_.params(59)*M_.params(58)*M_.params(55)+M_.params(62)*M_.params(53));
alpha_2 = M_.params( 39 );
M_.params( 61 ) = (M_.params(59)*M_.params(55))^M_.params(39)*M_.params(53)^(1-M_.params(39));
C_n_ss = M_.params( 61 );
M_.params( 38 ) = (1-M_.params(39))*M_.params(61)^M_.params(37)/(M_.params(62)*M_.params(53))/((1-M_.params(39))*M_.params(61)^M_.params(37)/(M_.params(62)*M_.params(53))+M_.params(60)^(M_.params(37)-1));
alpha_1 = M_.params( 38 );
M_.params( 63 ) = M_.params(54)+M_.params(53);
h_ss = M_.params( 63 );
M_.params( 64 ) = 1-M_.params(63);
l_ss = M_.params( 64 );
M_.params( 43 ) = (M_.params(62)*M_.params(53)+(1-M_.params(39))*M_.params(60))/(M_.params(62)*M_.params(53)+(1-M_.params(39))*(M_.params(60)+M_.params(62)*M_.params(64)));
b = M_.params( 43 );
C_ss        =   (alpha_1*C_m_ss^b_1+(1-alpha_1)*C_n_ss^b_1)^(1/b_1);
I_ss        =    i_ratio_ss*(kn_y_ss+km_y_ss)*Y_ss;
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end  
cd(thispath);  
M_.params( 34 ) = 1/M_.params(35);
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 21 ) = log(M_.params(59));
oo_.steady_state( 43 ) = oo_.steady_state(21);
oo_.steady_state( 19 ) = log(M_.params(49));
oo_.steady_state( 41 ) = oo_.steady_state(19);
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 5 ) = log(M_.params(56)*M_.params(59));
oo_.steady_state( 27 ) = oo_.steady_state(5);
oo_.steady_state( 6 ) = log(M_.params(59)*M_.params(55));
oo_.steady_state( 28 ) = oo_.steady_state(6);
oo_.steady_state( 4 ) = log(M_.params(59)*M_.params(55)+M_.params(56)*M_.params(59));
oo_.steady_state( 26 ) = oo_.steady_state(4);
oo_.steady_state( 9 ) = log(M_.params(54));
oo_.steady_state( 31 ) = oo_.steady_state(9);
oo_.steady_state( 10 ) = log(M_.params(53));
oo_.steady_state( 32 ) = oo_.steady_state(10);
oo_.steady_state( 8 ) = log(M_.params(62));
oo_.steady_state( 30 ) = oo_.steady_state(8);
oo_.steady_state( 7 ) = log(I_ss);
oo_.steady_state( 29 ) = oo_.steady_state(7);
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 1 ) = log(C_ss);
oo_.steady_state( 23 ) = oo_.steady_state(1);
oo_.steady_state( 2 ) = log(M_.params(60));
oo_.steady_state( 24 ) = oo_.steady_state(2);
oo_.steady_state( 3 ) = log(M_.params(61));
oo_.steady_state( 25 ) = oo_.steady_state(3);
oo_.steady_state( 11 ) = log(M_.params(58));
oo_.steady_state( 33 ) = oo_.steady_state(11);
oo_.steady_state( 13 ) = log(M_.params(60)^(M_.params(37)-1)*M_.params(43)*M_.params(38)*(1-M_.params(53)-M_.params(54))^((1-M_.params(43))*(1-M_.params(45)))*C_ss^(M_.params(43)*(1-M_.params(45))-M_.params(37)));
oo_.steady_state( 35 ) = oo_.steady_state(13);
oo_.steady_state( 12 ) = log(1/M_.params(44));
oo_.steady_state( 34 ) = log(1/M_.params(44));
oo_.steady_state( 18 ) = log(M_.params(52));
oo_.steady_state( 40 ) = oo_.steady_state(18);
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 16 ) = log((M_.params(49)+M_.params(60)+I_ss)/(1-M_.params(44)*M_.params(47)));
oo_.steady_state( 38 ) = log((M_.params(49)+M_.params(60)+I_ss)/(1-M_.params(44)*M_.params(65)));
oo_.steady_state( 17 ) = oo_.steady_state(16);
oo_.steady_state( 39 ) = oo_.steady_state(38);
oo_.steady_state( 47 ) = 0;
oo_.steady_state( 48 ) = 0;
oo_.steady_state( 49 ) = 4*oo_.steady_state(14);
oo_.steady_state( 50 ) = oo_.steady_state(21)-oo_.steady_state(43);
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 52 ) = 0;
oo_.steady_state(53)=oo_.steady_state(14);
oo_.steady_state(54)=oo_.steady_state(53);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
steady;
resid;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = (M_.params(34))^2;
options_.irf = 40;
options_.nograph = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('NK_GHP16_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GHP16_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GHP16_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GHP16_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GHP16_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GHP16_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GHP16_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
