%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GK13_rep';
M_.dynare_version = '4.5.3';
oo_.dynare_version = '4.5.3';
options_.dynare_version = '4.5.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GK13_rep.log');
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'e_ksi');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ksi');
M_.exo_names_long = char(M_.exo_names_long, 'e_ksi');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_Ne');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Ne');
M_.exo_names_long = char(M_.exo_names_long, 'e_Ne');
M_.exo_names = char(M_.exo_names, 'e_ir');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ir');
M_.exo_names_long = char(M_.exo_names_long, 'e_ir');
M_.exo_names = char(M_.exo_names, 'e_psi');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_psi');
M_.exo_names_long = char(M_.exo_names_long, 'e_psi');
M_.exo_names = char(M_.exo_names, 'e_Gamma');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Gamma');
M_.exo_names_long = char(M_.exo_names_long, 'e_Gamma');
M_.exo_names = char(M_.exo_names, 'e_zlb');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_zlb');
M_.exo_names_long = char(M_.exo_names_long, 'e_zlb');
M_.endo_names = 'Ym';
M_.endo_names_tex = 'Ym';
M_.endo_names_long = 'Ym';
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Keff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Keff');
M_.endo_names_long = char(M_.endo_names_long, 'Keff');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ne');
M_.endo_names_long = char(M_.endo_names_long, 'Ne');
M_.endo_names = char(M_.endo_names, 'Nn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nn');
M_.endo_names_long = char(M_.endo_names_long, 'Nn');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'qn');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn');
M_.endo_names_long = char(M_.endo_names_long, 'qn');
M_.endo_names = char(M_.endo_names, 'mu_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_s');
M_.endo_names_long = char(M_.endo_names_long, 'mu_s');
M_.endo_names = char(M_.endo_names, 'mu_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_b');
M_.endo_names_long = char(M_.endo_names_long, 'mu_b');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'Omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'Omega');
M_.endo_names_long = char(M_.endo_names_long, 'Omega');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'ir');
M_.endo_names_tex = char(M_.endo_names_tex, 'ir');
M_.endo_names_long = char(M_.endo_names_long, 'ir');
M_.endo_names = char(M_.endo_names, 'ib');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib');
M_.endo_names_long = char(M_.endo_names_long, 'ib');
M_.endo_names = char(M_.endo_names, 'prem_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_K');
M_.endo_names_long = char(M_.endo_names_long, 'prem_K');
M_.endo_names = char(M_.endo_names, 'prem_B');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_B');
M_.endo_names_long = char(M_.endo_names_long, 'prem_B');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'qn_rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn\_rf');
M_.endo_names_long = char(M_.endo_names_long, 'qn_rf');
M_.endo_names = char(M_.endo_names, 'iir');
M_.endo_names_tex = char(M_.endo_names_tex, 'iir');
M_.endo_names_long = char(M_.endo_names_long, 'iir');
M_.endo_names = char(M_.endo_names, 'prem_ib');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_ib');
M_.endo_names_long = char(M_.endo_names_long, 'prem_ib');
M_.endo_names = char(M_.endo_names, 'rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rb');
M_.endo_names_long = char(M_.endo_names_long, 'rb');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'qB');
M_.endo_names_tex = char(M_.endo_names_tex, 'qB');
M_.endo_names_long = char(M_.endo_names_long, 'qB');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'Kb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kb');
M_.endo_names_long = char(M_.endo_names_long, 'Kb');
M_.endo_names = char(M_.endo_names, 'Bb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bb');
M_.endo_names_long = char(M_.endo_names_long, 'Bb');
M_.endo_names = char(M_.endo_names, 'Dep');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dep');
M_.endo_names_long = char(M_.endo_names_long, 'Dep');
M_.endo_names = char(M_.endo_names, 'Nbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nbook');
M_.endo_names_long = char(M_.endo_names_long, 'Nbook');
M_.endo_names = char(M_.endo_names, 'phibook');
M_.endo_names_tex = char(M_.endo_names_tex, 'phibook');
M_.endo_names_long = char(M_.endo_names_long, 'phibook');
M_.endo_names = char(M_.endo_names, 'Kbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kbook');
M_.endo_names_long = char(M_.endo_names_long, 'Kbook');
M_.endo_names = char(M_.endo_names, 'Qfair');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qfair');
M_.endo_names_long = char(M_.endo_names_long, 'Qfair');
M_.endo_names = char(M_.endo_names, 'Qbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qbook');
M_.endo_names_long = char(M_.endo_names_long, 'Qbook');
M_.endo_names = char(M_.endo_names, 'qnbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnbook');
M_.endo_names_long = char(M_.endo_names_long, 'qnbook');
M_.endo_names = char(M_.endo_names, 'Kh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kh');
M_.endo_names_long = char(M_.endo_names_long, 'Kh');
M_.endo_names = char(M_.endo_names, 'Bh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bh');
M_.endo_names_long = char(M_.endo_names_long, 'Bh');
M_.endo_names = char(M_.endo_names, 'irstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'irstar');
M_.endo_names_long = char(M_.endo_names_long, 'irstar');
M_.endo_names = char(M_.endo_names, 'Welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welf');
M_.endo_names_long = char(M_.endo_names_long, 'Welf');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'shock_ir');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_ir');
M_.endo_names_long = char(M_.endo_names_long, 'shock_ir');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'Gamma');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma');
M_.endo_names = char(M_.endo_names, 'shock_psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_psi');
M_.endo_names_long = char(M_.endo_names_long, 'shock_psi');
M_.endo_names = char(M_.endo_names, 'shock_Gamma');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_Gamma');
M_.endo_names_long = char(M_.endo_names_long, 'shock_Gamma');
M_.endo_names = char(M_.endo_names, 'QKg_Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_Y');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_Y');
M_.endo_names = char(M_.endo_names, 'qBg_Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_Y');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_Y');
M_.endo_names = char(M_.endo_names, 'QKg_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_A');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_A');
M_.endo_names = char(M_.endo_names, 'qBg_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_A');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_A');
M_.endo_names = char(M_.endo_names, 'zlb');
M_.endo_names_tex = char(M_.endo_names_tex, 'zlb');
M_.endo_names_long = char(M_.endo_names_long, 'zlb');
M_.endo_names = char(M_.endo_names, 'e_zlb1');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_zlb1');
M_.endo_names_long = char(M_.endo_names_long, 'e_zlb1');
M_.endo_names = char(M_.endo_names, 'e_zlb2');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_zlb2');
M_.endo_names_long = char(M_.endo_names_long, 'e_zlb2');
M_.endo_names = char(M_.endo_names, 'e_zlb3');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_zlb3');
M_.endo_names_long = char(M_.endo_names_long, 'e_zlb3');
M_.endo_names = char(M_.endo_names, 'e_zlb4');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_zlb4');
M_.endo_names_long = char(M_.endo_names_long, 'e_zlb4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_1');
M_.endo_partitions = struct();
M_.param_names = 'betta';
M_.param_names_tex = 'betta';
M_.param_names_long = 'betta';
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'hh');
M_.param_names_tex = char(M_.param_names_tex, 'hh');
M_.param_names_long = char(M_.param_names_long, 'hh');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'zetta');
M_.param_names_tex = char(M_.param_names_tex, 'zetta');
M_.param_names_long = char(M_.param_names_long, 'zetta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'Delta');
M_.param_names_tex = char(M_.param_names_tex, 'Delta');
M_.param_names_long = char(M_.param_names_long, 'Delta');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'Psi');
M_.param_names_tex = char(M_.param_names_tex, 'Psi');
M_.param_names_long = char(M_.param_names_long, 'Psi');
M_.param_names = char(M_.param_names, 'Sigma');
M_.param_names_tex = char(M_.param_names_tex, 'Sigma');
M_.param_names_long = char(M_.param_names_long, 'Sigma');
M_.param_names = char(M_.param_names, 'kappa_s');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_s');
M_.param_names_long = char(M_.param_names_long, 'kappa_s');
M_.param_names = char(M_.param_names, 'kappa_b');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_b');
M_.param_names_long = char(M_.param_names_long, 'kappa_b');
M_.param_names = char(M_.param_names, 'switch_Kh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'switch\_Kh\_bar');
M_.param_names_long = char(M_.param_names_long, 'switch_Kh_bar');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'gam_P');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_P');
M_.param_names_long = char(M_.param_names_long, 'gam_P');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_pi_ex');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi\_ex');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi_ex');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'rho_ir');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir');
M_.param_names_long = char(M_.param_names_long, 'rho_ir');
M_.param_names = char(M_.param_names, 'rho_ir_DSGE');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_DSGE');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_DSGE');
M_.param_names = char(M_.param_names, 'rho_ir_QE2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_QE2');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_QE2');
M_.param_names = char(M_.param_names, 'rho_ir_zlb');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_zlb');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_zlb');
M_.param_names = char(M_.param_names, 'rho_ir_zlb_ex');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_zlb\_ex');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_zlb_ex');
M_.param_names = char(M_.param_names, 'rho_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ksi');
M_.param_names_long = char(M_.param_names_long, 'rho_ksi');
M_.param_names = char(M_.param_names, 'sigma_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ksi');
M_.param_names_long = char(M_.param_names_long, 'sigma_ksi');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_Ne');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_Ne');
M_.param_names_long = char(M_.param_names_long, 'sigma_Ne');
M_.param_names = char(M_.param_names, 'sigma_ir');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ir');
M_.param_names_long = char(M_.param_names_long, 'sigma_ir');
M_.param_names = char(M_.param_names, 'sigma_ir_ZLB');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ir\_ZLB');
M_.param_names_long = char(M_.param_names_long, 'sigma_ir_ZLB');
M_.param_names = char(M_.param_names, 'rho1_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho1\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho1_shock_psi');
M_.param_names = char(M_.param_names, 'rho2_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho2\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho2_shock_psi');
M_.param_names = char(M_.param_names, 'ma1_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'ma1\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'ma1_shock_psi');
M_.param_names = char(M_.param_names, 'ma2_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'ma2\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'ma2_shock_psi');
M_.param_names = char(M_.param_names, 'sigma_psi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_psi');
M_.param_names_long = char(M_.param_names_long, 'sigma_psi');
M_.param_names = char(M_.param_names, 'rho1_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho1\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho1_shock_Gamma');
M_.param_names = char(M_.param_names, 'rho2_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho2\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho2_shock_Gamma');
M_.param_names = char(M_.param_names, 'ma1_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'ma1\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'ma1_shock_Gamma');
M_.param_names = char(M_.param_names, 'ma2_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'ma2\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'ma2_shock_Gamma');
M_.param_names = char(M_.param_names, 'sigma_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'sigma_Gamma');
M_.param_names = char(M_.param_names, 'rho_shock_ir');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_shock\_ir');
M_.param_names_long = char(M_.param_names_long, 'rho_shock_ir');
M_.param_names = char(M_.param_names, 'nu_K');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_K');
M_.param_names_long = char(M_.param_names_long, 'nu_K');
M_.param_names = char(M_.param_names, 'nu_B');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_B');
M_.param_names_long = char(M_.param_names_long, 'nu_B');
M_.param_names = char(M_.param_names, 'rho_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho_psi');
M_.param_names = char(M_.param_names, 'rho_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho_Gamma');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'w_book');
M_.param_names_tex = char(M_.param_names_tex, 'w\_book');
M_.param_names_long = char(M_.param_names_long, 'w_book');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'B');
M_.param_names_tex = char(M_.param_names_tex, 'B');
M_.param_names_long = char(M_.param_names_long, 'B');
M_.param_names = char(M_.param_names, 'Kh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Kh\_bar');
M_.param_names_long = char(M_.param_names_long, 'Kh_bar');
M_.param_names = char(M_.param_names, 'Bh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Bh\_bar');
M_.param_names_long = char(M_.param_names_long, 'Bh_bar');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'delta_c');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_c');
M_.param_names_long = char(M_.param_names_long, 'delta_c');
M_.param_names = char(M_.param_names, 'Xi');
M_.param_names_tex = char(M_.param_names_tex, 'Xi');
M_.param_names_long = char(M_.param_names_long, 'Xi');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'RkmR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'RkmR\_ss');
M_.param_names_long = char(M_.param_names_long, 'RkmR_ss');
M_.param_names = char(M_.param_names, 'RbmR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'RbmR\_ss');
M_.param_names_long = char(M_.param_names_long, 'RbmR_ss');
M_.param_names = char(M_.param_names, 'Ym_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ym\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ym_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'D_ss');
M_.param_names_tex = char(M_.param_names_tex, 'D\_ss');
M_.param_names_long = char(M_.param_names_long, 'D_ss');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Keff_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Keff\_ss');
M_.param_names_long = char(M_.param_names_long, 'Keff_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'varrho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varrho\_ss');
M_.param_names_long = char(M_.param_names_long, 'varrho_ss');
M_.param_names = char(M_.param_names, 'Lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lambda_ss');
M_.param_names = char(M_.param_names, 'Z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_ss');
M_.param_names_long = char(M_.param_names_long, 'Z_ss');
M_.param_names = char(M_.param_names, 'Ne_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ne\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ne_ss');
M_.param_names = char(M_.param_names, 'Nn_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nn\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nn_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'R_ss');
M_.param_names_tex = char(M_.param_names_tex, 'R\_ss');
M_.param_names_long = char(M_.param_names_long, 'R_ss');
M_.param_names = char(M_.param_names, 'qn_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qn\_ss');
M_.param_names_long = char(M_.param_names_long, 'qn_ss');
M_.param_names = char(M_.param_names, 'mu_s_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_s\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_s_ss');
M_.param_names = char(M_.param_names, 'mu_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_b_ss');
M_.param_names = char(M_.param_names, 'nu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_ss');
M_.param_names = char(M_.param_names, 'phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_ss');
M_.param_names = char(M_.param_names, 'x_ss');
M_.param_names_tex = char(M_.param_names_tex, 'x\_ss');
M_.param_names_long = char(M_.param_names_long, 'x_ss');
M_.param_names = char(M_.param_names, 'Omega_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Omega\_ss');
M_.param_names_long = char(M_.param_names_long, 'Omega_ss');
M_.param_names = char(M_.param_names, 'Pm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pm\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pm_ss');
M_.param_names = char(M_.param_names, 'X_ss');
M_.param_names_tex = char(M_.param_names_tex, 'X\_ss');
M_.param_names_long = char(M_.param_names_long, 'X_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'H_ss');
M_.param_names_tex = char(M_.param_names_tex, 'H\_ss');
M_.param_names_long = char(M_.param_names_long, 'H_ss');
M_.param_names = char(M_.param_names, 'ir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ir\_ss');
M_.param_names_long = char(M_.param_names_long, 'ir_ss');
M_.param_names = char(M_.param_names, 'ib_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ib\_ss');
M_.param_names_long = char(M_.param_names_long, 'ib_ss');
M_.param_names = char(M_.param_names, 'prem_K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_K\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_K_ss');
M_.param_names = char(M_.param_names, 'prem_B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_B\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_B_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'qn_rf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qn\_rf\_ss');
M_.param_names_long = char(M_.param_names_long, 'qn_rf_ss');
M_.param_names = char(M_.param_names, 'iir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'iir\_ss');
M_.param_names_long = char(M_.param_names_long, 'iir_ss');
M_.param_names = char(M_.param_names, 'prem_ib_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_ib\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_ib_ss');
M_.param_names = char(M_.param_names, 'rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'rb_ss');
M_.param_names = char(M_.param_names, 'q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'q\_ss');
M_.param_names_long = char(M_.param_names_long, 'q_ss');
M_.param_names = char(M_.param_names, 'qB_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qB\_ss');
M_.param_names_long = char(M_.param_names_long, 'qB_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'Kb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kb_ss');
M_.param_names = char(M_.param_names, 'Bb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Bb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Bb_ss');
M_.param_names = char(M_.param_names, 'Dep_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Dep\_ss');
M_.param_names_long = char(M_.param_names_long, 'Dep_ss');
M_.param_names = char(M_.param_names, 'Nbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nbook_ss');
M_.param_names = char(M_.param_names, 'phibook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phibook\_ss');
M_.param_names_long = char(M_.param_names_long, 'phibook_ss');
M_.param_names = char(M_.param_names, 'Kbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kbook_ss');
M_.param_names = char(M_.param_names, 'Qfair_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Qfair\_ss');
M_.param_names_long = char(M_.param_names_long, 'Qfair_ss');
M_.param_names = char(M_.param_names, 'Qbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Qbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Qbook_ss');
M_.param_names = char(M_.param_names, 'qnbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qnbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'qnbook_ss');
M_.param_names = char(M_.param_names, 'Kh_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kh\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kh_ss');
M_.param_names = char(M_.param_names, 'Bh_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Bh\_ss');
M_.param_names_long = char(M_.param_names_long, 'Bh_ss');
M_.param_names = char(M_.param_names, 'irstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'irstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'irstar_ss');
M_.param_names = char(M_.param_names, 'Welf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Welf\_ss');
M_.param_names_long = char(M_.param_names_long, 'Welf_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'ksi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ksi\_ss');
M_.param_names_long = char(M_.param_names_long, 'ksi_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'shock_ir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_ir\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_ir_ss');
M_.param_names = char(M_.param_names, 'infl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'infl\_ss');
M_.param_names_long = char(M_.param_names_long, 'infl_ss');
M_.param_names = char(M_.param_names, 'inflstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inflstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'inflstar_ss');
M_.param_names = char(M_.param_names, 'psi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_ss');
M_.param_names_long = char(M_.param_names_long, 'psi_ss');
M_.param_names = char(M_.param_names, 'Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma_ss');
M_.param_names = char(M_.param_names, 'shock_psi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_psi\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_psi_ss');
M_.param_names = char(M_.param_names, 'shock_Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_Gamma_ss');
M_.param_names = char(M_.param_names, 'QKg_Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'QKg\_Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'QKg_Y_ss');
M_.param_names = char(M_.param_names, 'qBg_Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qBg\_Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'qBg_Y_ss');
M_.param_names = char(M_.param_names, 'QKg_A_ss');
M_.param_names_tex = char(M_.param_names_tex, 'QKg\_A\_ss');
M_.param_names_long = char(M_.param_names_long, 'QKg_A_ss');
M_.param_names = char(M_.param_names, 'qBg_A_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qBg\_A\_ss');
M_.param_names_long = char(M_.param_names_long, 'qBg_A_ss');
M_.param_names = char(M_.param_names, 'zlb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zlb\_ss');
M_.param_names_long = char(M_.param_names_long, 'zlb_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 75;
M_.param_nbr = 133;
M_.orig_endo_nbr = 73;
M_.aux_vars(1).endo_index = 74;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 63;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 75;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 64;
M_.aux_vars(2).orig_lead_lag = -1;
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_GK13_rep_static');
erase_compiled_function('NK_GK13_rep_dynamic');
M_.orig_eq_nbr = 73;
M_.eq_nbr = 75;
M_.ramsey_eq_nbr = 0;
M_.lead_lag_incidence = [
 0 29 0;
 0 30 0;
 1 31 0;
 2 32 0;
 0 33 0;
 0 34 0;
 3 35 104;
 4 36 105;
 0 37 0;
 5 38 106;
 6 39 107;
 0 40 0;
 0 41 108;
 0 42 0;
 0 43 0;
 0 44 109;
 0 45 110;
 7 46 0;
 8 47 111;
 0 48 112;
 0 49 0;
 0 50 113;
 9 51 0;
 10 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 114;
 0 57 115;
 11 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 116;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 117;
 0 68 0;
 12 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 13 75 0;
 0 76 118;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 119;
 14 83 0;
 15 84 120;
 16 85 0;
 17 86 0;
 18 87 121;
 0 88 0;
 19 89 0;
 20 90 0;
 21 91 0;
 22 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 23 97 0;
 24 98 0;
 25 99 0;
 26 100 0;
 0 101 0;
 27 102 0;
 28 103 0;]';
M_.nstatic = 36;
M_.nfwrd   = 11;
M_.npred   = 21;
M_.nboth   = 7;
M_.nsfwrd   = 18;
M_.nspred   = 28;
M_.ndynamic   = 39;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(75, 1);
M_.maximum_exo_lag = 1;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(133, 1);
M_.NNZDerivatives = [303; 0; -1];
M_.params( 1 ) = 0.99500000;
betta = M_.params( 1 );
M_.params( 2 ) = 1.00000000;
sig = M_.params( 2 );
M_.params( 3 ) = 0.81500000;
hh = M_.params( 3 );
M_.params( 4 ) = 0.27600000;
varphi = M_.params( 4 );
M_.params( 5 ) = 7.20000000;
zetta = M_.params( 5 );
M_.params( 6 ) = 0.97155955;
theta = M_.params( 6 );
M_.params( 7 ) = 0.50000000;
Delta = M_.params( 7 );
M_.params( 8 ) = 0.33000000;
alfa = M_.params( 8 );
M_.params( 9 ) = 0.02500000;
delta = M_.params( 9 );
M_.params( 10 ) = 0.20000000;
G_over_Y = M_.params( 10 );
M_.params( 11 ) = 1.72800000;
eta_i = M_.params( 11 );
M_.params( 12 ) = 0.50000000;
Psi = M_.params( 12 );
M_.params( 13 ) = 0.75000000;
Sigma = M_.params( 13 );
M_.params( 14 ) = 1.00000000;
kappa_s = M_.params( 14 );
M_.params( 15 ) = 1.00000000;
kappa_b = M_.params( 15 );
M_.params( 16 ) = 0.00000000;
switch_Kh_bar = M_.params( 16 );
M_.params( 17 ) = 4.16700000;
epsilon = M_.params( 17 );
M_.params( 18 ) = 0.77900000;
gam = M_.params( 18 );
M_.params( 19 ) = 0.00000000;
gam_P = M_.params( 19 );
M_.params( 20 ) = 1.50000000;
kappa_pi = M_.params( 20 );
M_.params( 21 ) = 1.50000000;
kappa_pi_ex = M_.params( 21 );
M_.params( 22 ) = (-0.12500000);
kappa_y = M_.params( 22 );
M_.params( 23 ) = 0.00000000;
rho_ir = M_.params( 23 );
M_.params( 24 ) = 0.00000000;
rho_ir_DSGE = M_.params( 24 );
M_.params( 25 ) = 0.00000000;
rho_ir_QE2 = M_.params( 25 );
M_.params( 26 ) = 0.00000000;
rho_ir_zlb = M_.params( 26 );
M_.params( 27 ) = 0.00000000;
rho_ir_zlb_ex = M_.params( 27 );
M_.params( 28 ) = 0.70000000;
rho_ksi = M_.params( 28 );
M_.params( 29 ) = 0.04000000;
sigma_ksi = M_.params( 29 );
M_.params( 30 ) = 0.95000000;
rho_a = M_.params( 30 );
M_.params( 31 ) = 0.01000000;
sigma_a = M_.params( 31 );
M_.params( 32 ) = 0.95000000;
rho_g = M_.params( 32 );
M_.params( 33 ) = 0.01000000;
sigma_g = M_.params( 33 );
M_.params( 34 ) = 0.30000000;
sigma_Ne = M_.params( 34 );
M_.params( 35 ) = 0.00250000;
sigma_ir = M_.params( 35 );
M_.params( 36 ) = 0.00100000;
sigma_ir_ZLB = M_.params( 36 );
M_.params( 37 ) = 1.50000000;
rho1_shock_psi = M_.params( 37 );
M_.params( 38 ) = (-0.55000000);
rho2_shock_psi = M_.params( 38 );
M_.params( 39 ) = 0.00000000;
ma1_shock_psi = M_.params( 39 );
M_.params( 40 ) = 0.00000000;
ma2_shock_psi = M_.params( 40 );
M_.params( 41 ) = 0.00758333;
sigma_psi = M_.params( 41 );
M_.params( 42 ) = 1.50000000;
rho1_shock_Gamma = M_.params( 42 );
M_.params( 43 ) = (-0.55000000);
rho2_shock_Gamma = M_.params( 43 );
M_.params( 44 ) = 0.00000000;
ma1_shock_Gamma = M_.params( 44 );
M_.params( 45 ) = 0.00000000;
ma2_shock_Gamma = M_.params( 45 );
M_.params( 46 ) = 0.03159722;
sigma_Gamma = M_.params( 46 );
M_.params( 47 ) = 0.00000000;
rho_shock_ir = M_.params( 47 );
M_.params( 48 ) = 0.00000000;
nu_K = M_.params( 48 );
M_.params( 49 ) = 0.00000000;
nu_B = M_.params( 49 );
M_.params( 50 ) = 0.00000000;
rho_psi = M_.params( 50 );
M_.params( 51 ) = 0.00000000;
rho_Gamma = M_.params( 51 );
M_.params( 52 ) = 0.00100000;
tau = M_.params( 52 );
M_.params( 53 ) = 0.75000000;
w_book = M_.params( 53 );
M_.params( 54 ) = 0.00072872;
omega = M_.params( 54 );
M_.params( 55 ) = 0.34530233;
lambda = M_.params( 55 );
M_.params( 54 ) = 0.00072872;
omega = M_.params( 54 );
M_.params( 55 ) = 0.34530233;
lambda = M_.params( 55 );
M_.params( 119 ) = 0;
a_ss = M_.params( 119 );
M_.params( 120 ) = 0;
ksi_ss = M_.params( 120 );
M_.params( 120 ) = 0;
ksi_ss = M_.params( 120 );
M_.params( 121 ) = 0;
g_ss = M_.params( 121 );
M_.params( 122 ) = 0;
shock_ir_ss = M_.params( 122 );
M_.params( 125 ) = 0;
psi_ss = M_.params( 125 );
M_.params( 126 ) = 0;
Gamma_ss = M_.params( 126 );
M_.params( 127 ) = 0;
shock_psi_ss = M_.params( 127 );
M_.params( 128 ) = 0;
shock_Gamma_ss = M_.params( 128 );
inflstarf=0;
M_.params( 129 ) = 0;
QKg_Y_ss = M_.params( 129 );
M_.params( 130 ) = 0;
qBg_Y_ss = M_.params( 130 );
M_.params( 131 ) = 0;
QKg_A_ss = M_.params( 131 );
M_.params( 132 ) = 0;
qBg_A_ss = M_.params( 132 );
M_.params( 133 ) = 0;
zlb_ss = M_.params( 133 );
M_.params( 71 ) = (-1.098612288668111);
L_ss = M_.params( 71 );
M_.params( 87 ) = 1.670062534250535;
phi_ss = M_.params( 87 );
M_.params( 64 ) = 0.002484411292921;
RkmR_ss = M_.params( 64 );
M_.params( 88 ) = (-2.120263536200091);
x_ss = M_.params( 88 );
M_.params( 75 ) = 0;
Q_ss = M_.params( 75 );
M_.params( 112 ) = 0;
Qfair_ss = M_.params( 112 );
M_.params( 113 ) = 0;
Qbook_ss = M_.params( 113 );
M_.params( 90 ) = log((M_.params(17)-1)/M_.params(17));
Pm_ss = M_.params( 90 );
M_.params( 91 ) = log(1/exp(M_.params(90)));
X_ss = M_.params( 91 );
M_.params( 68 ) = 0;
D_ss = M_.params( 68 );
M_.params( 77 ) = 0;
Lambda_ss = M_.params( 77 );
M_.params( 82 ) = log(1/M_.params(1));
R_ss = M_.params( 82 );
M_.params( 63 ) = M_.params(64)+M_.params(82);
Rk_ss = M_.params( 63 );
M_.params( 69 ) = log(((exp(M_.params(63))-(1-M_.params(9)))/(exp(M_.params(90))*M_.params(8)))^(1/(M_.params(8)-1))*exp(M_.params(71)));
K_ss = M_.params( 69 );
M_.params( 67 ) = log(exp(M_.params(69))^M_.params(8)*exp(M_.params(71))^(1-M_.params(8)));
Y_ss = M_.params( 67 );
M_.params( 66 ) = M_.params(67);
Ym_ss = M_.params( 66 );
M_.params( 72 ) = log(M_.params(9)*exp(M_.params(69)));
I_ss = M_.params( 72 );
M_.params( 74 ) = log(M_.params(10)*exp(M_.params(67)));
G_ss = M_.params( 74 );
M_.params( 73 ) = log(exp(M_.params(67))-exp(M_.params(72))-exp(M_.params(74)));
C_ss = M_.params( 73 );
M_.params( 76 ) = log((1-M_.params(1)*M_.params(3))*((1-M_.params(3))*exp(M_.params(73)))^(-M_.params(2)));
varrho_ss = M_.params( 76 );
M_.params( 81 ) = M_.params(63)*M_.params(7)+M_.params(82)*(1-M_.params(7));
Rb_ss = M_.params( 81 );
M_.params( 65 ) = M_.params(81)-M_.params(82);
RbmR_ss = M_.params( 65 );
M_.params( 62 ) = exp(M_.params(81))-1;
Xi = M_.params( 62 );
M_.params( 95 ) = log(1+M_.params(62));
ib_ss = M_.params( 95 );
M_.params( 102 ) = log(1+M_.params(62));
rb_ss = M_.params( 102 );
M_.params( 83 ) = log(M_.params(62)/(exp(M_.params(81))-1));
qn_ss = M_.params( 83 );
M_.params( 114 ) = M_.params(83);
qnbook_ss = M_.params( 114 );
M_.params( 103 ) = M_.params(83);
q_ss = M_.params( 103 );
M_.params( 98 ) = log(exp(M_.params(67))*exp(M_.params(90))*(1-M_.params(8))/exp(M_.params(71)));
w_ss = M_.params( 98 );
M_.params( 78 ) = log(exp(M_.params(90))*M_.params(8)*exp(M_.params(67))/exp(M_.params(69)));
Z_ss = M_.params( 78 );
M_.params( 56 ) = exp(M_.params(67))*exp(M_.params(90))*(1-M_.params(8))/exp(M_.params(71))/(1/exp(M_.params(76))*exp(M_.params(71))^M_.params(4));
chi = M_.params( 56 );
M_.params( 118 ) = (log((1-M_.params(3))*exp(M_.params(73)))-M_.params(56)*exp(M_.params(71))^(1+M_.params(4))/(1+M_.params(4)))/(1-M_.params(1));
Welf_ss = M_.params( 118 );
M_.params( 92 ) = log(exp(M_.params(90))*exp(M_.params(67))/(1-M_.params(1)*M_.params(18)));
F_ss = M_.params( 92 );
M_.params( 93 ) = log(exp(M_.params(67))/(1-M_.params(1)*M_.params(18)));
H_ss = M_.params( 93 );
M_.params( 123 ) = 0;
infl_ss = M_.params( 123 );
M_.params( 124 ) = 0;
inflstar_ss = M_.params( 124 );
M_.params( 94 ) = M_.params(82);
ir_ss = M_.params( 94 );
M_.params( 117 ) = M_.params(94);
irstar_ss = M_.params( 117 );
M_.params( 100 ) = M_.params(94);
iir_ss = M_.params( 100 );
M_.params( 99 ) = log(M_.params(62)/(exp(M_.params(94))-1));
qn_rf_ss = M_.params( 99 );
M_.params( 60 ) = exp(M_.params(90))*M_.params(8)*exp(M_.params(67))/exp(M_.params(69));
b = M_.params( 60 );
M_.params( 61 ) = M_.params(9)-M_.params(60)/(1+M_.params(5));
delta_c = M_.params( 61 );
M_.params( 57 ) = exp(M_.params(69))*exp(M_.params(88))*(1-M_.params(12))/(1-M_.params(13));
B = M_.params( 57 );
M_.params( 89 ) = log((1-M_.params(6))/(1-M_.params(6)-M_.params(64)*M_.params(1)*M_.params(6)*(1+M_.params(7)*exp(M_.params(88)))*exp(M_.params(87))));
Omega_ss = M_.params( 89 );
M_.params( 84 ) = log(M_.params(64)*M_.params(1)*exp(M_.params(89)));
mu_s_ss = M_.params( 84 );
M_.params( 85 ) = log(M_.params(1)*exp(M_.params(89))*M_.params(65));
mu_b_ss = M_.params( 85 );
M_.params( 86 ) = log(M_.params(1)*exp(M_.params(89))*exp(M_.params(82)));
nu_ss = M_.params( 86 );
M_.params( 105 ) = log(M_.params(54)*(exp(M_.params(69))+exp(M_.params(83))*M_.params(57))/(1-M_.params(6)*(exp(M_.params(82))+M_.params(64)*exp(M_.params(87))+exp(M_.params(88))*exp(M_.params(87))*M_.params(65))));
N_ss = M_.params( 105 );
M_.params( 79 ) = log(M_.params(6)*(exp(M_.params(82))+M_.params(64)*exp(M_.params(87))+exp(M_.params(88))*exp(M_.params(87))*M_.params(65))*exp(M_.params(105)));
Ne_ss = M_.params( 79 );
M_.params( 80 ) = log(M_.params(54)*(exp(M_.params(69))+exp(M_.params(83))*M_.params(57)));
Nn_ss = M_.params( 80 );
M_.params( 104 ) = log(M_.params(57)*exp(M_.params(103)));
qB_ss = M_.params( 104 );
M_.params( 58 ) = exp(M_.params(69))*M_.params(12)-M_.params(1)*M_.params(14)*(exp(M_.params(63))-exp(M_.params(82)));
Kh_bar = M_.params( 58 );
M_.params( 59 ) = M_.params(13)*M_.params(57)-(exp(M_.params(63))-exp(M_.params(82)))*M_.params(1)*M_.params(7)*M_.params(15);
Bh_bar = M_.params( 59 );
M_.params( 106 ) = log(exp(M_.params(69))-M_.params(58)-M_.params(1)*M_.params(14)*(exp(M_.params(63))-exp(M_.params(82))));
Kb_ss = M_.params( 106 );
M_.params( 107 ) = log(M_.params(57)-M_.params(59)-(exp(M_.params(63))-exp(M_.params(82)))*M_.params(1)*M_.params(7)*M_.params(15));
Bb_ss = M_.params( 107 );
M_.params( 115 ) = log(exp(M_.params(69))-exp(M_.params(106)));
Kh_ss = M_.params( 115 );
M_.params( 116 ) = log(M_.params(57)-exp(M_.params(107)));
Bh_ss = M_.params( 116 );
M_.params( 108 ) = log(exp(M_.params(106))+exp(M_.params(107))-exp(M_.params(105)));
Dep_ss = M_.params( 108 );
M_.params( 109 ) = M_.params(105);
Nbook_ss = M_.params( 109 );
M_.params( 110 ) = log(exp(M_.params(108))/exp(M_.params(109)));
phibook_ss = M_.params( 110 );
M_.params( 111 ) = M_.params(69);
Kbook_ss = M_.params( 111 );
M_.params( 70 ) = M_.params(69);
Keff_ss = M_.params( 70 );
M_.params( 96 ) = log(exp(M_.params(63))/exp(M_.params(82)));
prem_K_ss = M_.params( 96 );
M_.params( 97 ) = log(exp(M_.params(81))/exp(M_.params(82)));
prem_B_ss = M_.params( 97 );
M_.params( 101 ) = log(exp(M_.params(95))/exp(M_.params(100)));
prem_ib_ss = M_.params( 101 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 4 ) = 0.00000000;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 38 ) = 0;
oo_.steady_state( 39 ) = 0;
oo_.steady_state( 40 ) = 0;
oo_.steady_state( 41 ) = 0;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 43 ) = 0;
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 45 ) = 0;
oo_.steady_state( 46 ) = 0;
oo_.steady_state( 47 ) = 0;
oo_.steady_state( 48 ) = 0;
oo_.steady_state( 49 ) = 0;
oo_.steady_state( 50 ) = 0;
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 52 ) = 0;
oo_.steady_state( 53 ) = 0;
oo_.steady_state( 54 ) = 0;
oo_.steady_state( 55 ) = 0;
oo_.steady_state( 56 ) = 0;
oo_.steady_state( 57 ) = 0;
oo_.steady_state( 58 ) = 0;
oo_.steady_state( 59 ) = 0;
oo_.steady_state( 60 ) = 0;
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 62 ) = 0;
oo_.steady_state( 63 ) = 0;
oo_.steady_state( 64 ) = 0;
oo_.steady_state( 65 ) = 0;
oo_.steady_state( 66 ) = 0;
oo_.steady_state( 67 ) = 0;
oo_.steady_state( 68 ) = 0;
oo_.steady_state( 69 ) = 0;
oo_.exo_steady_state( 1 ) = 0;
oo_.exo_steady_state( 2 ) = 0;
oo_.exo_steady_state( 3 ) = 0;
oo_.exo_steady_state( 4 ) = 0;
oo_.exo_steady_state( 5 ) = 0;
oo_.exo_steady_state( 6 ) = 0;
oo_.exo_steady_state( 7 ) = 0;
oo_.exo_steady_state( 8 ) = 0;
oo_.steady_state( 70 ) = 0;
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = 0;
oo_.steady_state( 73 ) = 0;
oo_.steady_state(74)=oo_.steady_state(63);
oo_.steady_state(75)=oo_.steady_state(64);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% ENDVAL instructions
%
ys0_= oo_.steady_state;
ex0_ = oo_.exo_steady_state;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 38 ) = 0;
oo_.steady_state( 39 ) = 0;
oo_.steady_state( 40 ) = 0;
oo_.steady_state( 41 ) = 0;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 43 ) = 0;
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 45 ) = 0;
oo_.steady_state( 46 ) = 0;
oo_.steady_state( 47 ) = 0;
oo_.steady_state( 48 ) = 0;
oo_.steady_state( 49 ) = 0;
oo_.steady_state( 50 ) = 0;
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 52 ) = 0;
oo_.steady_state( 53 ) = 0;
oo_.steady_state( 54 ) = 0;
oo_.steady_state( 55 ) = 0;
oo_.steady_state( 56 ) = 0;
oo_.steady_state( 57 ) = 0;
oo_.steady_state( 58 ) = 0;
oo_.steady_state( 59 ) = 0;
oo_.steady_state( 60 ) = 0;
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 62 ) = 0;
oo_.steady_state( 63 ) = 0;
oo_.steady_state( 64 ) = 0;
oo_.steady_state( 65 ) = 0;
oo_.steady_state( 66 ) = 0;
oo_.steady_state( 67 ) = 0;
oo_.steady_state( 68 ) = 0;
oo_.steady_state( 69 ) = 0;
oo_.exo_steady_state( 1 ) = 0;
oo_.exo_steady_state( 2 ) = 0;
oo_.exo_steady_state( 3 ) = 0;
oo_.exo_steady_state( 4 ) = 0;
oo_.exo_steady_state( 5 ) = 0;
oo_.exo_steady_state( 6 ) = 0;
oo_.exo_steady_state( 7 ) = 0;
oo_.exo_steady_state( 8 ) = 0;
oo_.steady_state( 70 ) = 0;
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = 0;
oo_.steady_state( 73 ) = 0;
oo_.steady_state(74)=oo_.steady_state(63);
oo_.steady_state(75)=oo_.steady_state(64);
%
% SHOCKS instructions
%
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',7,'multiplicative',0,'periods',1:1,'value',0.03159722) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',8,'multiplicative',0,'periods',1:1,'value',1) ];
M_.exo_det_length = 0;
options_.slowc     =   1;
options_.maxit_     =   1000;
options_.periods = 500;
perfect_foresight_setup;
perfect_foresight_solver;
save('NK_GK13_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GK13_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GK13_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GK13_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GK13_rep_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GK13_rep_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GK13_rep_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
