%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'NK_KW16_rep';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_KW16_rep.log');
M_.exo_names = 'e_ksi';
M_.exo_names_tex = 'e\_ksi';
M_.exo_names_long = 'e_ksi';
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_i');
M_.exo_names_long = char(M_.exo_names_long, 'e_i');
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'e_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n');
M_.exo_names_long = char(M_.exo_names_long, 'e_n');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'Ym');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ym');
M_.endo_names_long = char(M_.endo_names_long, 'Ym');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'U_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'U\_c');
M_.endo_names_long = char(M_.endo_names_long, 'U_c');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'Dis');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dis');
M_.endo_names_long = char(M_.endo_names_long, 'Dis');
M_.endo_names = char(M_.endo_names, 'Rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rd');
M_.endo_names_long = char(M_.endo_names_long, 'Rd');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'Rp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rp');
M_.endo_names_long = char(M_.endo_names_long, 'Rp');
M_.endo_names = char(M_.endo_names, 'ERk');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERk');
M_.endo_names_long = char(M_.endo_names_long, 'ERk');
M_.endo_names = char(M_.endo_names, 'ERb');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERb');
M_.endo_names_long = char(M_.endo_names_long, 'ERb');
M_.endo_names = char(M_.endo_names, 'prem');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem');
M_.endo_names_long = char(M_.endo_names_long, 'prem');
M_.endo_names = char(M_.endo_names, 'prem2');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem2');
M_.endo_names_long = char(M_.endo_names_long, 'prem2');
M_.endo_names = char(M_.endo_names, 'Phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Phi');
M_.endo_names_long = char(M_.endo_names_long, 'Phi');
M_.endo_names = char(M_.endo_names, 'portf_B');
M_.endo_names_tex = char(M_.endo_names_tex, 'portf\_B');
M_.endo_names_long = char(M_.endo_names_long, 'portf_B');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'Om');
M_.endo_names_tex = char(M_.endo_names_tex, 'Om');
M_.endo_names_long = char(M_.endo_names_long, 'Om');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'nu_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_k');
M_.endo_names_long = char(M_.endo_names_long, 'nu_k');
M_.endo_names = char(M_.endo_names, 'nu_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_b');
M_.endo_names_long = char(M_.endo_names_long, 'nu_b');
M_.endo_names = char(M_.endo_names, 'nu_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_n');
M_.endo_names_long = char(M_.endo_names_long, 'nu_n');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Gy');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gy');
M_.endo_names_long = char(M_.endo_names_long, 'Gy');
M_.endo_names = char(M_.endo_names, 'T');
M_.endo_names_tex = char(M_.endo_names_tex, 'T');
M_.endo_names_long = char(M_.endo_names_long, 'T');
M_.endo_names = char(M_.endo_names, 'B');
M_.endo_names_tex = char(M_.endo_names_tex, 'B');
M_.endo_names_long = char(M_.endo_names_long, 'B');
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'hh');
M_.param_names_tex = char(M_.param_names_tex, 'hh');
M_.param_names_long = char(M_.param_names_long, 'hh');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'B_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'B\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'B_over_Y');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'rho_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ksi');
M_.param_names_long = char(M_.param_names_long, 'rho_ksi');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_i');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_i');
M_.param_names_long = char(M_.param_names_long, 'sigma_i');
M_.param_names = char(M_.param_names, 'sigma_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ksi');
M_.param_names_long = char(M_.param_names_long, 'sigma_ksi');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_n');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_n');
M_.param_names_long = char(M_.param_names_long, 'sigma_n');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'U_c_ss');
M_.param_names_tex = char(M_.param_names_tex, 'U\_c\_ss');
M_.param_names_long = char(M_.param_names_long, 'U_c_ss');
M_.param_names = char(M_.param_names, 'Y_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'Y_over_K');
M_.param_names = char(M_.param_names, 'L_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'L\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'L_over_K');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Ym_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ym\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ym_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'Z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_ss');
M_.param_names_long = char(M_.param_names_long, 'Z_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'B\_ss');
M_.param_names_long = char(M_.param_names_long, 'B_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'D_ss');
M_.param_names_tex = char(M_.param_names_tex, 'D\_ss');
M_.param_names_long = char(M_.param_names_long, 'D_ss');
M_.param_names = char(M_.param_names, 'T_ss');
M_.param_names_tex = char(M_.param_names_tex, 'T\_ss');
M_.param_names_long = char(M_.param_names_long, 'T_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'ksi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ksi\_ss');
M_.param_names_long = char(M_.param_names_long, 'ksi_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'Lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lambda_ss');
M_.param_names = char(M_.param_names, 'Pm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pm\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pm_ss');
M_.param_names = char(M_.param_names, 'Phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'Phi_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'Dis_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Dis\_ss');
M_.param_names_long = char(M_.param_names_long, 'Dis_ss');
M_.param_names = char(M_.param_names, 'infl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'infl\_ss');
M_.param_names_long = char(M_.param_names_long, 'infl_ss');
M_.param_names = char(M_.param_names, 'inflstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inflstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'inflstar_ss');
M_.param_names = char(M_.param_names, 'Rd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rd\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rd_ss');
M_.param_names = char(M_.param_names, 'Rp_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rp\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rp_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'i_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_ss');
M_.param_names = char(M_.param_names, 'prem_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_ss');
M_.param_names = char(M_.param_names, 'nu_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_b_ss');
M_.param_names = char(M_.param_names, 'nu_n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_n\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_n_ss');
M_.param_names = char(M_.param_names, 'nu_k_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_k\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_k_ss');
M_.param_names = char(M_.param_names, 'portf_B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'portf\_B\_ss');
M_.param_names_long = char(M_.param_names_long, 'portf_B_ss');
M_.param_names = char(M_.param_names, 'Om_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Om\_ss');
M_.param_names_long = char(M_.param_names_long, 'Om_ss');
M_.param_names = char(M_.param_names, 'Gy_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gy\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gy_ss');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 40;
M_.param_nbr = 63;
M_.orig_endo_nbr = 40;
M_.aux_vars = [];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('NK_KW16_rep_static');
erase_compiled_function('NK_KW16_rep_dynamic');
M_.lead_lag_incidence = [
 1 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 2 20 56;
 3 21 0;
 0 22 57;
 4 23 58;
 5 24 59;
 6 25 60;
 7 26 0;
 8 27 0;
 0 28 0;
 0 29 61;
 0 30 0;
 0 31 62;
 0 32 63;
 9 33 0;
 0 34 64;
 10 35 0;
 0 36 65;
 0 37 66;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 11 43 0;
 0 44 0;
 12 45 67;
 13 46 0;
 0 47 0;
 0 48 68;
 0 49 69;
 0 50 70;
 0 51 0;
 14 52 0;
 0 53 0;
 0 54 0;
 15 55 71;]';
M_.nstatic = 15;
M_.nfwrd   = 10;
M_.npred   = 9;
M_.nboth   = 6;
M_.nsfwrd   = 16;
M_.nspred   = 15;
M_.ndynamic   = 25;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(40, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(63, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 158;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
M_.params( 1 ) = 0.99;
beta = M_.params( 1 );
M_.params( 2 ) = 0.815;
hh = M_.params( 2 );
M_.params( 3 ) = 0.025;
delta = M_.params( 3 );
M_.params( 4 ) = 0.276;
varphi = M_.params( 4 );
M_.params( 5 ) = 1.728;
eta_i = M_.params( 5 );
M_.params( 6 ) = 0.33;
alpha = M_.params( 6 );
M_.params( 7 ) = 0.779;
gam = M_.params( 7 );
M_.params( 8 ) = 4.167;
epsilon = M_.params( 8 );
M_.params( 11 ) = 0.2;
G_over_Y = M_.params( 11 );
M_.params( 12 ) = 2.4;
B_over_Y = M_.params( 12 );
M_.params( 47 ) = 4;
Phi_ss = M_.params( 47 );
M_.params( 13 ) = 0.9375;
theta = M_.params( 13 );
M_.params( 9 ) = 1.50000000;
kappa_pi = M_.params( 9 );
M_.params( 10 ) = 0.12500000;
kappa_y = M_.params( 10 );
M_.params( 16 ) = 0.8;
rho_i = M_.params( 16 );
M_.params( 17 ) = 0.66;
rho_ksi = M_.params( 17 );
M_.params( 18 ) = 0.95;
rho_a = M_.params( 18 );
M_.params( 19 ) = 0.80;
rho_g = M_.params( 19 );
M_.params( 21 ) = 0.05;
sigma_ksi = M_.params( 21 );
M_.params( 22 ) = 0.01;
sigma_a = M_.params( 22 );
M_.params( 23 ) = 0.05;
sigma_g = M_.params( 23 );
M_.params( 20 ) = 0.0025;
sigma_i = M_.params( 20 );
M_.params( 24 ) = 0.01;
sigma_n = M_.params( 24 );
M_.params( 45 ) = 1;
Lambda_ss = M_.params( 45 );
M_.params( 48 ) = 1;
Q_ss = M_.params( 48 );
M_.params( 49 ) = 1;
Dis_ss = M_.params( 49 );
M_.params( 50 ) = 1;
infl_ss = M_.params( 50 );
M_.params( 51 ) = 1;
inflstar_ss = M_.params( 51 );
M_.params( 42 ) = 1;
a_ss = M_.params( 42 );
M_.params( 44 ) = 1;
g_ss = M_.params( 44 );
M_.params( 43 ) = 1;
ksi_ss = M_.params( 43 );
M_.params( 46 ) = (M_.params(8)-1)/M_.params(8);
Pm_ss = M_.params( 46 );
M_.params( 57 ) = 0.0025;
prem_ss = M_.params( 57 );
prem2_ss = prem_ss;
M_.params( 47 ) = 4;
Phi_ss = M_.params( 47 );
M_.params( 52 ) = 1/M_.params(1);
Rd_ss = M_.params( 52 );
M_.params( 56 ) = M_.params(52);
i_ss = M_.params( 56 );
M_.params( 55 ) = M_.params(52)+M_.params(57);
Rk_ss = M_.params( 55 );
M_.params( 54 ) = M_.params(55);
Rb_ss = M_.params( 54 );
M_.params( 53 ) = M_.params(55);
Rp_ss = M_.params( 53 );
ERk_ss=Rk_ss;
ERb_ss=Rk_ss;
M_.params( 59 ) = M_.params(52)*M_.params(1)*(1-M_.params(13))/(1-M_.params(1)*M_.params(13));
nu_n_ss = M_.params( 59 );
M_.params( 60 ) = M_.params(1)*(1-M_.params(13))*(M_.params(55)-M_.params(52))/(1-M_.params(1)*M_.params(13));
nu_k_ss = M_.params( 60 );
M_.params( 58 ) = M_.params(60);
nu_b_ss = M_.params( 58 );
M_.params( 14 ) = M_.params(60)+M_.params(59)/M_.params(47);
lambda = M_.params( 14 );
M_.params( 15 ) = 1-M_.params(13)*(M_.params(52)+(M_.params(55)-M_.params(52))*M_.params(47));
chi = M_.params( 15 );
M_.params( 27 ) = (M_.params(6)^M_.params(6)*(1-M_.params(6))^(1-M_.params(6))*M_.params(46)*(M_.params(55)-1+M_.params(3))^(-M_.params(6)))^(1/(1-M_.params(6)));
w_ss = M_.params( 27 );
M_.params( 29 ) = (M_.params(55)-1+M_.params(3))/(M_.params(6)*M_.params(46));
Y_over_K = M_.params( 29 );
M_.params( 30 ) = M_.params(29)^(1/(1-M_.params(6)));
L_over_K = M_.params( 30 );
I_over_Y = delta*(Y_over_K)^(-1);
C_over_Y = 1-G_over_Y-I_over_Y;
habit = (1-beta*hh)/(1-hh);
M_.params( 25 ) = M_.params(30)^((-M_.params(6))*M_.params(4)/(1+M_.params(4)))*(habit*M_.params(27)*C_over_Y^(-1))^(1/(1+M_.params(4)));
Y_ss = M_.params( 25 );
M_.params( 32 ) = M_.params(25);
Ym_ss = M_.params( 32 );
M_.params( 35 ) = C_over_Y*M_.params(25);
C_ss = M_.params( 35 );
M_.params( 33 ) = M_.params(25)*M_.params(11);
G_ss = M_.params( 33 );
M_.params( 63 ) = M_.params(11);
Gy_ss = M_.params( 63 );
M_.params( 34 ) = M_.params(25)*I_over_Y;
I_ss = M_.params( 34 );
M_.params( 31 ) = M_.params(34)/M_.params(3);
K_ss = M_.params( 31 );
M_.params( 26 ) = M_.params(30)*M_.params(31);
L_ss = M_.params( 26 );
M_.params( 28 ) = habit/M_.params(35);
U_c_ss = M_.params( 28 );
M_.params( 36 ) = M_.params(25)*1/(1-M_.params(1)*M_.params(7));
Z_ss = M_.params( 36 );
M_.params( 37 ) = M_.params(46)*M_.params(36);
F_ss = M_.params( 37 );
M_.params( 38 ) = M_.params(25)*M_.params(12);
B_ss = M_.params( 38 );
M_.params( 39 ) = (M_.params(31)+M_.params(38))/M_.params(47);
N_ss = M_.params( 39 );
M_.params( 62 ) = M_.params(31)/(M_.params(31)+M_.params(38));
Om_ss = M_.params( 62 );
M_.params( 53 ) = M_.params(55)*M_.params(62)+(1-M_.params(62))*M_.params(54);
Rp_ss = M_.params( 53 );
M_.params( 41 ) = M_.params(38)*(M_.params(54)-1)+M_.params(33);
T_ss = M_.params( 41 );
M_.params( 61 ) = M_.params(47)*M_.params(39);
portf_B_ss = M_.params( 61 );
M_.params( 40 ) = M_.params(31)+M_.params(38)-M_.params(39);
D_ss = M_.params( 40 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(25));
oo_.steady_state( 2 ) = log(M_.params(32));
oo_.steady_state( 9 ) = log(M_.params(31));
oo_.steady_state( 3 ) = log(M_.params(26));
oo_.steady_state( 8 ) = log(M_.params(34));
oo_.steady_state( 5 ) = log(M_.params(35));
oo_.steady_state( 36 ) = log(M_.params(33));
oo_.steady_state( 10 ) = log(M_.params(48));
oo_.steady_state( 6 ) = log(M_.params(28));
oo_.steady_state( 7 ) = log(M_.params(45));
oo_.steady_state( 21 ) = log(M_.params(55));
oo_.steady_state( 19 ) = log(M_.params(52));
oo_.steady_state( 30 ) = log(M_.params(39));
oo_.steady_state( 13 ) = log(M_.params(46));
oo_.steady_state( 4 ) = log(M_.params(27));
oo_.steady_state( 18 ) = log(M_.params(49));
oo_.steady_state( 16 ) = log(M_.params(37));
oo_.steady_state( 17 ) = log(M_.params(36));
oo_.steady_state( 20 ) = log(M_.params(56));
oo_.steady_state( 26 ) = log(M_.params(57));
oo_.steady_state( 11 ) = 0.00000000;
oo_.steady_state( 12 ) = 0.00000000;
oo_.steady_state( 37 ) = 0.00000000;
oo_.steady_state( 14 ) = 0.00000000;
oo_.steady_state( 15 ) = 0.00000000;
oo_.exo_steady_state( 4 ) = 0.00000000;
oo_.exo_steady_state( 1 ) = 0.00000000;
oo_.exo_steady_state( 2 ) = 0.00000000;
oo_.exo_steady_state( 3 ) = 0.00000000;
oo_.steady_state( 40 ) = log(M_.params(38));
oo_.steady_state( 32 ) = log(M_.params(40));
oo_.steady_state( 39 ) = log(M_.params(41));
oo_.steady_state( 28 ) = log(M_.params(47));
oo_.steady_state( 22 ) = log(M_.params(54));
oo_.steady_state( 33 ) = log(M_.params(60));
oo_.steady_state( 34 ) = log(M_.params(58));
oo_.steady_state( 35 ) = log(M_.params(59));
oo_.steady_state( 27 ) = log(prem2_ss);
oo_.steady_state( 24 ) = log(M_.params(55));
oo_.steady_state( 25 ) = log(M_.params(54));
oo_.steady_state( 23 ) = log(M_.params(53));
oo_.steady_state( 29 ) = log(M_.params(61));
oo_.steady_state( 31 ) = log(M_.params(62));
oo_.steady_state( 38 ) = log(M_.params(63));
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = 25;
options_.irf = 30;
options_.order = 1;
var_list_=[];
var_list_ = 'infl';
var_list_ = char(var_list_, 'i');
var_list_ = char(var_list_, 'Y');
info = stoch_simul(var_list_);
save('NK_KW16_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_KW16_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_KW16_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_KW16_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_KW16_rep_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
