%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'chen_replication';
M_.dynare_version = '4.5.3';
oo_.dynare_version = '4.5.3';
options_.dynare_version = '4.5.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('chen_replication.log');
M_.exo_names = 'eps_z';
M_.exo_names_tex = 'eps\_z';
M_.exo_names_long = 'eps_z';
M_.exo_names = char(M_.exo_names, 'eps_phi');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_phi');
M_.exo_names_long = char(M_.exo_names_long, 'eps_phi');
M_.exo_names = char(M_.exo_names, 'eps_lambda');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_lambda');
M_.exo_names_long = char(M_.exo_names_long, 'eps_lambda');
M_.exo_names = char(M_.exo_names, 'eps_mu');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_mu');
M_.exo_names_long = char(M_.exo_names_long, 'eps_mu');
M_.exo_names = char(M_.exo_names, 'eps_zeta');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_zeta');
M_.exo_names_long = char(M_.exo_names_long, 'eps_zeta');
M_.exo_names = char(M_.exo_names, 'eps_m');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_m');
M_.exo_names_long = char(M_.exo_names_long, 'eps_m');
M_.exo_names = char(M_.exo_names, 'eps_bu');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_bu');
M_.exo_names_long = char(M_.exo_names_long, 'eps_bu');
M_.exo_names = char(M_.exo_names, 'eps_br');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_br');
M_.exo_names_long = char(M_.exo_names_long, 'eps_br');
M_.exo_names = char(M_.exo_names, 'eps_Gz');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Gz');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Gz');
M_.exo_names = char(M_.exo_names, 'eps_T');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_T');
M_.exo_names_long = char(M_.exo_names_long, 'eps_T');
M_.exo_names = char(M_.exo_names, 'eps_B');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_B');
M_.exo_names_long = char(M_.exo_names_long, 'eps_B');
M_.endo_names = 'marc';
M_.endo_names_tex = 'marc';
M_.endo_names_long = 'marc';
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'rL');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL');
M_.endo_names_long = char(M_.endo_names_long, 'rL');
M_.endo_names = char(M_.endo_names, 'wz');
M_.endo_names_tex = char(M_.endo_names_tex, 'wz');
M_.endo_names_long = char(M_.endo_names_long, 'wz');
M_.endo_names = char(M_.endo_names, 'Kz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kz');
M_.endo_names_long = char(M_.endo_names_long, 'Kz');
M_.endo_names = char(M_.endo_names, 'Kz_eff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kz\_eff');
M_.endo_names_long = char(M_.endo_names_long, 'Kz_eff');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'Yz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yz');
M_.endo_names_long = char(M_.endo_names_long, 'Yz');
M_.endo_names = char(M_.endo_names, 'Xpnu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xpnu');
M_.endo_names_long = char(M_.endo_names_long, 'Xpnu');
M_.endo_names = char(M_.endo_names, 'Xpnr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xpnr');
M_.endo_names_long = char(M_.endo_names_long, 'Xpnr');
M_.endo_names = char(M_.endo_names, 'Xpdu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xpdu');
M_.endo_names_long = char(M_.endo_names_long, 'Xpdu');
M_.endo_names = char(M_.endo_names, 'Xpdr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xpdr');
M_.endo_names_long = char(M_.endo_names_long, 'Xpdr');
M_.endo_names = char(M_.endo_names, 'Xwnu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xwnu');
M_.endo_names_long = char(M_.endo_names_long, 'Xwnu');
M_.endo_names = char(M_.endo_names, 'Xwnr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xwnr');
M_.endo_names_long = char(M_.endo_names_long, 'Xwnr');
M_.endo_names = char(M_.endo_names, 'Xwdu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xwdu');
M_.endo_names_long = char(M_.endo_names_long, 'Xwdu');
M_.endo_names = char(M_.endo_names, 'Xwdr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xwdr');
M_.endo_names_long = char(M_.endo_names_long, 'Xwdr');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'Iz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Iz');
M_.endo_names_long = char(M_.endo_names_long, 'Iz');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'lambda_ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_ms');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_ms');
M_.endo_names = char(M_.endo_names, 'bu');
M_.endo_names_tex = char(M_.endo_names_tex, 'bu');
M_.endo_names_long = char(M_.endo_names_long, 'bu');
M_.endo_names = char(M_.endo_names, 'br');
M_.endo_names_tex = char(M_.endo_names_tex, 'br');
M_.endo_names_long = char(M_.endo_names_long, 'br');
M_.endo_names = char(M_.endo_names, 'Xiu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xiu');
M_.endo_names_long = char(M_.endo_names_long, 'Xiu');
M_.endo_names = char(M_.endo_names, 'Xir');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xir');
M_.endo_names_long = char(M_.endo_names_long, 'Xir');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'Czu');
M_.endo_names_tex = char(M_.endo_names_tex, 'Czu');
M_.endo_names_long = char(M_.endo_names_long, 'Czu');
M_.endo_names = char(M_.endo_names, 'Czr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Czr');
M_.endo_names_long = char(M_.endo_names_long, 'Czr');
M_.endo_names = char(M_.endo_names, 'zeta_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'zeta\_h');
M_.endo_names_long = char(M_.endo_names_long, 'zeta_h');
M_.endo_names = char(M_.endo_names, 'Bz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bz');
M_.endo_names_long = char(M_.endo_names_long, 'Bz');
M_.endo_names = char(M_.endo_names, 'BzL');
M_.endo_names_tex = char(M_.endo_names_tex, 'BzL');
M_.endo_names_long = char(M_.endo_names_long, 'BzL');
M_.endo_names = char(M_.endo_names, 'Gz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gz');
M_.endo_names_long = char(M_.endo_names_long, 'Gz');
M_.endo_names = char(M_.endo_names, 'Tz');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tz');
M_.endo_names_long = char(M_.endo_names_long, 'Tz');
M_.endo_names = char(M_.endo_names, 'shock_zeta');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_zeta');
M_.endo_names_long = char(M_.endo_names_long, 'shock_zeta');
M_.endo_names = char(M_.endo_names, 'BLMVz');
M_.endo_names_tex = char(M_.endo_names_tex, 'BLMVz');
M_.endo_names_long = char(M_.endo_names_long, 'BLMVz');
M_.endo_names = char(M_.endo_names, 'BTotMVz');
M_.endo_names_tex = char(M_.endo_names_tex, 'BTotMVz');
M_.endo_names_long = char(M_.endo_names_long, 'BTotMVz');
M_.endo_names = char(M_.endo_names, 'slope');
M_.endo_names_tex = char(M_.endo_names_tex, 'slope');
M_.endo_names_long = char(M_.endo_names_long, 'slope');
M_.endo_names = char(M_.endo_names, 'rLEH');
M_.endo_names_tex = char(M_.endo_names_tex, 'rLEH');
M_.endo_names_long = char(M_.endo_names_long, 'rLEH');
M_.endo_names = char(M_.endo_names, 'RP');
M_.endo_names_tex = char(M_.endo_names_tex, 'RP');
M_.endo_names_long = char(M_.endo_names_long, 'RP');
M_.endo_names = char(M_.endo_names, 'rr');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr');
M_.endo_names_long = char(M_.endo_names_long, 'rr');
M_.endo_names = char(M_.endo_names, 'rLr');
M_.endo_names_tex = char(M_.endo_names_tex, 'rLr');
M_.endo_names_long = char(M_.endo_names_long, 'rLr');
M_.endo_names = char(M_.endo_names, 'rLEHr');
M_.endo_names_tex = char(M_.endo_names_tex, 'rLEHr');
M_.endo_names_long = char(M_.endo_names_long, 'rLEHr');
M_.endo_names = char(M_.endo_names, 'Yz_growth');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yz\_growth');
M_.endo_names_long = char(M_.endo_names_long, 'Yz_growth');
M_.endo_names = char(M_.endo_names, 'pi_ann');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_ann');
M_.endo_names_long = char(M_.endo_names_long, 'pi_ann');
M_.endo_names = char(M_.endo_names, 'r_ann');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_ann');
M_.endo_names_long = char(M_.endo_names_long, 'r_ann');
M_.endo_names = char(M_.endo_names, 'rL_ann');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL\_ann');
M_.endo_names_long = char(M_.endo_names_long, 'rL_ann');
M_.endo_names = char(M_.endo_names, 'dy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy');
M_.endo_names_long = char(M_.endo_names_long, 'dy');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'FFR');
M_.endo_names_tex = char(M_.endo_names_tex, 'FFR');
M_.endo_names_long = char(M_.endo_names_long, 'FFR');
M_.endo_names = char(M_.endo_names, 'bondrate');
M_.endo_names_tex = char(M_.endo_names_tex, 'bondrate');
M_.endo_names_long = char(M_.endo_names_long, 'bondrate');
M_.endo_names = char(M_.endo_names, 'riskprem');
M_.endo_names_tex = char(M_.endo_names_tex, 'riskprem');
M_.endo_names_long = char(M_.endo_names_long, 'riskprem');
M_.endo_names = char(M_.endo_names, 'y_level');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_level');
M_.endo_names_long = char(M_.endo_names_long, 'y_level');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_21_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_21\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_21_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_21_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_21\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_21_2');
M_.endo_partitions = struct();
M_.param_names = 'alpha';
M_.param_names_tex = 'alpha';
M_.param_names_long = 'alpha';
M_.param_names = char(M_.param_names, 'betau');
M_.param_names_tex = char(M_.param_names_tex, 'betau');
M_.param_names_long = char(M_.param_names_long, 'betau');
M_.param_names = char(M_.param_names, 'betar');
M_.param_names_tex = char(M_.param_names_tex, 'betar');
M_.param_names_long = char(M_.param_names_long, 'betar');
M_.param_names = char(M_.param_names, 'beta_av');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_av');
M_.param_names_long = char(M_.param_names_long, 'beta_av');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'lambdaw');
M_.param_names_tex = char(M_.param_names_tex, 'lambdaw');
M_.param_names_long = char(M_.param_names_long, 'lambdaw');
M_.param_names = char(M_.param_names, 'lambdaf');
M_.param_names_tex = char(M_.param_names_tex, 'lambdaf');
M_.param_names_long = char(M_.param_names_long, 'lambdaf');
M_.param_names = char(M_.param_names, 'zeta');
M_.param_names_tex = char(M_.param_names_tex, 'zeta');
M_.param_names_long = char(M_.param_names_long, 'zeta');
M_.param_names = char(M_.param_names, 'zetap');
M_.param_names_tex = char(M_.param_names_tex, 'zetap');
M_.param_names_long = char(M_.param_names_long, 'zetap');
M_.param_names = char(M_.param_names, 'zetaw');
M_.param_names_tex = char(M_.param_names_tex, 'zetaw');
M_.param_names_long = char(M_.param_names_long, 'zetaw');
M_.param_names = char(M_.param_names, 'chi_pu');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_pu');
M_.param_names_long = char(M_.param_names_long, 'chi_pu');
M_.param_names = char(M_.param_names, 'chi_wu');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_wu');
M_.param_names_long = char(M_.param_names_long, 'chi_wu');
M_.param_names = char(M_.param_names, 'omegau');
M_.param_names_tex = char(M_.param_names_tex, 'omegau');
M_.param_names_long = char(M_.param_names_long, 'omegau');
M_.param_names = char(M_.param_names, 'omegar');
M_.param_names_tex = char(M_.param_names_tex, 'omegar');
M_.param_names_long = char(M_.param_names_long, 'omegar');
M_.param_names = char(M_.param_names, 'S_dp');
M_.param_names_tex = char(M_.param_names_tex, 'S\_dp');
M_.param_names_long = char(M_.param_names_long, 'S_dp');
M_.param_names = char(M_.param_names, 'a_dp');
M_.param_names_tex = char(M_.param_names_tex, 'a\_dp');
M_.param_names_long = char(M_.param_names_long, 'a_dp');
M_.param_names = char(M_.param_names, 'zeta_prime');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_prime');
M_.param_names_long = char(M_.param_names_long, 'zeta_prime');
M_.param_names = char(M_.param_names, 'RL');
M_.param_names_tex = char(M_.param_names_tex, 'RL');
M_.param_names_long = char(M_.param_names_long, 'RL');
M_.param_names = char(M_.param_names, 'phi_T');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_T');
M_.param_names_long = char(M_.param_names_long, 'phi_T');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pi');
M_.param_names_long = char(M_.param_names_long, 'phi_pi');
M_.param_names = char(M_.param_names, 'phi_y');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_y');
M_.param_names_long = char(M_.param_names_long, 'phi_y');
M_.param_names = char(M_.param_names, 'qu');
M_.param_names_tex = char(M_.param_names_tex, 'qu');
M_.param_names_long = char(M_.param_names_long, 'qu');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'sigmau');
M_.param_names_tex = char(M_.param_names_tex, 'sigmau');
M_.param_names_long = char(M_.param_names_long, 'sigmau');
M_.param_names = char(M_.param_names, 'sigmar');
M_.param_names_tex = char(M_.param_names_tex, 'sigmar');
M_.param_names_long = char(M_.param_names_long, 'sigmar');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'rho_bu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_bu');
M_.param_names_long = char(M_.param_names_long, 'rho_bu');
M_.param_names = char(M_.param_names, 'rho_br');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_br');
M_.param_names_long = char(M_.param_names_long, 'rho_br');
M_.param_names = char(M_.param_names, 'rho_B');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_B');
M_.param_names_long = char(M_.param_names_long, 'rho_B');
M_.param_names = char(M_.param_names, 'rho_zeta');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zeta');
M_.param_names_long = char(M_.param_names_long, 'rho_zeta');
M_.param_names = char(M_.param_names, 'rho_Gz');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Gz');
M_.param_names_long = char(M_.param_names_long, 'rho_Gz');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'rho_phi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_phi');
M_.param_names_long = char(M_.param_names_long, 'rho_phi');
M_.param_names = char(M_.param_names, 'rho_mu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu');
M_.param_names_long = char(M_.param_names_long, 'rho_mu');
M_.param_names = char(M_.param_names, 'rk_SS');
M_.param_names_tex = char(M_.param_names_tex, 'rk\_SS');
M_.param_names_long = char(M_.param_names_long, 'rk_SS');
M_.param_names = char(M_.param_names, 'r_SS');
M_.param_names_tex = char(M_.param_names_tex, 'r\_SS');
M_.param_names_long = char(M_.param_names_long, 'r_SS');
M_.param_names = char(M_.param_names, 'Bz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Bz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Bz_SS');
M_.param_names = char(M_.param_names, 'C_ratio');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ratio');
M_.param_names_long = char(M_.param_names_long, 'C_ratio');
M_.param_names = char(M_.param_names, 'Czu_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Czu\_SS');
M_.param_names_long = char(M_.param_names_long, 'Czu_SS');
M_.param_names = char(M_.param_names, 'Czr_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Czr\_SS');
M_.param_names_long = char(M_.param_names_long, 'Czr_SS');
M_.param_names = char(M_.param_names, 'BzL_SS');
M_.param_names_tex = char(M_.param_names_tex, 'BzL\_SS');
M_.param_names_long = char(M_.param_names_long, 'BzL_SS');
M_.param_names = char(M_.param_names, 'Gz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Gz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Gz_SS');
M_.param_names = char(M_.param_names, 'Iz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Iz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Iz_SS');
M_.param_names = char(M_.param_names, 'Yz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Yz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Yz_SS');
M_.param_names = char(M_.param_names, 'Tz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Tz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Tz_SS');
M_.param_names = char(M_.param_names, 'Pi_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Pi\_SS');
M_.param_names_long = char(M_.param_names_long, 'Pi_SS');
M_.param_names = char(M_.param_names, 'Kz_eff_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Kz\_eff\_SS');
M_.param_names_long = char(M_.param_names_long, 'Kz_eff_SS');
M_.param_names = char(M_.param_names, 'Kz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'Kz\_SS');
M_.param_names_long = char(M_.param_names_long, 'Kz_SS');
M_.param_names = char(M_.param_names, 'X_ratio');
M_.param_names_tex = char(M_.param_names_tex, 'X\_ratio');
M_.param_names_long = char(M_.param_names_long, 'X_ratio');
M_.param_names = char(M_.param_names, 'sigma_z');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_z');
M_.param_names_long = char(M_.param_names_long, 'sigma_z');
M_.param_names = char(M_.param_names, 'sigma_lambda');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_lambda');
M_.param_names_long = char(M_.param_names_long, 'sigma_lambda');
M_.param_names = char(M_.param_names, 'sigma_mu');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_mu');
M_.param_names_long = char(M_.param_names_long, 'sigma_mu');
M_.param_names = char(M_.param_names, 'sigma_b');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_b');
M_.param_names_long = char(M_.param_names_long, 'sigma_b');
M_.param_names = char(M_.param_names, 'sigma_phi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_phi');
M_.param_names_long = char(M_.param_names_long, 'sigma_phi');
M_.param_names = char(M_.param_names, 'sigma_B');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_B');
M_.param_names_long = char(M_.param_names_long, 'sigma_B');
M_.param_names = char(M_.param_names, 'sigma_T');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_T');
M_.param_names_long = char(M_.param_names_long, 'sigma_T');
M_.param_names = char(M_.param_names, 'sigma_m');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_m');
M_.param_names_long = char(M_.param_names_long, 'sigma_m');
M_.param_names = char(M_.param_names, 'sigma_zeta');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_zeta');
M_.param_names_long = char(M_.param_names_long, 'sigma_zeta');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'BLMVB');
M_.param_names_tex = char(M_.param_names_tex, 'BLMVB');
M_.param_names_long = char(M_.param_names_long, 'BLMVB');
M_.param_names = char(M_.param_names, 'BLB');
M_.param_names_tex = char(M_.param_names_tex, 'BLB');
M_.param_names_long = char(M_.param_names_long, 'BLB');
M_.param_names = char(M_.param_names, 'BLMVz_SS');
M_.param_names_tex = char(M_.param_names_tex, 'BLMVz\_SS');
M_.param_names_long = char(M_.param_names_long, 'BLMVz_SS');
M_.param_names = char(M_.param_names, 'kappaEH');
M_.param_names_tex = char(M_.param_names_tex, 'kappaEH');
M_.param_names_long = char(M_.param_names_long, 'kappaEH');
M_.param_names = char(M_.param_names, 'BondDuration');
M_.param_names_tex = char(M_.param_names_tex, 'BondDuration');
M_.param_names_long = char(M_.param_names_long, 'BondDuration');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 61;
M_.param_nbr = 67;
M_.orig_endo_nbr = 56;
M_.aux_vars(1).endo_index = 57;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 9;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 58;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 9;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(3).endo_index = 59;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 9;
M_.aux_vars(3).orig_lead_lag = -3;
M_.aux_vars(4).endo_index = 60;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 22;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 61;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 22;
M_.aux_vars(5).orig_lead_lag = -2;
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('chen_replication_static');
erase_compiled_function('chen_replication_dynamic');
M_.orig_eq_nbr = 56;
M_.eq_nbr = 61;
M_.ramsey_eq_nbr = 0;
M_.lead_lag_incidence = [
 0 23 0;
 0 24 84;
 1 25 0;
 0 26 85;
 2 27 0;
 3 28 0;
 0 29 0;
 0 30 0;
 4 31 0;
 0 32 86;
 0 33 87;
 0 34 88;
 0 35 89;
 0 36 90;
 0 37 91;
 0 38 92;
 0 39 93;
 0 40 94;
 0 41 0;
 5 42 95;
 6 43 0;
 7 44 96;
 8 45 0;
 0 46 0;
 9 47 97;
 10 48 98;
 0 49 99;
 0 50 100;
 0 51 101;
 11 52 102;
 12 53 103;
 0 54 0;
 13 55 0;
 14 56 0;
 15 57 0;
 0 58 0;
 16 59 0;
 17 60 0;
 0 61 0;
 0 62 0;
 0 63 104;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 18 79 0;
 19 80 0;
 20 81 0;
 21 82 0;
 22 83 0;]';
M_.nstatic = 24;
M_.nfwrd   = 15;
M_.npred   = 16;
M_.nboth   = 6;
M_.nsfwrd   = 21;
M_.nspred   = 22;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(61, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(67, 1);
M_.NNZDerivatives = [254; 0; -1];
M_.params( 1 ) = 0.33;
alpha = M_.params( 1 );
M_.params( 8 ) = 0.15;
lambdaw = M_.params( 8 );
M_.params( 9 ) = 0.15;
lambdaf = M_.params( 9 );
M_.params( 5 ) = 0.025;
delta = M_.params( 5 );
M_.params( 45 ) = 0.2;
Gz_SS = M_.params( 45 );
M_.params( 6 ) = 0.005;
gamma = M_.params( 6 );
M_.params( 2 ) = 0.9988;
betau = M_.params( 2 );
pi_SS       = 0.0053;             
M_.params( 10 ) = 0.001242;
zeta = M_.params( 10 );
M_.params( 19 ) = 0.003274;
zeta_prime = M_.params( 19 );
M_.params( 67 ) = 30;
BondDuration = M_.params( 67 );
M_.params( 63 ) = 0.8533;
BLMVB = M_.params( 63 );
M_.params( 11 ) = 0.9288;
zetap = M_.params( 11 );
M_.params( 12 ) = 0.7342;
zetaw = M_.params( 12 );
M_.params( 14 ) = 0.5611;
chi_wu = M_.params( 14 );
M_.params( 15 ) = 0.9468;
omegau = M_.params( 15 );
M_.params( 16 ) = 1-M_.params(15);
omegar = M_.params( 16 );
M_.params( 17 ) = 4.7815;
S_dp = M_.params( 17 );
M_.params( 18 ) = 0.2159;
a_dp = M_.params( 18 );
M_.params( 21 ) = 1.2543;
phi_T = M_.params( 21 );
M_.params( 22 ) = 1.5979;
phi_pi = M_.params( 22 );
M_.params( 23 ) = 0.3251;
phi_y = M_.params( 23 );
M_.params( 25 ) = 0.8020;
h = M_.params( 25 );
M_.params( 26 ) = 3.3548;
sigmau = M_.params( 26 );
M_.params( 27 ) = 2.0825;
sigmar = M_.params( 27 );
M_.params( 28 ) = 1.9295;
nu = M_.params( 28 );
M_.params( 29 ) = 0.9614;
rho_bu = M_.params( 29 );
M_.params( 30 ) = 0.9614;
rho_br = M_.params( 30 );
M_.params( 31 ) = 0.9659;
rho_B = M_.params( 31 );
M_.params( 32 ) = 0.9426;
rho_zeta = M_.params( 32 );
M_.params( 33 ) = 0.7491;
rho_Gz = M_.params( 33 );
M_.params( 34 ) = 0.8565;
rho_r = M_.params( 34 );
M_.params( 35 ) = 0.1430;
rho_z = M_.params( 35 );
M_.params( 36 ) = 0.5074;
rho_phi = M_.params( 36 );
M_.params( 37 ) = 0.8489;
rho_mu = M_.params( 37 );
M_.params( 53 ) = 0.7588;
sigma_z = M_.params( 53 );
M_.params( 54 ) = 1.7939;
sigma_lambda = M_.params( 54 );
M_.params( 55 ) = 2.9725;
sigma_mu = M_.params( 55 );
M_.params( 56 ) = 3.5860;
sigma_b = M_.params( 56 );
M_.params( 57 ) = 0.7628;
sigma_phi = M_.params( 57 );
M_.params( 58 ) = 0.3578;
sigma_B = M_.params( 58 );
M_.params( 59 ) = 0.3457;
sigma_T = M_.params( 59 );
M_.params( 60 ) = 0.0625;
sigma_m = M_.params( 60 );
M_.params( 61 ) = 0.2592;
sigma_zeta = M_.params( 61 );
M_.params( 62 ) = 0.3429;
sigma_g = M_.params( 62 );
M_.params( 41 ) = 0.9760;
C_ratio = M_.params( 41 );
M_.params( 47 ) = 1;
Yz_SS = M_.params( 47 );
M_.params( 52 ) = 1.7030;
X_ratio = M_.params( 52 );
M_.params( 3 ) = M_.params(2)/(1+M_.params(10));
betar = M_.params( 3 );
M_.params( 49 ) = 1+pi_SS;
Pi_SS = M_.params( 49 );
M_.params( 39 ) = 1/M_.params(2)*exp(M_.params(6))*M_.params(49);
r_SS = M_.params( 39 );
M_.params( 20 ) = (1+M_.params(10))*M_.params(39);
RL = M_.params( 20 );
M_.params( 7 ) = M_.params(20)*(1-1/M_.params(67));
kappa = M_.params( 7 );
M_.params( 66 ) = M_.params(39)*(1-1/M_.params(67));
kappaEH = M_.params( 66 );
M_.params( 64 ) = (M_.params(20)-M_.params(7))*M_.params(63);
BLB = M_.params( 64 );
M_.params( 40 ) = 1/(1+M_.params(64));
Bz_SS = M_.params( 40 );
M_.params( 44 ) = M_.params(64)*M_.params(40);
BzL_SS = M_.params( 44 );
M_.params( 65 ) = M_.params(63)*M_.params(40);
BLMVz_SS = M_.params( 65 );
M_.params( 4 ) = (M_.params(15)*M_.params(2)*M_.params(52)+M_.params(16)*M_.params(3))/(M_.params(16)+M_.params(15)*M_.params(52));
beta_av = M_.params( 4 );
M_.params( 38 ) = exp(M_.params(6))*M_.params(4)^(-1)-(1-M_.params(5));
rk_SS = M_.params( 38 );
M_.params( 24 ) = (M_.params(4)/M_.params(3)-1)*M_.params(10)^(-1);
qu = M_.params( 24 );
M_.params( 13 ) = M_.params(15)/(M_.params(15)+M_.params(52)*M_.params(16)*(1-M_.params(2)*M_.params(11))/(1-M_.params(3)*M_.params(11)));
chi_pu = M_.params( 13 );
M_.params( 50 ) = M_.params(1)/(1+M_.params(9))/M_.params(38);
Kz_eff_SS = M_.params( 50 );
M_.params( 51 ) = exp(M_.params(6))*M_.params(1)/(1+M_.params(9))/M_.params(38);
Kz_SS = M_.params( 51 );
M_.params( 46 ) = M_.params(1)*(exp(M_.params(6))-(1-M_.params(5)))/(1+M_.params(9))/M_.params(38);
Iz_SS = M_.params( 46 );
M_.params( 48 ) = M_.params(45)-M_.params(40)*(1-1/M_.params(2)+M_.params(64)*(1-1/M_.params(3))/(M_.params(20)-M_.params(7)));
Tz_SS = M_.params( 48 );
M_.params( 43 ) = (1-M_.params(46)-M_.params(45))/(M_.params(16)+M_.params(15)*M_.params(41));
Czr_SS = M_.params( 43 );
M_.params( 42 ) = M_.params(41)*M_.params(43);
Czu_SS = M_.params( 42 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(6, 6) = M_.params(60)^2;
options_.irf = 24;
options_.nograph = 1;
var_list_ = char('dy','y','infl','FFR','bondrate','riskprem');
info = stoch_simul(var_list_);
save('chen_replication_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('chen_replication_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('chen_replication_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('chen_replication_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('chen_replication_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('chen_replication_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('chen_replication_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
