%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_ET14_rep';
M_.dynare_version = '4.5.3';
oo_.dynare_version = '4.5.3';
options_.dynare_version = '4.5.3';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_ET14_rep.log');
M_.exo_names = 'epsC';
M_.exo_names_tex = 'epsC';
M_.exo_names_long = 'epsC';
M_.exo_names = char(M_.exo_names, 'epsL');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsL');
M_.exo_names_long = char(M_.exo_names_long, 'epsL');
M_.exo_names = char(M_.exo_names, 'epsA');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsA');
M_.exo_names_long = char(M_.exo_names_long, 'epsA');
M_.exo_names = char(M_.exo_names, 'epsthet');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsthet');
M_.exo_names_long = char(M_.exo_names_long, 'epsthet');
M_.exo_names = char(M_.exo_names, 'epsG');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsG');
M_.exo_names_long = char(M_.exo_names_long, 'epsG');
M_.exo_names = char(M_.exo_names, 'epsnu');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsnu');
M_.exo_names_long = char(M_.exo_names_long, 'epsnu');
M_.exo_names = char(M_.exo_names, 'epsksi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsksi');
M_.exo_names_long = char(M_.exo_names_long, 'epsksi');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'ChiC');
M_.endo_names_tex = char(M_.endo_names_tex, 'ChiC');
M_.endo_names_long = char(M_.endo_names_long, 'ChiC');
M_.endo_names = char(M_.endo_names, 'Ps');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ps');
M_.endo_names_long = char(M_.endo_names_long, 'Ps');
M_.endo_names = char(M_.endo_names, 'PQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'PQ');
M_.endo_names_long = char(M_.endo_names_long, 'PQ');
M_.endo_names = char(M_.endo_names, 'PB');
M_.endo_names_tex = char(M_.endo_names_tex, 'PB');
M_.endo_names_long = char(M_.endo_names_long, 'PB');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'ChiL');
M_.endo_names_tex = char(M_.endo_names_tex, 'ChiL');
M_.endo_names_long = char(M_.endo_names_long, 'ChiL');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'qbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'qbar');
M_.endo_names_long = char(M_.endo_names_long, 'qbar');
M_.endo_names = char(M_.endo_names, 'qCB');
M_.endo_names_tex = char(M_.endo_names_tex, 'qCB');
M_.endo_names_long = char(M_.endo_names_long, 'qCB');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'iQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'iQ');
M_.endo_names_long = char(M_.endo_names_long, 'iQ');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta');
M_.endo_names_long = char(M_.endo_names_long, 'theta');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'Pss');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pss');
M_.endo_names_long = char(M_.endo_names_long, 'Pss');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_11');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_12');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_12');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_11');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_13');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_13');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_12');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_12');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_14');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_14');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_13');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_13');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_15');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_15');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_14');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_14');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_16');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_16');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_15');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_15');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_17');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_17');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_16');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_16');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_18');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_18');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_17');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_17');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'SStheta');
M_.param_names_tex = char(M_.param_names_tex, 'SStheta');
M_.param_names_long = char(M_.param_names_long, 'SStheta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'SSPi');
M_.param_names_tex = char(M_.param_names_tex, 'SSPi');
M_.param_names_long = char(M_.param_names_long, 'SSPi');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'gbar');
M_.param_names_tex = char(M_.param_names_tex, 'gbar');
M_.param_names_long = char(M_.param_names_long, 'gbar');
M_.param_names = char(M_.param_names, 'trho');
M_.param_names_tex = char(M_.param_names_tex, 'trho');
M_.param_names_long = char(M_.param_names_long, 'trho');
M_.param_names = char(M_.param_names, 'f');
M_.param_names_tex = char(M_.param_names_tex, 'f');
M_.param_names_long = char(M_.param_names_long, 'f');
M_.param_names = char(M_.param_names, 'a1');
M_.param_names_tex = char(M_.param_names_tex, 'a1');
M_.param_names_long = char(M_.param_names_long, 'a1');
M_.param_names = char(M_.param_names, 'a2');
M_.param_names_tex = char(M_.param_names_tex, 'a2');
M_.param_names_long = char(M_.param_names_long, 'a2');
M_.param_names = char(M_.param_names, 'gB');
M_.param_names_tex = char(M_.param_names_tex, 'gB');
M_.param_names_long = char(M_.param_names_long, 'gB');
M_.param_names = char(M_.param_names, 'gQ');
M_.param_names_tex = char(M_.param_names_tex, 'gQ');
M_.param_names_long = char(M_.param_names_long, 'gQ');
M_.param_names = char(M_.param_names, 'rhonu');
M_.param_names_tex = char(M_.param_names_tex, 'rhonu');
M_.param_names_long = char(M_.param_names_long, 'rhonu');
M_.param_names = char(M_.param_names, 'rhoksi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoksi');
M_.param_names_long = char(M_.param_names_long, 'rhoksi');
M_.param_names = char(M_.param_names, 'rhoC');
M_.param_names_tex = char(M_.param_names_tex, 'rhoC');
M_.param_names_long = char(M_.param_names_long, 'rhoC');
M_.param_names = char(M_.param_names, 'rhoL');
M_.param_names_tex = char(M_.param_names_tex, 'rhoL');
M_.param_names_long = char(M_.param_names_long, 'rhoL');
M_.param_names = char(M_.param_names, 'rhoG');
M_.param_names_tex = char(M_.param_names_tex, 'rhoG');
M_.param_names_long = char(M_.param_names_long, 'rhoG');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rhotheta');
M_.param_names_tex = char(M_.param_names_tex, 'rhotheta');
M_.param_names_long = char(M_.param_names_long, 'rhotheta');
M_.param_names = char(M_.param_names, 'gampi');
M_.param_names_tex = char(M_.param_names_tex, 'gampi');
M_.param_names_long = char(M_.param_names_long, 'gampi');
M_.param_names = char(M_.param_names, 'gamY');
M_.param_names_tex = char(M_.param_names_tex, 'gamY');
M_.param_names_long = char(M_.param_names_long, 'gamY');
M_.param_names = char(M_.param_names, 'gampiQE');
M_.param_names_tex = char(M_.param_names_tex, 'gampiQE');
M_.param_names_long = char(M_.param_names_long, 'gampiQE');
M_.param_names = char(M_.param_names, 'gamYQE');
M_.param_names_tex = char(M_.param_names_tex, 'gamYQE');
M_.param_names_long = char(M_.param_names_long, 'gamYQE');
M_.param_names = char(M_.param_names, 'SSY');
M_.param_names_tex = char(M_.param_names_tex, 'SSY');
M_.param_names_long = char(M_.param_names_long, 'SSY');
M_.param_names = char(M_.param_names, 'SSG');
M_.param_names_tex = char(M_.param_names_tex, 'SSG');
M_.param_names_long = char(M_.param_names_long, 'SSG');
M_.param_names = char(M_.param_names, 'SSC');
M_.param_names_tex = char(M_.param_names_tex, 'SSC');
M_.param_names_long = char(M_.param_names_long, 'SSC');
M_.param_names = char(M_.param_names, 'SSD');
M_.param_names_tex = char(M_.param_names_tex, 'SSD');
M_.param_names_long = char(M_.param_names_long, 'SSD');
M_.param_names = char(M_.param_names, 'SSL');
M_.param_names_tex = char(M_.param_names_tex, 'SSL');
M_.param_names_long = char(M_.param_names_long, 'SSL');
M_.param_names = char(M_.param_names, 'SSw');
M_.param_names_tex = char(M_.param_names_tex, 'SSw');
M_.param_names_long = char(M_.param_names_long, 'SSw');
M_.param_names = char(M_.param_names, 'SSs');
M_.param_names_tex = char(M_.param_names_tex, 'SSs');
M_.param_names_long = char(M_.param_names_long, 'SSs');
M_.param_names = char(M_.param_names, 'SSqbar');
M_.param_names_tex = char(M_.param_names_tex, 'SSqbar');
M_.param_names_long = char(M_.param_names_long, 'SSqbar');
M_.param_names = char(M_.param_names, 'SSPB');
M_.param_names_tex = char(M_.param_names_tex, 'SSPB');
M_.param_names_long = char(M_.param_names_long, 'SSPB');
M_.param_names = char(M_.param_names, 'SSPQ');
M_.param_names_tex = char(M_.param_names_tex, 'SSPQ');
M_.param_names_long = char(M_.param_names_long, 'SSPQ');
M_.param_names = char(M_.param_names, 'SSi');
M_.param_names_tex = char(M_.param_names_tex, 'SSi');
M_.param_names_long = char(M_.param_names_long, 'SSi');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 61;
M_.param_nbr = 37;
M_.orig_endo_nbr = 26;
M_.aux_vars(1).endo_index = 27;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 17;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 28;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 17;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(3).endo_index = 29;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 5;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(4).endo_index = 30;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 17;
M_.aux_vars(4).orig_lead_lag = -3;
M_.aux_vars(5).endo_index = 31;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 5;
M_.aux_vars(5).orig_lead_lag = -2;
M_.aux_vars(6).endo_index = 32;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 17;
M_.aux_vars(6).orig_lead_lag = -4;
M_.aux_vars(7).endo_index = 33;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 5;
M_.aux_vars(7).orig_lead_lag = -3;
M_.aux_vars(8).endo_index = 34;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 17;
M_.aux_vars(8).orig_lead_lag = -5;
M_.aux_vars(9).endo_index = 35;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 5;
M_.aux_vars(9).orig_lead_lag = -4;
M_.aux_vars(10).endo_index = 36;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 17;
M_.aux_vars(10).orig_lead_lag = -6;
M_.aux_vars(11).endo_index = 37;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 5;
M_.aux_vars(11).orig_lead_lag = -5;
M_.aux_vars(12).endo_index = 38;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 17;
M_.aux_vars(12).orig_lead_lag = -7;
M_.aux_vars(13).endo_index = 39;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 5;
M_.aux_vars(13).orig_lead_lag = -6;
M_.aux_vars(14).endo_index = 40;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 17;
M_.aux_vars(14).orig_lead_lag = -8;
M_.aux_vars(15).endo_index = 41;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 5;
M_.aux_vars(15).orig_lead_lag = -7;
M_.aux_vars(16).endo_index = 42;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 17;
M_.aux_vars(16).orig_lead_lag = -9;
M_.aux_vars(17).endo_index = 43;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 5;
M_.aux_vars(17).orig_lead_lag = -8;
M_.aux_vars(18).endo_index = 44;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 17;
M_.aux_vars(18).orig_lead_lag = -10;
M_.aux_vars(19).endo_index = 45;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 5;
M_.aux_vars(19).orig_lead_lag = -9;
M_.aux_vars(20).endo_index = 46;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 17;
M_.aux_vars(20).orig_lead_lag = -11;
M_.aux_vars(21).endo_index = 47;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 5;
M_.aux_vars(21).orig_lead_lag = -10;
M_.aux_vars(22).endo_index = 48;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 17;
M_.aux_vars(22).orig_lead_lag = -12;
M_.aux_vars(23).endo_index = 49;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 5;
M_.aux_vars(23).orig_lead_lag = -11;
M_.aux_vars(24).endo_index = 50;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 17;
M_.aux_vars(24).orig_lead_lag = -13;
M_.aux_vars(25).endo_index = 51;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 5;
M_.aux_vars(25).orig_lead_lag = -12;
M_.aux_vars(26).endo_index = 52;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 17;
M_.aux_vars(26).orig_lead_lag = -14;
M_.aux_vars(27).endo_index = 53;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 5;
M_.aux_vars(27).orig_lead_lag = -13;
M_.aux_vars(28).endo_index = 54;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 17;
M_.aux_vars(28).orig_lead_lag = -15;
M_.aux_vars(29).endo_index = 55;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 5;
M_.aux_vars(29).orig_lead_lag = -14;
M_.aux_vars(30).endo_index = 56;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 17;
M_.aux_vars(30).orig_lead_lag = -16;
M_.aux_vars(31).endo_index = 57;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 5;
M_.aux_vars(31).orig_lead_lag = -15;
M_.aux_vars(32).endo_index = 58;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 17;
M_.aux_vars(32).orig_lead_lag = -17;
M_.aux_vars(33).endo_index = 59;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 5;
M_.aux_vars(33).orig_lead_lag = -16;
M_.aux_vars(34).endo_index = 60;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 17;
M_.aux_vars(34).orig_lead_lag = -18;
M_.aux_vars(35).endo_index = 61;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 5;
M_.aux_vars(35).orig_lead_lag = -17;
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_ET14_rep_static');
erase_compiled_function('NK_ET14_rep_dynamic');
M_.orig_eq_nbr = 26;
M_.eq_nbr = 61;
M_.ramsey_eq_nbr = 0;
M_.lead_lag_incidence = [
 0 47 0;
 0 48 108;
 1 49 0;
 2 50 0;
 3 51 109;
 0 52 0;
 4 53 110;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 5 58 0;
 0 59 111;
 0 60 112;
 6 61 0;
 0 62 0;
 7 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 8 68 0;
 9 69 0;
 10 70 0;
 11 71 0;
 0 72 0;
 12 73 0;
 13 74 0;
 14 75 0;
 15 76 0;
 16 77 0;
 17 78 0;
 18 79 0;
 19 80 0;
 20 81 0;
 21 82 0;
 22 83 0;
 23 84 0;
 24 85 0;
 25 86 0;
 26 87 0;
 27 88 0;
 28 89 0;
 29 90 0;
 30 91 0;
 31 92 0;
 32 93 0;
 33 94 0;
 34 95 0;
 35 96 0;
 36 97 0;
 37 98 0;
 38 99 0;
 39 100 0;
 40 101 0;
 41 102 0;
 42 103 0;
 43 104 0;
 44 105 0;
 45 106 0;
 46 107 0;]';
M_.nstatic = 12;
M_.nfwrd   = 3;
M_.npred   = 44;
M_.nboth   = 2;
M_.nsfwrd   = 5;
M_.nspred   = 46;
M_.ndynamic   = 49;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(61, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(37, 1);
M_.NNZDerivatives = [212; -1; -1];
close all;
clc;
M_.params( 1 ) = 0.99;
beta = M_.params( 1 );
M_.params( 2 ) = 2;
delta = M_.params( 2 );
M_.params( 3 ) = 0.5;
psi = M_.params( 3 );
M_.params( 4 ) = 6;
SStheta = M_.params( 4 );
M_.params( 5 ) = 1.1;
phi = M_.params( 5 );
M_.params( 6 ) = 0.85;
alpha = M_.params( 6 );
M_.params( 7 ) = 1.005;
SSPi = M_.params( 7 );
M_.params( 8 ) = 20;
tau = M_.params( 8 );
M_.params( 9 ) = 0.4;
gbar = M_.params( 9 );
M_.params( 10 ) = 0.5;
trho = M_.params( 10 );
M_.params( 11 ) = 0.66;
f = M_.params( 11 );
M_.params( 12 ) = 0.95;
a1 = M_.params( 12 );
M_.params( 13 ) = 0;
a2 = M_.params( 13 );
M_.params( 14 ) = 10.21;
gB = M_.params( 14 );
M_.params( 15 ) = 0.59;
gQ = M_.params( 15 );
M_.params( 16 ) = 0.1;
rhonu = M_.params( 16 );
M_.params( 17 ) = 0.1;
rhoksi = M_.params( 17 );
M_.params( 18 ) = 0.1;
rhoC = M_.params( 18 );
M_.params( 19 ) = 0.7;
rhoL = M_.params( 19 );
M_.params( 20 ) = 0.1;
rhoG = M_.params( 20 );
M_.params( 21 ) = 0.7;
rhoA = M_.params( 21 );
M_.params( 22 ) = 0.95;
rhotheta = M_.params( 22 );
M_.params( 23 ) = 1.01;
gampi = M_.params( 23 );
M_.params( 24 ) = 0.3;
gamY = M_.params( 24 );
M_.params( 25 ) = 0;
gampiQE = M_.params( 25 );
M_.params( 26 ) = 60;
gamYQE = M_.params( 26 );
SSA = 1; 
SSChiC = 1; 
SSChiL = 1; 
SSnu = 1;  
SSksi = 1; 
M_.params( 30 ) = (1-M_.params(6))/(1-M_.params(6)*M_.params(7)^(M_.params(4)*M_.params(5)))*((1-M_.params(6)*M_.params(7)^(M_.params(4)-1))/(1-M_.params(6)))^(M_.params(4)*M_.params(5)/(M_.params(4)-1));
SSD = M_.params( 30 );
M_.params( 27 ) = (M_.params(5)*M_.params(4)*(1-M_.params(7)^(M_.params(4)-1)*M_.params(6)*M_.params(1))/(1-M_.params(7)^(M_.params(4)*M_.params(5))*M_.params(6)*M_.params(1))/(M_.params(4)-1)*M_.params(30)^M_.params(3)*(1-M_.params(9))^M_.params(2)*((1-M_.params(6)*M_.params(7)^(M_.params(4)-1))/(1-M_.params(6)))^((1+M_.params(4)*(M_.params(5)-1))/(M_.params(4)-1)))^(1/(1-M_.params(2)-M_.params(5)*(1+M_.params(3))));
SSY = M_.params( 27 );
M_.params( 28 ) = M_.params(9)*M_.params(27);
SSG = M_.params( 28 );
M_.params( 29 ) = M_.params(27)-M_.params(28);
SSC = M_.params( 29 );
SSF = SSY*SSC^(-delta)/(1-alpha*beta*SSPi^(SStheta-1)); 
SSK = 1/(1-alpha*beta*SSPi^(SStheta*phi))*SStheta*phi/(SStheta-1)*SSD^(psi)*SSY^(phi*(psi+1)); 
M_.params( 31 ) = M_.params(30)*M_.params(27)^M_.params(5);
SSL = M_.params( 31 );
M_.params( 32 ) = M_.params(31)^M_.params(3)*M_.params(29)^M_.params(2);
SSw = M_.params( 32 );
SSPs = beta/SSPi;  
SSqCB = 0; 
M_.params( 34 ) = M_.params(27)*M_.params(11);
SSqbar = M_.params( 34 );
SSq = SSqbar;  
M_.params( 33 ) = M_.params(7)/(1-M_.params(1))*(M_.params(28)+M_.params(29)-M_.params(31)*M_.params(10)*M_.params(32)-M_.params(27)*(1-M_.params(10)));
SSs = M_.params( 33 );
SSb = SSs - SSqbar/tau*(1-1/(SSPi^(tau)))*SSPi/(SSPi-1); 
SSPss = SSPs*SSs;
M_.params( 35 ) = 0.9878;
SSPB = M_.params( 35 );
M_.params( 36 ) = 0.8927;
SSPQ = M_.params( 36 );
M_.params( 37 ) = 1/M_.params(35)-1;
SSi = M_.params( 37 );
SSiQ = 0.011058944907359073835186213923637; 
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 15 ) = SSA;
oo_.steady_state( 7 ) = SSChiC;
oo_.steady_state( 12 ) = SSChiL;
oo_.steady_state( 24 ) = SSnu;
oo_.steady_state( 25 ) = SSksi;
oo_.steady_state( 5 ) = M_.params(7);
oo_.steady_state( 23 ) = M_.params(4);
oo_.steady_state( 22 ) = M_.params(30);
oo_.steady_state( 1 ) = M_.params(27);
oo_.steady_state( 4 ) = M_.params(28);
oo_.steady_state( 2 ) = M_.params(29);
oo_.steady_state( 13 ) = SSF;
oo_.steady_state( 14 ) = SSK;
oo_.steady_state( 6 ) = M_.params(31);
oo_.steady_state( 11 ) = M_.params(32);
oo_.steady_state( 8 ) = SSPs;
oo_.steady_state( 26 ) = SSPss;
oo_.steady_state( 19 ) = SSqCB;
oo_.steady_state( 18 ) = M_.params(34);
oo_.steady_state( 17 ) = SSq;
oo_.steady_state( 3 ) = M_.params(33);
oo_.steady_state( 16 ) = SSb;
oo_.steady_state( 9 ) = M_.params(36);
oo_.steady_state( 10 ) = M_.params(35);
oo_.steady_state( 20 ) = M_.params(37);
oo_.steady_state( 21 ) = SSiQ;
oo_.steady_state(27)=oo_.steady_state(17);
oo_.steady_state(28)=oo_.steady_state(27);
oo_.steady_state(29)=oo_.steady_state(5);
oo_.steady_state(30)=oo_.steady_state(28);
oo_.steady_state(31)=oo_.steady_state(29);
oo_.steady_state(32)=oo_.steady_state(30);
oo_.steady_state(33)=oo_.steady_state(31);
oo_.steady_state(34)=oo_.steady_state(32);
oo_.steady_state(35)=oo_.steady_state(33);
oo_.steady_state(36)=oo_.steady_state(34);
oo_.steady_state(37)=oo_.steady_state(35);
oo_.steady_state(38)=oo_.steady_state(36);
oo_.steady_state(39)=oo_.steady_state(37);
oo_.steady_state(40)=oo_.steady_state(38);
oo_.steady_state(41)=oo_.steady_state(39);
oo_.steady_state(42)=oo_.steady_state(40);
oo_.steady_state(43)=oo_.steady_state(41);
oo_.steady_state(44)=oo_.steady_state(42);
oo_.steady_state(45)=oo_.steady_state(43);
oo_.steady_state(46)=oo_.steady_state(44);
oo_.steady_state(47)=oo_.steady_state(45);
oo_.steady_state(48)=oo_.steady_state(46);
oo_.steady_state(49)=oo_.steady_state(47);
oo_.steady_state(50)=oo_.steady_state(48);
oo_.steady_state(51)=oo_.steady_state(49);
oo_.steady_state(52)=oo_.steady_state(50);
oo_.steady_state(53)=oo_.steady_state(51);
oo_.steady_state(54)=oo_.steady_state(52);
oo_.steady_state(55)=oo_.steady_state(53);
oo_.steady_state(56)=oo_.steady_state(54);
oo_.steady_state(57)=oo_.steady_state(55);
oo_.steady_state(58)=oo_.steady_state(56);
oo_.steady_state(59)=oo_.steady_state(57);
oo_.steady_state(60)=oo_.steady_state(58);
oo_.steady_state(61)=oo_.steady_state(59);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(6, 6) = (0.0025)^2;
M_.Sigma_e(7, 7) = (0.0025)^2;
options_.irf = 21;
options_.nocorr = 1;
options_.nofunctions = 1;
options_.nograph = 1;
options_.nomoments = 1;
options_.noprint = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('NK_ET14_rep_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_ET14_rep_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_ET14_rep_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_ET14_rep_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_ET14_rep_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_ET14_rep_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_ET14_rep_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
